### ISSUE TITLE
Init Fails w/ ansible-container build due to Debian Jessie Fetch Package Directory

### ISSUE THREAD

**Issue by darkn3rd** [ansible/ansible-container#109]
### SUMMARY 
Trying to start a project that uses Debian Jessie, but `ansible-container build` fails.  

In case these were important:

**container.yml**
```yaml
version: '1'
services:
  express:
    image: node:argon
    command: [ "echo", "hello" ]

registries: {}
```

**main.yml**
```yaml
- hosts: express
  tasks:
    - name: Make AppDir
      file: name=/usr/src/app state=directory recurse=true
```

### ACTUAL RESULT

Full Debug Gist: https://gist.github.com/darkn3rd/792ef1356058667ddf91e63c13d7c047

```
...
...
{"stream":"\u001b[91mFailed to fetch http://httpredir.debian.org/debian/dists/jessie/main/binary-amd64/Packages  404  Not Found [IP: 128.31.0.66 80]\n\n\u001b[0m"}

{"stream":"\u001b[91mE: \u001b[0m"}

{"stream":"\u001b[91mSome index files failed to download. They have been ignored, or old ones used instead.\n\u001b[0m"}

{"errorDetail":{"code":100,"message":"The command '/bin/sh -c apt-get update -y \u0026\u0026     apt-get install -y apt-transport-https ca-certificates \u0026\u0026     echo \"deb https://apt.dockerproject.org/repo debian-jessie main\"\u003e/etc/apt/sources.list.d/docker.list \u0026\u0026     apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D \u0026\u0026     apt-get update -y \u0026\u0026     apt-get install -y python-setuptools git python-pip docker-engine \u0026\u0026     apt-get clean \u0026\u0026 rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*' returned a non-zero code: 100"},"error":"The command '/bin/sh -c apt-get update -y \u0026\u0026     apt-get install -y apt-transport-https ca-certificates \u0026\u0026     echo \"deb https://apt.dockerproject.org/repo debian-jessie main\"\u003e/etc/apt/sources.list.d/docker.list \u0026\u0026     apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D \u0026\u0026     apt-get update -y \u0026\u0026     apt-get install -y python-setuptools git python-pip docker-engine \u0026\u0026     apt-get clean \u0026\u0026 rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*' returned a non-zero code: 100"}

No image with the name ansible-container-builder
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/ansible_container-0.1-py2.7.egg/container/cli.py", line 154, in commandline
    getattr(engine, u'cmdrun_{}'.format(args.subcommand))(**vars(args))
  File "/usr/local/lib/python2.7/site-packages/ansible_container-0.1-py2.7.egg/container/engine.py", line 248, in cmdrun_build
    create_build_container(engine_obj, base_path)
  File "/usr/local/lib/python2.7/site-packages/ansible_container-0.1-py2.7.egg/container/engine.py", line 352, in create_build_container
    builder_img_id = container_engine_obj.get_builder_image_id()
  File "/usr/local/lib/python2.7/site-packages/ansible_container-0.1-py2.7.egg/container/docker/engine.py", line 174, in get_builder_image_id
    return self.get_image_id_by_tag(self.builder_container_img_tag)
  File "/usr/local/lib/python2.7/site-packages/ansible_container-0.1-py2.7.egg/container/docker/engine.py", line 127, in get_image_id_by_tag
    raise NameError('No image with the name %s' % name)
NameError: No image with the name ansible-container-builder
```

Looked through the debug output to see what is wrong with the side-kick container build, found that the [URL](http://mirrors.kernel.org/debian/dists/jessie/main/binary-amd64/Package) tries to access a non-existent `Package` directory. There were files in the parent directory like `Package.gz`.

### System Configuration

* Host OS: El Capitan
* Docker: `Docker version 1.11.2, build b9f10c9`
* Docker-Compose: `docker-compose version 1.7.0, build 0d7bf73`
* Python: `Python 2.7.11`

**Comment by darkn3rd** [comment]
Closing this one.  My `docker-machine` default VM ran out of space, which created all sorts of weird errors.  After recreating the VM, no more container issues.
