### ISSUE TITLE
HTTP timeout

### ISSUE THREAD

**Issue by chouseknecht** [ansible/ansible-container#11]
Noticed when running the *build* command that long running tasks cause a timeout. I think the timeout is a parameter that needs to be set when the docker-py client is instantiated, but I could be wrong.

An example is running *yum: name= {{ item }}" and iterating over a list of package names. If the time it takes to install all of the packages exceeds some threshold, a timeout occurs.

**Comment by gaieges** [comment]
Stumbled upon this issue as well today.  For a little more color, looks like it's coming from the docker compose python libs waiting for log messages from the engine:

```
HTTPConnectionPool(host='10.0.2.15', port=2375): Read timed out.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible_container-0.1-py2.7.egg/container/cli.py", line 173, in commandline
    **vars(args))
  File "/usr/local/lib/python2.7/dist-packages/ansible_container-0.1-py2.7.egg/container/engine.py", line 232, in cmdrun_build
    engine_obj.orchestrate('build', temp_dir, context=dict(rebuild=rebuild))
  File "/usr/local/lib/python2.7/dist-packages/ansible_container-0.1-py2.7.egg/container/docker/engine.py", line 234, in orchestrate
    **context)
  File "/usr/local/lib/python2.7/dist-packages/ansible_container-0.1-py2.7.egg/container/docker/utils.py", line 158, in launch_docker_compose
    command.up(command_options)
  File "/usr/local/lib/python2.7/dist-packages/docker_compose-1.7.0-py2.7.egg/compose/cli/main.py", line 741, in up
    log_printer.run()
  File "/usr/local/lib/python2.7/dist-packages/docker_compose-1.7.0-py2.7.egg/compose/cli/log_printer.py", line 86, in run
    for line in consume_queue(queue, self.cascade_stop):
  File "/usr/local/lib/python2.7/dist-packages/docker_compose-1.7.0-py2.7.egg/compose/cli/log_printer.py", line 222, in consume_queue
    raise item.exc
ConnectionError: HTTPConnectionPool(host='10.0.2.15', port=2375): Read timed out.
```

Will poke around a little try to figure out how to get around it.

**Comment by gaieges** [comment]
Looking around at the [compose docs](https://github.com/docker/compose/blob/master/docs/reference/envvars.md#compose_http_timeout) a little bit: it looks like you can set the ```COMPOSE_HTTP_TIMEOUT``` env variable on the building shell to a high value to get around it.    I can confirm that fixes this for me.

Not sure how you want to go about it though - either by documenting this variable to use, or actually set it in the orchestrating container (haven't tested that yet though).  

I believe you're right regarding creating the client with a ```timeout``` kwarg, as that's [all this env variable does](https://github.com/docker/compose/blob/master/compose/cli/docker_client.py#L67).  If you want to go that way.

**Comment by j00bar** [comment]
We do set the `COMPOSE_HTTP_TIMEOUT` variable. Some searching around suggested that it's more or less ignored in the case that a `tty` is allocated to the container. The latest iteration of the code removes that, and I've ceased seeing these timeouts. Feel free to re-open this issue if you continue to run into it.

**Comment by gaieges** [comment]
That's helpful, thanks. Will give it a try.
