### ISSUE TITLE
Build trackback due to image child-parent creation order

### ISSUE THREAD

**Issue by darkn3rd** [ansible/ansible-container#111]
### SUMMARY

Getting a lot of these `unable to delete $sha (cannot be forced) - image has dependent child images")` messages when making and change and wanting to rebulid. 

### STEPS

1. `ansible-container build`
2. change something in main.yml, such as mkdir task
3. `ansible-container build`

### ACTUAL RESULT

```
(Re)building the Ansible Container image.
Building Docker Engine context...
Starting Docker build of Ansible Container image (please be patient)...
Ansible Container image has ID sha256:8b59430249e8ed9e5e275c8b35fc9eb53500f61250d4e0bdbad71ff3eba2be34
Starting Docker Compose engine to build your images...
Attaching to ansible_ansible-container_1
Cleaning up Ansible Container builder...
Attaching to ansible_express_1, ansible_ansible-container_1
ansible-container_1  | 
ansible-container_1  | PLAY [express] *****************************************************************
ansible-container_1  | 
ansible-container_1  | TASK [setup] *******************************************************************
ansible-container_1  | ok: [express]
ansible-container_1  | 
ansible-container_1  | TASK [Make AppDir] *************************************************************
ansible-container_1  | changed: [express]
ansible-container_1  | 
ansible-container_1  | PLAY RECAP *********************************************************************
ansible-container_1  | express                    : ok=2    changed=1    unreachable=0    failed=0   
ansible-container_1  | 
ansible_ansible-container_1 exited with code 0
Aborting on container exit...
Stopping ansible_express_1 ... done
Exporting built containers as images...
Committing image...
Exported express-express with image ID sha256:af73a679fb777d1c07a6820562879b4dc3765c872d9eed10edc513f0ac6924a4
Cleaning up express build container...
Removing previous image...
409 Client Error: Conflict ("conflict: unable to delete 8bc3842ac7ad (cannot be forced) - image has dependent child images")
```

### EXPECTED RESULT

That it would build and apply the change.

### SCRIPTS

```yaml
version: '1'
services:
  express:
    image: node:argon
registries: {}
```

```yaml
- hosts: express
  tasks:
     - name: Make AppDir
       file: name=/usr/src/app state=directory recurse=true
```

### NOTES

I have to go force purge my image before rebuilding.  This seems to work.

```bash
docker images | grep express | awk '{print $3}' | xargs docker rmi —force
```

**Comment by darkn3rd** [comment]
Created a gist with consecutive `ansible-container build` and `dockviz` tool: 
* https://gist.github.com/darkn3rd/7bda7ef1d70dc2c8001f73bcbe7ce06c

It looks like it is create a child image from the previous created image, and then deletes the previous created image, which is now the parent.  I am deducing it should have deleted the previously created image, then create the new parent.

For example, in the snippet previous step created `a51d564edf96`, then it creates a child image under it and tries to delete the parent `a51d564edf96`.

Snippet:
```bash
# before
...
└─abb6383ef5fe Virtual Size: 656.9 MB Tags: node:argon
  └─a51d564edf96 Virtual Size: 656.9 MB Tags: express-express:20160705084124, express-express:latest
...
# after
└─abb6383ef5fe Virtual Size: 656.9 MB Tags: node:argon
  └─a51d564edf96 Virtual Size: 656.9 MB Tags: express-express:20160705084124
    └─3ba4802716c4 Virtual Size: 656.9 MB Tags: express-express:20160705084519, express-express:latest
```

**Comment by chouseknecht** [comment]
I can confirm the same. Build the example app. Make a change to the django example app and run `ansible-containe build`.  This results in the following errror:

```
ansible-container_1  |
ansible-container_1  | PLAY RECAP *********************************************************************
ansible-container_1  | django                     : ok=15   changed=4    unreachable=0    failed=0
ansible-container_1  | gulp                       : ok=13   changed=3    unreachable=0    failed=0
ansible-container_1  | static                     : ok=10   changed=1    unreachable=0    failed=0
ansible-container_1  |
ansible_ansible-container_1 exited with code 0
Aborting on container exit...
Stopping ansible_gulp_1 ... done
Stopping ansible_static_1 ... done
Stopping ansible_django_1 ... done
Stopping ansible_postgresql_1 ... done
Exporting built containers as images...
Committing image...
Exported django-admin-gulp with image ID sha256:3863f2734c6d26e9c050bfb2007c8fbad7db245f0e34386d09ef93ed78586ea7
Cleaning up gulp build container...
Removing previous image...
Cleaning up temporary directory /var/folders/g_/mr68c1yn1rl4b7qh6pntbmmm0000gn/T/tmplL5ZUW...
409 Client Error: Conflict ("conflict: unable to delete f5130456bf13 (cannot be forced) - image has dependent child images")
Traceback (most recent call last):
  File "/Users/chouseknecht/projects/ansible-container/container/cli.py", line 154, in commandline
    getattr(engine, u'cmdrun_{}'.format(args.subcommand))(**vars(args))
  File "/Users/chouseknecht/projects/ansible-container/container/engine.py", line 264, in cmdrun_build
    engine_obj.post_build(host, version, flatten=flatten, purge_last=purge_last)
  File "/Users/chouseknecht/projects/ansible-container/container/docker/engine.py", line 464, in post_build
    client.remove_image(previous_image_id, force=True)
  File "/usr/local/lib/python2.7/site-packages/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/docker/api/image.py", line 252, in remove_image
    self._raise_for_status(res)
  File "/usr/local/lib/python2.7/site-packages/docker/client.py", line 154, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
APIError: 409 Client Error: Conflict ("conflict: unable to delete f5130456bf13 (cannot be forced) - image has dependent child images")
```

I think the error is in [docker/engine.py](https://github.com/ansible/ansible-container/blob/master/container/docker/engine.py#L462). It needs to check that previous_image_id != image_id before attempting to remove the image. Testing this theory now...
