### ISSUE TITLE
Error: TemplateNotFound: shipit_role/test.j2.yml

### ISSUE THREAD

**Issue by ganapar** [ansible/ansible-container#114]
I followed the steps for installation and was able to successfully complete an ansible-container build from the examples: https://github.com/ansible/ansible-container-examples

I want to deploy it on a kubernetes cluster and the shipit command throws me an error:

Creating role path /home/centos/ansible-container-examples/django-cms/ansible/roles/django-cms-kubernetes
Rendering template for test/test.j2.yml
shipit_role/test.j2.yml
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible_container-0.1-py2.7.egg/container/cli.py", line 154, in commandline
    getattr(engine, u'cmdrun_{}'.format(args.subcommand))(**vars(args))
  File "/usr/lib/python2.7/site-packages/ansible_container-0.1-py2.7.egg/container/engine.py", line 337, in cmdrun_shipit
    shipit_engine_obj.run()
  File "/usr/lib/python2.7/site-packages/ansible_container-0.1-py2.7.egg/container/shipit/kubernetes/engine.py", line 28, in run
    self.init_role()
  File "/usr/lib/python2.7/site-packages/ansible_container-0.1-py2.7.egg/container/shipit/base_engine.py", line 139, in init_role
    **context)
  File "/usr/lib/python2.7/site-packages/ansible_container-0.1-py2.7.egg/container/utils.py", line 68, in jinja_render_to_temp
    j2_tmpl = j2_env.get_template(template_file)
  File "/usr/lib64/python2.7/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/lib64/python2.7/site-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/usr/lib64/python2.7/site-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: shipit_role/test.j2.yml

Am I missing something ?

**Comment by gregdek** [comment]
I wonder if this is a bug here or with the actual example. If the latter, we may want to file it against that.

**Comment by containscafeine** [comment]
I am facing the same issue while trying to do a `ansible-container shipit kube` on my application, while it builds and runs fine with other ansible-container commands.

@gregdek In the templates [directory](https://github.com/ansible/ansible-container/tree/master/container/templates), none of the template files are named like expected [here](https://github.com/ansible/ansible-container/blob/master/container/shipit/base_engine.py#L136), imo that's why the template is not found.

**Comment by chouseknecht** [comment]
Ah-hah. So when I *install* the application via `python ./setup.py install` the *templates/shipit_role* directory is completely missing.
