### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by mwardRH** [ansible/ansible-container#17]
Error when trying to run the following command. 

[root@earth ansible-container] # ansible-container init
Traceback (most recent call last):
  File "/usr/bin/ansible-container", line 9, in <module>
    load_entry_point('ansible-container==0.1', 'console_scripts', 'ansible-container')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/ansible_container-0.1-py2.7.egg/container/cli.py", line 13, in <module>
    from . import engine
  File "/usr/lib/python2.7/site-packages/ansible_container-0.1-py2.7.egg/container/engine.py", line 17, in <module>
    from compose.config.config import load as config_load, find as config_find
ImportError: No module named compose.config.config

**Comment by talonx** [comment]
You need to install docker-compose

**Comment by defionscode** [comment]
correct. works fine on OSX
