### ISSUE TITLE
Error while pushing image to google cloud

### ISSUE THREAD

**Issue by nonotest** [ansible/ansible-container#177]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Error while pushing to google cloud..

```
The push refers to a repository [asia.gcr.io/.../...-static]
Extra data: line 2 column 1 - line 3 column 1 (char 64 - 128)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/container/cli.py", line 154, in commandline
    getattr(engine, u'cmdrun_{}'.format(args.subcommand))(**vars(args))
  File "/usr/local/lib/python2.7/site-packages/container/engine.py", line 322, in cmdrun_push
    engine_obj.push_latest_image(host, url=url, namespace=namespace)
  File "/usr/local/lib/python2.7/site-packages/container/docker/engine.py", line 640, in push_latest_image
    line = json.loads(line)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
```

GCE reports progress like below:

```
{"status":"Pushing","progressDetail":{"current":56037376,"total":785160510},"progress":"[===\u003e                                               ] 56.04 MB/785.2 MB","id":"187ffb413488"}
```

so maybe there is a hidden break line or something going on with the unicode character..?

if using ````splitlines()```` just before the json.loads the script finishes correctly and this is a lines output:
````
['{"status":"Pushing","progressDetail":{"current":532784,"total":785160510},"progress":"[\\u003e                                                  ] 532.8 kB/785.2 MB","id":"187ffb413488"}']
````

##### STEPS TO REPRODUCE
Push any container to GCE with ansible-container push eg
````
 ansible-container --debug push --username oauth2accesstoken --password "$(gcloud auth print-access-token)" --push-to https://asia.gcr.io/xxx
````

**Comment by j00bar** [comment]
Please provide the requested debugging information as requested in the bug report template:

https://raw.githubusercontent.com/ansible/ansible-container/develop/.github/ISSUE_TEMPLATE.md

**Comment by roderickrandolph** [comment]
this issue isn't unique to google cloud - it happens when pushing to docker hub as well

```
Pushing to "https://index.docker.io/v1/roderickrandolph
Attaching to ansible_ansible-container_1
Cleaning up Ansible Container builder...
Tagging roderickrandolph/tripler-tracker-app
Pushing roderickrandolph/tripler-tracker-app:20160828163740...
The push refers to a repository [docker.io/roderickrandolph/tripler-tracker-app]
Preparing
Extra data: line 2 column 1 - line 6 column 1 (char 64 - 320)
```

**Comment by chouseknecht** [comment]
Test the latest code in develop branch by building and pushing the images. 

My environment:

```
$ ansible-container --debug version
Ansible Container, version 0.2.0-pre
Darwin, Chriss-MacBook-Pro.local, 15.6.0, Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64, x86_64
2.7.11 (default, Jan 22 2016, 08:29:18)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] /usr/local/opt/python/bin/python2.7
{u'Architecture': u'x86_64',
 u'BridgeNfIp6tables': True,
 u'BridgeNfIptables': True,
 u'CPUSet': True,
 u'CPUShares': True,
 u'CgroupDriver': u'cgroupfs',
 u'ClusterAdvertise': u'',
 u'ClusterStore': u'',
 u'Containers': 1,
 u'ContainersPaused': 0,
 u'ContainersRunning': 0,
 u'ContainersStopped': 1,
 u'CpuCfsPeriod': True,
 u'CpuCfsQuota': True,
 u'Debug': True,
 u'DockerRootDir': u'/mnt/sda1/var/lib/docker',
 u'Driver': u'aufs',
 u'DriverStatus': [[u'Root Dir', u'/mnt/sda1/var/lib/docker/aufs'],
                   [u'Backing Filesystem', u'extfs'],
                   [u'Dirs', u'30'],
                   [u'Dirperm1 Supported', u'true']],
 u'ExecutionDriver': u'',
 u'ExperimentalBuild': False,
 u'HttpProxy': u'',
 u'HttpsProxy': u'',
 u'ID': u'TNH2:JOIY:XYYD:WFYR:FTTG:Z4NR:QVRT:PRKH:N2Z6:3DH2:RKHV:3LTF',
 u'IPv4Forwarding': True,
 u'Images': 6,
 u'IndexServerAddress': u'https://index.docker.io/v1/',
 u'KernelMemory': True,
 u'KernelVersion': u'4.4.12-boot2docker',
 u'Labels': [u'provider=virtualbox'],
 u'LoggingDriver': u'json-file',
 u'MemTotal': 1044250624,
 u'MemoryLimit': True,
 u'NCPU': 1,
 u'NEventsListener': 0,
 u'NFd': 17,
 u'NGoroutines': 34,
 u'Name': u'default',
 u'NoProxy': u'',
 u'OSType': u'linux',
 u'OomKillDisable': True,
 u'OperatingSystem': u'Boot2Docker 1.11.2 (TCL 7.1); HEAD : a6645c3 - Wed Jun  1 22:59:51 UTC 2016',
 u'Plugins': {u'Authorization': None,
              u'Network': [u'bridge', u'null', u'host'],
              u'Volume': [u'local']},
 u'RegistryConfig': {u'IndexConfigs': {u'docker.io': {u'Mirrors': None,
                                                      u'Name': u'docker.io',
                                                      u'Official': True,
                                                      u'Secure': True}},
                     u'InsecureRegistryCIDRs': [u'127.0.0.0/8'],
                     u'Mirrors': None},
 u'ServerVersion': u'1.11.2',
 u'SwapLimit': True,
 u'SystemStatus': None,
 u'SystemTime': u'2016-09-02T16:25:06.249001321Z'}
{u'ApiVersion': u'1.23',
 u'Arch': u'amd64',
 u'BuildTime': u'2016-06-01T21:20:08.558909126+00:00',
 u'GitCommit': u'b9f10c9',
 u'GoVersion': u'go1.5.4',
 u'KernelVersion': u'4.4.12-boot2docker',
 u'Os': u'linux',
 u'Version': u'1.11.2'}
```


Here's the push to gcloud:

```
$ ansible-container push --username oauth2accesstoken --password "$(gcloud auth print-access-token)" --push-to https://us.gcr.io/pure-stronghold-142215
Pushing to "https://us.gcr.io/pure-stronghold-142215
Attaching to ansible_ansible-container_1
Cleaning up Ansible Container builder...
Tagging us.gcr.io/pure-stronghold-142215/django-admin-gulp
Pushing us.gcr.io/pure-stronghold-142215/django-admin-gulp:20160902154424...
The push refers to a repository [us.gcr.io/pure-stronghold-142215/django-admin-gulp]
Preparing
Pushing
Pushed
Pushing
Pushed
20160902154424: digest: sha256:93c7eb5cfe07496ba5e291967eb10563272ba60100c6e19987f1d8ea9fb34ed1 size: 4299
Tagging us.gcr.io/pure-stronghold-142215/django-admin-static
Pushing us.gcr.io/pure-stronghold-142215/django-admin-static:20160902154424...
The push refers to a repository [us.gcr.io/pure-stronghold-142215/django-admin-static]
Preparing
Mounted from pure-stronghold-142215/django-admin-gulp
Pushing
Pushed
20160902154424: digest: sha256:81a9bf6aea0bc0d9dc0ed8e696c0523c21ae9dbaffed67656f7d3821611a76fa size: 4415
Tagging us.gcr.io/pure-stronghold-142215/django-admin-django
Pushing us.gcr.io/pure-stronghold-142215/django-admin-django:20160902154424...
The push refers to a repository [us.gcr.io/pure-stronghold-142215/django-admin-django]
Preparing
Pushing
Mounted from pure-stronghold-142215/django-admin-static
Pushing
Pushed
20160902154424: digest: sha256:00a8723aaac28b1a3a645cf9260bf5b7f72fbcb3bf9d69b5d17fb28be4e01b0f size: 4456
```

And, here's a push to Docker Hub:

```
$ ansible-container push --username chouseknecht
Enter password for chouseknecht at https://index.docker.io/v1/:
Pushing to "https://index.docker.io/v1/chouseknecht
Attaching to ansible_ansible-container_1
Cleaning up Ansible Container builder...
Tagging chouseknecht/django-admin-gulp
Pushing chouseknecht/django-admin-gulp:20160902154424...
The push refers to a repository [docker.io/chouseknecht/django-admin-gulp]
Preparing
Mounted from openshift/postgresql-92-centos7
Pushing
Pushed
20160902154424: digest: sha256:cb81f4517cc6029a08bcec5ad9eff448405e2bfc693622cb03e85b8e699c1d9a size: 741
Tagging chouseknecht/django-admin-static
Pushing chouseknecht/django-admin-static:20160902154424...
The push refers to a repository [docker.io/chouseknecht/django-admin-static]
Preparing
Pushing
Mounted from chouseknecht/django-admin-gulp
Pushing
Pushed
20160902154424: digest: sha256:1ca4bebab09d000c5fb5cc2a398b15939e112523af38c2f0832c85f49c1db501 size: 742
Tagging chouseknecht/django-admin-django
Pushing chouseknecht/django-admin-django:20160902154424...
The push refers to a repository [docker.io/chouseknecht/django-admin-django]
Preparing
Pushing
Mounted from chouseknecht/django-admin-static
Pushing
...
```

**Comment by chouseknecht** [comment]
Closing as *push* seems to be working fine with @roderickrandolph 's fix.  Nice work!

If this is still in issue or there are additional questions, please feel free to re-open.
