### ISSUE TITLE
Jinja2 template not working when used in service name

### ISSUE THREAD

**Issue by vpjapp-avoltus** [ansible/ansible-container#205]
##### ISSUE TYPE

 - Bug Report

##### container.yml 

```
version: "1"
services:

  'test-{{target_env}}':
    image: ubuntu:trusty
    entrypoint: ["/bin/bash", "-c", "tail -f /var/log/dmesg"]

registries: {}
```

##### main.yml 

```
- hosts: test-se
  gather_facts: false
  vars:
    - target_env: se
  tasks:
    - debug: var=inventory_hostname
    - raw: which python || apt-get update
    - raw: (which python && which aptitude) || apt-get install -y python python-apt aptitude
    - command: "echo Hello world!"
```

##### OS / ENVIRONMENT

```
Ansible Container, version 0.2.0-pre
Linux, kontiainen, 3.13.0-65-generic, #106-Ubuntu SMP Fri Oct 2 22:08:27 UTC 2015, x86_64
2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] /home/vpjapp/git/talentum/talentum-ansible-container-dev/ansible-container-dev/ansible-container/bin/python
No DOCKER_HOST environment variable found. Assuming UNIX socket at /var/run/docker.sock
{u'Architecture': u'x86_64',
 u'BridgeNfIp6tables': True,
 u'BridgeNfIptables': True,
 u'CPUSet': True,
 u'CPUShares': True,
 u'CgroupDriver': u'cgroupfs',
 u'ClusterAdvertise': u'',
 u'ClusterStore': u'',
 u'Containers': 6,
 u'ContainersPaused': 0,
 u'ContainersRunning': 0,
 u'ContainersStopped': 6,
 u'CpuCfsPeriod': True,
 u'CpuCfsQuota': True,
 u'Debug': False,
 u'DefaultRuntime': u'runc',
 u'DockerRootDir': u'/home/docker/lib',
 u'Driver': u'aufs',
 u'DriverStatus': [[u'Root Dir', u'/home/docker/lib/aufs'],
                   [u'Backing Filesystem', u'extfs'],
                   [u'Dirs', u'38'],
                   [u'Dirperm1 Supported', u'false']],
 u'ExecutionDriver': u'',
 u'ExperimentalBuild': False,
 u'HttpProxy': u'',
 u'HttpsProxy': u'',
 u'ID': u'4WHL:QIIU:XRDY:SUMQ:N4LY:5RYY:VQZF:2JZ7:LM5Z:P4GT:JGKK:W3SN',
 u'IPv4Forwarding': True,
 u'Images': 8,
 u'IndexServerAddress': u'https://index.docker.io/v1/',
 u'KernelMemory': True,
 u'KernelVersion': u'3.13.0-65-generic',
 u'Labels': None,
 u'LiveRestoreEnabled': False,
 u'LoggingDriver': u'json-file',
 u'MemTotal': 16732880896,
 u'MemoryLimit': True,
 u'NCPU': 4,
 u'NEventsListener': 0,
 u'NFd': 43,
 u'NGoroutines': 73,
 u'Name': u'kontiainen',
 u'NoProxy': u'',
 u'OSType': u'linux',
 u'OomKillDisable': True,
 u'OperatingSystem': u'Ubuntu 14.04.5 LTS',
 u'Plugins': {u'Authorization': None,
              u'Network': [u'bridge', u'null', u'host', u'overlay'],
              u'Volume': [u'local']},
 u'RegistryConfig': {u'IndexConfigs': {u'docker.io': {u'Mirrors': None,
                                                      u'Name': u'docker.io',
                                                      u'Official': True,
                                                      u'Secure': True}},
                     u'InsecureRegistryCIDRs': [u'127.0.0.0/8'],
                     u'Mirrors': None},
 u'Runtimes': {u'runc': {u'path': u'docker-runc'}},
 u'SecurityOptions': [u'apparmor'],
 u'ServerVersion': u'1.12.1',
 u'SwapLimit': False,
 u'Swarm': {u'Cluster': {u'CreatedAt': u'0001-01-01T00:00:00Z',
                         u'ID': u'',
                         u'Spec': {u'CAConfig': {},
                                   u'Dispatcher': {},
                                   u'Orchestration': {},
                                   u'Raft': {},
                                   u'TaskDefaults': {}},
                         u'UpdatedAt': u'0001-01-01T00:00:00Z',
                         u'Version': {}},
            u'ControlAvailable': False,
            u'Error': u'',
            u'LocalNodeState': u'inactive',
            u'Managers': 0,
            u'NodeAddr': u'',
            u'NodeID': u'',
            u'Nodes': 0,
            u'RemoteManagers': None},
 u'SystemStatus': None,
 u'SystemTime': u'2016-08-30T16:14:31.307147202+03:00'}
{u'ApiVersion': u'1.24',
 u'Arch': u'amd64',
 u'BuildTime': u'2016-08-18T05:22:43.932726241+00:00',
 u'GitCommit': u'23cf638',
 u'GoVersion': u'go1.6.3',
 u'KernelVersion': u'3.13.0-65-generic',
 u'Os': u'linux',
 u'Version': u'1.12.1'}
```
##### SUMMARY

Seems that using jinja2 template in service name works only partly.
The hostname for the main.yml is not rendered correctly leaving it like this in my case: test-{{target_env}} and thus not matching hosts-definition of test-se as I think it should.

##### STEPS TO REPRODUCE

With provided container.yml and main.yml:

```
export target_env=se
ansible-container --debug version
```

##### EXPECTED RESULTS
The build should go through without errors and match the test-se host.

##### ACTUAL RESULTS
No hosts are matched. This seems to be because ansible tries to match "test-{{target_env}}" against "test-se".

```

$ ansible-container --debug build
No DOCKER_HOST environment variable found. Assuming UNIX socket at /var/run/docker.sock
Project name is ansible-container-bug
Getting environment variables...
Template variables:
 {
    "target_env": "se"
}
Rendered config:
 version: "1"
services:

  'test-se':
    image: ubuntu:trusty
    entrypoint: ["/bin/bash", "-c", "tail -f /var/log/dmesg"]

registries: {}
Config:
{
    "registries": {},
    "services": {
        "test-se": {
            "entrypoint": [
                "/bin/bash",
                "-c",
                "tail -f /var/log/dmesg"
            ],
            "image": "ubuntu:trusty"
        }
    },
    "version": "1"
}
Initialized with params: {'with_volumes': None, 'local_builder': False, 'with_variables': None, 'rebuild': False, 'subcommand': 'build', 'var_file': None, 'engine_args': {'local_builder': False, 'subcommand': 'build', 'base_path': '/home/vpjapp/git/talentum/ansible-container-bug', 'ansible_options': u'', 'flatten': False, 'no_purge_last': True, 'with_volumes': None, 'engine_name': 'docker', 'with_variables': None, 'rebuild': False, 'var_file': None, 'engine_args': {...}, 'save_build_container': False, 'kwargs': {'with_volumes': None, 'with_variables': None, 'subcommand': 'build', 'var_file': None, 'debug': True, 'no_purge_last': True}, 'debug': True, 'purge_last': True}, 'save_build_container': False, 'purge_last': True, 'ansible_options': u'', 'flatten': False, 'kwargs': {'with_volumes': None, 'with_variables': None, 'subcommand': 'build', 'var_file': None, 'debug': True, 'no_purge_last': True}, 'debug': True, 'no_purge_last': True}
Using temporary directory /tmp/tmpJ_XcMs...
Starting Docker Compose engine to build your images...
Using temporary directory /tmp/tmp7gVgcK...
Compose derived from config:
{'test-se': {'image': 'ubuntu:trusty', 'entrypoint': ['/bin/bash', '-c', 'tail -f /var/log/dmesg']}}
{'test-se': {'working_dir': '/', 'entrypoint': [], 'user': 'root', 'command': 'sh -c "while true; do sleep 1; done"', 'image': 'ubuntu:trusty'}}
Config YAML is
test-se:
  command: sh -c "while true; do sleep 1; done"
  entrypoint: []
  image: ubuntu:trusty
  user: root
  working_dir: /

Rendered Jinja Template:
ansible-container:
  # If no $DOCKER_HOST then we need to run privileged so we can access /var/run/docker.sock
  privileged: true
  image: "sha256:16eaadfbd806531a702336c6f62d2fd9fc5e356db706905cb42cb6ca129ab25e"
  command: /usr/local/bin/builder.sh /usr/local/bin/ansible-playbook -i /etc/ansible/ansible-container-inventory.py -c docker  --list-hosts main.yml
  environment:
    - DOCKER_HOST=unix:///var/run/docker.sock
    
    
    - COMPOSE_HTTP_TIMEOUT=3000
    - DOCKER_API_VERSION=1.24
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    
    - /home/vpjapp/git/talentum/ansible-container-bug:/ansible-container/:Z
  working_dir: /ansible-container/ansible/
  stdin_open: true
  tty: true
test-se:
  command: sh -c "while true; do sleep 1; done"
  entrypoint: []
  image: ubuntu:trusty
  user: root
  working_dir: /

Cleaning up Ansible Container builder...
--list-hosts
ansible-container_1  | 
ansible-container_1  | playbook: main.yml
ansible-container_1  | 
ansible-container_1  |   play #1 (test-se): 	TAGS: []
ansible-container_1  |     pattern: [u'test-se']
ansible-container_1  |     hosts (0):
ansible_ansible-container_1 exited with code 0

Cleaning up temporary directory /tmp/tmp7gVgcK...
Compose derived from config:
{'test-se': {'image': 'ubuntu:trusty', 'entrypoint': ['/bin/bash', '-c', 'tail -f /var/log/dmesg']}}
Using temporary directory /tmp/tmpO_1fUS...
Compose derived from config:
{'test-se': {'image': 'ubuntu:trusty', 'entrypoint': ['/bin/bash', '-c', 'tail -f /var/log/dmesg']}}
{'test-se': {'working_dir': '/', 'entrypoint': [], 'user': 'root', 'command': 'sh -c "while true; do sleep 1; done"', 'image': 'ubuntu:trusty'}}
Config YAML is
test-se:
  command: sh -c "while true; do sleep 1; done"
  entrypoint: []
  image: ubuntu:trusty
  user: root
  working_dir: /

Rendered Jinja Template:
ansible-container:
  # If no $DOCKER_HOST then we need to run privileged so we can access /var/run/docker.sock
  privileged: true
  image: "sha256:16eaadfbd806531a702336c6f62d2fd9fc5e356db706905cb42cb6ca129ab25e"
  command: /usr/local/bin/builder.sh /usr/local/bin/ansible-playbook -i /etc/ansible/ansible-container-inventory.py -c docker  --list-hosts main.yml
  environment:
    - DOCKER_HOST=unix:///var/run/docker.sock
    
    
    - COMPOSE_HTTP_TIMEOUT=3000
    - DOCKER_API_VERSION=1.24
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    
    - /home/vpjapp/git/talentum/ansible-container-bug:/ansible-container/:Z
  working_dir: /ansible-container/ansible/
  stdin_open: true
  tty: true
test-se:
  command: sh -c "while true; do sleep 1; done"
  entrypoint: []
  image: ubuntu:trusty
  user: root
  working_dir: /

Cleaning up Ansible Container builder...
--list-hosts
ansible-container_1  | 
ansible-container_1  | playbook: main.yml
ansible-container_1  | 
ansible-container_1  |   play #1 (test-se): 	TAGS: []
ansible-container_1  |     pattern: [u'test-se']
ansible-container_1  |     hosts (0):
ansible_ansible-container_1 exited with code 0

Cleaning up temporary directory /tmp/tmpO_1fUS...
Orchestrated hosts: []
No image found for tag ansible-container-bug-test-se:latest, so building from scratch
{'test-se': {'image': 'ubuntu:trusty', 'entrypoint': ['/bin/bash', '-c', 'tail -f /var/log/dmesg']}}
Config YAML is
test-se:
  entrypoint: [/bin/bash, -c, tail -f /var/log/dmesg]
  image: ubuntu:trusty

Rendered Jinja Template:
ansible-container:
  # If no $DOCKER_HOST then we need to run privileged so we can access /var/run/docker.sock
  privileged: true
  image: "sha256:16eaadfbd806531a702336c6f62d2fd9fc5e356db706905cb42cb6ca129ab25e"
  command: "/usr/local/bin/builder.sh /usr/local/bin/ansible-playbook -vvv -i /etc/ansible/ansible-container-inventory.py -c docker  main.yml"
  environment:
    - DOCKER_HOST=unix:///var/run/docker.sock
    
    
    - COMPOSE_HTTP_TIMEOUT=3000
    - DOCKER_API_VERSION=1.24
    
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    
    - /home/vpjapp/git/talentum/ansible-container-bug:/ansible-container/:Z
    
  working_dir: /ansible-container/ansible/
test-se:
  entrypoint: [/bin/bash, -c, tail -f /var/log/dmesg]
  image: ubuntu:trusty

Attaching to ansible_ansible-container_1
Attaching to ansible_ansible-container_1
Attaching to ansible_ansible-container_1, ansible_test-se_1
test-se_1            | (Nothing has been logged yet.)
ansible-container_1  | No config file found; using defaults
ansible-container_1  | 1 plays in main.yml
ansible-container_1  | 
ansible-container_1  | PLAY ***************************************************************************
ansible-container_1  | skipping: no hosts matched
ansible-container_1  | 
ansible-container_1  | PLAY RECAP *********************************************************************
ansible-container_1  | 
ansible_ansible-container_1 exited with code 0
Stopping ansible_test-se_1 ... done
Exporting built containers as images...
Cleaning up Ansible Container builder...
Cleaning up temporary directory /tmp/tmpJ_XcMs...
Aborting on container exit...
```

If you change the hosts to all, it will show that it matches and the matched host is test-{{target_env}} and not test-se as it should.

```
ansible-container_1  | 
ansible-container_1  | playbook: main.yml
ansible-container_1  | 
ansible-container_1  |   play #1 (all): 	TAGS: []
ansible-container_1  |     pattern: [u'all']
ansible-container_1  |     hosts (1):
ansible-container_1  |       test-{{target_env}}
ansible_ansible-container_1 exited with code 0

```

Relates to the new feature "Jinja2 template rendering in container.yml" #183

**Comment by chouseknecht** [comment]
Template rendering of the service name was not meant to work. If you peek at the code, you will see a comment to this effect [on line 39 of config.py](https://github.com/ansible/ansible-container/blob/develop/container/config.py#L39)

**Why?** Because services names are fed into the playbook as host names by way of an inventory script, and I really don't want to duplicate all of the template rendering logic in the inventory script. At some point we may be forced to either duplicate the code, or perhaps store the rendered result to disk, mount it into the Ansible Builder Container, and point the inventory script at it. In the meantime, it simply means you cannot use a variable name as a service name, which feels like a very minor inconvenience.

**Apologies** for the inconvenience. Working on documentation now that will hopefully explain how to use template rendering in container.yml and avoid issues such as this. Your patience is appreciated.

**Comment by vpjapp-avoltus** [comment]
Thanks for the fast reply and explanation!
I totally understand this not being a top priority, so no need for apologies.

Actually I was first trying to use the docker containers _container_name_-property, but could not get that to work, so this was to be kind of a workaround for that. Is that a known issue/shortcoming or could that perhaps be fixed/supported? I thought that the service-templating might have been easier to fix that this so I made this issue instead of about the container_name. And would there be similar limitations with templating with the container_name?
https://docs.docker.com/compose/compose-file/#container-name
I can make another issue about that with details if that would be useful.

**Comment by chouseknecht** [comment]
@vpjapp-avoltus, after doing some more testing I discovered a few bugs in the template implementation and refactored it. Your example now works. 

One thing to note, environment variables should be prefixed with 'AC' and uppercase. So in your example, change the environment variable to the following:

```
export AC_TARGET_ENV=se
```  

In the code we remove 'AC' and convert the to lowercase, so your container.yml works just as you have it.

**Comment by vpjapp-avoltus** [comment]
@chouseknecht: Hey great! You guys are fast responders =)
I'll try this on my real case, but it looks good. Thanks a bunch!

Thanks also for the note about env variables. I had missed the uppercase part.

**Comment by vpjapp-avoltus** [comment]
One observation: For the templating to work with services after the #209  fix there still needs to be
```
vars:
  - paramname: "paramvalue"
```
in the playbook. Otherwise it will fail with 
```
ansible-container_1  | No config file found; using defaults
ansible-container_1  | 1 plays in main.yml
ansible-container_1  | 
ansible-container_1  | PLAY ***************************************************************************
ansible-container_1  | 
ansible-container_1  | TASK [debug] *******************************************************************
ansible-container_1  | task path: /ansible-container/ansible/main.yml:12
ansible-container_1  | fatal: [test-{{target_env}}]: FAILED! => {"failed": true, "msg": "'target_env' is undefined"}
ansible-container_1  | 
ansible-container_1  | NO MORE HOSTS LEFT *************************************************************
ansible-container_1  | 	to retry, use: --limit @main.retry
ansible-container_1  | 
ansible-container_1  | PLAY RECAP *********************************************************************
ansible-container_1  | test-{{target_env}}        : ok=0    changed=0    unreachable=0    failed=1   
ansible-container_1  | 
ansible_ansible-container_1 exited with code 2
```
I did have that in my test case, so you are right about the test case working, but that may be little confusing for users.

**Comment by chouseknecht** [comment]
@vpjapp-avoltus 

Yes, using env variables works for sharing variables between AC and a playbook. It might be easier, however, to put the vars in a file. 

You can pass a file to AC using --var-file, and pass the same file to the playbook using -e"@filename.yml" or at a play level inside the playbook using the var_files directive.

Passing to the playbook via the -e option would look something like the following:

```
ansible-container --var-file myvars.yml build -- -e"@myvars.yml"
```

**Comment by vpjapp-avoltus** [comment]
@chouseknecht 
Thanks. The var-file is indeed more convenient method. And I was unaware that you can do -e "@var-file.yml", that's cool =)

With those mods (and btw with the env-method also) the build goes through nicely, but when the images are being created, it fails. I assume it has something to do with that part not handling the templated service name correctly, but that's just a guess. This is how the  build ends:
```
ansible-container_1  | 
ansible-container_1  | PLAY RECAP *********************************************************************
ansible-container_1  | test-{{target_env}}        : ok=5    changed=2    unreachable=0    failed=0   
ansible-container_1  | 
ansible_ansible-container_1 exited with code 0
Aborting on container exit...
Stopping ansible_test-se_1 ... done
Exporting built containers as images...
Cleaning up temporary directory /tmp/tmpHVO32P...
need more than 0 values to unpack
Traceback (most recent call last):
  File "/home/vpjapp/git/talentum/talentum-ansible-container-dev/ansible-container-dev/container/cli.py", line 195, in commandline
    getattr(engine, u'cmdrun_{}'.format(args.subcommand))(**vars(args))
  File "/home/vpjapp/git/talentum/talentum-ansible-container-dev/ansible-container-dev/container/engine.py", line 325, in cmdrun_build
    engine_obj.post_build(host, version, flatten=flatten, purge_last=purge_last)
  File "/home/vpjapp/git/talentum/talentum-ansible-container-dev/ansible-container-dev/container/docker/engine.py", line 561, in post_build
    limit=1, all=True, quiet=True
ValueError: need more than 0 values to unpack

```

It might be that nothing was changed in the previous test, so this did not come up. I added a lineinfile task to make a change:
```
- hosts: test-*
  gather_facts: false
  tasks:
    - debug: var=inventory_hostname
    - raw: which python || apt-get update
    - raw: (which python && which aptitude) || apt-get install -y python python-apt aptitude
    - command: "echo Hello world!"
    - lineinfile:
        dest: /tmp/test
        line: "Just to make a change"
        create: yes

```

**Comment by vpjapp-avoltus** [comment]
Seems that this nowadays works! =) Great. Thanks.
(In case someone sees my last comment complaining it does not work.)
