### ISSUE TITLE
Shipit kube command fails when listing multiple ports

### ISSUE THREAD

**Issue by nonotest** [ansible/ansible-container#253]
##### ISSUE TYPE

- Bug Report
##### container.yml

```
version: "1"
services:
 jenkins-master:
  image: jenkins:2.7.4
  command: ['/usr/bin/dumb-init', '/usr/local/bin/jenkins.sh']
  user: jenkins
  ports:
    - "8080:8080"
    - "50000:50000"
  volumes:
    - "/var/jenkins_home"
  dev_overrides:
   volumes:
    - '~/tmp/jenkins_home:/var/jenkins_home'
  options:
   kube:
    runAsUser: 1000
registries:
 google:
  url: asia.gcr.io
  namespace: ci-cd
```
##### main.yml

```
- hosts: jenkins-master
  tasks:
    - name: Install dumb init
      get_url: dest=/usr/bin/dumb-init url=https://github.com/Yelp/dumb-init/releases/download/v1.1.3/dumb-init_1.1.3_amd64 mode=0775 validate_certs=no
    - name: Update cache
      apt: update_cache=yes
    - name: Install vim
      apt: name=vim state=latest
    - name: Copy plugin file
      copy: src=jenkins-plugins.txt dest=/usr/share/jenkins/ref/plugins.txt

```
##### OS / ENVIRONMENT

```
Ansible Container, version 0.2.0-pre
Darwin, AM-MBP.local, 15.6.0, Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64, x86_64
2.7.12 (default, Jun 29 2016, 14:05:02)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] /usr/local/opt/python/bin/python2.7
No DOCKER_HOST environment variable found. Assuming UNIX socket at /var/run/docker.sock
{u'Architecture': u'x86_64',
 u'BridgeNfIp6tables': True,
 u'BridgeNfIptables': True,
 u'CPUSet': True,
 u'CPUShares': True,
 u'CgroupDriver': u'cgroupfs',
 u'ClusterAdvertise': u'',
 u'ClusterStore': u'',
 u'Containers': 2,
 u'ContainersPaused': 0,
 u'ContainersRunning': 0,
 u'ContainersStopped': 2,
 u'CpuCfsPeriod': True,
 u'CpuCfsQuota': True,
 u'Debug': True,
 u'DefaultRuntime': u'runc',
 u'DockerRootDir': u'/var/lib/docker',
 u'Driver': u'aufs',
 u'DriverStatus': [[u'Root Dir', u'/var/lib/docker/aufs'],
                   [u'Backing Filesystem', u'extfs'],
                   [u'Dirs', u'34'],
                   [u'Dirperm1 Supported', u'true']],
 u'ExecutionDriver': u'',
 u'ExperimentalBuild': True,
 u'HttpProxy': u'',
 u'HttpsProxy': u'',
 u'ID': u'4UTH:SQ3O:ZLLD:TQ66:EFOH:OVOW:X3M4:QFY6:4ZOE:TMBX:REDT:QRYF',
 u'IPv4Forwarding': True,
 u'Images': 3,
 u'IndexServerAddress': u'https://index.docker.io/v1/',
 u'KernelMemory': True,
 u'KernelVersion': u'4.4.20-moby',
 u'Labels': None,
 u'LiveRestoreEnabled': False,
 u'LoggingDriver': u'json-file',
 u'MemTotal': 8360996864,
 u'MemoryLimit': True,
 u'NCPU': 4,
 u'NEventsListener': 2,
 u'NFd': 18,
 u'NGoroutines': 32,
 u'Name': u'moby',
 u'NoProxy': u'*.local, 169.254/16',
 u'OSType': u'linux',
 u'OomKillDisable': True,
 u'OperatingSystem': u'Alpine Linux v3.4',
 u'Plugins': {u'Authorization': None,
              u'Network': [u'bridge', u'null', u'host', u'overlay'],
              u'Volume': [u'local']},
 u'RegistryConfig': {u'IndexConfigs': {u'docker.io': {u'Mirrors': None,
                                                      u'Name': u'docker.io',
                                                      u'Official': True,
                                                      u'Secure': True}},
                     u'InsecureRegistryCIDRs': [u'127.0.0.0/8'],
                     u'Mirrors': None},
 u'Runtimes': {u'runc': {u'path': u'docker-runc'}},
 u'SecurityOptions': [u'seccomp'],
 u'ServerVersion': u'1.12.1',
 u'SwapLimit': True,
 u'Swarm': {u'Cluster': {u'CreatedAt': u'0001-01-01T00:00:00Z',
                         u'ID': u'',
                         u'Spec': {u'CAConfig': {},
                                   u'Dispatcher': {},
                                   u'Orchestration': {},
                                   u'Raft': {},
                                   u'TaskDefaults': {}},
                         u'UpdatedAt': u'0001-01-01T00:00:00Z',
                         u'Version': {}},
            u'ControlAvailable': False,
            u'Error': u'',
            u'LocalNodeState': u'inactive',
            u'Managers': 0,
            u'NodeAddr': u'',
            u'NodeID': u'',
            u'Nodes': 0,
            u'RemoteManagers': None},
 u'SystemStatus': None,
 u'SystemTime': u'2016-09-26T04:50:32.283730696Z'}
{u'ApiVersion': u'1.24',
 u'Arch': u'amd64',
 u'BuildTime': u'2016-08-18T17:32:24.504694950+00:00',
 u'Experimental': True,
 u'GitCommit': u'23cf638',
 u'GoVersion': u'go1.6.3',
 u'KernelVersion': u'4.4.20-moby',
 u'Os': u'linux',
 u'Version': u'1.12.1'}
```
##### SUMMARY

Shipit kube command fails when listing multiple ports.
Example works if only using 1 port 
##### STEPS TO REPRODUCE

```
ansible-container shipit kube  --pull-from test
```

##### EXPECTED RESULTS

Properly generate the kube role
##### ACTUAL RESULTS

```
Cleaning up temporary directory /var/folders/7b/9vsp8rz50v70wdd61svzgjzc0000gn/T/tmpkjHeDq...
volume: /var/jenkins_home
source: None destination: /var/jenkins_home permissions: None
'int' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/container/cli.py", line 195, in commandline
    getattr(engine, u'cmdrun_{}'.format(args.subcommand))(**vars(args))
  File "/usr/local/lib/python2.7/site-packages/container/engine.py", line 425, in cmdrun_shipit
    shipit_engine_obj.run()
  File "/usr/local/lib/python2.7/site-packages/container/shipit/kubernetes/engine.py", line 27, in run
    tasks += Deployment(config=self.config, project_name=self.project_name).get_task()
  File "/usr/local/lib/python2.7/site-packages/container/shipit/kubernetes/deployment.py", line 28, in get_task
    return self._get_template_or_task(request_type="task", service_names=service_names)
  File "/usr/local/lib/python2.7/site-packages/container/shipit/kubernetes/deployment.py", line 33, in _get_template_or_task
    new_template = self._create(request_type, name, service)
  File "/usr/local/lib/python2.7/site-packages/container/shipit/kubernetes/deployment.py", line 43, in _create
    container, volumes, pod = self._service_to_container(name, service, type=type)
  File "/usr/local/lib/python2.7/site-packages/container/shipit/kubernetes/deployment.py", line 241, in _service_to_container
    self._get_ports(value, type, container['ports'])
  File "/usr/local/lib/python2.7/site-packages/container/shipit/kubernetes/deployment.py", line 350, in _get_ports
    if not self._port_exists(parts[1], existing_ports):
  File "/usr/local/lib/python2.7/site-packages/container/shipit/kubernetes/deployment.py", line 366, in _port_exists
    if p['containerPort'] == int(port):
TypeError: 'int' object has no attribute '__getitem__'
```

**Comment by dalethestirling** [comment]
I have created pull request https://github.com/ansible/ansible-container/pull/277 that resolves this issue.
