### ISSUE TITLE
--pull-from fails with shipit

### ISSUE THREAD

**Issue by containscafeine** [ansible/ansible-container#265]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The command `ansible-container shipit  kube --save-config --pull-from docker.io/containscafeine` fails.

##### STEPS TO REPRODUCE
```bash
$ ac --debug shipit kube --pull-from docker.io/containscafeine
Project name is example
Failed to load ansible.plugin.filters - No module named ansible.plugins.filter
Default vars:
{}
Getting environment variables...
Template variables:
 {}
Config:
{
    "services": {
        "webclient": {
            "command": [
                "./tmp/client.sh"
            ],
            "expose": [
                "9998"
            ],
            "image": "centos:7",
            "links": [
                "webserver"
            ]
        },
        "webserver": {
            "command": [
                "/usr/sbin/apachectl",
                "-DFOREGROUND"
            ],
            "expose": [
                "80"
            ],
            "image": "centos:7"
        }
    },
    "version": "1"
}
Initialized with params: {'with_volumes': [], 'shipit_engine': 'kube', 'with_variables': [], 'subcommand': 'shipit', 'var_file': None, 'engine_args': {'with_volumes': [], 'shipit_engine': 'kube', 'engine_name': 'docker', 'with_variables': [], 'subcommand': 'shipit', 'var_file': None, 'engine_args': {...}, 'base_path': '/vagrant/example', 'save_config': False, 'roles_path': None, 'kwargs': {'with_volumes': [], 'shipit_engine': 'kube', 'with_variables': [], 'subcommand': 'shipit', 'var_file': None, 'save_config': False, 'roles_path': None, 'debug': True}, 'debug': True, 'pull_from': 'docker.io/containscafeine'}, 'save_config': False, 'roles_path': None, 'kwargs': {'with_volumes': [], 'shipit_engine': 'kube', 'with_variables': [], 'subcommand': 'shipit', 'var_file': None, 'save_config': False, 'roles_path': None, 'debug': True}, 'debug': True, 'pull_from': 'docker.io/containscafeine'}
'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/vagrant/ansible-container/container/cli.py", line 209, in commandline
    getattr(engine, u'cmdrun_{}'.format(args.subcommand))(**vars(args))
  File "/home/vagrant/ansible-container/container/engine.py", line 407, in cmdrun_shipit
    elif config.get('registries', {}).get(pull_from):
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by j00bar** [comment]
@containscafeine Test with my PR to confirm resolved? Thanks!
