### ISSUE TITLE
Just crashes on first run

### ISSUE THREAD

**Issue by dmilith** [ansible/ansible-container#371]
Installed via

```
⇢ pip install ansible-container
Collecting ansible-container
  Downloading ansible-container-0.2.0.tar.gz (53kB)
    100% |████████████████████████████████| 61kB 522kB/s
Requirement already satisfied: docker-compose==1.7.0 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from ansible-container)
Requirement already satisfied: docker-py==1.8.0 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from ansible-container)
Requirement already satisfied: Jinja2==2.8 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from ansible-container)
Requirement already satisfied: PyYAML==3.11 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from ansible-container)
Requirement already satisfied: requests==2.7.0 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from ansible-container)
Requirement already satisfied: cached-property<2,>=1.2.0 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from docker-compose==1.7.0->ansible-container)
Requirement already satisfied: docopt<0.7,>=0.6.1 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from docker-compose==1.7.0->ansible-container)
Requirement already satisfied: texttable<0.9,>=0.8.1 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from docker-compose==1.7.0->ansible-container)
Requirement already satisfied: websocket-client<1.0,>=0.32.0 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from docker-compose==1.7.0->ansible-container)
Requirement already satisfied: dockerpty<0.5,>=0.4.1 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from docker-compose==1.7.0->ansible-container)
Requirement already satisfied: six<2,>=1.3.0 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from docker-compose==1.7.0->ansible-container)
Requirement already satisfied: jsonschema<3,>=2.5.1 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from docker-compose==1.7.0->ansible-container)
Requirement already satisfied: MarkupSafe in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from Jinja2==2.8->ansible-container)
Installing collected packages: ansible-container
  Running setup.py install for ansible-container ... done
Successfully installed ansible-container-0.2.0
```

first try:

```
⇢ ansible-container init tschifftner.php5-fpm
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/ansible-container", line 9, in <module>
    load_entry_point('ansible-container==0.2.0', 'console_scripts', 'ansible-container')()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/container/cli.py", line 213
    except exceptions.AnsibleContainerAlreadyInitializedException, e:
                                                                 ^
SyntaxError: invalid syntax
```

System: OSX 10.12.3.

**Comment by dmilith** [comment]
Also doesn't work using virtualenv "instructions" - nothing like `ansible-container/bin/activate` to read...

**Comment by dmilith** [comment]
Also "installation from source" doesn't work:

```
⇢ python ./setup.py install
Traceback (most recent call last):
  File "./setup.py", line 2, in <module>
    from pip.req import parse_requirements
ImportError: No module named pip.req
```

**Comment by dmilith** [comment]
It picks python3 by default. Cool stuff.
