### ISSUE TITLE
The "copy" task is not working

### ISSUE THREAD

**Issue by elad** [ansible/ansible-container#393]
##### ISSUE TYPE

 - Bug Report

##### container.yml 

```
version: "1"
services:
  myapp:
    image: python:2-onbuild
    ports:
      - "8080:8080"
    command: ['python', '/usr/src/app/myapp/main.py']
```

##### main.yml 

```
- hosts: myapp
  gather_facts: false
  tasks:
    - name: Copy app
      copy:
        src: ..
        dest: /usr/src/app
    - name: Install requirements
      pip:
        executable: pip
        requirements: /usr/src/app/requirements.txt
```

##### OS / ENVIRONMENT

```
$ ansible-container --debug version
Ansible Container, version 0.2.0
Darwin, mbp.local, 16.4.0, Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64, x86_64
2.7.13 (default, Dec 18 2016, 07:03:39) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] /usr/local/opt/python/bin/python2.7
No DOCKER_HOST environment variable found. Assuming UNIX socket at /var/run/docker.sock
{u'Architecture': u'x86_64',
 u'BridgeNfIp6tables': True,
 u'BridgeNfIptables': True,
 u'CPUSet': True,
 u'CPUShares': True,
 u'CgroupDriver': u'cgroupfs',
 u'ClusterAdvertise': u'',
 u'ClusterStore': u'',
 u'ContainerdCommit': {u'Expected': u'977c511eda0925a723debdc94d09459af49d082a',
                       u'ID': u'977c511eda0925a723debdc94d09459af49d082a'},
 u'Containers': 1,
 u'ContainersPaused': 0,
 u'ContainersRunning': 0,
 u'ContainersStopped': 1,
 u'CpuCfsPeriod': True,
 u'CpuCfsQuota': True,
 u'Debug': True,
 u'DefaultRuntime': u'runc',
 u'DockerRootDir': u'/var/lib/docker',
 u'Driver': u'aufs',
 u'DriverStatus': [[u'Root Dir', u'/var/lib/docker/aufs'],
                   [u'Backing Filesystem', u'extfs'],
                   [u'Dirs', u'20'],
                   [u'Dirperm1 Supported', u'true']],
 u'ExperimentalBuild': True,
 u'HttpProxy': u'',
 u'HttpsProxy': u'',
 u'ID': u'HBFQ:TU6L:XQQV:5JQV:DBKW:5JAI:6ZRX:KIMH:QX3C:N2OX:5JFA:IZMO',
 u'IPv4Forwarding': True,
 u'Images': 3,
 u'IndexServerAddress': u'https://index.docker.io/v1/',
 u'InitBinary': u'docker-init',
 u'InitCommit': {u'Expected': u'949e6fa', u'ID': u'949e6fa'},
 u'Isolation': u'',
 u'KernelMemory': True,
 u'KernelVersion': u'4.9.12-moby',
 u'Labels': None,
 u'LiveRestoreEnabled': False,
 u'LoggingDriver': u'json-file',
 u'MemTotal': 2096185344,
 u'MemoryLimit': True,
 u'NCPU': 2,
 u'NEventsListener': 1,
 u'NFd': 17,
 u'NGoroutines': 28,
 u'Name': u'moby',
 u'NoProxy': u'*.local, 169.254/16',
 u'OSType': u'linux',
 u'OomKillDisable': True,
 u'OperatingSystem': u'Alpine Linux v3.5',
 u'Plugins': {u'Authorization': None,
              u'Network': [u'bridge',
                           u'host',
                           u'ipvlan',
                           u'macvlan',
                           u'null',
                           u'overlay'],
              u'Volume': [u'local']},
 u'RegistryConfig': {u'IndexConfigs': {u'docker.io': {u'Mirrors': None,
                                                      u'Name': u'docker.io',
                                                      u'Official': True,
                                                      u'Secure': True}},
                     u'InsecureRegistryCIDRs': [u'127.0.0.0/8'],
                     u'Mirrors': []},
 u'RuncCommit': {u'Expected': u'a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70',
                 u'ID': u'a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70'},
 u'Runtimes': {u'runc': {u'path': u'docker-runc'}},
 u'SecurityOptions': [u'name=seccomp,profile=default'],
 u'ServerVersion': u'17.03.0-ce',
 u'SwapLimit': True,
 u'Swarm': {u'Cluster': {u'CreatedAt': u'0001-01-01T00:00:00Z',
                         u'ID': u'',
                         u'Spec': {u'CAConfig': {},
                                   u'Dispatcher': {},
                                   u'EncryptionConfig': {u'AutoLockManagers': False},
                                   u'Orchestration': {},
                                   u'Raft': {u'ElectionTick': 0,
                                             u'HeartbeatTick': 0},
                                   u'TaskDefaults': {}},
                         u'UpdatedAt': u'0001-01-01T00:00:00Z',
                         u'Version': {}},
            u'ControlAvailable': False,
            u'Error': u'',
            u'LocalNodeState': u'inactive',
            u'Managers': 0,
            u'NodeAddr': u'',
            u'NodeID': u'',
            u'Nodes': 0,
            u'RemoteManagers': None},
 u'SystemStatus': None,
 u'SystemTime': u'2017-03-12T16:51:05.03065932Z'}
{u'ApiVersion': u'1.26',
 u'Arch': u'amd64',
 u'BuildTime': u'2017-02-28T07:52:04.010823282+00:00',
 u'Experimental': True,
 u'GitCommit': u'3a232c8',
 u'GoVersion': u'go1.7.5',
 u'KernelVersion': u'4.9.12-moby',
 u'MinAPIVersion': u'1.12',
 u'Os': u'linux',
 u'Version': u'17.03.0-ce'}
$ 
```
##### SUMMARY

I'm trying to build and deploy a container with ansible-container. I already have it working with Docker. The root of the project is in `myapp` and ansible's stuff is in `myapp/ansible`. For some reason the `copy` isn't working right. When the `src` is set to `..` it's not working at all (I expected a recursive copy). When `src` is set to `../` the copy is working, but it's not recursive (this seems to be consistent with documentation).

I assume I'm missing something very obvious, any help figuring out what it is would be greatly appreciated. :)

##### STEPS TO REPRODUCE

```
ansible-container --debug  build --from-scratch
```

##### EXPECTED RESULTS

I expected the parent directory (`..`) to be copied recursively to the container at `/usr/src/app`.

##### ACTUAL RESULTS

It doesn't seem like anything is copied at all. The next task, which is supposed to install pip requirements, can't find the file at all. Since the file is at the top level, not even a "shallow" copy is made.

```
$ ansible-container --debug  build --from-scratch
No DOCKER_HOST environment variable found. Assuming UNIX socket at /var/run/docker.sock
Project name is myapp
Failed to load ansible.plugin.filters - No module named ansible.plugins.filter
Default vars:
{}
Getting environment variables...
Template variables:
 {}
Config:
{
    "services": {
        "myapp": {
            "command": [
                "python",
                "/usr/src/app/myapp/main.py"
            ],
            "image": "python:2-onbuild",
            "ports": [
                "8080:8080"
            ]
        }
    },
    "version": "1"
}
Initialized with params: {'with_volumes': [], 'local_builder': False, 'service': None, 'with_variables': [], 'rebuild': True, 'subcommand': 'build', 'var_file': None, 'engine_args': {'local_builder': False, 'subcommand': 'build', 'base_path': '/Users/elad/Developer/nsof/ansible/myapp', 'ansible_options': u'', 'flatten': False, 'no_purge_last': True, 'with_volumes': [], 'service': None, 'engine_name': 'docker', 'with_variables': [], 'rebuild': True, 'var_file': None, 'engine_args': {...}, 'save_build_container': False, 'roles_path': None, 'kwargs': {'with_volumes': [], 'with_variables': [], 'subcommand': 'build', 'var_file': None, 'debug': True, 'no_purge_last': True}, 'debug': True, 'purge_last': True}, 'save_build_container': False, 'purge_last': True, 'roles_path': None, 'ansible_options': u'', 'flatten': False, 'kwargs': {'with_volumes': [], 'with_variables': [], 'subcommand': 'build', 'var_file': None, 'debug': True, 'no_purge_last': True}, 'debug': True, 'no_purge_last': True}
Using temporary directory /var/folders/r1/9g6vpzy92dv7smm35bjy71sh0000gn/T/tmpj5qZUO...
Starting Docker Compose engine to build your images...
Using temporary directory /var/folders/r1/9g6vpzy92dv7smm35bjy71sh0000gn/T/tmpKQkNr5...
Compose derived from config:
{'myapp': {'image': 'python:2-onbuild', 'command': ['python', '/usr/src/app/myapp/main.py'], 'ports': ['8080:8080']}}
{'myapp': {'working_dir': '/', 'command': 'sh -c "while true; do sleep 1; done"', 'user': 'root', 'entrypoint': [], 'image': 'python:2-onbuild', 'ports': ['8080:8080']}}
Config YAML is
myapp:
  command: sh -c "while true; do sleep 1; done"
  entrypoint: []
  image: python:2-onbuild
  ports: ['8080:8080']
  user: root
  working_dir: /

Rendered Jinja Template:
ansible-container:
  # If no $DOCKER_HOST then we need to run privileged so we can access /var/run/docker.sock
  privileged: true
  image: "ansible/ansible-container-builder:0.2"
  command: /usr/local/bin/builder.sh /usr/bin/ansible-playbook -i /etc/ansible/ansible-container-inventory.py -c docker  --list-hosts main.yml
  environment:
    - DOCKER_HOST=unix:///var/run/docker.sock
    
    
    - COMPOSE_HTTP_TIMEOUT=3000
    - DOCKER_API_VERSION=1.26
    - ANSIBLE_ORCHESTRATED_HOSTS=myapp
    - ANSIBLE_CONTAINER=1
    
    
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    
    - /Users/elad/Developer/nsof/ansible/myapp:/ansible-container/:Z
    
    
  working_dir: /ansible-container/ansible/
  stdin_open: true
  tty: true
myapp:
  command: sh -c "while true; do sleep 1; done"
  entrypoint: []
  image: python:2-onbuild
  ports: ['8080:8080']
  user: root
  working_dir: /

Attaching to ansible_ansible-container_1
Cleaning up Ansible Container builder...
--list-hosts
ansible-container_1  | Host myapp failed
ansible-container_1  | 
ansible-container_1  | playbook: main.yml
ansible-container_1  | 
ansible-container_1  |   play #1 (myapp): myapp TAGS: []
ansible-container_1  |     pattern: [u'myapp']
ansible-container_1  |     hosts (1):
ansible-container_1  |       myapp
ansible_ansible-container_1 exited with code 0

Cleaning up temporary directory /var/folders/r1/9g6vpzy92dv7smm35bjy71sh0000gn/T/tmpKQkNr5...
Compose derived from config:
{'myapp': {'image': 'python:2-onbuild', 'command': ['python', '/usr/src/app/myapp/main.py'], 'ports': ['8080:8080']}}
Orchestrated hosts: ['myapp']
Setting myapp to sleep
{'myapp': {'environment': {'ANSIBLE_CONTAINER': 1}, 'working_dir': '/', 'command': 'sh -c "while true; do sleep 1; done"', 'user': 'root', 'entrypoint': [], 'image': 'python:2-onbuild', 'ports': ['8080:8080']}}
Config YAML is
myapp:
  command: sh -c "while true; do sleep 1; done"
  entrypoint: []
  environment: {ANSIBLE_CONTAINER: 1}
  image: python:2-onbuild
  ports: ['8080:8080']
  user: root
  working_dir: /

Rendered Jinja Template:
ansible-container:
  # If no $DOCKER_HOST then we need to run privileged so we can access /var/run/docker.sock
  privileged: true
  image: "ansible/ansible-container-builder:0.2"
  command: "/usr/local/bin/builder.sh /usr/bin/ansible-playbook -vvv -i /etc/ansible/ansible-container-inventory.py -c docker  main.yml"
  environment:
    - DOCKER_HOST=unix:///var/run/docker.sock
    
    
    - COMPOSE_HTTP_TIMEOUT=3000
    - DOCKER_API_VERSION=1.26
    - ANSIBLE_ORCHESTRATED_HOSTS=myapp
    - ANSIBLE_CONTAINER=1
    
    
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    
    - /Users/elad/Developer/nsof/ansible/myapp:/ansible-container/:Z
    
    
  working_dir: /ansible-container/ansible/
myapp:
  command: sh -c "while true; do sleep 1; done"
  entrypoint: []
  environment: {ANSIBLE_CONTAINER: 1}
  image: python:2-onbuild
  ports: ['8080:8080']
  user: root
  working_dir: /

Attaching to ansible_ansible-container_1, ansible_myapp_1
ansible-container_1  | Host myapp running
ansible-container_1  | Using /ansible-container/ansible/ansible.cfg as config file
ansible-container_1  | 
ansible-container_1  | PLAYBOOK: main.yml *************************************************************
ansible-container_1  | 1 plays in main.yml
ansible-container_1  | 
ansible-container_1  | PLAY [myapp] *******************************************************************
ansible-container_1  | 
ansible-container_1  | TASK [Copy app] ****************************************************************
ansible-container_1  | task path: /ansible-container/ansible/main.yml:4
ansible-container_1  | <ansible_myapp_1> ESTABLISH DOCKER CONNECTION FOR USER: root
ansible-container_1  | <ansible_myapp_1> EXEC ['/usr/bin/docker', 'exec', '-i', u'ansible_myapp_1', u'/bin/sh', '-c', u'/bin/sh -c \'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1489337797.93-52329737410342 `" && echo ansible-tmp-1489337797.93-52329737410342="` echo $HOME/.ansible/tmp/ansible-tmp-1489337797.93-52329737410342 `" ) && sleep 0\'']
ansible-container_1  | <ansible_myapp_1> PUT /tmp/tmpDeGVtg TO /root/.ansible/tmp/ansible-tmp-1489337797.93-52329737410342/stat
ansible-container_1  | <ansible_myapp_1> EXEC ['/usr/bin/docker', 'exec', '-i', u'ansible_myapp_1', u'/bin/sh', '-c', u"/bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1489337797.93-52329737410342/stat && sleep 0'"]
ansible-container_1  | <ansible_myapp_1> PUT /ansible-container/ansible/ansible.cfg TO /root/.ansible/tmp/ansible-tmp-1489337797.93-52329737410342/source
ansible-container_1  | <ansible_myapp_1> PUT /tmp/tmpl5da09 TO /root/.ansible/tmp/ansible-tmp-1489337797.93-52329737410342/copy
ansible-container_1  | <ansible_myapp_1> EXEC ['/usr/bin/docker', 'exec', '-i', u'ansible_myapp_1', u'/bin/sh', '-c', u"/bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1489337797.93-52329737410342/copy && sleep 0'"]
ansible-container_1  | <ansible_myapp_1> PUT /tmp/tmpwbRp1b TO /root/.ansible/tmp/ansible-tmp-1489337797.93-52329737410342/stat
ansible-container_1  | <ansible_myapp_1> EXEC ['/usr/bin/docker', 'exec', '-i', u'ansible_myapp_1', u'/bin/sh', '-c', u"/bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1489337797.93-52329737410342/stat && sleep 0'"]
ansible-container_1  | <ansible_myapp_1> PUT /ansible-container/ansible/container.yml TO /root/.ansible/tmp/ansible-tmp-1489337797.93-52329737410342/source
ansible-container_1  | <ansible_myapp_1> PUT /tmp/tmpyh53G1 TO /root/.ansible/tmp/ansible-tmp-1489337797.93-52329737410342/copy
ansible-container_1  | <ansible_myapp_1> EXEC ['/usr/bin/docker', 'exec', '-i', u'ansible_myapp_1', u'/bin/sh', '-c', u"/bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1489337797.93-52329737410342/copy && sleep 0'"]
ansible-container_1  | <ansible_myapp_1> PUT /tmp/tmpjF8_mC TO /root/.ansible/tmp/ansible-tmp-1489337797.93-52329737410342/stat
ansible-container_1  | <ansible_myapp_1> EXEC ['/usr/bin/docker', 'exec', '-i', u'ansible_myapp_1', u'/bin/sh', '-c', u"/bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1489337797.93-52329737410342/stat && sleep 0'"]
ansible-container_1  | <ansible_myapp_1> PUT /ansible-container/ansible/main.yml TO /root/.ansible/tmp/ansible-tmp-1489337797.93-52329737410342/source
ansible-container_1  | <ansible_myapp_1> PUT /tmp/tmpcQKn9w TO /root/.ansible/tmp/ansible-tmp-1489337797.93-52329737410342/copy
ansible-container_1  | <ansible_myapp_1> EXEC ['/usr/bin/docker', 'exec', '-i', u'ansible_myapp_1', u'/bin/sh', '-c', u"/bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1489337797.93-52329737410342/copy && sleep 0'"]
ansible-container_1  | <ansible_myapp_1> PUT /tmp/tmpPaQJBN TO /root/.ansible/tmp/ansible-tmp-1489337797.93-52329737410342/stat
ansible-container_1  | <ansible_myapp_1> EXEC ['/usr/bin/docker', 'exec', '-i', u'ansible_myapp_1', u'/bin/sh', '-c', u"/bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1489337797.93-52329737410342/stat && sleep 0'"]
ansible-container_1  | <ansible_myapp_1> PUT /ansible-container/ansible/requirements.txt TO /root/.ansible/tmp/ansible-tmp-1489337797.93-52329737410342/source
ansible-container_1  | <ansible_myapp_1> PUT /tmp/tmpTAJDDW TO /root/.ansible/tmp/ansible-tmp-1489337797.93-52329737410342/copy
ansible-container_1  | <ansible_myapp_1> EXEC ['/usr/bin/docker', 'exec', '-i', u'ansible_myapp_1', u'/bin/sh', '-c', u"/bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1489337797.93-52329737410342/copy && sleep 0'"]
ansible-container_1  | <ansible_myapp_1> PUT /tmp/tmp7i0ALm TO /root/.ansible/tmp/ansible-tmp-1489337797.93-52329737410342/stat
ansible-container_1  | <ansible_myapp_1> EXEC ['/usr/bin/docker', 'exec', '-i', u'ansible_myapp_1', u'/bin/sh', '-c', u"/bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1489337797.93-52329737410342/stat && sleep 0'"]
ansible-container_1  | <ansible_myapp_1> PUT /ansible-container/ansible/requirements.yml TO /root/.ansible/tmp/ansible-tmp-1489337797.93-52329737410342/source
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/site-packages/compose/cli/log_printer.py", line 190, in watch_events
    for event in event_stream:
  File "/usr/local/lib/python2.7/site-packages/compose/project.py", line 343, in events
    decode=True
  File "/usr/local/lib/python2.7/site-packages/docker/client.py", line 233, in _stream_helper
    data = json.loads(data)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 2 column 1 - line 3 column 1 (char 842 - 1682)
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/site-packages/compose/cli/log_printer.py", line 190, in watch_events
    for event in event_stream:
  File "/usr/local/lib/python2.7/site-packages/compose/project.py", line 343, in events
    decode=True
  File "/usr/local/lib/python2.7/site-packages/docker/client.py", line 233, in _stream_helper
    data = json.loads(data)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 2 column 1 - line 3 column 1 (char 842 - 1682)


ansible-container_1  | <ansible_myapp_1> PUT /tmp/tmpZJGRck TO /root/.ansible/tmp/ansible-tmp-1489337797.93-52329737410342/copy
ansible-container_1  | <ansible_myapp_1> EXEC ['/usr/bin/docker', 'exec', '-i', u'ansible_myapp_1', u'/bin/sh', '-c', u"/bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1489337797.93-52329737410342/copy && sleep 0'"]
ansible-container_1  | <ansible_myapp_1> EXEC ['/usr/bin/docker', 'exec', '-i', u'ansible_myapp_1', u'/bin/sh', '-c', u"/bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1489337797.93-52329737410342/ > /dev/null 2>&1 && sleep 0'"]
ansible-container_1  | changed: [myapp] => {"changed": true, "dest": "/usr/src/app/", "invocation": {"module_args": {"dest": "/usr/src/app", "src": ".."}, "module_name": "copy"}, "src": "/ansible-container/ansible"}
ansible-container_1  | 
ansible-container_1  | TASK [Install requirements] ****************************************************
ansible-container_1  | task path: /ansible-container/ansible/main.yml:8
ansible-container_1  | <ansible_myapp_1> ESTABLISH DOCKER CONNECTION FOR USER: root
ansible-container_1  | <ansible_myapp_1> EXEC ['/usr/bin/docker', 'exec', '-i', u'ansible_myapp_1', u'/bin/sh', '-c', u'/bin/sh -c \'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1489337801.76-161509211256258 `" && echo ansible-tmp-1489337801.76-161509211256258="` echo $HOME/.ansible/tmp/ansible-tmp-1489337801.76-161509211256258 `" ) && sleep 0\'']
ansible-container_1  | <ansible_myapp_1> PUT /tmp/tmpQ4S0de TO /root/.ansible/tmp/ansible-tmp-1489337801.76-161509211256258/pip
ansible-container_1  | <ansible_myapp_1> EXEC ['/usr/bin/docker', 'exec', '-i', u'ansible_myapp_1', u'/bin/sh', '-c', u'/bin/sh -c \'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1489337801.76-161509211256258/pip; rm -rf "/root/.ansible/tmp/ansible-tmp-1489337801.76-161509211256258/" > /dev/null 2>&1 && sleep 0\'']
ansible-container_1  | fatal: [myapp]: FAILED! => {"changed": false, "cmd": "/usr/local/bin/pip install -r /usr/src/app/requirements.txt", "failed": true, "invocation": {"module_args": {"chdir": null, "editable": true, "executable": "pip", "extra_args": null, "name": null, "requirements": "/usr/src/app/requirements.txt", "state": "present", "umask": null, "use_mirrors": true, "version": null, "virtualenv": null, "virtualenv_command": "virtualenv", "virtualenv_python": null, "virtualenv_site_packages": false}, "module_name": "pip"}, "msg": "\n:stderr: Could not open requirements file: [Errno 2] No such file or directory: '/usr/src/app/requirements.txt'\n"}
ansible-container_1  | 
ansible-container_1  | NO MORE HOSTS LEFT *************************************************************
ansible-container_1  | 
ansible-container_1  | PLAY RECAP *********************************************************************
ansible-container_1  | myapp                      : ok=1    changed=1    unreachable=0    failed=1   
ansible-container_1  | 
ansible-container_1  |  [WARNING]: Could not create retry file 'main.retry'.         [Errno 2] No such
ansible-container_1  | file or directory: ''
ansible_ansible-container_1 exited with code 1
Aborting on container exit...
Stopping ansible_myapp_1 ... done
Ansible playbook run failed.
Cleaning up Ansible Container builder...
Cleaning up temporary directory /var/folders/r1/9g6vpzy92dv7smm35bjy71sh0000gn/T/tmpj5qZUO...
Ansible build failed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/container/cli.py", line 212, in commandline
    getattr(engine, u'cmdrun_{}'.format(args.subcommand))(**vars(args))
  File "/usr/local/lib/python2.7/site-packages/container/engine.py", line 384, in cmdrun_build
    raise RuntimeError(u'Ansible build failed')
RuntimeError: Ansible build failed
$ 
```

**Comment by chouseknecht** [comment]
@elad, I would recommend running from source. The latest code in the `develop` branch is release 0.3.0, but it was never pushed to PyPi, and at this point it won't be. We're currently busy refactoring, and the refactor will be released in the next couple weeks. 

Anyway, if you follow the [run from source guide](http://docs.ansible.com/ansible-container/installation.html#running-from-source), you can actually use the `synchronize` module to perform the copy.

The task to copy your source from the build container to the target container will look something like the following:

```
- name: Copy source
  synchronize:
    src: "{{ lookup('pipe', 'dirname `pwd`') }}/"
    dest: "{{ DJANGO_ROOT }}"
  remote_user: "{{ DJANGO_USER }}"
```

The above was copied from [ansible/django-gulp-nginx](https://github.com/ansible/django-gulp-nginx), a demo framework project for Ansible Container, and it actually works.

**Comment by elad** [comment]
@chouseknecht thanks for the prompt response. However, I insist that I still must be missing something fundamental about ansible-container because your suggestion doesn't make sense to me.

According to [the documentation](https://docs.ansible.com/ansible-container/reference/build.html), `ansible-container build` is analogous to `docker build`. Now, what the latter does (according to [its documentation](https://docs.docker.com/engine/reference/commandline/build/)) is build an image from a Dockerfile and a "context". I understand that the YAML files replace the Dockerfile. I'm having trouble with the "context" - the actual files to put in the container. Since that's the basic functionality of containers (a fancy chroot), I find it hard to believe that in it's something not entirely straightforward and obvious.

So, again, my question is: Do I *really* have to do the above? or is there a much simpler way to say "here are the files for the container" - just like I'd pass a "context" to Docker or a path to chroot? :)

**Comment by jmalacho** [comment]
The copy task in ansible looks for a file by searching for it path. In the
SRC field: ".." is meaningless, because, relative to WHAT? What exactly are
you trying to copy? Please perhaps post the entire tree or link to your
repository.
I use copy just fine, but I copy in single files.

**Comment by chouseknecht** [comment]
@elad, you don't have to copy a context into the build container. The root of the project is mounted to the container automatically at `/ansible-container`, and `/ansible-container/ansible` (where your `main.yml` is located) becomes the build container's `workdir`.

From there it will run your `main.yml`, executing tasks on the containers representing the services you defined in `container.yml`. Each service name becomes an entry in the `inventory` during playbook execution. 

Hopefully that makes sense. For an actual example, and walkthrough, check out [Getting Started](http://docs.ansible.com/ansible-container/getting_started.html). There's also a [demo project](https://github.com/ansible/ansible-container-demo) that may help.

**Comment by elad** [comment]
It could be that "copy" is the wrong module to use here. (To answer your question, I was under the impression that it copied files from my working directory, in which case `..` means the parent directory of where the script is. Apparently that's not the case.)

Let me explain what I'm trying to do. I have a directory with files that I want to containerize. Here it is:

```
$ cd myapp
$ tree
.
|-- Dockerfile
|-- ansible
|   |-- ansible.cfg
|   |-- container.yml
|   |-- main.yml
|   |-- requirements.txt
|   `-- requirements.yml
|-- myapp
|   |-- __init__.py
|   `-- main.py
|-- requirements.txt
|-- schemas
|   `-- swagger.yaml
`-- test.sh

3 directories, 11 files
$ 
```

With chroot it's `chroot("/path/to/myapp");`. With Docker it's `docker build .`. What do I have to do for ansible-container?

**Comment by jmalacho** [comment]
Can I see your main.yml?
if you are using a role, the default search paths are different. If you are inlining the copy task in main.yml, then the search paths are relative to the playbook itself.  (typically something like ./templates, ./files, ./

Here I made an example for you (https://github.com/jmalacho/ansible-container-example2):
```
[root@centos71 ansible-container-example2]# ansible-container  build
...
Attaching to ansible_example_1, ansible_ansible-container_1
ansible-container_1  | Host example running
ansible-container_1  | 
ansible-container_1  | PLAY [all] *********************************************************************
ansible-container_1  | 
ansible-container_1  | TASK [copy] ********************************************************************
ansible-container_1  | changed: [example]
ansible-container_1  | 
ansible-container_1  | PLAY RECAP *********************************************************************
ansible-container_1  | example                    : ok=1    changed=1    unreachable=0    failed=0   
ansible-container_1  | 
ansible_ansible-container_1 exited with code 0
...

[root@centos71 ansible-container-example2]# docker images
REPOSITORY                           TAG                 IMAGE ID            CREATED             SIZE
ansible-container-example2-example   20170313204826      99ad26e2f282        2 seconds ago       192 MB
ansible-container-example2-example   latest              99ad26e2f282        2 seconds ago       192 MB
ansible/ansible-container-builder    0.2                 6a0481cdff24        5 months ago        711 MB
[root@centos71 ansible-container-example2]# docker run -it ansible-container-example2-example /bin/bash
[root@a7b50c5e34c8 /]# ls /myapp/
main.py


```

**Comment by elad** [comment]
@jmalacho thanks for that. I understand that my directory hierarchy was wrong. Ansible expects its configuration data to be at the root, and the container files to be in a directory called `files`. That's what I was missing. Thanks!

**Comment by drzraf** [comment]
I think this is a problematic limitation.

My project contains a `composer.json` that I would like the container to process.
But `composer.json` is **not** only used by Ansible Containers but also by the rest of the project (mainly PHP). So `composer.json` **ouside** the `ansible/` directory.

How am I expected to copy that file into the container where Ansible will run the role?
Should I really encapsulate calls to `ansible-container build` inside a Makefile??

**Comment by krisfris** [comment]
I had the same problem. I'm deploying a locally built package which does not reside in the ansible directory to a docker container. Solved it by adding a sibling directory to volumes:
```
conductor:
  base: ubuntu:xenial
  volumes:
    - ../data:/data
```
The root ansible directory is mounted to /_src so I can use {{inventory_dir}}/../data/bla.xml in my roles and it works.
