### ISSUE TITLE
Unable to run ansible-container init

### ISSUE THREAD

**Issue by asemt** [ansible/ansible-container#41]
Hey,

I get following errors running `ansible-container` (Git SHA id: `429dcc5`):

      $ ansible-container init
      Traceback (most recent call last):
        File "/home/asemt/coding/python/ansible-container-venv/bin/ansible-container", line 9, in <module>
          load_entry_point('ansible-container==0.1', 'console_scripts', 'ansible-container')()
        File "/home/asemt/coding/python/ansible-container-venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
          return get_distribution(dist).load_entry_point(group, name)
        File "/home/asemt/coding/python/ansible-container-venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
          return ep.load()
        File "/home/asemt/coding/python/ansible-container-venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2355, in load
          return self.resolve()
        File "/home/asemt/coding/python/ansible-container-venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2361, in resolve
          module = __import__(self.module_name, fromlist=['__name__'], level=0)
      ImportError: No module named container.cli

I followed [these instructions](https://github.com/ansible/ansible-container#to-install-ansible-container) to install `ansible-container` inside a virtualenv on a Ubuntu 14.04.4 LTS machine.

**Comment by gaieges** [comment]
Ran into the same problem, [this fix](https://github.com/ansible/ansible-container/pull/42) seems to have worked for me
