### ISSUE TITLE
Can't install with k8s/openshift engines

### ISSUE THREAD

**Issue by chouseknecht** [ansible/ansible-container#442]
1) The requirement to add an engine is not mentioned on our README.
2) Adding an engine other than Docker is busted.

Attempting `pip install -e.[docker,k8s,openshift]` results in the following:

```
Obtaining file:///Users/chouseknecht/projects/ansible-container
Collecting Jinja2>=2.9 (from ansible-container==0.9.1rc0)
  Using cached Jinja2-2.9.6-py2.py3-none-any.whl
Collecting PyYAML>=3.12 (from ansible-container==0.9.1rc0)
Collecting requests>=2 (from ansible-container==0.9.1rc0)
  Using cached requests-2.13.0-py2.py3-none-any.whl
Collecting ruamel.yaml>=0.14.2 (from ansible-container==0.9.1rc0)
  Using cached ruamel.yaml-0.14.8.tar.gz
Requirement already satisfied: six>=1.10 in /Users/chouseknecht/projects/actest/lib/python2.7/site-packages (from ansible-container==0.9.1rc0)
Collecting structlog[dev]>=16.1 (from ansible-container==0.9.1rc0)
  Using cached structlog-16.1.0-py2.py3-none-any.whl
Collecting docker>=2.1 (from ansible-container==0.9.1rc0)
  Using cached docker-2.2.1-py2.py3-none-any.whl
Collecting openshift==1.0.0 (from ansible-container==0.9.1rc0)
  Could not find a version that satisfies the requirement openshift==1.0.0 (from ansible-container==0.9.1rc0) (from versions: )
No matching distribution found for openshift==1.0.0 (from ansible-container==0.9.1rc0)
```

**Comment by chouseknecht** [comment]
Same for `pip install ansible-container[docker,k8s,openshift]`

Result:

```
Requirement already satisfied: ansible-container[docker,k8s,openshift] in /Users/chouseknecht/projects/ansible-container
Collecting Jinja2>=2.9 (from ansible-container[docker,k8s,openshift])
  Using cached Jinja2-2.9.6-py2.py3-none-any.whl
Collecting PyYAML>=3.12 (from ansible-container[docker,k8s,openshift])
Collecting requests>=2 (from ansible-container[docker,k8s,openshift])
  Using cached requests-2.13.0-py2.py3-none-any.whl
Collecting ruamel.yaml>=0.14.2 (from ansible-container[docker,k8s,openshift])
  Using cached ruamel.yaml-0.14.8.tar.gz
Requirement already satisfied: six>=1.10 in /Users/chouseknecht/projects/actest/lib/python2.7/site-packages (from ansible-container[docker,k8s,openshift])
Collecting structlog[dev]>=16.1 (from ansible-container[docker,k8s,openshift])
  Using cached structlog-16.1.0-py2.py3-none-any.whl
Collecting docker>=2.1 (from ansible-container[docker,k8s,openshift])
  Using cached docker-2.2.1-py2.py3-none-any.whl
Collecting openshift==1.0.0 (from ansible-container[docker,k8s,openshift])
  Could not find a version that satisfies the requirement openshift==1.0.0 (from ansible-container[docker,k8s,openshift]) (from versions: )
No matching distribution found for openshift==1.0.0 (from ansible-container[docker,k8s,openshift])
```

**Comment by chouseknecht** [comment]
Please, make it so that `pip install ansible-container` works, and installs all the pieces for all the engines.

Maybe at some point it will make sense to separate packages by engine, but we're not there yet. Let's keep it simple for now.

**Comment by chouseknecht** [comment]
Turns out Docker seem to fail as well. Here's the scenario:

```
$ virtualenv actest
... virtualenv does things ...
$ source ./actest/bin/activate
$ pip install ansible-container[docker]
... installation works ... 
$ mkdir testac
$ cd testac
$ ansible-container init
```
See the following stack trace: 

```
Traceback (most recent call last):
  File "/usr/local/bin/ansible-container", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Users/chouseknecht/Library/Python/2.7/lib/python/site-packages/pkg_resources/__init__.py", line 2994, in <module>
    @_call_aside
  File "/Users/chouseknecht/Library/Python/2.7/lib/python/site-packages/pkg_resources/__init__.py", line 2980, in _call_aside
    f(*args, **kwargs)
  File "/Users/chouseknecht/Library/Python/2.7/lib/python/site-packages/pkg_resources/__init__.py", line 3007, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/chouseknecht/Library/Python/2.7/lib/python/site-packages/pkg_resources/__init__.py", line 658, in _build_master
    ws.require(__requires__)
  File "/Users/chouseknecht/Library/Python/2.7/lib/python/site-packages/pkg_resources/__init__.py", line 966, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/chouseknecht/Library/Python/2.7/lib/python/site-packages/pkg_resources/__init__.py", line 852, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'structlog[dev]>=16.1' distribution was not found and is 
required by ansible-container
```

**Comment by asquelt** [comment]
same here.
i can install ansible-container with docker extra but it lacks previously available shipit command.
trying to install k8s extra results with error claiming dependency to nonexistant `openshift==1.0.0`.

**Comment by chouseknecht** [comment]
@asquelt

This is still broken, unfortunately. Just for reference, the `shipit` command has been replaced by `deploy`.

**Comment by asquelt** [comment]
i've managed to fix it, by manually installing from repo https://github.com/openshift/openshift-restclient-python. but still, there seem to be some dependency errors, as now i get:
```
azureuser@k8s-master-2A2CBE85-0:~/examples/wordpress/ansible$ ansible-container build
WARNING	Version '1' is deprecated. Consider upgrading to version '2'.	
Building Docker Engine context...	
ERROR	Unknown exception	
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/container/cli.py", line 259, in __call__
    getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
  File "/usr/local/lib/python2.7/dist-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/container/core.py", line 144, in hostcmd_build
    cache=kwargs['cache']
  File "/usr/local/lib/python2.7/dist-packages/container/docker/engine.py", line 81, in __wrapped__
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/container/docker/engine.py", line 629, in build_conductor_image
    arcname='contrib/get-pip.py')
  File "/usr/lib/python2.7/tarfile.py", line 2007, in add
    tarinfo = self.gettarinfo(name, arcname)
  File "/usr/lib/python2.7/tarfile.py", line 1879, in gettarinfo
    statres = os.lstat(name)
OSError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/container/docker/files/get-pip.py'
```

**Comment by j00bar** [comment]
How did you end up installing the ansible-container package? Do you have a file `/usr/local/lib/python2.7/dist-packages/ansible_container-0.9.0.0.dist-info/RECORD` and if so, what are its contents? Or do you have a file `/usr/local/lib/python2.7/dist-packages/ansible_container.egg-info/SOURCES.txt` and if so, what are its contents? Thanks!

**Comment by asquelt** [comment]
package has been installed with Ansible, from master branch.

```
      - name: Get ansible-container
        git:
            repo: "https://github.com/ansible/ansible-container.git"
            dest: /var/tmp/ansible-container
            version: master
        tags: ansible

      - name: Install ansible-container
        #pip:
        #    name: /var/tmp/ansible-container[docker,k8s]
        # BUG: pip breaks here, as it translates command to: /var/tmp/ansible-container[docker k8s]
        command: pip install /var/tmp/ansible-container[docker,k8s]
        tags: ansible
```
files contents: https://gist.github.com/asquelt/85cb5d565f678dc170c37e2ace15749c
my repo for ansible-container lab: https://github.com/linuxpolska/ansible-container-demo

**Comment by vgallissot** [comment]
Same issue here, installs with anything else than docker are not working because of a the above openshift==1.0.0 error.

This works fine:
```bash
$ sudo pip install ansible-container
```

This works fine:
```bash
$ sudo pip install ansible-container[docker]
```

This complains about openshift
```bash
$ sudo pip install ansible-container[docker,k8s]
  Could not find a version that satisfies the requirement openshift==1.0.0 (from ansible-container[docker,k8s]) (from versions: )
No matching distribution found for openshift==1.0.0 (from ansible-container[docker,k8s])
```

Following installs always fail with previous error:
```bash
$ sudo pip install ansible-container[openshift]
$ sudo pip install ansible-container[k8s]
```

**Comment by chouseknecht** [comment]
FWIW, when installing from source, the following works:

```
$ pip install -e .[k8s] --process-dependency-links
```

`--process-dependency-links` is deprecated, but it still works.

However, it refuses to work without the `-e .`, so it's only applicable when installing from source.

**Comment by cans** [comment]
To definitely close this, a new release (with PR #462 merged) of ansible-container should be uploaded to PyPI.
In the meantime, the following seems to do the work:

    pip install ssh+https://github.com/ansible/ansible-container.git@37dce2364281e2d9ab68ba6c65c1f3e5e124bf04#egg=ansible-container[docker,k8s,openshift]

Of course you only have to keep what you need between the brackets at the end of the URL.

**Comment by is-daimonos** [comment]
![apply](https://user-images.githubusercontent.com/11807763/29948693-faa8d210-8e75-11e7-940c-3c37800fa484.png)
![update_from_repository](https://user-images.githubusercontent.com/11807763/29948694-faad0934-8e75-11e7-9434-ef8e29db9c06.png)

Good afternoon
I used a this ansible playbook to upgrade this modules

`---
- hosts: localhost
  become: true
  tasks:
  - name: Install c compile for python build
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - gcc
      - python-devel

  - name: Get ansible-container
    git:
      repo: "https://github.com/ansible/ansible-container.git"
      dest: /var/tmp/ansible-container
      version: master
    tags: ansible

  - name: Update setuptools
    command: pip install --upgrade setuptools
    tags: ansible

  - name: Install ansible-container
    command: pip install /var/tmp/ansible-container[{{ item }}]
    with_items:
      - docker
      - k8s
      - openshift
    tags: ansible
`
This worked for me
