### ISSUE TITLE
ansible-container build fails

### ISSUE THREAD

**Issue by Object905** [ansible/ansible-container#451]
##### ISSUE TYPE
 - Bug Report

##### container.yml 
```
version: "2"

defaults:
  APP_PORT: 8080
  APP_ROOT: '/redmine'
  APP_USER: redmine

settings:
  conductor_base: ubuntu:xenial

services:
  web:
    from: 'ubuntu:xenial'
    working_dir: '{{ APP_ROOT }}'
    user: '{{ APP_USER }}'
    expose:
      - '{{ APP_PORT }}'

  nginx:
    from: ubuntu:xenial
    roles:
      - nginx-container
    user: nginx
    command: ['/usr/bin/dumb-init', 'nginx', '-c', '/etc/nginx/nginx.conf']
    ports:
      - '{{ APP_PORT }}:8000'

registries: {}

```

##### main.yml 
```
None
```

##### OS / ENVIRONMENT
```
nsible Container, version 0.9.0.0
Linux, Object, 4.10.10-1-ARCH, #1 SMP PREEMPT Wed Apr 12 18:50:28 CEST 2017, x86_64
2.7.13 (default, Dec 21 2016, 07:16:46) 
[GCC 6.2.1 20160830] /usr/bin/python2
{
  "ContainersPaused": 0, 
  "Labels": null, 
  "CgroupDriver": "cgroupfs", 
  "ContainersRunning": 0, 
  "ContainerdCommit": {
    "Expected": "422e31ce907fd9c3833a38d7b8fdd023e5a76e73", 
    "ID": "422e31ce907fd9c3833a38d7b8fdd023e5a76e73"
  }, 
  "InitBinary": "", 
  "NGoroutines": 23, 
  "Swarm": {
    "Managers": 0, 
    "ControlAvailable": false, 
    "NodeID": "", 
    "Cluster": {
      "Spec": {
        "Labels": null, 
        "TaskDefaults": {}, 
        "Orchestration": {}, 
        "EncryptionConfig": {
          "AutoLockManagers": false
        }, 
        "Raft": {
          "HeartbeatTick": 0, 
          "ElectionTick": 0
        }, 
        "CAConfig": {}, 
        "Dispatcher": {}
      }, 
      "Version": {}, 
      "ID": "", 
      "CreatedAt": "0001-01-01T00:00:00Z", 
      "UpdatedAt": "0001-01-01T00:00:00Z"
    }, 
    "Nodes": 0, 
    "Error": "", 
    "RemoteManagers": null, 
    "LocalNodeState": "inactive", 
    "NodeAddr": ""
  }, 
  "LoggingDriver": "json-file", 
  "OSType": "linux", 
  "HttpProxy": "", 
  "Runtimes": {
    "runc": {
      "path": "docker-runc"
    }
  }, 
  "DriverStatus": [
    [
      "Backing Filesystem", 
      "extfs"
    ], 
    [
      "Supports d_type", 
      "true"
    ], 
    [
      "Native Overlay Diff", 
      "true"
    ]
  ], 
  "OperatingSystem": "Arch Linux", 
  "Containers": 48, 
  "HttpsProxy": "", 
  "BridgeNfIp6tables": true, 
  "MemTotal": 4058443776, 
  "SecurityOptions": [
    "name=seccomp,profile=default"
  ], 
  "Driver": "overlay2", 
  "IndexServerAddress": "https://index.docker.io/v1/", 
  "ClusterStore": "", 
  "InitCommit": {
    "Expected": "949e6fa", 
    "ID": "949e6fa"
  }, 
  "Isolation": "", 
  "SystemStatus": null, 
  "OomKillDisable": true, 
  "ClusterAdvertise": "", 
  "SystemTime": "2017-04-21T20:48:12.766866091+05:00", 
  "Name": "Object", 
  "CPUSet": true, 
  "RegistryConfig": {
    "InsecureRegistryCIDRs": [
      "127.0.0.0/8"
    ], 
    "IndexConfigs": {
      "docker.io": {
        "Official": true, 
        "Name": "docker.io", 
        "Secure": true, 
        "Mirrors": []
      }
    }, 
    "Mirrors": []
  }, 
  "DefaultRuntime": "runc", 
  "ContainersStopped": 48, 
  "NCPU": 4, 
  "NFd": 15, 
  "Architecture": "x86_64", 
  "KernelMemory": true, 
  "CpuCfsQuota": true, 
  "Debug": false, 
  "ID": "YKVT:DE6Y:7IOA:RTIY:JX3X:T3AF:PPSJ:TQYV:777S:PL7H:F7XH:XTR4", 
  "IPv4Forwarding": true, 
  "KernelVersion": "4.10.10-1-ARCH", 
  "BridgeNfIptables": true, 
  "NoProxy": "", 
  "LiveRestoreEnabled": false, 
  "ServerVersion": "17.04.0-ce", 
  "CpuCfsPeriod": true, 
  "ExperimentalBuild": false, 
  "MemoryLimit": true, 
  "SwapLimit": true, 
  "Plugins": {
    "Volume": [
      "local"
    ], 
    "Network": [
      "bridge", 
      "host", 
      "macvlan", 
      "null", 
      "overlay"
    ], 
    "Authorization": []
  }, 
  "Images": 56, 
  "DockerRootDir": "/var/lib/docker", 
  "NEventsListener": 0, 
  "CPUShares": true, 
  "RuncCommit": {
    "Expected": "9c2d8d184e5da67c95d601382adf14862e4f2228", 
    "ID": "9c2d8d184e5da67c95d601382adf14862e4f2228"
  }
}
{
  "KernelVersion": "4.10.10-1-ARCH", 
  "Arch": "amd64", 
  "BuildTime": "2017-04-08T18:55:45.235834955+02:00", 
  "ApiVersion": "1.28", 
  "Version": "17.04.0-ce", 
  "MinAPIVersion": "1.12", 
  "GitCommit": "4845c567eb", 
  "Os": "linux", 
  "GoVersion": "go1.8"
}
```
##### SUMMARY

`ansible-container build` fails to build. Tried on Archlinux thought that it's something to do with python (in arch python3 is in /bin/python), then tried on ubuntu vm. Also I fixed examples placing roles in container.yml and use `from` instead of `image`, but it fails with same error. Also tried switching conductor_base, but with this error it never gets to build step.

##### STEPS TO REPRODUCE
Just `ansible-container build` 

##### EXPECTED RESULTS
Build will pass

##### ACTUAL RESULTS

```
ansible-container --debug build                                                                                              
2017-04-21T20:54:20.612647 The default type is            [container.config] caller_file='/usr/lib/python2.7/site-packages/container/config.py' caller_func='_resolve_defaults' caller_line=124 config="<class 'ruamel.yaml.comments.CommentedMap'>" defaults="<class 'ruamel.yaml.comments.CommentedMap'>"
2017-04-21T20:54:20.613602 Getting environment variables... [container.config] caller_file='/usr/lib/python2.7/site-packages/container/config.py' caller_func='_get_environment_variables' caller_line=140
2017-04-21T20:54:20.614431 Read environment variables     [container.config] caller_file='/usr/lib/python2.7/site-packages/container/config.py' caller_func='_get_environment_variables' caller_line=145 env_vars='{}'
2017-04-21T20:54:20.615166 Resolved template variables    [container.config] caller_file='/usr/lib/python2.7/site-packages/container/config.py' caller_func='_resolve_defaults' caller_line=129 template_vars='{"APP_PORT": 8080, "APP_ROOT": "/redmine", "APP_USER": "redmine"}'
2017-04-21T20:54:20.615934 Parsed config                  [container.config] caller_file='/usr/lib/python2.7/site-packages/container/config.py' caller_func='set_env' caller_line=110 config='{"version": "2", "defaults": {"APP_PORT": 8080, "APP_ROOT": "/redmine", "APP_USER": "redmine"}, "settings": {"conductor_base": "ubuntu:xenial"}, "services": {"web": {"from": "ubuntu:xenial", "working_dir": "{{ APP_ROOT }}", "user": "{{ APP_USER }}", "expose": ["{{ APP_PORT }}"]}, "nginx": {"from": "ubuntu:xenial", "roles": ["nginx-container"], "user": "nginx", "command": ["/usr/bin/dumb-init", "nginx", "-c", "/etc/nginx/nginx.conf"], "ports": ["{{ APP_PORT }}:8000"]}}, "registries": {}}'
2017-04-21T20:54:20.616567 Loading engine capabilities    [container.utils.loader] caller_file='/usr/lib/python2.7/site-packages/container/utils/loader.py' caller_func='load_engine' caller_line=14 capabilities=['BUILD', 'RUN'] engine='docker'
2017-04-21T20:54:20.628106 Unknown exception 'function' object has no attribute 'get' [container.cli] caller_file='/usr/lib/python2.7/site-packages/structlog/stdlib.py' caller_func='exception' caller_line=95
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/container/cli.py", line 259, in __call__
    getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
  File "/usr/lib/python2.7/site-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/container/core.py", line 133, in hostcmd_build
    conductor_container_id = engine_obj.get_container_id_for_service('conductor')
  File "/usr/lib/python2.7/site-packages/container/docker/engine.py", line 347, in get_container_id_for_service
    container_info = self.client.containers.get(self.container_name_for_service(service_name))
AttributeError: 'function' object has no attribute 'get'
```

**Comment by chouseknecht** [comment]
@Object905 Thanks for trying Ansible Container, and taking the time to open an issue. 

I'm working on getting builds to work with Xenial now. Will have an update shortly. Thanks for your patience!

**Comment by j00bar** [comment]
@chouseknecht This appears unrelated to the other Xenial issues we're having.

@Object905 Docker had major breaking changes in their Python bindings semi-recently, to the point that they even changed the name of their package. It appears that your install of Ansible Container is picking up a version 1.x set of the bindings (Python package `docker-py`) instead of the 2.x set of the bindings (Python package `docker`). In the 1.x series, `client.containers` is a function, roughly equivalent to `docker ps`, whereas in the 2.x series, `client.containers` is an object that provides a higher level API for all container-centric commands.

To wit:
```
Python 2.7.13 (default, Dec 18 2016, 07:03:39) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import docker
>>> docker.__version__
'1.10.6'
>>> c = docker.from_env(version='auto')
>>> c.containers
<bound method Client.containers of <docker.client.Client object at 0x1103622d0>>
```
... versus ...
```
Python 2.7.13 (default, Dec 18 2016, 07:03:39) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import docker
>>> docker.__version__
'2.2.1'
>>> c = docker.from_env(version='auto')
>>> c.containers
<docker.models.containers.ContainerCollection object at 0x101308710>
```

Try the following, please?

```
pip uninstall docker-py
pip install 'docker>=2.1'
```

And let me know if that fixes things?

**Comment by saitejamc** [comment]
`pip uninstall docker-py
pip install 'docker>=2.1'`

Just tried these and ran "ansible-container build"
It just went through.

Thanks.

**Comment by Miyurz** [comment]
It still doesn't work for me :(

I set up a virtualenv and have the following pip packages
```
$ pip list
appdirs (1.4.3)
backports.ssl-match-hostname (3.5.0.1)
docker (2.2.1)
docker-pycreds (0.2.1)
ipaddress (1.0.18)
packaging (16.8)
pip (9.0.1)
pyparsing (2.2.0)
PyYAML (3.12)
requests (2.13.0)
setuptools (35.0.1)
six (1.10.0)
websocket-client (0.40.0)
wheel (0.29.0)
yamllint (1.7.0)
```

This is what I still get 

> $ ansible-container build
> ERROR   Unknown exception
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/site-packages/container/cli.py", line 259, in __call__
>     getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
>   File "/usr/local/lib/python2.7/site-packages/container/__init__.py", line 28, in __wrapped__
>     return fn(*args, **kwargs)
>   File "/usr/local/lib/python2.7/site-packages/container/core.py", line 133, in hostcmd_build
>     conductor_container_id = engine_obj.get_container_id_for_service('conductor')
>   File "/usr/local/lib/python2.7/site-packages/container/docker/engine.py", line 347, in get_container_id_for_service
>     container_info = self.client.containers.get(self.container_name_for_service(service_name))
> AttributeError: 'function' object has no attribute 'get'

**Comment by Miyurz** [comment]
@chouseknecht do we know when would this be fixed? as a temporary work around, I have rolled back to ansible-conatienr 0.3 version

**Comment by j00bar** [comment]
@Miyurz Please run `/usr/bin/env python` and in the interpreter it spawns, run the following and share the output:

```
>>> import docker
>>> docker.__version__
>>> c = docker.from_env(version='auto')
>>> c.containers
```

**Comment by jdoss** [comment]
I have encountered this issue on Fedora 26. Here is the output you requested.

```
$ sudo /usr/bin/env python
Python 2.7.13 (default, Sep  5 2017, 08:53:59) 
[GCC 7.1.1 20170622 (Red Hat 7.1.1-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import docker
>>> docker.__version__
'2.5.1'
>>> 
>>> c = docker.from_env(version='auto')
>>> c.containers
<docker.models.containers.ContainerCollection object at 0x7f8419c6a150>
>>>
```

Looking into this more, I moved my `container.yml` file and made a new one from `ansible-container init` and the `AttributeError: 'function' object has no attribute 'get'` went away with the defaults. It has to do with issues with the container.yml being used and it's not giving a good error message as a result. 

I was trying to mix Multi-Container Pod directives with additional service directives. Once I fixed my container.yml the error went away. Hope that helps.
