### ISSUE TITLE
Import Error - labels

### ISSUE THREAD

**Issue by chouseknecht** [ansible/ansible-container#464]
##### ISSUE TYPE
 - Bug Report

##### Dockerfile 
```
# Set the base image
FROM centos:latest

# File Author / Maintainer
LABEL maintainer "your name here!"

# Add ngix and PHP repos
ADD nginx.repo /etc/yum.repos.d/nginx.repo

# Installing nginx
RUN yum -y update && \
    yum -y install epel-release \
    yum -y install nginx && \
    yum -y --enablerepo=remi,remi-php56 install nginx php-fpm php-common &&\
    yum install -y python-pip python-develop python-setuptools && \
    pip install supervisor

# Add nginx configuration files
ADD nginx.conf /etc/nginx/nginx.conf
ADD default.conf /etc/nginx/conf.d/default.conf

# Add Supervisor configuration file
ADD supervisord.conf /etc/

# Add default index.php
ADD index.php /var/www/index.php

# Expose port 80
EXPOSE 80

# Start Supervisor
CMD ["supervisord", "-n"]
```
##### SUMMARY

Attempt to import the above Docker results in the following traceback:

```
ERROR	Unknown exception
Traceback (most recent call last):
  File "/Users/chouseknecht/projects/ansible-container/container/cli.py", line 257, in __call__
    getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
  File "/Users/chouseknecht/projects/ansible-container/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/Users/chouseknecht/projects/ansible-container/container/core.py", line 430, in hostcmd_import
    engine_obj.import_project(base_path, **kwargs)
  File "/Users/chouseknecht/projects/ansible-container/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/Users/chouseknecht/projects/ansible-container/container/docker/engine.py", line 742, in import_project
    dfi.run()
  File "/Users/chouseknecht/projects/ansible-container/container/docker/importer.py", line 475, in run
    (list(parser), os.path.join(self.role_path, 'tasks', 'main.yml')),
  File "/Users/chouseknecht/projects/ansible-container/container/docker/importer.py", line 185, in __iter__
    comments=preparsed.get('comments', [])):
  File "/Users/chouseknecht/projects/ansible-container/container/docker/importer.py", line 262, in parse_LABEL
    for k, v in [kv.split('=', 1) for kv in kv_pairs]:
ValueError: need more than 1 value to unpack
```

**Comment by chouseknecht** [comment]
Docker's documentation indicates that labels should be in the form `key=value`. However, they give an explicit example for turning the now deprecated `MAINTAINER` directive into `LABEL author "author@email.com"`.  Notice the missing `=`. 

Further, providing `LABEL foo bar` works as well. The labels on the resulting image are as follows:

```json
"Labels": {
    "build-date": "20170406",
    "foo": "bar",
    "license": "GPLv2",
    "maintainer": "your name here!",
    "name": "CentOS Base Image",
    "vendor": "CentOS"
}
```
