### ISSUE TITLE
OSError: Could not bind-mount /src into tmpdir

### ISSUE THREAD

**Issue by sarlindo** [ansible/ansible-container#467]
##### ISSUE TYPE

 - Bug Report

##### container.yml 
```
version: "2"
settings:
  conductor_base: centos:7

services:
  web:
    from: centos:7
    privileged: true
    roles:
      - dumb-init
      - httpd
      - epelrepo
      - sclrepo
      - remirepo
      - php
    ports:
      - "80:80"
    command: ['/usr/local/bin/dumb-init', '/usr/sbin/httpd', '-D', 'FOREGROUND']
registries: {}

```

##### OS / ENVIRONMENT
```
Ansible Container, version 0.9.1rc0
Linux, arlindo-UX31E, 4.4.0-75-generic, #96-Ubuntu SMP Thu Apr 20 09:56:33 UTC 2017, x86_64
2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] /usr/bin/python
{
  "ContainersPaused": 0, 
  "Labels": null, 
  "CgroupDriver": "cgroupfs", 
  "ContainersRunning": 0, 
  "ContainerdCommit": {
    "Expected": "4ab9917febca54791c5f071a9d1f404867857fcc", 
    "ID": "4ab9917febca54791c5f071a9d1f404867857fcc"
  }, 
  "InitBinary": "docker-init", 
  "NGoroutines": 23, 
  "Swarm": {
    "Managers": 0, 
    "ControlAvailable": false, 
    "NodeID": "", 
    "Cluster": {
      "Spec": {
        "TaskDefaults": {}, 
        "Orchestration": {}, 
        "EncryptionConfig": {
          "AutoLockManagers": false
        }, 
        "Raft": {
          "HeartbeatTick": 0, 
          "ElectionTick": 0
        }, 
        "CAConfig": {}, 
        "Dispatcher": {}
      }, 
      "Version": {}, 
      "ID": "", 
      "CreatedAt": "0001-01-01T00:00:00Z", 
      "UpdatedAt": "0001-01-01T00:00:00Z"
    }, 
    "Nodes": 0, 
    "Error": "", 
    "RemoteManagers": null, 
    "LocalNodeState": "inactive", 
    "NodeAddr": ""
  }, 
  "LoggingDriver": "json-file", 
  "OSType": "linux", 
  "HttpProxy": "", 
  "Runtimes": {
    "runc": {
      "path": "docker-runc"
    }
  }, 
  "DriverStatus": [
    [
      "Root Dir", 
      "/var/lib/docker/aufs"
    ], 
    [
      "Backing Filesystem", 
      "extfs"
    ], 
    [
      "Dirs", 
      "492"
    ], 
    [
      "Dirperm1 Supported", 
      "true"
    ]
  ], 
  "OperatingSystem": "Ubuntu 16.04.2 LTS", 
  "Containers": 8, 
  "HttpsProxy": "", 
  "BridgeNfIp6tables": true, 
  "MemTotal": 4039610368, 
  "SecurityOptions": [
    "name=apparmor", 
    "name=seccomp,profile=default"
  ], 
  "Driver": "aufs", 
  "IndexServerAddress": "https://index.docker.io/v1/", 
  "ClusterStore": "", 
  "InitCommit": {
    "Expected": "949e6fa", 
    "ID": "949e6fa"
  }, 
  "Isolation": "", 
  "SystemStatus": null, 
  "OomKillDisable": true, 
  "ClusterAdvertise": "", 
  "SystemTime": "2017-04-30T16:48:59.204964404-04:00", 
  "Name": "arlindo-UX31E", 
  "CPUSet": true, 
  "RegistryConfig": {
    "InsecureRegistryCIDRs": [
      "127.0.0.0/8"
    ], 
    "IndexConfigs": {
      "docker.io": {
        "Official": true, 
        "Name": "docker.io", 
        "Secure": true, 
        "Mirrors": null
      }
    }, 
    "Mirrors": []
  }, 
  "DefaultRuntime": "runc", 
  "ContainersStopped": 8, 
  "NCPU": 4, 
  "NFd": 15, 
  "Architecture": "x86_64", 
  "KernelMemory": true, 
  "CpuCfsQuota": true, 
  "Debug": false, 
  "ID": "U6F5:UBRL:EFRU:5X4E:OAWH:RSQ6:2ESO:N3CA:KQL3:DWPX:E5A6:UHOX", 
  "IPv4Forwarding": true, 
  "KernelVersion": "4.4.0-75-generic", 
  "BridgeNfIptables": true, 
  "NoProxy": "", 
  "LiveRestoreEnabled": false, 
  "ServerVersion": "17.03.1-ce", 
  "CpuCfsPeriod": true, 
  "ExperimentalBuild": false, 
  "MemoryLimit": true, 
  "SwapLimit": false, 
  "Plugins": {
    "Volume": [
      "local"
    ], 
    "Network": [
      "bridge", 
      "host", 
      "macvlan", 
      "null", 
      "overlay"
    ], 
    "Authorization": null
  }, 
  "Images": 304, 
  "DockerRootDir": "/var/lib/docker", 
  "NEventsListener": 0, 
  "CPUShares": true, 
  "RuncCommit": {
    "Expected": "54296cf40ad8143b62dbcaa1d90e520a2136ddfe", 
    "ID": "54296cf40ad8143b62dbcaa1d90e520a2136ddfe"
  }
}
{
  "KernelVersion": "4.4.0-75-generic", 
  "Arch": "amd64", 
  "BuildTime": "2017-03-27T17:14:09.765618756+00:00", 
  "ApiVersion": "1.27", 
  "Version": "17.03.1-ce", 
  "MinAPIVersion": "1.12", 
  "GitCommit": "c6d412e", 
  "Os": "linux", 
  "GoVersion": "go1.7.5"

```
##### SUMMARY
Ran into issue 446 https://github.com/ansible/ansible-container/issues/446 with my build and I downloaded the latest code from source and was able to get past build, but now failed on the run with the same mount/priv issue.

##### STEPS TO REPRODUCE

```
sudo ansible-container run

```

##### EXPECTED RESULTS
For it to run the containers.

##### ACTUAL RESULTS
```
arlindo@arlindo-UX31E:~/projects/ansible-container-testapp$ sudo ansible-container run
Parsing conductor CLI args.
Engine integration loaded. Preparing run.	engine=Docker™ daemon
Verifying service image	service=web
mount: /src is write-protected, mounting read-only
mount: cannot mount /src read-only
Traceback (most recent call last):
  File "/usr/bin/conductor", line 11, in <module>
    load_entry_point('ansible-container', 'console_scripts', 'conductor')()
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/cli.py", line 349, in conductor_commandline
    **params)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/core.py", line 733, in conductorcmd_run
    rc = run_playbook(playbook, engine, services, tags=['start'], **kwargs)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/core.py", line 524, in run_playbook
    raise OSError('Could not bind-mount /src into tmpdir')
OSError: Could not bind-mount /src into tmpdir
Conductor terminated. Cleaning up.	command_rc=1 conductor_id=39c41b1b762d866263c52ffbfde0641f80af12ad89243d182f95d605edea5b75 save_container=False
ERROR	Conductor exited with status 1	

```

**Comment by j00bar** [comment]
I believe this is a duplicate of #446 - please re-open if your issue is not resolved with that fix.

**Comment by sarlindo** [comment]
@j00bar as I mentioned I did run into issue #446 and I downloaded the latest code from source and was able to get past **build** part only, but now it sames with same issue on the **run** with the same mount/priv issue, so I think this issue outlined in #446 only fixed part of the problem.

**Comment by brucellino** [comment]
I can reproduce the run issue here
```
mount: /src is write-protected, mounting read-only
mount: cannot mount /src read-only
Traceback (most recent call last):
  File "/usr/bin/conductor", line 11, in <module>
    load_entry_point('ansible-container', 'console_scripts', 'conductor')()
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/cli.py", line 349, in conductor_commandline
    **params)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/core.py", line 733, in conductorcmd_run
    rc = run_playbook(playbook, engine, services, tags=['start'], **kwargs)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/core.py", line 524, in run_playbook
    raise OSError('Could not bind-mount /src into tmpdir')
OSError: Could not bind-mount /src into tmpdir
```

**Comment by bearrito** [comment]
I am able to reproduce as well.

**Comment by micmania1** [comment]
I've ran into this following the video instructions here: https://ansible.github.io/ansible-container-demo/

`build` works fine but `run` fails with the same error as posted above.

My host machine OS is Ubuntu 16.04.

**Comment by brucellino** [comment]
Hi all,

This is a showstopper for me - I can't run the services. Has anyone found a workaround ?

**Comment by chouseknecht** [comment]
@brucellino, can you confirm that this is resolved with PR #518.  

Thanks!

**Comment by brucellino** [comment]
Yep, #518  does the trick :+1: :white_check_mark:
