### ISSUE TITLE
Failed Interpolation in Vars files

### ISSUE THREAD

**Issue by bearrito** [ansible/ansible-container#491]
##### ISSUE TYPE

 - Bug Report

##### OS / ENVIRONMENT

```
14.04 LTS
```
##### SUMMARY
Variables are not interpolated when passing a vars file.

My invocation is 

##### STEPS TO REPRODUCE

```
ansible-container --debug  --var-file ./flume/vars.yml  build -- -e"@/ansible-container/vars.yml
```

vars.yml

```
source: foo
derived: "{{ foo }}/bar"
```

##### EXPECTED RESULTS

Variable to be interpolated

##### ACTUAL RESULTS

an exception is raised

```
parsing conductor CLI args.
2017-05-03T15:15:51.944546 Processing defaults section... [container.config] caller_file=/_ansible/container/config.py caller_func=_process_defaults caller_line=251
Traceback (most recent call last):
  File "/usr/bin/conductor", line 11, in <module>
    load_entry_point('ansible-container', 'console_scripts', 'conductor')()
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/cli.py", line 339, in conductor_commandline
    conductor_config = AnsibleContainerConductorConfig(containers_config)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/config.py", line 223, in __init__
    self._process_defaults()
  File "/_ansible/container/config.py", line 254, in _process_defaults
    callback=lambda processed: self._templar.set_available_variables(
  File "/_ansible/container/config.py", line 234, in _process_section
    processed[key] = templar.template(value)
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 444, in template
    disable_lookups=disable_lookups,
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 694, in do_template
    raise AnsibleUndefinedVariable(e)
ansible.errors.AnsibleUndefinedVariable: 'foo' is undefined

```

**Comment by chouseknecht** [comment]
@bearrito 

Thanks for using Ansible Container, and for taking the time to open an issue. We appreciate your feedback. 

The error is `ansible.errors.AnsibleUndefinedVariable: 'foo' is undefined`.  I'm confused about where the `foo` variable is actually defined.  It's not defined in your `vars.yml` file. 

Am I missing something obvious. Is it defined in `container.yml` defaults. If so, could you share a copy of that file. 

Also, you do not need to pass the variable file to `ansible-playbook`.  The result of aggregating variables from the defaults, any variable file, and environment vars is passed for you, automatically.
