### ISSUE TITLE
ansible-container run: avc denied  { connectto } /run/docker.sock with SELinux is enabled

### ISSUE THREAD

**Issue by NavinF** [ansible/ansible-container#494]
ISSUE TYPE: Bug Report
container.yml: N/A
##### OS / ENVIRONMENT
Fedora 25, latest versions from dnf and pip. ([`ansible-container --debug version` output](https://gist.github.com/NavinF/23bc58fea4053927cf16cf5d607905a5))

##### STEPS TO REPRODUCE
```
$ mkdir test && cd test/
$ ansible-container init
$ sudo ansible-container build
$ sudo ansible-container run
```

##### RESULTS
(see line 3):
```
May 03 14:23:22 dockerd-current[8353]: Parsing conductor CLI args.
May 03 14:23:22 dockerd-current[8353]: Engine integration loaded. Preparing run.        engine=Docker™ daemon
May 03 14:23:22 audit[17375]: AVC avc:  denied  { connectto } for  pid=17375 comm="conductor" path="/run/docker.sock" scontext=system_u:system_r:container_t:s0:c218,c771 tcontext=sy
tem_u:system_r:container_runtime_t:s0 tclass=unix_stream_socket permissive=0
May 03 14:23:22 dockerd-current[8353]: Traceback (most recent call last):
May 03 14:23:22 dockerd-current[8353]:   File "/usr/bin/conductor", line 11, in <module>
May 03 14:23:22 dockerd-current[8353]:     load_entry_point('ansible-container', 'console_scripts', 'conductor')()
May 03 14:23:22 dockerd-current[8353]:   File "/_ansible/container/__init__.py", line 19, in __wrapped__
May 03 14:23:22 dockerd-current[8353]:     return fn(*args, **kwargs)
May 03 14:23:22 dockerd-current[8353]:   File "/_ansible/container/cli.py", line 351, in conductor_commandline
May 03 14:23:22 dockerd-current[8353]:     **params)
May 03 14:23:22 dockerd-current[8353]:   File "/_ansible/container/__init__.py", line 19, in __wrapped__
May 03 14:23:22 dockerd-current[8353]:     return fn(*args, **kwargs)
May 03 14:23:22 dockerd-current[8353]:   File "/_ansible/container/core.py", line 716, in conductorcmd_run
May 03 14:23:22 dockerd-current[8353]:     playbook = engine.generate_orchestration_playbook(**kwargs)
May 03 14:23:22 dockerd-current[8353]:   File "/_ansible/container/__init__.py", line 19, in __wrapped__
May 03 14:23:22 dockerd-current[8353]:     return fn(*args, **kwargs)
May 03 14:23:22 dockerd-current[8353]:   File "/_ansible/container/docker/engine.py", line 550, in generate_orchestration_playbook
May 03 14:23:22 dockerd-current[8353]:     for image in self.client.images.list(name=image_name):
May 03 14:23:22 dockerd-current[8353]:   File "/_ansible/container/docker/engine.py", line 121, in client
May 03 14:23:22 dockerd-current[8353]:     self._client = docker.from_env(version='auto')
May 03 14:23:22 dockerd-current[8353]:   File "/usr/lib/python2.7/site-packages/docker/client.py", line 79, in from_env
May 03 14:23:22 dockerd-current[8353]:     **kwargs_from_env(**kwargs))
May 03 14:23:22 dockerd-current[8353]:   File "/usr/lib/python2.7/site-packages/docker/client.py", line 36, in __init__
May 03 14:23:22 dockerd-current[8353]:     self.api = APIClient(*args, **kwargs)
May 03 14:23:22 dockerd-current[8353]:   File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 141, in __init__
May 03 14:23:22 dockerd-current[8353]:     self._version = self._retrieve_server_version()
May 03 14:23:22 dockerd-current[8353]:   File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 168, in _retrieve_server_version
May 03 14:23:22 dockerd-current[8353]:     'Error while fetching server API version: {0}'.format(e)
May 03 14:23:22 dockerd-current[8353]: docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', error(13, 'Permission denied'))
May 03 14:23:22 systemd-machined[4177]: Machine 682c059cbfdbd362e1e760b99e7cdf19 terminated.
```

Same command works with SELinux disabled :(
```
$ sudo setenforce 0
$ sudo ansible-container run
Parsing conductor CLI args.
Engine integration loaded. Preparing run.       engine=Docker™ daemon
 [WARNING]: provided hosts list is empty, only localhost is available
PLAY [localhost] ***************************************************************
TASK [docker_service] **********************************************************
ok: [localhost]
PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0
All services running.   playbook_rc=0
Conductor terminated. Cleaning up.      command_rc=0 conductor_id=54fc0503e7456740e786e2a8060ed47f5fea8657731f09165c05bc9326c09e66 save_container=False
```

**Comment by NavinF** [comment]
This issue is very similar to #458 except `ansible-container build` works for me with SELinux enforcing. I guess my issue is a reduced test case of that other one since mine breaks with the default (almost empty) container.yml generated by `ansible-container init`. 

I'm guessing the solution here is to pass `--security-opt label=disable` to docker when starting the conductor. This seems a hell of a lot nicer than disabling SELinux globally or relabeling the host's `/run/docker.sock`.  
I think adding that flag to `/usr/lib/python2.7/site-packages/container/templates/build-docker-compose.j2.yml` would fix this mess, but [ansible-container doesn't support `security_opt`](https://docs.ansible.com/ansible-container/container_yml/reference.html#service-level-directives). AAAARRRGGHHH!

**Comment by NavinF** [comment]
Hmm if I do `sudo docker run --rm -it --privileged -v /run/docker.sock:/run/docker.sock fedora bash`, I can open the docker sock from inside this container. I have the process context `system_u:system_r:container_runtime_t:s0` inside this working container. 

However when `ansible-container run` opens the docker socket, it has the process context `system_u:system_r:container_t:s0:c218,c771`. 

If I remove `--privileged` from the docker command above, I can reproduce the same error ansible gets:
```
avc:  denied  { connectto } for  pid=7746 comm="nc" path="/run/docker.sock" scontext=system_u:system_r:container_t:s0:c317,c949 tcontext=system_u:system_r:container_runtime_t:s0 tclass=unix_stream_socket permissive=0
```

Ansible should always use `--privileged` for the conductor (#192) but it looks like it isn't.

btw @chouseknecht why did you label this "enhancement" but not "bug"?
