### ISSUE TITLE
ansible-container installation failed mac OSsierra-10.12.3

### ISSUE THREAD

**Issue by ansham22** [ansible/ansible-container#507]
python --version                                                                                                                                                                                    1 ↵
Python 2.7.10
pip --version
pip 9.0.1 from /Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg (python 2.7)

team, I am facing below issue while installing ansible-container on my local. OS version given. Please help me with the same as I want to start working on this project asap
```pip install ansible-container[docker,k8s]                                                                                                                                                           1 ↵
Collecting ansible-container[docker,k8s]
  Using cached ansible-container-0.9.0.0.tar.gz
Requirement already satisfied: Jinja2>=2.9 in /Library/Python/2.7/site-packages (from ansible-container[docker,k8s])
Requirement already satisfied: PyYAML>=3.12 in /Library/Python/2.7/site-packages (from ansible-container[docker,k8s])
Collecting requests>=2 (from ansible-container[docker,k8s])
  Using cached requests-2.13.0-py2.py3-none-any.whl
Collecting ruamel.yaml>=0.14.2 (from ansible-container[docker,k8s])
  Using cached ruamel.yaml-0.14.11.tar.gz
    Complete output from command python setup.py egg_info:
    /var/folders/r9/ksg7qk9n55b6647k470m2b4r0000gn/T/tmp_ruamel_FW8kTg/test_ruamel_yaml.c:6:8: warning: explicitly assigning value of variable of type 'yaml_parser_t' (aka 'struct yaml_parser_s') to itself [-Wself-assign]
    parser = parser;  /* prevent warning */
    ~~~~~~ ^ ~~~~~~
    /var/folders/r9/ksg7qk9n55b6647k470m2b4r0000gn/T/tmp_ruamel_FW8kTg/test_ruamel_yaml.c:6:10: warning: variable 'parser' is uninitialized when used here [-Wuninitialized]
    parser = parser;  /* prevent warning */
             ^~~~~~
    /var/folders/r9/ksg7qk9n55b6647k470m2b4r0000gn/T/tmp_ruamel_FW8kTg/test_ruamel_yaml.c:5:1: note: variable 'parser' is declared here
    yaml_parser_t parser;
    ^
    2 warnings generated.
    /var/folders/r9/ksg7qk9n55b6647k470m2b4r0000gn/T/tmp_ruamel_FW8kTg/test_ruamel_yaml.c:6:8: warning: explicitly assigning value of variable of type 'yaml_parser_t' (aka 'struct yaml_parser_s') to itself [-Wself-assign]
    parser = parser;  /* prevent warning */
    ~~~~~~ ^ ~~~~~~
    /var/folders/r9/ksg7qk9n55b6647k470m2b4r0000gn/T/tmp_ruamel_FW8kTg/test_ruamel_yaml.c:6:10: warning: variable 'parser' is uninitialized when used here [-Wuninitialized]
    parser = parser;  /* prevent warning */
             ^~~~~~
    /var/folders/r9/ksg7qk9n55b6647k470m2b4r0000gn/T/tmp_ruamel_FW8kTg/test_ruamel_yaml.c:5:1: note: variable 'parser' is declared here
    yaml_parser_t parser;
    ^
    2 warnings generated.
    sys.argv ['-c', 'egg_info', '--egg-base', 'pip-egg-info']
    test compiling test_ruamel_yaml
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/r9/ksg7qk9n55b6647k470m2b4r0000gn/T/pip-build-u3BCZ4/ruamel.yaml/setup.py", line 858, in <module>
        main()
      File "/private/var/folders/r9/ksg7qk9n55b6647k470m2b4r0000gn/T/pip-build-u3BCZ4/ruamel.yaml/setup.py", line 847, in main
        setup(**kw)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 326, in finalize_options
        ep.require(installer=self.fetch_build_egg)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2385, in require
        reqs = self.dist.requires(self.extras)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2617, in requires
        dm = self._dep_map
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2606, in _dep_map
        if invalid_marker(marker):
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1424, in is_invalid_marker
        cls.evaluate_marker(text)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1549, in _markerlib_evaluate
        env = cls._translate_metadata2(_markerlib.default_environment())
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1537, in _translate_metadata2
        for key, value in env
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1536, in <genexpr>
        (key.replace('.', '_'), value)
    ValueError: too many values to unpack

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/r9/ksg7qk9n55b6647k470m2b4r0000gn/T/pip-build-u3BCZ4/ruamel.yaml/```

**Comment by ansham22** [comment]
Can someone please help. @j00bar

**Comment by chouseknecht** [comment]
@ansham22 

What OS are you on, and what command did you execute to perform the install?

It looks like you may have tried to install using `setup.py`. If so, you need to use `pip`. I would recommend, using `virtualenv`, and installing from source. 

Here's basically what you should do:

```bash
# clone the repo
$ git clone https://github.com/ansible/ansible-container.git

# create a virtualenv
$ virtualenv acenv

# activate the new environment
$ source ./acenv/bin/activate

# set the working directory to ansible-container
(acvenv) $ cd ansible-container

# install ansible-container
(acvenv) $ pip install -e .[docker,k8s]
```

**Comment by ansham22** [comment]
@chouseknecht thank you so much i was struggling with it. now got it
