### ISSUE TITLE
Error parsing reference - 500 Server Error: Internal Server Error 

### ISSUE THREAD

**Issue by sieben** [ansible/ansible-container#519]
##### container.yml 

```
version: "2"
settings:
  # The deployment_output_path is mounted to the Conductor container, so
  # that the `run` and `deployment` commands can write generated Ansible
  # playbooks to it.
  # deployment_output_path: ~/ansible-deployment
  # The Conductor container does the heavy lifting, and provides a portable
  # Python runtime for building your target containers. It should be derived
  # from the same distribution as you're building your target containers with.
  conductor_base: ubuntu:trusty

services:
  # Add your containers here, specifying the base image you want to build from
  testing_tool:
    from: ubuntu:trusty
    roles:
      - manager
      - dissector

  demo:
    from: ubuntu:trusty
    roles:
      - demo

```

##### OS / ENVIRONMENT

```
sudo ansible-container --debug version
Ansible Container, version 0.9.1rc0
Linux, vm1, 4.4.0-59-generic, #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017, x86_64
3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] /usr/bin/python3
{
  "Driver": "overlay2",
  "OomKillDisable": true,
  "RegistryConfig": {
    "IndexConfigs": {
      "docker.io": {
        "Name": "docker.io",
        "Secure": true,
        "Official": true,
        "Mirrors": null
      }
    },
    "InsecureRegistryCIDRs": [
      "127.0.0.0/8"
    ],
    "Mirrors": []
  },
  "Debug": false,
  "Runtimes": {
    "runc": {
      "path": "docker-runc"
    }
  },
  "CgroupDriver": "cgroupfs",
  "NoProxy": "",
  "SystemStatus": null,
  "OSType": "linux",
  "NGoroutines": 23,
  "InitBinary": "docker-init",
  "RuncCommit": {
    "Expected": "54296cf40ad8143b62dbcaa1d90e520a2136ddfe",
    "ID": "54296cf40ad8143b62dbcaa1d90e520a2136ddfe"
  },
  "NCPU": 1,
  "DefaultRuntime": "runc",
  "Images": 1,
  "CpuCfsQuota": true,
  "IPv4Forwarding": true,
  "InitCommit": {
    "Expected": "949e6fa",
    "ID": "949e6fa"
  },
  "CpuCfsPeriod": true,
  "KernelVersion": "4.4.0-59-generic",
  "BridgeNfIp6tables": true,
  "ClusterAdvertise": "",
  "ContainersPaused": 0,
  "Swarm": {
    "Managers": 0,
    "NodeID": "",
    "Nodes": 0,
    "Cluster": {
      "UpdatedAt": "0001-01-01T00:00:00Z",
      "CreatedAt": "0001-01-01T00:00:00Z",
      "Spec": {
        "EncryptionConfig": {
          "AutoLockManagers": false
        },
        "Orchestration": {},
        "TaskDefaults": {},
        "Raft": {
          "HeartbeatTick": 0,
          "ElectionTick": 0
        },
        "Dispatcher": {},
        "CAConfig": {}
      },
      "ID": "",
      "Version": {}
    },
    "NodeAddr": "",
    "RemoteManagers": null,
    "ControlAvailable": false,
    "LocalNodeState": "inactive",
    "Error": ""
  },
  "ContainersStopped": 1,
  "LoggingDriver": "json-file",
  "OperatingSystem": "Ubuntu 16.04.1 LTS",
  "MemoryLimit": true,
  "ContainersRunning": 0,
  "DockerRootDir": "/var/lib/docker",
  "IndexServerAddress": "https://index.docker.io/v1/",
  "Isolation": "",
  "CPUShares": true,
  "HttpProxy": "",
  "KernelMemory": true,
  "NFd": 19,
  "SecurityOptions": [
    "name=apparmor",
    "name=seccomp,profile=default"
  ],
  "Containers": 1,
  "Labels": null,
  "ID": "2R3A:GDIK:KOBE:AU7T:QRYO:4Q4C:E6I5:TOZD:NIHM:QBK4:AFDU:AKVZ",
  "ExperimentalBuild": false,
  "Name": "vm1",
  "ContainerdCommit": {
    "Expected": "4ab9917febca54791c5f071a9d1f404867857fcc",
    "ID": "4ab9917febca54791c5f071a9d1f404867857fcc"
  },
  "SystemTime": "2017-05-15T14:00:14.835506313Z",
  "NEventsListener": 0,
  "HttpsProxy": "",
  "ClusterStore": "",
  "BridgeNfIptables": true,
  "Plugins": {
    "Authorization": null,
    "Volume": [
      "local"
    ],
    "Network": [
      "bridge",
      "host",
      "macvlan",
      "null",
      "overlay"
    ]
  },
  "DriverStatus": [
    [
      "Backing Filesystem",
      "extfs"
    ],
    [
      "Supports d_type",
      "true"
    ],
    [
      "Native Overlay Diff",
      "true"
    ]
  ],
  "CPUSet": true,
  "SwapLimit": false,
  "ServerVersion": "17.03.1-ce",
  "Architecture": "x86_64",
  "MemTotal": 4143734784,
  "LiveRestoreEnabled": false
}
{
  "KernelVersion": "4.4.0-59-generic",
  "ApiVersion": "1.27",
  "GoVersion": "go1.7.5",
  "GitCommit": "c6d412e",
  "Arch": "amd64",
  "Version": "17.03.1-ce",
  "Os": "linux",
  "BuildTime": "2017-03-27T17:14:09.765618756+00:00",
  "MinAPIVersion": "1.12"
}
```
##### SUMMARY

I'm trying to build my containers using the same command I use on my laptop.

##### STEPS TO REPRODUCE

```
sudo ansible-container --debug build --roles-path ansible/roles
```

##### EXPECTED RESULTS

I expected my containers to be built normally in the Jenkins CI server.

##### ACTUAL RESULTS

They were not.

```
2017-05-15T12:59:53.347895 Unknown exception 500 Server Error: Internal Server Error ("Error parsing reference: "6tisch_testing_tool_tasks-LE6OUUUANE4BKCP7UIDZCQ376ISZ2TTIAG5D5C75FP75ZSKAJPLA-conductor" is not a valid repository/tag: repository name must be lowercase") [container.cli] caller_file=/usr/local/lib/python3.5/dist-packages/structlog/stdlib.py caller_func=exception caller_line=95
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/docker/api/client.py", line 214, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localunixsocket/v1.27/build?pull=False&rm=True&forcerm=False&q=False&t=6tisch_testing_tool_tasks-LE6OUUUANE4BKCP7UIDZCQ376ISZ2TTIAG5D5C75FP75ZSKAJPLA-conductor&nocache=False

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/workspace/6tisch_testing_tool_tasks-LE6OUUUANE4BKCP7UIDZCQ376ISZ2TTIAG5D5C75FP75ZSKAJPLA/ansible-container/container/cli.py", line 261, in __call__
    getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
  File "/home/ubuntu/workspace/6tisch_testing_tool_tasks-LE6OUUUANE4BKCP7UIDZCQ376ISZ2TTIAG5D5C75FP75ZSKAJPLA/ansible-container/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/home/ubuntu/workspace/6tisch_testing_tool_tasks-LE6OUUUANE4BKCP7UIDZCQ376ISZ2TTIAG5D5C75FP75ZSKAJPLA/ansible-container/container/core.py", line 150, in hostcmd_build
    cache=kwargs['cache']
  File "/home/ubuntu/workspace/6tisch_testing_tool_tasks-LE6OUUUANE4BKCP7UIDZCQ376ISZ2TTIAG5D5C75FP75ZSKAJPLA/ansible-container/container/docker/engine.py", line 83, in __wrapped__
    return fn(self, *args, **kwargs)
  File "/home/ubuntu/workspace/6tisch_testing_tool_tasks-LE6OUUUANE4BKCP7UIDZCQ376ISZ2TTIAG5D5C75FP75ZSKAJPLA/ansible-container/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/home/ubuntu/workspace/6tisch_testing_tool_tasks-LE6OUUUANE4BKCP7UIDZCQ376ISZ2TTIAG5D5C75FP75ZSKAJPLA/ansible-container/container/docker/engine.py", line 703, in build_conductor_image
    nocache=not cache):
  File "/usr/local/lib/python3.5/dist-packages/docker/api/client.py", line 305, in _stream_helper
    yield self._result(response, json=decode)
  File "/usr/local/lib/python3.5/dist-packages/docker/api/client.py", line 220, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.5/dist-packages/docker/api/client.py", line 216, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/docker/errors.py", line 30, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("Error parsing reference: "6tisch_testing_tool_tasks-LE6OUUUANE4BKCP7UIDZCQ376ISZ2TTIAG5D5C75FP75ZSKAJPLA-conductor" is not a valid repository/tag: repository name must be lowercase")
```

**Comment by chouseknecht** [comment]
Looks like we need to lower() the project name when tagging the conductor.

**Comment by chouseknecht** [comment]
@sieben 

Thanks for using Ansible Container! We appreciate you taking the time to open an issue and share your feedback. 

I think PR #520 fixes this issue. Would appreciate it, if you can test in your CI environment and confirm.

Thanks!

**Comment by sieben** [comment]
I think it works now. Thanks for the quick actions :-)

Le lun. 15 mai 2017 à 17:37, Chris Houseknecht <notifications@github.com> a
écrit :

**Comment by chouseknecht** [comment]
Cool!

Closing this issue. If you run into additional problems, please feel free to re-open, or start a new issue.
