### ISSUE TITLE
Ansible Container pip installation sets owner to awx ? 

### ISSUE THREAD

**Issue by brucellino** [ansible/ansible-container#537]
##### ISSUE TYPE

 - Bug Report

##### container.yml 
N/A

##### OS / ENVIRONMENT

```
Ansible Container, version 0.9.1rc0
Linux, serbaggio, 4.4.0-72-generic, #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017, x86_64
2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] /usr/bin/python
{
  "ContainersPaused": 0, 
  "Labels": null, 
  "CgroupDriver": "cgroupfs", 
  "ContainersRunning": 0, 
  "ContainerdCommit": {
    "Expected": "4ab9917febca54791c5f071a9d1f404867857fcc", 
    "ID": "4ab9917febca54791c5f071a9d1f404867857fcc"
  }, 
  "InitBinary": "docker-init", 
  "NGoroutines": 109, 
  "Swarm": {
    "Managers": 1, 
    "ControlAvailable": true, 
    "NodeID": "q687zdq49cxj9q63z8zkgvxkp", 
    "Cluster": {
      "Spec": {
        "Name": "default", 
        "TaskDefaults": {}, 
        "Orchestration": {
          "TaskHistoryRetentionLimit": 5
        }, 
        "EncryptionConfig": {
          "AutoLockManagers": false
        }, 
        "Raft": {
          "HeartbeatTick": 1, 
          "LogEntriesForSlowFollowers": 500, 
          "KeepOldSnapshots": 0, 
          "ElectionTick": 3, 
          "SnapshotInterval": 10000
        }, 
        "CAConfig": {
          "NodeCertExpiry": 7776000000000000
        }, 
        "Dispatcher": {
          "HeartbeatPeriod": 5000000000
        }
      }, 
      "Version": {
        "Index": 91
      }, 
      "ID": "42khy9138y1jh6rmin6z5tv87", 
      "CreatedAt": "2017-04-22T08:33:52.369122993Z", 
      "UpdatedAt": "2017-05-22T09:16:26.573444432Z"
    }, 
    "Nodes": 1, 
    "Error": "", 
    "RemoteManagers": [
      {
        "NodeID": "q687zdq49cxj9q63z8zkgvxkp", 
        "Addr": "192.168.1.8:2377"
      }
    ], 
    "LocalNodeState": "active", 
    "NodeAddr": "192.168.1.8"
  }, 
  "LoggingDriver": "json-file", 
  "OSType": "linux", 
  "HttpProxy": "", 
  "Runtimes": {
    "runc": {
      "path": "docker-runc"
    }
  }, 
  "DriverStatus": [
    [
      "Root Dir", 
      "/var/lib/docker/aufs"
    ], 
    [
      "Backing Filesystem", 
      "extfs"
    ], 
    [
      "Dirs", 
      "308"
    ], 
    [
      "Dirperm1 Supported", 
      "true"
    ]
  ], 
  "OperatingSystem": "Ubuntu 16.04.2 LTS", 
  "Containers": 84, 
  "HttpsProxy": "", 
  "BridgeNfIp6tables": true, 
  "MemTotal": 8235982848, 
  "SecurityOptions": [
    "name=apparmor", 
    "name=seccomp,profile=default"
  ], 
  "Driver": "aufs", 
  "IndexServerAddress": "https://index.docker.io/v1/", 
  "ClusterStore": "", 
  "InitCommit": {
    "Expected": "949e6fa", 
    "ID": "949e6fa"
  }, 
  "Isolation": "", 
  "SystemStatus": null, 
  "OomKillDisable": true, 
  "ClusterAdvertise": "", 
  "SystemTime": "2017-05-23T10:51:18.862056131+02:00", 
  "Name": "serbaggio", 
  "CPUSet": true, 
  "RegistryConfig": {
    "InsecureRegistryCIDRs": [
      "127.0.0.0/8"
    ], 
    "IndexConfigs": {
      "docker.io": {
        "Official": true, 
        "Name": "docker.io", 
        "Secure": true, 
        "Mirrors": null
      }
    }, 
    "Mirrors": []
  }, 
  "DefaultRuntime": "runc", 
  "ContainersStopped": 84, 
  "NCPU": 8, 
  "NFd": 30, 
  "Architecture": "x86_64", 
  "KernelMemory": true, 
  "CpuCfsQuota": true, 
  "Debug": false, 
  "ID": "O4O7:C7V3:PT4A:3GDE:PDWG:KHS2:MOI2:CNIJ:DMZH:OH7U:WOTC:5345", 
  "IPv4Forwarding": true, 
  "KernelVersion": "4.4.0-72-generic", 
  "BridgeNfIptables": true, 
  "NoProxy": "", 
  "LiveRestoreEnabled": false, 
  "ServerVersion": "17.03.1-ce", 
  "CpuCfsPeriod": true, 
  "ExperimentalBuild": false, 
  "MemoryLimit": true, 
  "SwapLimit": false, 
  "Plugins": {
    "Volume": [
      "local"
    ], 
    "Network": [
      "bridge", 
      "host", 
      "macvlan", 
      "null", 
      "overlay"
    ], 
    "Authorization": null
  }, 
  "Images": 45, 
  "DockerRootDir": "/var/lib/docker", 
  "NEventsListener": 0, 
  "CPUShares": true, 
  "RuncCommit": {
    "Expected": "54296cf40ad8143b62dbcaa1d90e520a2136ddfe", 
    "ID": "54296cf40ad8143b62dbcaa1d90e520a2136ddfe"
  }
}
{
  "KernelVersion": "4.4.0-72-generic", 
  "Arch": "amd64", 
  "BuildTime": "2017-03-27T17:14:09.765618756+00:00", 
  "ApiVersion": "1.27", 
  "Version": "17.03.1-ce", 
  "MinAPIVersion": "1.12", 
  "GitCommit": "c6d412e", 
  "Os": "linux", 
  "GoVersion": "go1.7.5"
}

```
##### SUMMARY

This is a funny one - I've tried to find a way to reliably reproduce it, but I'm not sure where the actual problem is introduced. Bear with me please.

The description of the problem is that at some point in the development workflow, the ownership of files in my project directory is changed to awx.  This creates permissions problems : 

```
 pip install ansible-container[docker]
Collecting ansible-container[docker]
Collecting structlog[dev]>=16.1 (from ansible-container[docker])
  Using cached structlog-17.2.0-py2.py3-none-any.whl
Requirement already satisfied: six>=1.10 in ./dev/lib/python2.7/site-packages (from ansible-container[docker])
Collecting requests>=2 (from ansible-container[docker])
  Using cached requests-2.14.2-py2.py3-none-any.whl
Collecting PyYAML>=3.12 (from ansible-container[docker])
Collecting ruamel.yaml>=0.14.2 (from ansible-container[docker])
  Using cached ruamel.yaml-0.14.12-cp27-cp27mu-manylinux1_x86_64.whl
Collecting Jinja2>=2.9 (from ansible-container[docker])
  Using cached Jinja2-2.9.6-py2.py3-none-any.whl
Collecting docker>=2.1; extra == "docker" (from ansible-container[docker])
  Using cached docker-2.3.0-py2.py3-none-any.whl
Collecting colorama; extra == "dev" (from structlog[dev]>=16.1->ansible-container[docker])
  Using cached colorama-0.3.9-py2.py3-none-any.whl
Collecting ruamel.ordereddict (from ruamel.yaml>=0.14.2->ansible-container[docker])
  Using cached ruamel.ordereddict-0.4.9-cp27-cp27mu-manylinux1_x86_64.whl
Collecting MarkupSafe>=0.23 (from Jinja2>=2.9->ansible-container[docker])
Collecting backports.ssl-match-hostname>=3.5; python_version < "3.5" (from docker>=2.1; extra == "docker"->ansible-container[docker])
Collecting websocket-client>=0.32.0 (from docker>=2.1; extra == "docker"->ansible-container[docker])
Collecting ipaddress>=1.0.16; python_version < "3.3" (from docker>=2.1; extra == "docker"->ansible-container[docker])
  Using cached ipaddress-1.0.18-py2-none-any.whl
Collecting docker-pycreds>=0.2.1 (from docker>=2.1; extra == "docker"->ansible-container[docker])
  Using cached docker_pycreds-0.2.1-py2.py3-none-any.whl
Installing collected packages: colorama, structlog, requests, PyYAML, ruamel.ordereddict, ruamel.yaml, MarkupSafe, Jinja2, backports.ssl-match-hostname, websocket-client, ipaddress, docker-pycreds, docker, ansible-container
Exception:
Traceback (most recent call last):
  File "/home/becker/Ops/AAROC/fgSetup/AnsibleContainer/dev/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/becker/Ops/AAROC/fgSetup/AnsibleContainer/dev/local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/becker/Ops/AAROC/fgSetup/AnsibleContainer/dev/local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/becker/Ops/AAROC/fgSetup/AnsibleContainer/dev/local/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/becker/Ops/AAROC/fgSetup/AnsibleContainer/dev/local/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/becker/Ops/AAROC/fgSetup/AnsibleContainer/dev/local/lib/python2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/becker/Ops/AAROC/fgSetup/AnsibleContainer/dev/local/lib/python2.7/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/home/becker/Ops/AAROC/fgSetup/AnsibleContainer/dev/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/home/becker/Ops/AAROC/fgSetup/AnsibleContainer/dev/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/home/becker/Ops/AAROC/fgSetup/AnsibleContainer/dev/lib/python2.7/site-packages/colorama-0.3.9.dist-info'
```

This is a really low-priority issue, I don't expect it to get "fixed", and there's an obvious workaround. I just wanted to report it since I hadn't seen it reported anywhere.

**Comment by j00bar** [comment]
I'm not convinced that this is something that Ansible Container is doing. While Ansible Tower has an `awx` user that's significant, Ansible Container definitely does not. I'm open to being convinced, but I encourage you to look elsewhere for the source of this permissions issue.
