### ISSUE TITLE
Cant deploy to openshift

### ISSUE THREAD

**Issue by karmab** [ansible/ansible-container#539]
##### ISSUE TYPE

 - Bug Report
 
##### container.yml 

```
version: "2"
settings:
  # The deployment_output_path is mounted to the Conductor container, so
  # that the `run` and `deployment` commands can write generated Ansible
  # playbooks to it.
  # deployment_output_path: ~/ansible-deployment
  # The Conductor container does the heavy lifting, and provides a portable
  # Python runtime for building your target containers. It should be derived
  # from the same distribution as you're building your target containers with.
  conductor_base: centos:7

  # When using the k8s or openshift engines, use the following to authorize with the API.
  # Values set here will be passed to the Ansible modules. Any file paths will be mounted
  # to the conductor container, allowing the `run` command to access the API.
  k8s_auth:
    # path to a K8s config file
    config_file: /root/.kube/config
    # name of a context found within the config.json file
    # context:
    # URL for accessing the K8s API
    #host: https://origin:8443/oapi/v1
    # An API authentication token
    #api_key: u1hS5G1HNVRUABU7b5hjt4a8BpmYd6O92PsOTh_7pXY
    # Path to a ca cert file
    #ssl_ca_cert:
    # Path to a cert file
    #cert_file:
    # Path to a key file
    #key_file:
    #boolean, indicating if SSL certs should be validated
    verify_ssl: false

  # When using the k8s or openshift engines, use the following to set the namespace.
  # If not set, the project name will be used. For openshift, the namespace maps to a project,
  # and description and display_name are supported.
  k8s_namespace:
    name: proutos
  #  description:
  #  display_name:

services:
  # Add your containers here, specifying the base image you want to build from
  # For example:
  #
  httpd:
    from: centos:7
    roles:
      - x
    ports:
      - "80:80"
    command: ['/usr/bin/dumb-init', '/usr/sbin/httpd', '-D', 'FOREGROUND']
    dev_overrides:
      environment:
        - "DEBUG=1"

registries:
  # Add optional registries used for deployment. For example:
  #  google:
  #    url: https://gcr.io
  #    namespace: my-cool-project-xxxxxx
  #openshift:
  # url: https://192.168.122.115.xip.io
```

##### OS / ENVIRONMENT

```
Ansible Container, version 0.9.0.0
Linux, ansible-container.localdomain, 3.10.0-327.22.2.el7.x86_64, #1 SMP Thu Jun 23 17:05:11 UTC 2016, x86_64
2.7.5 (default, Nov 20 2015, 02:00:19)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] /usr/bin/python2
{
  "ContainersPaused": 0,
  "Labels": null,
  "DefaultRuntime": "docker-runc",
  "CgroupDriver": "systemd",
  "ClusterAdvertise": "",
  "ContainersRunning": 0,
  "NGoroutines": 25,
  "Swarm": {
    "Managers": 0,
    "ControlAvailable": false,
    "NodeID": "",
    "Cluster": {
      "Spec": {
        "Raft": {},
        "CAConfig": {},
        "Dispatcher": {},
        "Orchestration": {},
        "TaskDefaults": {}
      },
      "Version": {},
      "ID": "",
      "CreatedAt": "0001-01-01T00:00:00Z",
      "UpdatedAt": "0001-01-01T00:00:00Z"
    },
    "Nodes": 0,
    "Error": "",
    "RemoteManagers": null,
    "LocalNodeState": "inactive",
    "NodeAddr": ""
  },
  "LoggingDriver": "journald",
  "OSType": "linux",
  "HttpProxy": "",
  "Runtimes": {
    "runc": {
      "path": "docker-runc"
    },
    "docker-runc": {
      "path": "/usr/libexec/docker/docker-runc-current"
    }
  },
  "DriverStatus": [
    [
      "Pool Name",
      "docker-253:1-25167093-pool"
    ],
    [
      "Pool Blocksize",
      "65.54 kB"
    ],
    [
      "Base Device Size",
      "10.74 GB"
    ],
    [
      "Backing Filesystem",
      "xfs"
    ],
    [
      "Data file",
      "/dev/loop0"
    ],
    [
      "Metadata file",
      "/dev/loop1"
    ],
    [
      "Data Space Used",
      "798.8 MB"
    ],
    [
      "Data Space Total",
      "107.4 GB"
    ],
    [
      "Data Space Available",
      "8.668 GB"
    ],
    [
      "Metadata Space Used",
      "1.507 MB"
    ],
    [
      "Metadata Space Total",
      "2.147 GB"
    ],
    [
      "Metadata Space Available",
      "2.146 GB"
    ],
    [
      "Thin Pool Minimum Free Space",
      "10.74 GB"
    ],
    [
      "Udev Sync Supported",
      "true"
    ],
    [
      "Deferred Removal Enabled",
      "false"
    ],
    [
      "Deferred Deletion Enabled",
      "false"
    ],
    [
      "Deferred Deleted Device Count",
      "0"
    ],
    [
      "Data loop file",
      "/var/lib/docker/devicemapper/devicemapper/data"
    ],
    [
      "Metadata loop file",
      "/var/lib/docker/devicemapper/devicemapper/metadata"
    ],
    [
      "Library Version",
      "1.02.135-RHEL7 (2016-11-16)"
    ]
  ],
  "OperatingSystem": "CentOS Linux 7 (Core)",
  "Containers": 0,
  "HttpsProxy": "",
  "BridgeNfIp6tables": false,
  "MemTotal": 1929199616,
  "Driver": "devicemapper",
  "IndexServerAddress": "https://index.docker.io/v1/",
  "ClusterStore": "",
  "ExecutionDriver": "",
  "Registries": [
    {
      "Name": "docker.io",
      "Secure": true
    }
  ],
  "SystemStatus": null,
  "OomKillDisable": true,
  "PkgVersion": "docker-common-1.12.6-16.el7.centos.x86_64",
  "SystemTime": "2017-05-23T20:43:50.004889074Z",
  "Name": "ansible-container.localdomain",
  "CPUSet": true,
  "RegistryConfig": {
    "InsecureRegistryCIDRs": [
      "127.0.0.0/8"
    ],
    "IndexConfigs": {
      "docker.io": {
        "Official": true,
        "Name": "docker.io",
        "Secure": true,
        "Mirrors": null
      }
    },
    "Mirrors": null
  },
  "SecurityOptions": [
    "seccomp",
    "selinux"
  ],
  "ContainersStopped": 0,
  "NCPU": 2,
  "NFd": 17,
  "Architecture": "x86_64",
  "KernelMemory": true,
  "CpuCfsQuota": true,
  "Debug": false,
  "IndexServerName": "docker.io",
  "ID": "JBMT:N7KX:WYNW:QFFA:XECB:IMW2:NL4W:M5QI:JNLM:ULSA:STGW:DQWD",
  "IPv4Forwarding": true,
  "KernelVersion": "3.10.0-327.22.2.el7.x86_64",
  "BridgeNfIptables": false,
  "NoProxy": "",
  "LiveRestoreEnabled": false,
  "ServerVersion": "1.12.6",
  "CpuCfsPeriod": true,
  "ExperimentalBuild": false,
  "MemoryLimit": true,
  "SwapLimit": true,
  "Plugins": {
    "Volume": [
      "local"
    ],
    "Network": [
      "null",
      "bridge",
      "host",
      "overlay"
    ],
    "Authorization": null
  },
  "Images": 12,
  "DockerRootDir": "/var/lib/docker",
  "NEventsListener": 0,
  "CPUShares": true
}
{
  "KernelVersion": "3.10.0-327.22.2.el7.x86_64",
  "PkgVersion": "docker-common-1.12.6-16.el7.centos.x86_64",
  "Os": "linux",
  "BuildTime": "2017-04-14T13:46:13.608221474+00:00",
  "ApiVersion": "1.24",
  "Version": "1.12.6",
  "GitCommit": "3a094bd/1.12.6",
  "Arch": "amd64",
  "GoVersion": "go1.7.4"
}
```
##### SUMMARY

fails to deploy to openshift 

##### STEPS TO REPRODUCE

```
ansible-container --debug --engine openshift deploy --local-images
```

##### EXPECTED RESULTS

contacting openshift

##### ACTUAL RESULTS

```
2017-05-23T20:44:45.956670 Got extra args to `deploy` command [container.core] arguments={'with_volumes': [], 'username': None, 'roles_path': None, 'with_variables': [], 'selinux': True, 'subcommand': 'deploy', 'devel': False, 'deployment_output_path': None, 'tag': None, 'local_images': True, 'push_to': None, 'debug': True, 'password': None, 'email': None} caller_file=/usr/lib/python2.7/site-packages/container/core.py caller_func=hostcmd_deploy caller_line=167
2017-05-23T20:44:45.969393 The default type is            [container.config] caller_file=/usr/lib/python2.7/site-packages/container/config.py caller_func=_resolve_defaults caller_line=124 config=<class 'ruamel.yaml.comments.CommentedMap'> defaults=<type '_ordereddict.ordereddict'>
2017-05-23T20:44:45.970103 Getting environment variables... [container.config] caller_file=/usr/lib/python2.7/site-packages/container/config.py caller_func=_get_environment_variables caller_line=140
2017-05-23T20:44:45.971037 Read environment variables     [container.config] caller_file=/usr/lib/python2.7/site-packages/container/config.py caller_func=_get_environment_variables caller_line=145 env_vars={}
2017-05-23T20:44:45.971748 Resolved template variables    [container.config] caller_file=/usr/lib/python2.7/site-packages/container/config.py caller_func=_resolve_defaults caller_line=129 template_vars={}
2017-05-23T20:44:45.972401 Parsed config                  [container.config] caller_file=/usr/lib/python2.7/site-packages/container/config.py caller_func=set_env caller_line=110 config={"version": "2", "settings": {"conductor_base": "centos:7", "k8s_auth": {"config_file": "/root/.kube/config", "verify_ssl": false}, "k8s_namespace": {"name": "proutos"}}, "services": {"httpd": {"from": "centos:7", "roles": ["x"], "ports": ["80:80"], "command": ["/usr/bin/dumb-init", "/usr/sbin/httpd", "-D", "FOREGROUND"]}}, "registries": {}, "defaults": {}}
2017-05-23T20:44:45.973015 Loading engine capabilities    [container.utils.loader] caller_file=/usr/lib/python2.7/site-packages/container/utils/loader.py caller_func=load_engine caller_line=14 capabilities=['LOGIN', 'PUSH', 'DEPLOY'] engine=openshift
2017-05-23T20:44:46.248752 Volume for k8s                 [container.k8s.base_engine] caller_file=/usr/lib/python2.7/site-packages/container/k8s/base_engine.py caller_func=__init__ caller_line=44 volumes=None
2017-05-23T20:44:46.250040 Call: Engine.run_conductor     [container.docker.engine] args=('deploy', {'services': ordereddict([('httpd', ordereddict([('from', 'centos:7'), ('roles', ['x']), ('ports', ['80:80']), ('command', ['/usr/bin/dumb-init', '/usr/sbin/httpd', '-D', 'FOREGROUND'])]))]), 'version': '2', 'registries': ordereddict([]), 'defaults': ordereddict([]), 'settings': ordereddict([('conductor_base', 'centos:7'), ('k8s_auth', ordereddict([('config_file', '/root/.kube/config'), ('verify_ssl', False)])), ('k8s_namespace', ordereddict([('name', 'proutos')]))])}, '/root/x', {'username': None, 'selinux': True, 'subcommand': 'deploy', 'devel': False, 'debug': True, 'tag': None, 'local_images': True, 'password': None, 'k8s_auth': ordereddict([('config_file', '/root/.kube/config'), ('verify_ssl', False)]), 'with_volumes': [], 'roles_path': None, 'with_variables': [], 'deployment_output_path': '/root/x/ansible-deployment', 'host_user_uid': 0, 'push_to': None, 'host_user_gid': 0, 'email': None}) caller_file=/usr/lib/python2.7/site-packages/container/docker/engine.py caller_func=Engine.run_conductor caller_line=23 kwargs={'engine_name': 'openshift'}
2017-05-23T20:44:46.251045 Call: Engine.run_conductor     [container.docker.engine] args=('deploy', {'services': ordereddict([('httpd', ordereddict([('from', 'centos:7'), ('roles', ['x']), ('ports', ['80:80']), ('command', ['/usr/bin/dumb-init', '/usr/sbin/httpd', '-D', 'FOREGROUND'])]))]), 'version': '2', 'registries': ordereddict([]), 'defaults': ordereddict([]), 'settings': ordereddict([('conductor_base', 'centos:7'), ('k8s_auth', ordereddict([('config_file', '/root/.kube/config'), ('verify_ssl', False)])), ('k8s_namespace', ordereddict([('name', 'proutos')]))])}, '/root/x', {'username': None, 'selinux': True, 'subcommand': 'deploy', 'devel': False, 'debug': True, 'tag': None, 'local_images': True, 'password': None, 'k8s_auth': ordereddict([('config_file', '/root/.kube/config'), ('verify_ssl', False)]), 'with_volumes': [], 'roles_path': None, 'with_variables': [], 'deployment_output_path': '/root/x/ansible-deployment', 'host_user_uid': 0, 'push_to': None, 'host_user_gid': 0, 'email': None}) caller_file=/usr/lib/python2.7/site-packages/container/docker/engine.py caller_func=Engine.run_conductor caller_line=23 kwargs={'volumes': {'/root/.kube/config': {'bind': '/root/.kube/config', 'mode': 'ro'}}, 'engine_name': 'openshift'}
2017-05-23T20:44:46.290265 Docker run:                    [container.docker.engine] caller_file=/usr/lib/python2.7/site-packages/container/docker/engine.py caller_func=run_conductor caller_line=266 image=u'sha256:85ad61a3bf869544a111c6b470fb10b245163f90486219ff0036987450fd826c' params={'name': u'x_conductor', 'cap_add': ['SYS_ADMIN'], 'environment': {'DOCKER_HOST': 'unix:///var/run/docker.sock', 'ANSIBLE_ROLES_PATH': '/src/roles:/etc/ansible/roles'}, 'working_dir': '/src', 'command': ['conductor', 'deploy', '--project-name', 'x', '--engine', 'openshift', '--params', u'eyJ1c2VybmFtZSI6IG51bGwsICJzZWxpbnV4IjogdHJ1ZSwgInN1YmNvbW1hbmQiOiAiZGVwbG95IiwgImRldmVsIjogZmFsc2UsICJkZWJ1ZyI6IHRydWUsICJ0YWciOiBudWxsLCAibG9jYWxfaW1hZ2VzIjogdHJ1ZSwgInBhc3N3b3JkIjogbnVsbCwgIms4c19hdXRoIjogeyJjb25maWdfZmlsZSI6ICIvcm9vdC8ua3ViZS9jb25maWciLCAidmVyaWZ5X3NzbCI6IGZhbHNlfSwgIndpdGhfdm9sdW1lcyI6IFtdLCAicm9sZXNfcGF0aCI6IG51bGwsICJ3aXRoX3ZhcmlhYmxlcyI6IFtdLCAiZGVwbG95bWVudF9vdXRwdXRfcGF0aCI6ICIvcm9vdC94L2Fuc2libGUtZGVwbG95bWVudCIsICJob3N0X3VzZXJfdWlkIjogMCwgInB1c2hfdG8iOiBudWxsLCAiaG9zdF91c2VyX2dpZCI6IDAsICJlbWFpbCI6IG51bGx9', '--config', u'eyJzZXJ2aWNlcyI6IHsiaHR0cGQiOiB7ImZyb20iOiAiY2VudG9zOjciLCAicm9sZXMiOiBbIngiXSwgInBvcnRzIjogWyI4MDo4MCJdLCAiY29tbWFuZCI6IFsiL3Vzci9iaW4vZHVtYi1pbml0IiwgIi91c3Ivc2Jpbi9odHRwZCIsICItRCIsICJGT1JFR1JPVU5EIl19fSwgInZlcnNpb24iOiAiMiIsICJyZWdpc3RyaWVzIjoge30sICJkZWZhdWx0cyI6IHt9LCAic2V0dGluZ3MiOiB7InB3ZCI6ICIvcm9vdC94IiwgIms4c19hdXRoIjogeyJjb25maWdfZmlsZSI6ICIvcm9vdC8ua3ViZS9jb25maWciLCAidmVyaWZ5X3NzbCI6IGZhbHNlfSwgIms4c19uYW1lc3BhY2UiOiB7Im5hbWUiOiAicHJvdXRvcyJ9LCAiY29uZHVjdG9yX2Jhc2UiOiAiY2VudG9zOjcifX0=', '--encoding', 'b64json'], 'user': 'root', 'volumes': {'/root/x': {'bind': '/src', 'mode': 'ro'}, '/root/.kube/config': {'bind': '/root/.kube/config', 'mode': 'ro'}, '/var/run/docker.sock': {'bind': '/var/run/docker.sock', 'mode': 'rw'}, '/root/x/ansible-deployment': {'bind': '/root/x/ansible-deployment', 'mode': 'rw'}}, 'detach': True}
Parsing conductor CLI args.
2017-05-23T20:45:00.561399 Processing defaults section... [container.config] caller_file=/_ansible/container/config.py caller_func=_process_defaults caller_line=248
2017-05-23T20:45:00.563304 Processing section...          [container.config] caller_file=/_ansible/container/config.py caller_func=_process_top_level_sections caller_line=257 section=volumes
2017-05-23T20:45:00.565315 Processing section...          [container.config] caller_file=/_ansible/container/config.py caller_func=_process_top_level_sections caller_line=257 section=registries
2017-05-23T20:45:00.567385 Processing service...          [container.config] caller_file=/_ansible/container/config.py caller_func=_process_services caller_line=266 service=u'httpd'
2017-05-23T20:45:00.571504 Rendering service keys from defaults [container.config] caller_file=/_ansible/container/config.py caller_func=_process_services caller_line=292 defaults={} service=u'httpd'
2017-05-23T20:45:00.576969 Starting Ansible Container Conductor: deploy [container.cli] caller_file=/_ansible/container/cli.py caller_func=conductor_commandline caller_line=344 services={"httpd": {"command": ["/usr/bin/dumb-init", "/usr/sbin/httpd", "-D", "FOREGROUND"], "from": "centos:7", "ports": ["80:80"], "roles": ["x"], "defaults": {}}}
2017-05-23T20:45:00.579965 Loading engine capabilities    [container.utils.loader] caller_file=/_ansible/container/utils/loader.py caller_func=load_engine caller_line=14 capabilities=['DEPLOY'] engine=openshift
2017-05-23T20:45:00.887175 Volume for k8s                 [container.k8s.base_engine] caller_file=/_ansible/container/k8s/base_engine.py caller_func=__init__ caller_line=44 volumes=None
2017-05-23T20:45:00.889431 Engine integration loaded. Preparing deploy. [container.core] caller_file=/_ansible/container/core.py caller_func=conductorcmd_deploy caller_line=756 engine=u'OpenShift\u2122'
2017-05-23T20:45:00.891547 Verifying image for httpd      [container.core] caller_file=/_ansible/container/core.py caller_func=conductorcmd_deploy caller_line=760
2017-05-23T20:45:01.122431 conductorcmd_deploy            [container.core] caller_file=/_ansible/container/core.py caller_func=conductorcmd_deploy caller_line=767 kwargs={u'username': None, u'with_volumes': [], 'repository_data': ordereddict([]), u'local_images': True, u'roles_path': None, u'with_variables': [], u'selinux': True, u'subcommand': u'deploy', u'debug': True, u'devel': False, u'deployment_output_path': u'/root/x/ansible-deployment', u'tag': None, u'host_user_uid': 0, u'push_to': None, u'host_user_gid': 0, u'password': None, u'k8s_auth': {u'verify_ssl': False, u'config_file': u'/root/.kube/config'}, u'email': None, 'volume_data': ordereddict([])}
Traceback (most recent call last):
  File "/usr/bin/conductor", line 11, in <module>
    load_entry_point('ansible-container', 'console_scripts', 'conductor')()
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/cli.py", line 351, in conductor_commandline
    **params)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/core.py", line 770, in conductorcmd_deploy
    playbook = engine.generate_orchestration_playbook(**kwargs)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/openshift/engine.py", line 51, in generate_orchestration_playbook
    **kwargs)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/k8s/base_engine.py", line 97, in generate_orchestration_playbook
    self.k8s_client.set_authorization(kwargs['auth'])
AttributeError: 'OpenShiftObjectHelper' object has no attribute 'set_authorization'
2017-05-23T20:45:01.731773 Conductor terminated. Cleaning up. [container.docker.engine] caller_file=/usr/lib/python2.7/site-packages/container/docker/engine.py caller_func=await_conductor_command caller_line=293 command_rc=1 conductor_id=u'f23b7ec0d77958504c28769a02d352429abff2236f71f731aafe1d4ade0bd72e' save_container=False
2017-05-23T20:45:03.910769 Conductor exited with status 1 [container.cli] caller_file=/usr/lib/python2.7/site-packages/container/cli.py caller_func=__call__ caller_line=271
```

**Comment by chouseknecht** [comment]
This is honked-up for sure. The intention is to use `settings.k8s_auth` during the `run` command, and enable the generated playbook to execute inside the conductor container. 

I think the best, or safest, way to pass these settings to the Python openshift module, which is used by the Ansible modules to communicate with the API, is via environment variables. Otherwise, they need to be added to included in the generated playbook, and passed as parameters to each individual module.

The environment variables should be checked by the openshift module, rather than the Ansible modules, and so to that end, I have this PR opened: https://github.com/openshift/openshift-restclient-python/pull/59

When that lands, I'll update Ansible Container to use the latest openshift module code within the conductor.
