### ISSUE TITLE
Ensure pip version >= 6.0

### ISSUE THREAD

**Issue by ichilton** [ansible/ansible-container#543]
##### ISSUE TYPE

 - Bug Report

##### OS / ENVIRONMENT
Debian 8 (jessie)

##### SUMMARY
Unable to install

##### STEPS TO REPRODUCE

```
# pip install ansible-container
Downloading/unpacking ansible-container
  Downloading ansible-container-0.9.0.0.tar.gz (1.3MB): 1.3MB downloaded
  Running setup.py (path:/tmp/pip-build-Qkeeia/ansible-container/setup.py) egg_info for package ansible-container
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-Qkeeia/ansible-container/setup.py", line 50, in <module>
        install_requires=[str(ir.req) for ir in install_reqs if ir.match_markers()],
    AttributeError: 'InstallRequirement' object has no attribute 'match_markers'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-Qkeeia/ansible-container/setup.py", line 50, in <module>

    install_requires=[str(ir.req) for ir in install_reqs if ir.match_markers()],

AttributeError: 'InstallRequirement' object has no attribute 'match_markers'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-Qkeeia/ansible-container
Storing debug log for failure in /root/.pip/pip.log
```

I read in another issue about doing:
```
# pip uninstall docker-py
Cannot uninstall requirement docker-py, not installed
Storing debug log for failure in /root/.pip/pip.log
# pip install 'docker>=2.1'
Downloading/unpacking docker>=2.1
  Downloading docker-2.3.0-py2.py3-none-any.whl (108kB): 108kB downloaded
Downloading/unpacking docker-pycreds>=0.2.1 (from docker>=2.1)
  Downloading docker_pycreds-0.2.1-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.0 in /usr/lib/python2.7/dist-packages (from docker>=2.1)
Downloading/unpacking requests>=2.5.2,!=2.11.0,!=2.12.2 (from docker>=2.1)
  Downloading requests-2.14.2-py2.py3-none-any.whl (560kB): 560kB downloaded
Downloading/unpacking backports.ssl-match-hostname>=3.5 (from docker>=2.1)
  Downloading backports.ssl_match_hostname-3.5.0.1.tar.gz
  Running setup.py (path:/tmp/pip-build-LnnHiH/backports.ssl-match-hostname/setup.py) egg_info for package backports.ssl-match-hostname

Downloading/unpacking ipaddress>=1.0.16 (from docker>=2.1)
  Downloading ipaddress-1.0.18-py2-none-any.whl
Downloading/unpacking websocket-client>=0.32.0 (from docker>=2.1)
  Downloading websocket_client-0.40.0.tar.gz (196kB): 196kB downloaded
  Running setup.py (path:/tmp/pip-build-LnnHiH/websocket-client/setup.py) egg_info for package websocket-client

Installing collected packages: docker, docker-pycreds, requests, backports.ssl-match-hostname, ipaddress, websocket-client
  Found existing installation: requests 2.4.3
    Not uninstalling requests at /usr/lib/python2.7/dist-packages, owned by OS
  Running setup.py install for backports.ssl-match-hostname

  Running setup.py install for websocket-client
    changing mode of build/scripts-2.7/wsdump.py from 644 to 755

    changing mode of /usr/local/bin/wsdump.py to 755
Successfully installed docker docker-pycreds requests backports.ssl-match-hostname ipaddress websocket-client
Cleaning up...
```

but then:

```
# pip install ansible-container
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead
```

**Comment by karmab** [comment]
i think its related to packaged version of pip in debian8
running pip install -U pip made me go over the error ( but then i got an error when trying requirement python-dev ....)

**Comment by j00bar** [comment]
`match_markers` was introduced in pip 6.0 (pypa/pip@e2368429440). We should error out in `setup.py` if that requirement isn't met. It was released in 2014 - I think it's an okay thing to require. :)
