### ISSUE TITLE
openshift python module breaks build of conductor

### ISSUE THREAD

**Issue by TomasTomecek** [ansible/ansible-container#581]
##### ISSUE TYPE
 - Bug Report

##### OS / ENVIRONMENT

```
Ansible Container, version 0.9.1
Linux, oat, 4.11.3-300.fc26.x86_64, #1 SMP Thu May 25 18:43:57 UTC 2017, x86_64
3.6.1 (default, May 17 2017, 11:46:19)
[GCC 7.1.1 20170503 (Red Hat 7.1.1-1)] /bin/python3
<not pasting `docker info` since it's unrelated>
{
  "Version": "1.13.1",
  "ApiVersion": "1.26",
  "MinAPIVersion": "1.12",
  "GitCommit": "51eb16e/1.13.1",
  "GoVersion": "go1.8.1",
  "Os": "linux",
  "Arch": "amd64",
  "KernelVersion": "4.11.3-300.fc26.x86_64",
  "BuildTime": "2017-05-28T14:18:46.797017766+00:00",
  "PkgVersion": "docker-1.13.1-13.git51eb16e.fc27.x86_64"
}
```
##### SUMMARY
`ansible-container build` fails b/c build of conductor image fails

##### ACTUAL RESULTS

```
Installing collected packages: MarkupSafe, jinja2, PyYAML, idna, asn1crypto, six, enum34, ipaddress, pycparser, cffi, cryptography, pyasn1, paramiko, pycrypto, ansible, dictd
iffer, backports.ssl-match-hostname, websocket-client, python-dateutil, pyasn1-modules, rsa, httplib2, oauth2client, urllib3, certifi, kubernetes, python-string-utils, ruamel
.ordereddict, ruamel.yaml, openshift, cached-property, functools32, jsonschema, texttable, dockerpty, colorama, chardet, requests, docopt, docker-pycreds, docker, docker-comp
ose, structlog
  Running setup.py install for openshift: started
    Running setup.py install for openshift: finished with status 'done'
  Found existing installation: chardet 2.2.1
    Uninstalling chardet-2.2.1:
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/lib/python2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/usr/lib/python2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/usr/lib64/python2.7/shutil.py", line 299, in move
    rmtree(src)
  File "/usr/lib64/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib64/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/usr/lib/python2.7/site-packages/chardet'

```

```

```

**Comment by chouseknecht** [comment]
@TomasTomecek 

Thanks for taking the time to open an issue. 

What base image are you using for the conductor?

**Comment by TomasTomecek** [comment]
I'm using the default one: all I did was that I followed [your demo steps](https://ansible.github.io/ansible-container-demo/). [Here's the full output](https://paste.fedoraproject.org/paste/2XoPdQ2QsayVBnsb2TXKjl5M1UNdIGYhyRLivL9gydE=). You can even try reproduce yourself, here's my [Dockerfile](https://github.com/TomasTomecek/ansiblefest2017-talk/blob/master/Dockerfile) and [Makefile](https://github.com/TomasTomecek/ansiblefest2017-talk/blob/master/Makefile).

**Comment by chouseknecht** [comment]
Ah, well that demo is busted. I'm working on getting it updated to 0.9.

**Comment by chouseknecht** [comment]
Wait. You're running `ansible-container` inside a container. That's clever, but not really supported.

**Comment by j00bar** [comment]
Even still, there's some treachery afoot with openshift and the chardet dependency.

**Comment by TomasTomecek** [comment]
I just figured this out, this is a bug in pip. https://github.com/moby/moby/issues/12327

**Comment by lnunno** [comment]
@TomasTomecek How did you fix this?

**Comment by TomasTomecek** [comment]
@lnunno change docker graph backend to something other than `overlay`
