### ISSUE TITLE
stop command not supporting --var-file

### ISSUE THREAD

**Issue by random-char** [ansible/ansible-container#586]
##### ISSUE TYPE
 - Feature Idea

##### OS / ENVIRONMENT
irrelevant

##### SUMMARY

I've got a following project structure
```
project-folder
|_ansible
  |_roles
    |_apache...
    |_php...
  |_vars
    |_vars.yml
  |_container.yml
  |_...
|_project-code...
```
I run ansible-container build and run commands from /project/ansible folder and specify --var-file option (--var-file vars/vars.yml). stop command does not support it and if I try to stop running containers with it, it fails with error
```
Traceback (most recent call last):
  File "/usr/local/bin/conductor", line 11, in <module>
    load_entry_point('ansible-container', 'console_scripts', 'conductor')()
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/cli.py", line 357, in conductor_commandline
    conductor_config = AnsibleContainerConductorConfig(list_to_ordereddict(containers_config))
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/config.py", line 258, in __init__
    self._process_services()
  File "/_ansible/container/config.py", line 327, in _process_services
    templar=Templar(loader=None, variables=service_defaults)
  File "/_ansible/container/config.py", line 276, in _process_section
    templar.template(buffer.getvalue())
  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 450, in template
    disable_lookups=disable_lookups,
  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 703, in do_template
    raise AnsibleUndefinedVariable(e)
ansible.errors.AnsibleUndefinedVariable: 'some_variable' is undefined
```
So now I have to use docker stop container_ids.

##### STEPS TO REPRODUCE

```
ansible-container stop
```

##### EXPECTED RESULTS
being able to use something like this:
```
ansible-container stop --var-file vars/vars.yml
```

##### ACTUAL RESULTS
stop command fails with undefined variables errors

**Comment by j00bar** [comment]
Thank you so much for reporting this! @chouseknecht This is probably best fixed as part of your `conductor-settings` branch.
