### ISSUE TITLE
BuildError: /tmp/docker.tgz is a directory

### ISSUE THREAD

**Issue by thomscode** [ansible/ansible-container#592]
##### ISSUE TYPE
 - Bug Report

##### container.yml 

```
version: "2"
settings:
  conductor_base: alpine:latest
services:
  cli:
    from: php:7-fpm-alpine
    expose:
      - "9000:9000"
  web:
    from: nginx:alpine
    ports:
      - "8000:80"
    command: [nginx]

registries: {}
```

##### OS / ENVIRONMENT
```
Ansible Container, version 0.9.1
Darwin, WE27507, 16.6.0, Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64, x86_64
2.7.13 (default, Apr  4 2017, 08:47:57) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)] /usr/local/opt/python/bin/python2.7
{
  "ContainersPaused": 0, 
  "Labels": null, 
  "CgroupDriver": "cgroupfs", 
  "ContainersRunning": 1, 
  "ContainerdCommit": {
    "Expected": "3addd840653146c90a254301d6c3a663c7fd6429", 
    "ID": "3addd840653146c90a254301d6c3a663c7fd6429"
  }, 
  "InitBinary": "docker-init", 
  "NGoroutines": 34, 
  "Swarm": {
    "ControlAvailable": false, 
    "NodeID": "", 
    "Error": "", 
    "RemoteManagers": null, 
    "LocalNodeState": "inactive", 
    "NodeAddr": ""
  }, 
  "LoggingDriver": "json-file", 
  "OSType": "linux", 
  "HttpProxy": "", 
  "Runtimes": {
    "runc": {
      "path": "docker-runc"
    }
  }, 
  "DriverStatus": [
    [
      "Backing Filesystem", 
      "extfs"
    ], 
    [
      "Supports d_type", 
      "true"
    ], 
    [
      "Native Overlay Diff", 
      "true"
    ]
  ], 
  "OperatingSystem": "Alpine Linux v3.5", 
  "Containers": 9, 
  "HttpsProxy": "", 
  "BridgeNfIp6tables": true, 
  "MemTotal": 2095890432, 
  "SecurityOptions": [
    "name=seccomp,profile=default"
  ], 
  "Driver": "overlay2", 
  "IndexServerAddress": "https://index.docker.io/v1/", 
  "ClusterStore": "", 
  "InitCommit": {
    "Expected": "949e6fa", 
    "ID": "949e6fa"
  }, 
  "Isolation": "", 
  "SystemStatus": null, 
  "OomKillDisable": true, 
  "ClusterAdvertise": "", 
  "SystemTime": "2017-06-08T15:56:23.27498104Z", 
  "Name": "moby", 
  "CPUSet": true, 
  "RegistryConfig": {
    "AllowNondistributableArtifactsCIDRs": [], 
    "Mirrors": [], 
    "IndexConfigs": {
      "docker.io": {
        "Official": true, 
        "Name": "docker.io", 
        "Secure": true, 
        "Mirrors": []
      }
    }, 
    "AllowNondistributableArtifactsHostnames": [], 
    "InsecureRegistryCIDRs": [
      "127.0.0.0/8"
    ]
  }, 
  "DefaultRuntime": "runc", 
  "ContainersStopped": 8, 
  "NCPU": 4, 
  "NFd": 24, 
  "Architecture": "x86_64", 
  "KernelMemory": true, 
  "CpuCfsQuota": true, 
  "Debug": true, 
  "ID": "GM3F:26Z6:ZLPI:XZFU:FGV7:LBVB:ZJSH:S4HE:TI2Q:ODBO:KG7K:62ER", 
  "IPv4Forwarding": true, 
  "KernelVersion": "4.9.30-moby", 
  "BridgeNfIptables": true, 
  "NoProxy": "*.local, 169.254/16", 
  "LiveRestoreEnabled": false, 
  "ServerVersion": "17.06.0-ce-rc1", 
  "CpuCfsPeriod": true, 
  "ExperimentalBuild": true, 
  "MemoryLimit": true, 
  "SwapLimit": true, 
  "Plugins": {
    "Volume": [
      "local"
    ], 
    "Network": [
      "bridge", 
      "host", 
      "ipvlan", 
      "macvlan", 
      "null", 
      "overlay"
    ], 
    "Authorization": null, 
    "Log": [
      "awslogs", 
      "fluentd", 
      "gcplogs", 
      "gelf", 
      "journald", 
      "json-file", 
      "logentries", 
      "splunk", 
      "syslog"
    ]
  }, 
  "Images": 36, 
  "DockerRootDir": "/var/lib/docker", 
  "NEventsListener": 1, 
  "CPUShares": true, 
  "RuncCommit": {
    "Expected": "992a5be178a62e026f4069f443c6164912adbf09", 
    "ID": "992a5be178a62e026f4069f443c6164912adbf09"
  }
}
{
  "KernelVersion": "4.9.30-moby", 
  "Arch": "amd64", 
  "BuildTime": "2017-05-31T03:00:14.205343778+00:00", 
  "ApiVersion": "1.30", 
  "Version": "17.06.0-ce-rc1", 
  "MinAPIVersion": "1.12", 
  "GitCommit": "7f8486a", 
  "Os": "linux", 
  "Experimental": true, 
  "GoVersion": "go1.8.1"
}
```
##### SUMMARY
I cannot get `ansible-container build` to run. I keep getting an error that `tar` could not open `/tmp/docker.tgz` because it is a directory.

This happens regardless of whether I'm using `alpine`, `debian` or `centos` as the `conductor_base` .

This happens on macOS using Docker for Mac, but not on my Ubuntu system.

##### STEPS TO REPRODUCE
```
ansible-container --debug build
```

##### EXPECTED RESULTS
Successful `ansible-container build`

##### ACTUAL RESULTS
```
2017-06-08T08:59:11.845205 The default type is            [container.config] caller_file=/usr/local/lib/python2.7/site-packages/container/config.py caller_func=_resolve_defaults caller_line=140 config=<class 'ruamel.yaml.comments.CommentedMap'> defaults=<type '_ordereddict.ordereddict'>
2017-06-08T08:59:11.846736 Getting environment variables... [container.config] caller_file=/usr/local/lib/python2.7/site-packages/container/config.py caller_func=_get_environment_variables caller_line=156
2017-06-08T08:59:11.848058 Read environment variables     [container.config] caller_file=/usr/local/lib/python2.7/site-packages/container/config.py caller_func=_get_environment_variables caller_line=161 env_vars={}
2017-06-08T08:59:11.849277 Resolved template variables    [container.config] caller_file=/usr/local/lib/python2.7/site-packages/container/config.py caller_func=_resolve_defaults caller_line=145 template_vars={}
2017-06-08T08:59:11.850477 Parsed config                  [container.config] caller_file=/usr/local/lib/python2.7/site-packages/container/config.py caller_func=set_env caller_line=121 config={"version": "2", "settings": {"conductor_base": "alpine:latest", "pwd": "/Users/will202/Code/docker/nisac"}, "services": {"cli": {"from": "php:7-fpm-alpine", "expose": ["9000:9000"]}, "web": {"from": "nginx:alpine", "ports": ["8000:80"], "command": ["nginx"]}}, "registries": {}, "defaults": {}}
2017-06-08T08:59:11.851755 Loading engine capabilities    [container.utils.loader] caller_file=/usr/local/lib/python2.7/site-packages/container/utils/loader.py caller_func=load_engine caller_line=14 capabilities=['BUILD', 'RUN'] engine=docker
2017-06-08T08:59:11.942919 Could not find container for conductor [container.docker.engine] all_containers=[<Container: a183bcf2f7>] caller_file=/usr/local/lib/python2.7/site-packages/container/docker/engine.py caller_func=get_container_id_for_service caller_line=384 container=u'nisac_conductor'
2017-06-08T08:59:11.965362 Could not find the latest image for service, searching for other tags with same image name [container.docker.engine] caller_file=/usr/local/lib/python2.7/site-packages/container/docker/engine.py caller_func=get_latest_image_for_service caller_line=423 image_name=u'nisac-conductor' service=conductor
2017-06-08T08:59:11.972150 Call: Engine.build_conductor_image [container.docker.engine] args=('/Users/will202/Code/docker/nisac', 'alpine:latest') caller_file=/usr/local/lib/python2.7/site-packages/container/docker/engine.py caller_func=Engine.build_conductor_image caller_line=23 kwargs={'cache': True}
2017-06-08T08:59:11.976124 Using temporary directory      [container.utils.temp] caller_file=/usr/local/lib/python2.7/site-packages/container/utils/temp.py caller_func=__enter__ caller_line=17 path=/var/folders/w1/d8y44g4s2rs7shsyhj6s_lldh5n3rh/T/tmpdKm9FT
2017-06-08T08:59:11.977207 Building Docker Engine context... [container.docker.engine] caller_file=/usr/local/lib/python2.7/site-packages/container/docker/engine.py caller_func=build_conductor_image caller_line=649
2017-06-08T08:59:12.050868 Rendered Jinja Template:       [container.utils] body=FROM alpine:latest
ENV ANSIBLE_CONTAINER=1


RUN apk add --no-cache -U python2-dev git rsync libffi libffi-dev openssl openssl-dev gcc musl-dev tar openssh


ADD https://get.docker.com/builds/Linux/x86_64/docker-17.04.0-ce.tgz /tmp/docker.tgz

COPY /contrib/get-pip.py /get-pip.py
RUN python /get-pip.py && \
    mkdir -p /etc/ansible/roles /_ansible/src && \
    cd /usr/local/bin && \
    tar -xz --strip-components=1 -f /tmp/docker.tgz

# The COPY here will break cache if the version of conductor changed
COPY /container-src /_ansible/container
RUN cd /_ansible && \
    pip install -r container/conductor-build/conductor-requirements.txt && \
    PYTHONPATH=. LC_ALL="en_US.UTF-8" python container/conductor-build/setup.py develop -v && \
    ansible-galaxy install -p /etc/ansible/roles -r container/conductor-build/conductor-requirements.yml

# The COPY here will break cache if the requirements or ansible.cfg has changed
COPY /build-src /_ansible/build
RUN ( test -f /_ansible/build/ansible-requirements.txt && pip install --no-cache-dir -r /_ansible/build/ansible-requirements.txt || true ) && \
    ( test -f /_ansible/build/requirements.yml && ansible-galaxy install -p /etc/ansible/roles -r /_ansible/build/requirements.yml || true ) && \
    ( test -f /_ansible/build/ansible.cfg && cp /_ansible/build/ansible.cfg /etc/ansible/ansible.cfg || true)

VOLUME /usr

VOLUME /lib


 caller_file=/usr/local/lib/python2.7/site-packages/container/utils/__init__.py caller_func=jinja_render_to_temp caller_line=81
2017-06-08T08:59:12.052340 Context manifest:              [container.docker.engine] caller_file=/usr/local/lib/python2.7/site-packages/container/docker/engine.py caller_func=build_conductor_image caller_line=705
2017-06-08T08:59:12.052591 tarball item: build-src/ansible.cfg (144 bytes) [container.docker.engine] bytes=144 file=build-src/ansible.cfg
2017-06-08T08:59:12.052806 tarball item: build-src/ansible-requirements.txt (129 bytes) [container.docker.engine] bytes=129 file=build-src/ansible-requirements.txt
2017-06-08T08:59:12.053007 tarball item: build-src/requirements.yml (105 bytes) [container.docker.engine] bytes=105 file=build-src/requirements.yml
2017-06-08T08:59:12.053205 tarball item: build-src/.touch (0 bytes) [container.docker.engine] bytes=0 file=build-src/.touch
2017-06-08T08:59:12.053401 tarball item: contrib/get-pip.py (1595409 bytes) [container.docker.engine] bytes=1595409 file=contrib/get-pip.py
2017-06-08T08:59:12.053594 tarball item: container-src (0 bytes) [container.docker.engine] bytes=0L file=container-src
2017-06-08T08:59:12.053787 tarball item: container-src/__init__.py (947 bytes) [container.docker.engine] bytes=947 file=container-src/__init__.py
2017-06-08T08:59:12.053979 tarball item: container-src/__init__.pyc (1421 bytes) [container.docker.engine] bytes=1421 file=container-src/__init__.pyc
2017-06-08T08:59:12.054169 tarball item: container-src/cli.py (19540 bytes) [container.docker.engine] bytes=19540 file=container-src/cli.py
2017-06-08T08:59:12.054358 tarball item: container-src/cli.pyc (15710 bytes) [container.docker.engine] bytes=15710 file=container-src/cli.pyc
2017-06-08T08:59:12.054554 tarball item: container-src/config.py (14021 bytes) [container.docker.engine] bytes=14021 file=container-src/config.py
2017-06-08T08:59:12.054738 tarball item: container-src/config.pyc (12837 bytes) [container.docker.engine] bytes=12837 file=container-src/config.pyc
2017-06-08T08:59:12.054923 tarball item: container-src/core.py (37981 bytes) [container.docker.engine] bytes=37981 file=container-src/core.py
2017-06-08T08:59:12.055107 tarball item: container-src/core.pyc (27298 bytes) [container.docker.engine] bytes=27298 file=container-src/core.pyc
2017-06-08T08:59:12.055290 tarball item: container-src/docker (0 bytes) [container.docker.engine] bytes=0L file=container-src/docker
2017-06-08T08:59:12.055473 tarball item: container-src/docker/__init__.py (205 bytes) [container.docker.engine] bytes=205 file=container-src/docker/__init__.py
2017-06-08T08:59:12.055657 tarball item: container-src/docker/__init__.pyc (333 bytes) [container.docker.engine] bytes=333 file=container-src/docker/__init__.pyc
2017-06-08T08:59:12.055840 tarball item: container-src/docker/deploy.py (248 bytes) [container.docker.engine] bytes=248 file=container-src/docker/deploy.py
2017-06-08T08:59:12.056023 tarball item: container-src/docker/deploy.pyc (331 bytes) [container.docker.engine] bytes=331 file=container-src/docker/deploy.pyc
2017-06-08T08:59:12.056207 tarball item: container-src/docker/engine.py (34750 bytes) [container.docker.engine] bytes=34750 file=container-src/docker/engine.py
2017-06-08T08:59:12.056400 tarball item: container-src/docker/engine.pyc (29393 bytes) [container.docker.engine] bytes=29393 file=container-src/docker/engine.pyc
2017-06-08T08:59:12.056585 tarball item: container-src/docker/files (0 bytes) [container.docker.engine] bytes=0L file=container-src/docker/files
2017-06-08T08:59:12.056769 tarball item: container-src/docker/files/conductor-requirements.txt (294 bytes) [container.docker.engine] bytes=294 file=container-src/docker/files/conductor-requirements.txt
2017-06-08T08:59:12.056953 tarball item: container-src/docker/files/conductor-requirements.yml (60 bytes) [container.docker.engine] bytes=60 file=container-src/docker/files/conductor-requirements.yml
2017-06-08T08:59:12.057138 tarball item: container-src/docker/files/get-pip.py (1595409 bytes) [container.docker.engine] bytes=1595409 file=container-src/docker/files/get-pip.py
2017-06-08T08:59:12.057323 tarball item: container-src/docker/files/get-pip.pyc (1593406 bytes) [container.docker.engine] bytes=1593406 file=container-src/docker/files/get-pip.pyc
2017-06-08T08:59:12.057506 tarball item: container-src/docker/files/setup.py (3215 bytes) [container.docker.engine] bytes=3215 file=container-src/docker/files/setup.py
2017-06-08T08:59:12.057690 tarball item: container-src/docker/files/setup.pyc (4047 bytes) [container.docker.engine] bytes=4047 file=container-src/docker/files/setup.pyc
2017-06-08T08:59:12.057872 tarball item: container-src/docker/importer.py (23310 bytes) [container.docker.engine] bytes=23310 file=container-src/docker/importer.py
2017-06-08T08:59:12.058054 tarball item: container-src/docker/importer.pyc (19748 bytes) [container.docker.engine] bytes=19748 file=container-src/docker/importer.pyc
2017-06-08T08:59:12.058236 tarball item: container-src/docker/templates (0 bytes) [container.docker.engine] bytes=0L file=container-src/docker/templates
2017-06-08T08:59:12.058419 tarball item: container-src/docker/templates/conductor-dockerfile.j2 (2901 bytes) [container.docker.engine] bytes=2901 file=container-src/docker/templates/conductor-dockerfile.j2
2017-06-08T08:59:12.058603 tarball item: container-src/engine.py (6074 bytes) [container.docker.engine] bytes=6074 file=container-src/engine.py
2017-06-08T08:59:12.058787 tarball item: container-src/engine.pyc (9860 bytes) [container.docker.engine] bytes=9860 file=container-src/engine.pyc
2017-06-08T08:59:12.058970 tarball item: container-src/exceptions.py (1991 bytes) [container.docker.engine] bytes=1991 file=container-src/exceptions.py
2017-06-08T08:59:12.059143 tarball item: container-src/exceptions.pyc (5369 bytes) [container.docker.engine] bytes=5369 file=container-src/exceptions.pyc
2017-06-08T08:59:12.059311 tarball item: container-src/k8s (0 bytes) [container.docker.engine] bytes=0L file=container-src/k8s
2017-06-08T08:59:12.059478 tarball item: container-src/k8s/__init__.py (196 bytes) [container.docker.engine] bytes=196 file=container-src/k8s/__init__.py
2017-06-08T08:59:12.059645 tarball item: container-src/k8s/__init__.pyc (330 bytes) [container.docker.engine] bytes=330 file=container-src/k8s/__init__.pyc
2017-06-08T08:59:12.059812 tarball item: container-src/k8s/base_deploy.py (27642 bytes) [container.docker.engine] bytes=27642 file=container-src/k8s/base_deploy.py
2017-06-08T08:59:12.059979 tarball item: container-src/k8s/base_deploy.pyc (20075 bytes) [container.docker.engine] bytes=20075 file=container-src/k8s/base_deploy.pyc
2017-06-08T08:59:12.060146 tarball item: container-src/k8s/base_engine.py (5164 bytes) [container.docker.engine] bytes=5164 file=container-src/k8s/base_engine.py
2017-06-08T08:59:12.060313 tarball item: container-src/k8s/base_engine.pyc (5557 bytes) [container.docker.engine] bytes=5557 file=container-src/k8s/base_engine.pyc
2017-06-08T08:59:12.060480 tarball item: container-src/k8s/deploy.py (1720 bytes) [container.docker.engine] bytes=1720 file=container-src/k8s/deploy.py
2017-06-08T08:59:12.060646 tarball item: container-src/k8s/deploy.pyc (1991 bytes) [container.docker.engine] bytes=1991 file=container-src/k8s/deploy.pyc
2017-06-08T08:59:12.060812 tarball item: container-src/k8s/engine.py (2389 bytes) [container.docker.engine] bytes=2389 file=container-src/k8s/engine.py
2017-06-08T08:59:12.060979 tarball item: container-src/k8s/engine.pyc (1923 bytes) [container.docker.engine] bytes=1923 file=container-src/k8s/engine.pyc
2017-06-08T08:59:12.061149 tarball item: container-src/openshift (0 bytes) [container.docker.engine] bytes=0L file=container-src/openshift
2017-06-08T08:59:12.061316 tarball item: container-src/openshift/__init__.py (196 bytes) [container.docker.engine] bytes=196 file=container-src/openshift/__init__.py
2017-06-08T08:59:12.061517 tarball item: container-src/openshift/__init__.pyc (336 bytes) [container.docker.engine] bytes=336 file=container-src/openshift/__init__.pyc
2017-06-08T08:59:12.061698 tarball item: container-src/openshift/deploy.py (6203 bytes) [container.docker.engine] bytes=6203 file=container-src/openshift/deploy.py
2017-06-08T08:59:12.061866 tarball item: container-src/openshift/deploy.pyc (5234 bytes) [container.docker.engine] bytes=5234 file=container-src/openshift/deploy.pyc
2017-06-08T08:59:12.062033 tarball item: container-src/openshift/engine.py (2151 bytes) [container.docker.engine] bytes=2151 file=container-src/openshift/engine.py
2017-06-08T08:59:12.062201 tarball item: container-src/openshift/engine.pyc (2642 bytes) [container.docker.engine] bytes=2642 file=container-src/openshift/engine.pyc
2017-06-08T08:59:12.062367 tarball item: container-src/templates (0 bytes) [container.docker.engine] bytes=0L file=container-src/templates
2017-06-08T08:59:12.062534 tarball item: container-src/templates/ansible-container-inventory.py (1230 bytes) [container.docker.engine] bytes=1230 file=container-src/templates/ansible-container-inventory.py
2017-06-08T08:59:12.062701 tarball item: container-src/templates/ansible-container-inventory.pyc (2062 bytes) [container.docker.engine] bytes=2062 file=container-src/templates/ansible-container-inventory.pyc
2017-06-08T08:59:12.062867 tarball item: container-src/templates/ansible-dockerfile.j2 (1194 bytes) [container.docker.engine] bytes=1194 file=container-src/templates/ansible-dockerfile.j2
2017-06-08T08:59:12.063034 tarball item: container-src/templates/ansible.cfg (41 bytes) [container.docker.engine] bytes=41 file=container-src/templates/ansible.cfg
2017-06-08T08:59:12.063201 tarball item: container-src/templates/build-docker-compose.j2.yml (1635 bytes) [container.docker.engine] bytes=1635 file=container-src/templates/build-docker-compose.j2.yml
2017-06-08T08:59:12.063367 tarball item: container-src/templates/builder.sh (620 bytes) [container.docker.engine] bytes=620 file=container-src/templates/builder.sh
2017-06-08T08:59:12.063535 tarball item: container-src/templates/compose_versioned.j2.yml (237 bytes) [container.docker.engine] bytes=237 file=container-src/templates/compose_versioned.j2.yml
2017-06-08T08:59:12.063701 tarball item: container-src/templates/hosts.j2 (90 bytes) [container.docker.engine] bytes=90 file=container-src/templates/hosts.j2
2017-06-08T08:59:12.063866 tarball item: container-src/templates/init (0 bytes) [container.docker.engine] bytes=0L file=container-src/templates/init
2017-06-08T08:59:12.064033 tarball item: container-src/templates/init/ansible-requirements.j2.txt (130 bytes) [container.docker.engine] bytes=130 file=container-src/templates/init/ansible-requirements.j2.txt
2017-06-08T08:59:12.064198 tarball item: container-src/templates/init/ansible.j2.cfg (145 bytes) [container.docker.engine] bytes=145 file=container-src/templates/init/ansible.j2.cfg
2017-06-08T08:59:12.064364 tarball item: container-src/templates/init/container.j2.yml (2116 bytes) [container.docker.engine] bytes=2116 file=container-src/templates/init/container.j2.yml
2017-06-08T08:59:12.064531 tarball item: container-src/templates/init/meta.j2.yml (1231 bytes) [container.docker.engine] bytes=1231 file=container-src/templates/init/meta.j2.yml
2017-06-08T08:59:12.064696 tarball item: container-src/templates/init/requirements.j2.yml (298 bytes) [container.docker.engine] bytes=298 file=container-src/templates/init/requirements.j2.yml
2017-06-08T08:59:12.064862 tarball item: container-src/templates/install-docker-compose.j2.yml (712 bytes) [container.docker.engine] bytes=712 file=container-src/templates/install-docker-compose.j2.yml
2017-06-08T08:59:12.065027 tarball item: container-src/templates/listhosts-docker-compose.j2.yml (1640 bytes) [container.docker.engine] bytes=1640 file=container-src/templates/listhosts-docker-compose.j2.yml
2017-06-08T08:59:12.065192 tarball item: container-src/templates/restart-docker-compose.j2.yml (75 bytes) [container.docker.engine] bytes=75 file=container-src/templates/restart-docker-compose.j2.yml
2017-06-08T08:59:12.065357 tarball item: container-src/templates/role (0 bytes) [container.docker.engine] bytes=0L file=container-src/templates/role
2017-06-08T08:59:12.065523 tarball item: container-src/templates/role/.travis.j2.yml (540 bytes) [container.docker.engine] bytes=540 file=container-src/templates/role/.travis.j2.yml
2017-06-08T08:59:12.065690 tarball item: container-src/templates/role/defaults (0 bytes) [container.docker.engine] bytes=0L file=container-src/templates/role/defaults
2017-06-08T08:59:12.065856 tarball item: container-src/templates/role/defaults/main.j2.yml (55 bytes) [container.docker.engine] bytes=55 file=container-src/templates/role/defaults/main.j2.yml
2017-06-08T08:59:12.066036 tarball item: container-src/templates/role/meta (0 bytes) [container.docker.engine] bytes=0L file=container-src/templates/role/meta
2017-06-08T08:59:12.066205 tarball item: container-src/templates/role/meta/main.j2.yml (3220 bytes) [container.docker.engine] bytes=3220 file=container-src/templates/role/meta/main.j2.yml
2017-06-08T08:59:12.066371 tarball item: container-src/templates/role/README.j2.md (1287 bytes) [container.docker.engine] bytes=1287 file=container-src/templates/role/README.j2.md
2017-06-08T08:59:12.066536 tarball item: container-src/templates/role/test (0 bytes) [container.docker.engine] bytes=0L file=container-src/templates/role/test
2017-06-08T08:59:12.066705 tarball item: container-src/templates/role/test/test.j2.yml (81 bytes) [container.docker.engine] bytes=81 file=container-src/templates/role/test/test.j2.yml
2017-06-08T08:59:12.066877 tarball item: container-src/templates/run-docker-compose.j2.yml (75 bytes) [container.docker.engine] bytes=75 file=container-src/templates/run-docker-compose.j2.yml
2017-06-08T08:59:12.067045 tarball item: container-src/templates/stop-docker-compose.j2.yml (75 bytes) [container.docker.engine] bytes=75 file=container-src/templates/stop-docker-compose.j2.yml
2017-06-08T08:59:12.067211 tarball item: container-src/templates/wait_on_host.py (2365 bytes) [container.docker.engine] bytes=2365 file=container-src/templates/wait_on_host.py
2017-06-08T08:59:12.067378 tarball item: container-src/templates/wait_on_host.pyc (2495 bytes) [container.docker.engine] bytes=2495 file=container-src/templates/wait_on_host.pyc
2017-06-08T08:59:12.067543 tarball item: container-src/utils (0 bytes) [container.docker.engine] bytes=0L file=container-src/utils
2017-06-08T08:59:12.067708 tarball item: container-src/utils/__init__.py (10744 bytes) [container.docker.engine] bytes=10744 file=container-src/utils/__init__.py
2017-06-08T08:59:12.067874 tarball item: container-src/utils/__init__.pyc (11774 bytes) [container.docker.engine] bytes=11774 file=container-src/utils/__init__.pyc
2017-06-08T08:59:12.068039 tarball item: container-src/utils/_text.py (12304 bytes) [container.docker.engine] bytes=12304 file=container-src/utils/_text.py
2017-06-08T08:59:12.068204 tarball item: container-src/utils/_text.pyc (8773 bytes) [container.docker.engine] bytes=8773 file=container-src/utils/_text.pyc
2017-06-08T08:59:12.068368 tarball item: container-src/utils/galaxy.py (8120 bytes) [container.docker.engine] bytes=8120 file=container-src/utils/galaxy.py
2017-06-08T08:59:12.068533 tarball item: container-src/utils/galaxy.pyc (7887 bytes) [container.docker.engine] bytes=7887 file=container-src/utils/galaxy.pyc
2017-06-08T08:59:12.068697 tarball item: container-src/utils/loader.py (906 bytes) [container.docker.engine] bytes=906 file=container-src/utils/loader.py
2017-06-08T08:59:12.068862 tarball item: container-src/utils/loader.pyc (1182 bytes) [container.docker.engine] bytes=1182 file=container-src/utils/loader.pyc
2017-06-08T08:59:12.069027 tarball item: container-src/utils/logmux.py (1313 bytes) [container.docker.engine] bytes=1313 file=container-src/utils/logmux.py
2017-06-08T08:59:12.069191 tarball item: container-src/utils/logmux.pyc (2613 bytes) [container.docker.engine] bytes=2613 file=container-src/utils/logmux.pyc
2017-06-08T08:59:12.069355 tarball item: container-src/utils/temp.py (698 bytes) [container.docker.engine] bytes=698 file=container-src/utils/temp.py
2017-06-08T08:59:12.069520 tarball item: container-src/utils/temp.pyc (1382 bytes) [container.docker.engine] bytes=1382 file=container-src/utils/temp.pyc
2017-06-08T08:59:12.069686 tarball item: container-src/utils/visibility.py (3329 bytes) [container.docker.engine] bytes=3329 file=container-src/utils/visibility.py
2017-06-08T08:59:12.069851 tarball item: container-src/utils/visibility.pyc (4173 bytes) [container.docker.engine] bytes=4173 file=container-src/utils/visibility.pyc
2017-06-08T08:59:12.070017 tarball item: container-src/conductor-build/setup.py (3215 bytes) [container.docker.engine] bytes=3215 file=container-src/conductor-build/setup.py
2017-06-08T08:59:12.070188 tarball item: container-src/conductor-build/conductor-requirements.txt (294 bytes) [container.docker.engine] bytes=294 file=container-src/conductor-build/conductor-requirements.txt
2017-06-08T08:59:12.070355 tarball item: container-src/conductor-build/conductor-requirements.yml (60 bytes) [container.docker.engine] bytes=60 file=container-src/conductor-build/conductor-requirements.yml
2017-06-08T08:59:12.070521 tarball item: Dockerfile (1390 bytes) [container.docker.engine] bytes=1390 file=Dockerfile
2017-06-08T08:59:12.079158 Starting Docker build of Ansible Container Conductor image (please be patient)... [container.docker.engine] caller_file=/usr/local/lib/python2.7/site-packages/container/docker/engine.py caller_func=build_conductor_image caller_line=713
Step 1/12 : FROM alpine:latest
 ---> a41a7446062d
Step 2/12 : ENV ANSIBLE_CONTAINER 1
 ---> Using cache
 ---> c3eb2d5289cb
Step 3/12 : RUN apk add --no-cache -U python2-dev git rsync libffi libffi-dev openssl openssl-dev gcc musl-dev tar openssh
 ---> Using cache
 ---> a5138f22935b
Step 4/12 : ADD https://get.docker.com/builds/Linux/x86_64/docker-17.04.0-ce.tgz /tmp/docker.tgz

 ---> Using cache
 ---> 50cd8163717a
Step 5/12 : COPY /contrib/get-pip.py /get-pip.py
 ---> Using cache
 ---> 71e538d3e803
Step 6/12 : RUN python /get-pip.py &&     mkdir -p /etc/ansible/roles /_ansible/src &&     cd /usr/local/bin &&     tar -xz --strip-components=1 -f /tmp/docker.tgz
 ---> Running in 434a802afbd1
Collecting pip
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB)
Collecting setuptools
  Downloading setuptools-36.0.1-py2.py3-none-any.whl (476kB)
Collecting wheel
  Downloading wheel-0.29.0-py2.py3-none-any.whl (66kB)
Installing collected packages: pip, setuptools, wheel
Successfully installed pip-9.0.1 setuptools-36.0.1 wheel-0.29.0
tar (child): /tmp/docker.tgz: Cannot read: Is a directory
tar (child): At beginning of tape, quitting now
tar (child): Error is not recoverable: exiting now
gzip: invalid magic
tar: Child returned status 2
tar: Error is not recoverable: exiting now

2017-06-08T08:59:20.913025 Cleaning up temporary directory [container.utils.temp] caller_file=/usr/local/lib/python2.7/site-packages/container/utils/temp.py caller_func=__exit__ caller_line=22 path=/var/folders/w1/d8y44g4s2rs7shsyhj6s_lldh5n3rh/T/tmpdKm9FT
2017-06-08T08:59:20.914255 Unknown exception Error building conductor image: The command '/bin/sh -c python /get-pip.py &&     mkdir -p /etc/ansible/roles /_ansible/src &&     cd /usr/local/bin &&     tar -xz --strip-components=1 -f /tmp/docker.tgz' returned a non-zero code: 2 [container.cli] caller_file=/usr/local/lib/python2.7/site-packages/structlog/stdlib.py caller_func=exception caller_line=95
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/container/cli.py", line 268, in __call__
    getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
  File "/usr/local/lib/python2.7/site-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/container/core.py", line 150, in hostcmd_build
    cache=kwargs['cache']
  File "/usr/local/lib/python2.7/site-packages/container/docker/engine.py", line 82, in __wrapped__
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/container/docker/engine.py", line 729, in build_conductor_image
    "Error building conductor image: {0}".format(line_json['errorDetail']['message']))
AnsibleContainerException: Error building conductor image: The command '/bin/sh -c python /get-pip.py &&     mkdir -p /etc/ansible/roles /_ansible/src &&     cd /usr/local/bin &&     tar -xz --strip-components=1 -f /tmp/docker.tgz' returned a non-zero code: 2
```

**Comment by j00bar** [comment]
Howdy, and thanks for the bug report! You can see that the Conductor build is pulling Docker from the upstream source and putting it in `/tmp` as part of the build. You can also see in your output that the result you're seeing is coming from a cached layer. Does the error still occur if you run the build with `--no-cache`?

**Comment by thomscode** [comment]
Yes, it has the same issue when running with `--no-cache` option. Command run:
```
ansible-container --debug build --no-cache
```

**Comment by mhumeSF** [comment]
I am having this same issue and although my PR does get around it, docs do say

> If <src> is a local tar archive in a recognized compression format (identity, gzip, bzip2 or xz) then it is unpacked as a directory. Resources from remote URLs are not decompressed.
https://docs.docker.com/engine/reference/builder/#add

**Comment by mhumeSF** [comment]
I am only seeing this behavior in the docker edge for mac release. I downgraded to docker-for-mac 17.03.1-ce and the issue does not exist.

**Comment by geerlingguy** [comment]
I'm hitting this on the Edge release as well. If you, like me, have to use Edge for something, and still want to work with ansible-container prior to its next bugfix release, and want to use the version installed via `pip` because you're lazy (like me!):

  1. `pip show -f ansible-container | grep conductor-dockerfile.j2` to find where that file is.
  2. `python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"` to find where your pip packages are installed.
  3. Open that file and make the modifications in the commit above: https://github.com/ansible/ansible-container/commit/cc3758a0824f2f0e11c2db8f5e526596a614e06e
  4. Run a build with `--no-cache` to make sure it rebuilds the conductor container and has `curl` installed.

Note that I've opened up https://github.com/ansible/ansible-container/pull/615 to add in `curl` for `rhel` base images—it seems like it was not added in the earlier commit.
