### ISSUE TITLE
ImportError: You must install Ansible Container with Docker(tm) support

### ISSUE THREAD

**Issue by bala-v** [ansible/ansible-container#606]
##### ISSUE TYPE

```
version: '2'

settings:

  conductor:
    base: 'centos:7'
    volumes:
    - temp-space:/tmp   # Used to copy static content between containers

  k8s_namespace:
    name: demo
    display_name: Ansible Container Demo 
    description: Django framework demo 

defaults:
  POSTGRES_USER: django
  POSTGRES_PASSWORD: sesame
  POSTGRES_DB: django
  DJANGO_ROOT: /django
  DJANGO_USER: django
  DJANGO_PORT: 8080
  DJANGO_VENV: /venv
  NODE_USER: node
  NODE_HOME: /node
  NODE_ROOT: ''
  GULP_DEV_PORT: 8080

services:
  django:
    from: 'centos:7'
    roles:
    - role: django-gunicorn
    environment:
      DATABASE_URL: 'pgsql://{{ POSTGRES_USER }}:{{ POSTGRES_PASSWORD }}@postgresql:5432/{{ POSTGRES_DB }}'
      DJANGO_ROOT: '{{ DJANGO_ROOT }}'
      DJANGO_VENV: '{{ DJANGO_VENV }}'
    expose:
    - '{{ DJANGO_PORT }}'
    working_dir: '{{ DJANGO_ROOT }}'
    links:
    - postgresql
    user: '{{ DJANGO_USER }}'
    command: ['/usr/bin/dumb-init', '{{ DJANGO_VENV }}/bin/gunicorn', -w, '2', -b, '0.0.0.0:{{ DJANGO_PORT }}', 'project.wsgi:application']
    entrypoint: [/usr/bin/entrypoint.sh]
    dev_overrides:
      volumes:
      - '$PWD:{{ DJANGO_ROOT }}'
      command: [/usr/bin/dumb-init, '{{ DJANGO_VENV }}/bin/python', manage.py, runserver, '0.0.0.0:{{ DJANGO_PORT }}']
      depends_on:
      - postgresql

  gulp:
    from: 'centos:7'
    roles:
    - role: gulp-static 
    working_dir: '{{ NODE_HOME }}'
    command: ['/bin/false']
    environment:
      NODE_HOME: '{{ NODE_HOME }}'
    dev_overrides:
      entrypoint: [/entrypoint.sh]
      command: [/usr/bin/dumb-init, /usr/local/bin/gulp]
      ports:
      - '8080:{{ GULP_DEV_PORT }}'
      - 3001:3001
      links:
      - django
      volumes:
      - '$PWD:{{ NODE_HOME }}'
    openshift:
      state: absent

  nginx:
    from: 'centos:7'
    roles:
    - role: ansible.nginx-container
      ASSET_PATHS:
      - /tmp/dist
      PROXY: yes
      PROXY_PASS: 'http://django:8080'
      PROXY_LOCATION: "~* /(admin|api)"
    ports:
    - '{{ DJANGO_PORT }}:8000'
    links:
    - django
    dev_overrides:
      ports: []
      command: /bin/false

  postgresql:
    # Uses a pre-built postgresql image from Docker Hub 
    from: ansible/postgresql:latest
    environment:
    - 'POSTGRES_DB={{ POSTGRES_DB }}'
    - 'POSTGRES_USER={{ POSTGRES_USER }}'
    - 'POSTGRES_PASS={{ POSTGRES_PASSWORD }}'
    - 'PGDATA=/var/lib/pgsql/data/userdata'
    volumes:
    - postgres-data:/var/lib/pgsql/data
    expose:
    - 5432

volumes:
  postgres-data:
    docker: {}
    openshift:
      access_modes:
      - ReadWriteMany
      requested_storage: 3Gi 

  temp-space: 
    docker: {}
    openshift:
      state: absent

registries:
   local_openshift:
     url: https://local.openshift     # The push-to URL, created by chouseknecht.minishift-up role
     namespace: demo
     pull_from_url: 172.30.1.1:5000   # The pull-from URL from within minishift
```

##### OS / ENVIRONMENT

```
Ansible Container, version 0.9.1
Darwin, localhost, 16.6.0, Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64, x86_64
2.7.13 (default, Apr  4 2017, 08:44:49) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] /usr/local/opt/python/bin/python2.7
ERROR	Unknown exception You must install Ansible Container with Docker(tm) support. Try:
pip install ansible-container==0.9.1[docker]	
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/container/cli.py", line 268, in __call__
    getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
  File "/usr/local/lib/python2.7/site-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/container/core.py", line 414, in hostcmd_version
    {}, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/container/utils/loader.py", line 16, in load_engine
    package='container')
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/site-packages/container/docker/engine.py", line 44, in <module>
    container.__version__
ImportError: You must install Ansible Container with Docker(tm) support. Try:
pip install ansible-container==0.9.1[docker
```
##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by TomasTomecek** [comment]
What's the issue? Lack of docs?

~~Does it work when you perform the installation (`pip install ansible-container==0.9.1[docker]`) which is suggested by the error message?~~

See the correct syntax below.

**Comment by alapidas** [comment]
I have this issue as well, and I get an error trying to install using the specified command:
```
07:45 $ pip install ansible-container==0.9.1[docker]
Collecting ansible-container==0.9.1[docker]
  Could not find a version that satisfies the requirement ansible-container==0.9.1[docker] (from versions: 0.1.0, 0.2.0, 0.3.0, 0.9.0.0, 0.9.1)
No matching distribution found for ansible-container==0.9.1[docker]
```

**Comment by chouseknecht** [comment]
@alapidas 
@bala-v 

Hey guys, 

Thank you for trying Ansible Container. We appreciate your interest, and your willingness to share your feedback.

I'm sorry you're having difficulty getting it installed. Here's the recommended approach. Hopefully it will help.

The actual command you should run, and this is taken directly from [Getting Ansible Container](http://docs.ansible.com/ansible-container/installation.html#getting-ansible-container) at our [docs site](https://docs.ansible.com/ansible-container), is:

```
pip install ansible-container[docker,k8s]
```

Here's me installing it into a `virtualenv`, which is the recommended approach; otherwise, you'll likely need to use `sudo`:

```
~/projects $ virtualenv testins
New python executable in /Users/chouseknecht/projects/testins/bin/python2.7
Also creating executable in /Users/chouseknecht/projects/testins/bin/python
Please make sure you remove any previous custom paths from your /Users/chouseknecht/.pydistutils.cfg file.
Installing setuptools, pip, wheel...done.

~/projects $ source ./testins/bin/activate

(testins) ~/projects $ pip install ansible-container[docker,k8s]

Collecting ansible-container[docker,k8s]
  Downloading ansible-container-0.9.1.tar.gz (1.3MB)
    100% |████████████████████████████████| 1.4MB 897kB/s
Collecting Jinja2>=2.9 (from ansible-container[docker,k8s])
  Using cached Jinja2-2.9.6-py2.py3-none-any.whl
Collecting PyYAML>=3.12 (from ansible-container[docker,k8s])
Collecting requests>=2 (from ansible-container[docker,k8s])
  Downloading requests-2.18.1-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 92kB 5.2MB/s
Collecting ruamel.yaml>=0.14.2 (from ansible-container[docker,k8s])
  Downloading ruamel.yaml-0.15.7.tar.gz (250kB)
    100% |████████████████████████████████| 256kB 3.3MB/s
Collecting six>=1.10 (from ansible-container[docker,k8s])
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting structlog[dev]>=16.1 (from ansible-container[docker,k8s])
  Downloading structlog-17.2.0-py2.py3-none-any.whl
Collecting docker>=2.1 (from ansible-container[docker,k8s])
  Downloading docker-2.3.0-py2.py3-none-any.whl (108kB)
    100% |████████████████████████████████| 112kB 4.1MB/s
Collecting openshift==0.0.1 (from ansible-container[docker,k8s])
  Using cached openshift-0.0.1-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from Jinja2>=2.9->ansible-container[docker,k8s])
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2->ansible-container[docker,k8s])
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 4.2MB/s
Collecting certifi>=2017.4.17 (from requests>=2->ansible-container[docker,k8s])
  Using cached certifi-2017.4.17-py2.py3-none-any.whl
Collecting idna<2.6,>=2.5 (from requests>=2->ansible-container[docker,k8s])
  Using cached idna-2.5-py2.py3-none-any.whl
Collecting urllib3<1.22,>=1.21.1 (from requests>=2->ansible-container[docker,k8s])
  Using cached urllib3-1.21.1-py2.py3-none-any.whl
Collecting ruamel.ordereddict (from ruamel.yaml>=0.14.2->ansible-container[docker,k8s])
Collecting colorama; extra == "dev" (from structlog[dev]>=16.1->ansible-container[docker,k8s])
  Using cached colorama-0.3.9-py2.py3-none-any.whl
Collecting websocket-client>=0.32.0 (from docker>=2.1->ansible-container[docker,k8s])
Collecting backports.ssl-match-hostname>=3.5; python_version < "3.5" (from docker>=2.1->ansible-container[docker,k8s])
Collecting ipaddress>=1.0.16; python_version < "3.3" (from docker>=2.1->ansible-container[docker,k8s])
  Using cached ipaddress-1.0.18-py2-none-any.whl
Collecting docker-pycreds>=0.2.1 (from docker>=2.1->ansible-container[docker,k8s])
  Using cached docker_pycreds-0.2.1-py2.py3-none-any.whl
Collecting dictdiffer (from openshift==0.0.1->ansible-container[docker,k8s])
  Using cached dictdiffer-0.6.1-py2.py3-none-any.whl
Collecting kubernetes~=1.0.1 (from openshift==0.0.1->ansible-container[docker,k8s])
  Using cached kubernetes-1.0.2-py2.py3-none-any.whl
Collecting python-string-utils (from openshift==0.0.1->ansible-container[docker,k8s])
Collecting python-dateutil (from kubernetes~=1.0.1->openshift==0.0.1->ansible-container[docker,k8s])
  Using cached python_dateutil-2.6.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools in ./testins/lib/python2.7/site-packages (from kubernetes~=1.0.1->openshift==0.0.1->ansible-container[docker,k8s])
Collecting oauth2client (from kubernetes~=1.0.1->openshift==0.0.1->ansible-container[docker,k8s])
  Downloading oauth2client-4.1.1-py2.py3-none-any.whl (185kB)
    100% |████████████████████████████████| 194kB 4.2MB/s
Collecting pyasn1-modules>=0.0.5 (from oauth2client->kubernetes~=1.0.1->openshift==0.0.1->ansible-container[docker,k8s])
  Downloading pyasn1_modules-0.0.9-py2.py3-none-any.whl (60kB)
    100% |████████████████████████████████| 61kB 5.7MB/s
Collecting pyasn1>=0.1.7 (from oauth2client->kubernetes~=1.0.1->openshift==0.0.1->ansible-container[docker,k8s])
  Using cached pyasn1-0.2.3-py2.py3-none-any.whl
Collecting rsa>=3.1.4 (from oauth2client->kubernetes~=1.0.1->openshift==0.0.1->ansible-container[docker,k8s])
  Using cached rsa-3.4.2-py2.py3-none-any.whl
Collecting httplib2>=0.9.1 (from oauth2client->kubernetes~=1.0.1->openshift==0.0.1->ansible-container[docker,k8s])
Building wheels for collected packages: ansible-container, ruamel.yaml
  Running setup.py bdist_wheel for ansible-container ... done
  Stored in directory: /Users/chouseknecht/Library/Caches/pip/wheels/c5/c3/9f/32924061ba71fde10c44811702cf8da3bd5f5f34cf2d3026de
  Running setup.py bdist_wheel for ruamel.yaml ... done
  Stored in directory: /Users/chouseknecht/Library/Caches/pip/wheels/c3/9a/f1/ab3a93681297d07ee8e1b1589f33df4b0d5dd02bd2bc35e2cc
Successfully built ansible-container ruamel.yaml
Installing collected packages: MarkupSafe, Jinja2, PyYAML, chardet, certifi, idna, urllib3, requests, ruamel.ordereddict, ruamel.yaml, six, colorama, structlog, websocket-client, backports.ssl-match-hostname, ipaddress, docker-pycreds, docker, dictdiffer, python-dateutil, pyasn1, pyasn1-modules, rsa, httplib2, oauth2client, kubernetes, python-string-utils, openshift, ansible-container
Successfully installed Jinja2-2.9.6 MarkupSafe-1.0 PyYAML-3.12 ansible-container-0.9.1 backports.ssl-match-hostname-3.5.0.1 certifi-2017.4.17 chardet-3.0.4 colorama-0.3.9 dictdiffer-0.6.1 docker-2.3.0 docker-pycreds-0.2.1 httplib2-0.10.3 idna-2.5 ipaddress-1.0.18 kubernetes-1.0.2 oauth2client-4.1.1 openshift-0.0.1 pyasn1-0.2.3 pyasn1-modules-0.0.9 python-dateutil-2.6.0 python-string-utils-0.6.0 requests-2.18.1 rsa-3.4.2 ruamel.ordereddict-0.4.9 ruamel.yaml-0.15.7 six-1.10.0 structlog-17.2.0 urllib3-1.21.1 websocket-client-0.40.0
```

Now if I test the version of ansible container installed:

```
(testins) ~/projects $ ansible-container version
Ansible Container, version 0.9.1
```

Also, I would recommend installing from source, rather than directly from PyPi. There have been a significant number of bug fixes since 0.9.1, and you should run with the latest code to get the best experience. If you need assistance, follow the instructions in our [Running from source guide](http://docs.ansible.com/ansible-container/installation.html#running-from-source)

Thanks!

**Comment by bala-v** [comment]
>>Does it work when you perform the installation (pip install ansible-container==0.9.1[docker]) >>which is suggested by the error message?
$ pip install ansible-container==0.9.1[docker]
Collecting ansible-container==0.9.1[docker]
  Could not find a version that satisfies the requirement ansible-container==0.9.1[docker] (from versions: 0.1.0, 0.2.0, 0.3.0, 0.9.0.0, 0.9.1)
_No matching distribution found for ansible-container==0.9.1[docker]_

**Comment by miked0004** [comment]
The correct syntax is:

`$ pip install 'ansible-container[docker]'==0.9.2`

also if using zsh, you must quote as above, otherwise you will see this error:

`zsh: no matches found: ansible-container[docker]==0.9.2`

**Comment by fermenreq** [comment]
@miked0004 your response didn't work for me. I would like to migrate from some DockerFiles to Ansible container.

`root@osboxes:/home/osboxes/Desktop.............................# uname -a
Linux osboxes 4.13.0-32-generic #35~16.04.1-Ubuntu SMP Thu Jan 25 10:13:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
`

`root@osboxes:/home/osboxes/Desktop/......................# docker --version
Docker version 18.01.0-ce, build 03596f5
`

`root@osboxes:/home/osboxes/Desktop/Proyectos/....................# ansible-container import /home/osboxes/Desktop/Proyectos/............../..............................ShowcaseServer/
`
and it shows: 


`ERROR	Unknown exception	
Traceback (most recent call last):
  File "/home/osboxes/Desktop/Proyectos/STAMP/ansible-container/container/cli.py", line 302, in __call__
    getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
  File "/home/osboxes/Desktop/Proyectos/STAMP/ansible-container/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/home/osboxes/Desktop/Proyectos/STAMP/ansible-container/container/core.py", line 500, in hostcmd_import
    {}, **kwargs)
  File "/home/osboxes/Desktop/Proyectos/STAMP/ansible-container/container/utils/loader.py", line 16, in load_engine
    package='container')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/osboxes/Desktop/Proyectos/STAMP/ansible-container/container/docker/engine.py", line 38, in <module>
    from .secrets import DockerSecretsMixin
  File "/home/osboxes/Desktop/Proyectos/STAMP/ansible-container/container/docker/secrets.py", line 17, in <module>
    u'Try:\npip install ansible-container==%s[docker]' % container_version)
ImportError: You must install Ansible Container with Docker(tm) support. Try:
pip install ansible-container==0.9.3rc0[docker]
`

## Details 

`root@osboxes:/home/osboxes/Desktop/Proyectos/.............# ansible-container version
Ansible Container, version 0.9.3rc0
`

`root@osboxes:/home/osboxes/Desktop/Proyectos/.................o# ls
ansible.cfg  ansible-requirements.txt  container.yml  meta.yml	requirements.yml
`
