### ISSUE TITLE
shipit fails with selinux enabled

### ISSUE THREAD

**Issue by dustymabe** [ansible/ansible-container#61]
Running on Fedora 24 I get a failure when running  `ansible-container shipit`. Without selinux enable this works fine. This is most likely because we are mounting directories into a container (the `ansible-container`) and trying to modify the contents. 

```
[root@f24 test]# pwd
/sharedfolder/ansible-container/test
[root@f24 test]# git remote -v
origin  https://github.com/ansible/ansible-container (fetch)
origin  https://github.com/ansible/ansible-container (push)
[root@f24 test]# ls
ansible
[root@f24 test]# rpm -q docker
docker-1.10.3-9.git667d6d1.fc24.x86_64
[root@f24 test]#
[root@f24 test]# setenforce 1
[root@f24 test]# ansible-container --debug shipit
Project name is test
Initialized with params: {'shipit_engine': 'openshift', 'subcommand': 'shipit', 'save_config': False, 'engine_args': {'shipit_engine': 'openshift', 'engine_name': 'docker', 'subcommand': 'shipit', 'save_config': False, 'engine_args': {...}, 'base_path': '/sharedfolder/ansible-container/test', 'kwargs': {'debug': True, 'subcommand': 'shipit', 'shipit_engine': 'openshift', 'save_config': False}, 'debug': True}, 'kwargs': {'debug': True, 'subcommand': 'shipit', 'shipit_engine': 'openshift', 'save_config': False}, 'debug': True}
Creating roles path /sharedfolder/ansible-container/test/roles
Using temporary directory /tmp/tmpf4u9Cz...
Executing ansible-galaxy init test
Compose derived from config:
{'host2': {'image': 'ubuntu:trusty', 'command': ['/usr/bin/dumb-init', '/usr/sbin/apache2ctl', '-D', 'FOREGROUND'], 'ports': ['80:80']}, 'host1': {'image': 'ubuntu:trusty', 'command': '/bin/false'}}
{'host2': {'image': 'ubuntu:trusty', 'command': 'echo "Started"', 'ports': ['80:80']}, 'host1': {'image': 'ubuntu:trusty', 'command': 'echo "Started"'}}
Config YAML is
host1: {command: echo "Started", image: 'ubuntu:trusty'}
host2:
  command: echo "Started"
  image: ubuntu:trusty
  ports: ['80:80']

Rendered Jinja Template:
# Execute ansible-galaxy init to create the shipit role
ansible-container:
  image: "sha256:05abeabd1f189f0e921448a7bf914d6ca1ee8bd8ec4b25bd32c1c2e179280e18"
  command: ansible-galaxy init -p /roles --force test
  volumes:
      - /sharedfolder/ansible-container/test/roles:/roles
host1: {command: echo "Started", image: 'ubuntu:trusty'}
host2:
  command: echo "Started"
  image: ubuntu:trusty
  ports: ['80:80']

Attaching to ansible_host1_1, ansible_ansible-container_1, ansible_host2_1
host2_1              | Started
host1_1              | Started
ansible_host1_1 exited with code 0
ansible-container_1  | ERROR! Unexpected Exception: [Errno 13] Permission denied: '/roles/test/README.md'
ansible-container_1  | to see the full traceback, use -vvv
ansible_host2_1 exited with code 0
ansible_ansible-container_1 exited with code 250
Role initialization failed.
Cleaning up and removing build container...
Cleaning up temporary directory /tmp/tmpf4u9Cz...

```

**Comment by dustymabe** [comment]
I tried this patch, but I still got an error:

```
diff --git a/container/templates/galaxy-docker-compose.j2.yml b/container/templates/galaxy-docker-compose.j2.yml
index 7a09f7b..5512561 100644
--- a/container/templates/galaxy-docker-compose.j2.yml
+++ b/container/templates/galaxy-docker-compose.j2.yml
@@ -3,5 +3,5 @@ ansible-container:
   image: "{{ builder_img_id }}"
   command: ansible-galaxy init -p /roles --force {{ role_name }}
   volumes:
-      - {{ roles_path }}:/roles
+      - {{ roles_path }}:/roles:Z
 {{ config }}
```


ERROR:

```
[root@f24 test]# ansible-container --debug shipit                                                                                                                                                                                            
Project name is test
Initialized with params: {'shipit_engine': 'openshift', 'subcommand': 'shipit', 'save_config': False, 'engine_args': {'shipit_engine': 'openshift', 'engine_name': 'docker', 'subcommand': 'shipit', 'save_config': False, 'engine_args': {...}, 'base_path': '/sharedfolder/ansible-container/test', 'kwargs': {'debug': True, 'subcommand': 'shipit', 'shipit_engine': 'openshift', 'save_config': False}, 'debug': True}, 'kwargs': {'debug': True, 'subcommand': 'shipit', 'shipit_engine': 'openshift', 'save_config': False}, 'debug': True}
Creating roles path /sharedfolder/ansible-container/test/roles
Using temporary directory /tmp/tmpv4DGYh...
Executing ansible-galaxy init test
Compose derived from config:
{'host2': {'image': 'ubuntu:trusty', 'command': ['/usr/bin/dumb-init', '/usr/sbin/apache2ctl', '-D', 'FOREGROUND'], 'ports': ['80:80']}, 'host1': {'image': 'ubuntu:trusty', 'command': '/bin/false'}}
{'host2': {'image': 'ubuntu:trusty', 'command': 'echo "Started"', 'ports': ['80:80']}, 'host1': {'image': 'ubuntu:trusty', 'command': 'echo "Started"'}}
Config YAML is
host1: {command: echo "Started", image: 'ubuntu:trusty'}
host2:
  command: echo "Started"
  image: ubuntu:trusty
  ports: ['80:80']

Rendered Jinja Template:
# Execute ansible-galaxy init to create the shipit role
ansible-container:
  image: "sha256:05abeabd1f189f0e921448a7bf914d6ca1ee8bd8ec4b25bd32c1c2e179280e18"
  command: ansible-galaxy init -p /roles --force test
  volumes:
      - /sharedfolder/ansible-container/test/roles:/roles:Z
host1: {command: echo "Started", image: 'ubuntu:trusty'}
host2:
  command: echo "Started"
  image: ubuntu:trusty
  ports: ['80:80']


ERROR: for ansible-container  operation not supported
Attaching to ansible_host2_1, ansible_host1_1
host2_1              | Started
host1_1              | Started
ansible_host2_1 exited with code 0
ansible_host1_1 exited with code 0
Cleaning up temporary directory /tmp/tmpv4DGYh...
need more than 0 values to unpack
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible_container-0.1-py2.7.egg/container/cli.py", line 182, in commandline
    **vars(args))
  File "/usr/lib/python2.7/site-packages/ansible_container-0.1-py2.7.egg/container/engine.py", line 315, in cmdrun_shipit
    if not engine_obj.build_was_successful():
  File "/usr/lib/python2.7/site-packages/ansible_container-0.1-py2.7.egg/container/docker/engine.py", line 186, in build_was_successful
    limit=1, all=True
ValueError: need more than 0 values to unpack

```

**Comment by chouseknecht** [comment]
But...I'm OK with it changing the contents. Is there some attribute I can add to the directory that will cause selinux to smile and bless the changes or at least look away and cover its eye while the change take place?

**Comment by chouseknecht** [comment]
This might be the answer: http://www.projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux/.  Looks like doing something like `-v /SOURCE:/DESTINATION:z` might fix it.

**Comment by dustymabe** [comment]
> @dustymabe Looks you tried with :Z.Does using ':z' make a difference?

`Z` vs `z` doesn't make a difference. This looks like an issue in python when trying to interpret the value.. like it probably is only looking for one colon vs two in that statement.

**Comment by chouseknecht** [comment]
The shipit command has changed. It no longer attempts to run ansible-galaxy to generate the initial role. Instead it creates the directories it needs and then creates files, mostly from templates. Presumably this issue gone now.

**Comment by gregdek** [comment]
@dustymabe gonna go ahead and close this, but if you run into it again, feel free to reopen it.
