### ISSUE TITLE
BuildError(chunk['error'])

### ISSUE THREAD

**Issue by hyperized** [ansible/ansible-container#635]
##### ISSUE TYPE
 - Bug Report

##### container.yml 

```
n/a
```

##### OS / ENVIRONMENT

```
[myuser:~]$ source ansible-container/bin/activate
(ansible-container) [myuser:~/ansible-container/hello]$ ansible-container version
Ansible Container, version 0.9.1
(ansible-container) [myuser:~/ansible-container/hello]$ python -V
Python 2.7.10
(ansible-container) [myuser:~/ansible-container/hello]$ docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true
```
##### SUMMARY
Error unknown exception when building example.

##### STEPS TO REPRODUCE

```
(ansible-container) [myuser:~/ansible-container/hello]$ ansible-container init ansible.django-gulp-nginx
Ansible Container initialized from Galaxy container app 'ansible.django-gulp-nginx'
(ansible-container) [myuser:~/ansible-container/hello]$ ansible-container build
Building Docker Engine context...
Starting Docker build of Ansible Container Conductor image (please be patient)...
ERROR	Unknown exception
Traceback (most recent call last):
  File "/Users/myuser/ansible-container/lib/python2.7/site-packages/container/cli.py", line 268, in __call__
    getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
  File "/Users/myuser/ansible-container/lib/python2.7/site-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/Users/myuser/ansible-container/lib/python2.7/site-packages/container/core.py", line 150, in hostcmd_build
    cache=kwargs['cache']
  File "/Users/myuser/ansible-container/lib/python2.7/site-packages/container/docker/engine.py", line 82, in __wrapped__
    return fn(self, *args, **kwargs)
  File "/Users/myuser/ansible-container/lib/python2.7/site-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/Users/myuser/ansible-container/lib/python2.7/site-packages/container/docker/engine.py", line 744, in build_conductor_image
    nocache=not cache)
  File "/Users/myuser/ansible-container/lib/python2.7/site-packages/docker/models/images.py", line 175, in build
    raise BuildError(chunk['error'])
BuildError: The command '/bin/sh -c python /get-pip.py &&     mkdir -p /etc/ansible/roles /_ansible/src &&     cd /usr/local/bin &&     tar -xz --strip-components=1 -f /tmp/docker.tgz' returned a non-zero code: 2
```

##### EXPECTED RESULTS
It works.

##### ACTUAL RESULTS

```
It doesn't.
```

**Comment by chouseknecht** [comment]
@hyperized 

Thanks for trying Ansible Container, and sharing your feedback. 

As noted in the [README](https://github.com/ansible/django-gulp-nginx/blob/master/README.md) for [ansible/django-gulp-nginx](https://github.com/ansible/django-gulp-nginx), a prerequisite for building and using the project is running Ansible Container from source. It requires the latest code and bug fixes not currently found in the  PyPi release.

FWIW, I ran a local build of the project using the latest Ansible Code code from the `develop` branch, and it worked without any issues:

```

PLAY RECAP *********************************************************************
nginx                      : ok=18   changed=14   unreachable=0    failed=0

Applied role to service	role=ordereddict([('PROXY_LOCATION', '~* /(admin|api)'), ('PROXY_PASS', 'http://django:8080'), ('role', 'ansible.nginx-container'), ('PROXY', 'yes'), ('ASSET_PATHS', ['/tmp/dist'])]) service=nginx
Committed layer as image	image=sha256:da553654e791ed052571a94ecff02872b6d47522e03692451a1721768e77ba54 service=nginx
Build complete.	service=nginx
Building service...	project=test service=postgresql
Service had no roles specified. Nothing to do.	service=postgresql
All images successfully built.
Conductor terminated. Cleaning up.	command_rc=0 conductor_id=a3b1a3a047b3f73f4a7205d20cace01fd1b3baffd1e36954ab56983c5197462f save_container=False
```
