### ISSUE TITLE
ansible-container build fails using 0.9.2rc0 

### ISSUE THREAD

**Issue by mchassy** [ansible/ansible-container#638]
##### ISSUE TYPE
 - Bug Report

##### container.yml 
```
version: "2"
settings:
  conductor:
    base: "amazonlinux:2017.03"

services:
  mongo:
    from: "amazonlinux:2017.03"
    roles:
    - role: mongo_role
    working_dir: "/opt"
    user: orson
    expose:
      - 27017
    volumes:
      - mongo_data:/opt/orson/mongo/data
    dev_overides:
      links:
        tomee
    entrypoint: [/entrypoint.sh]
    command: [/usr/bin/dumb-init, /opt/orson/mongo/bin/mongod --config /opt/orson/mongo/conf/mongod.conf]
  tomee:
    from: "amazonlinux:2017.03"
    roles:
    - role: tomee_role
    working_dir: "/opt"
    ports:
      - 8080:8080
    dev_overides:
      links:
        mongo
      ports:
        - 8090:8080
    user: orson
    entrypoint: [/entrypoint.sh]
    command: [/usr/bin/dumb-init, /opt/orson/tomee/bin/catalina.sh, run]
volumes:
  mongo_data:
    docker: {}

registries: {}
```

##### OS / ENVIRONMENT
```
(venv_orson)[ec2-user@ip-172-31-31-72 ansible_orson]$ ansible-container --debug version
Ansible Container, version 0.9.2rc0
Linux, ip-172-31-31-72, 4.9.32-15.41.amzn1.x86_64, #1 SMP Thu Jun 22 06:20:54 UTC 2017, x86_64
2.7.12 (default, Sep  1 2016, 22:14:00)
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] /home/ec2-user/venv_orson/bin/python2.7
{
  "ContainersPaused": 0,
  "Labels": null,
  "CgroupDriver": "cgroupfs",
  "ContainersRunning": 0,
  "ContainerdCommit": {
    "Expected": "4ab9917febca54791c5f071a9d1f404867857fcc",
    "ID": ""
  },
  "InitBinary": "docker-init",
  "NGoroutines": 22,
  "Swarm": {
    "Managers": 0,
    "ControlAvailable": false,
    "NodeID": "",
    "Cluster": {
      "Spec": {
        "TaskDefaults": {},
        "Orchestration": {},
        "EncryptionConfig": {
          "AutoLockManagers": false
        },
        "Raft": {
          "HeartbeatTick": 0,
          "ElectionTick": 0
        },
        "CAConfig": {},
        "Dispatcher": {}
      },
      "Version": {},
      "ID": "",
      "CreatedAt": "0001-01-01T00:00:00Z",
      "UpdatedAt": "0001-01-01T00:00:00Z"
    },
    "Nodes": 0,
    "Error": "",
    "RemoteManagers": null,
    "LocalNodeState": "inactive",
    "NodeAddr": ""
  },
  "LoggingDriver": "json-file",
  "OSType": "linux",
  "HttpProxy": "",
  "Runtimes": {
    "runc": {
      "path": "docker-runc"
    }
  },
  "DriverStatus": [
    [
      "Backing Filesystem",
      "extfs"
    ],
    [
      "Supports d_type",
      "true"
    ],
    [
      "Native Overlay Diff",
      "true"
    ]
  ],
  "OperatingSystem": "Amazon Linux AMI 2017.03",
  "Containers": 0,
  "HttpsProxy": "",
  "BridgeNfIp6tables": true,
  "MemTotal": 8373010432,
  "SecurityOptions": [
    "name=seccomp,profile=default"
  ],
  "Driver": "overlay2",
  "IndexServerAddress": "https://index.docker.io/v1/",
  "ClusterStore": "",
  "InitCommit": {
    "Expected": "949e6facb77383876aeff8a6944dde66b3089574",
    "ID": "N/A"
  },
  "Isolation": "",
  "SystemStatus": null,
  "OomKillDisable": true,
  "ClusterAdvertise": "",
  "SystemTime": "2017-07-06T10:44:37.793313712Z",
  "Name": "ip-172-31-31-72",
  "CPUSet": true,
  "RegistryConfig": {
    "InsecureRegistryCIDRs": [
      "127.0.0.0/8"
    ],
    "IndexConfigs": {
      "docker.io": {
        "Official": true,
        "Name": "docker.io",
        "Secure": true,
        "Mirrors": null
      }
    },
    "Mirrors": []
  },
  "DefaultRuntime": "runc",
  "ContainersStopped": 0,
  "NCPU": 2,
  "NFd": 15,
  "Architecture": "x86_64",
  "KernelMemory": true,
  "CpuCfsQuota": true,
  "Debug": false,
  "ID": "OUL3:QZOO:27DV:BBMK:JW4K:YB7M:YV53:GZW5:BXSE:JMOU:R2T3:ANLH",
  "IPv4Forwarding": true,
  "KernelVersion": "4.9.32-15.41.amzn1.x86_64",
  "BridgeNfIptables": true,
  "NoProxy": "",
  "LiveRestoreEnabled": false,
  "ServerVersion": "17.03.1-ce",
  "CpuCfsPeriod": true,
  "ExperimentalBuild": false,
  "MemoryLimit": true,
  "SwapLimit": true,
  "Plugins": {
    "Volume": [
      "local"
    ],
    "Network": [
      "bridge",
      "host",
      "macvlan",
      "null",
      "overlay"
    ],
    "Authorization": null
  },
  "Images": 0,
  "DockerRootDir": "/var/lib/docker",
  "NEventsListener": 0,
  "CPUShares": true,
  "RuncCommit": {
    "Expected": "54296cf40ad8143b62dbcaa1d90e520a2136ddfe",
    "ID": "N/A"
  }
}
{
  "KernelVersion": "4.9.32-15.41.amzn1.x86_64",
  "Arch": "amd64",
  "BuildTime": "2017-05-30T17:59:44.502465179+00:00",
  "ApiVersion": "1.27",
  "Version": "17.03.1-ce",
  "MinAPIVersion": "1.12",
  "GitCommit": "7392c3b/17.03.1-ce",
  "Os": "linux",
  "GoVersion": "go1.7.5"
}
(venv_orson)[ec2-user@ip-172-31-31-72 ansible_orson]$
```
##### SUMMARY
I had already successfully built these services on my mac. The next step was to create a clean VM on AWS and build and deploy from there. The VM is aws linux,  
* latest versions of docker, docker-compose, 
* python 2.7 and pip 9.0.1
* virtual env created
* pip install -r using requirements file retrieved from a pip freeze on my mac
* latest version ansible
* ansible-container installed from source as documented `pip install -e .[docker,openshift,k8s]`

##### STEPS TO REPRODUCE
* create an AWS instance with AWS linux 64 bit. 
* In advanced config you can include a script to run. Put these lines into the file
```
#!/bin/bash
yum clean expire-cache
# yum install –y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
yum install -y gcc
yum install -y python-devel
yum install -y python-lxml
yum install -y libffi-devel
yum install -y openssl-devel
yum install -y git
yum install -y wget
sudo yum upgrade python*
curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
python get-pip.py
rm get-pip.py
pip install --upgrade pip
pip install virtualenv
yum install -y docker
curl -L https://github.com/docker/compose/releases/download/1.14.0/docker-compose-`uname -s`-`uname -m` | sudo tee /usr/local/bin/docker-compose > /dev/null
chmod +x /usr/local/bin/docker-compose
service docker start
chkconfig docker on
sudo usermod -aG docker ec2-user 

cat << EOF > /home/ec2-user/virtual.sh
#!/bin/bash
echo "###########################################"
echo "Installing ansible-container"
virtualenv venv_orson
source venv_orson/bin/activate
cd venv_orson
pip --version
pip install --upgrade pip
pip list installed
pip install ansible
ansible --version
# pip -e git+https://github.com/ansible/ansible-container@421d9b020fdce4d78522fcecff912117587f7914#egg=ansible_container
git clone https://github.com/ansible/ansible-container
cd ansible-container
pip install -e .[docker,openshift,k8s]
ansible-container version
pip list installed
echo "###########################################"
cd ~
git clone https://bitbucket.org/mchassy/orson_swarm
EOF

cat << EOF > /home/ec2-user/.bash_profile
#!/bin/bash
# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi
# User specific environment and startup programs
PATH=$PATH:$HOME/.local/bin:$HOME/bin:/usr/local/bin
export DOCKER_HOST="unix:///var/run/docker.sock"
export PATH
alias ll='ls -al'
source venv_orson/bin/activate

EOF

chmod a+x /home/ec2-user/.bash_profile
chmod a+x /home/ec2-user/virtual.sh
sudo -H -i -u ec2-user /home/ec2-user/virtual.sh
```

##### EXPECTED RESULTS
* Conductor and Service containers built

##### ACTUAL RESULTS

```
(venv_orson)[ec2-user@ip-172-31-47-182 ansible_orson]$ ansible-container --debug build
2017-07-06T02:12:08.509610 The default type is            [container.config] caller_file=/home/ec2-user/venv_orson/ansible-container/container/config.py caller_func=_resolve_defaults caller_line=160 config=<class 'ruamel.yaml.comments.CommentedMap'> defaults=<type '_ordereddict.ordereddict'>
2017-07-06T02:12:08.510468 Getting environment variables... [container.config] caller_file=/home/ec2-user/venv_orson/ansible-container/container/config.py caller_func=_get_environment_variables caller_line=176
2017-07-06T02:12:08.511277 Read environment variables     [container.config] caller_file=/home/ec2-user/venv_orson/ansible-container/container/config.py caller_func=_get_environment_variables caller_line=181 env_vars={}
2017-07-06T02:12:08.512030 Resolved template variables    [container.config] caller_file=/home/ec2-user/venv_orson/ansible-container/container/config.py caller_func=_resolve_defaults caller_line=165 template_vars={}
2017-07-06T02:12:08.512844 Parsed config                  [container.config] caller_file=/home/ec2-user/venv_orson/ansible-container/container/config.py caller_func=set_env caller_line=141 config={"version": "2", "settings": {"conductor": {"base": "amazonlinux:2017.03"}, "pwd": "/home/ec2-user/orson_swarm/ansible_orson"}, "services": {"mongo": {"from": "amazonlinux:2017.03", "roles": [{"role": "mongo_role"}], "working_dir": "/opt", "user": "orson", "expose": [27017], "volumes": ["mongo_data:/opt/orson/mongo/data"], "dev_overides": {"links": "tomee"}, "entrypoint": ["/entrypoint.sh"], "command": ["/usr/bin/dumb-init", "/opt/orson/mongo/bin/mongod --config /opt/orson/mongo/conf/mongod.conf"]}, "tomee": {"from": "amazonlinux:2017.03", "roles": [{"role": "tomee_role"}], "working_dir": "/opt", "ports": ["8080:8080"], "dev_overides": {"links": "mongo", "ports": ["8090:8080"]}, "user": "orson", "entrypoint": ["/entrypoint.sh"], "command": ["/usr/bin/dumb-init", "/opt/orson/tomee/bin/catalina.sh", "run"]}}, "volumes": {"mongo_data": {"docker": {}}}, "registries": {}, "defaults": {}}
2017-07-06T02:12:08.513561 Loading engine capabilities    [container.utils.loader] caller_file=/home/ec2-user/venv_orson/ansible-container/container/utils/loader.py caller_func=load_engine caller_line=14 capabilities=['BUILD', 'RUN'] engine=docker
2017-07-06T02:12:08.523128 Unknown exception You must install Ansible Container with Docker(tm) support. Try:
pip install ansible-container==0.9.2rc0[docker] [container.cli] caller_file=/home/ec2-user/venv_orson/local/lib/python2.7/site-packages/structlog/stdlib.py caller_func=exception caller_line=95
Traceback (most recent call last):
  File "/home/ec2-user/venv_orson/ansible-container/container/cli.py", line 278, in __call__
    getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
  File "/home/ec2-user/venv_orson/ansible-container/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/home/ec2-user/venv_orson/ansible-container/container/core.py", line 133, in hostcmd_build
    config['services'], **kwargs)
  File "/home/ec2-user/venv_orson/ansible-container/container/utils/loader.py", line 16, in load_engine
    package='container')
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ec2-user/venv_orson/ansible-container/container/docker/engine.py", line 45, in <module>
    container.__version__
ImportError: You must install Ansible Container with Docker(tm) support. Try:
pip install ansible-container==0.9.2rc0[docker]
(venv_orson)[ec2-user@ip-172-31-47-182 ansible_orson]$
```

**Comment by mchassy** [comment]
As a sanity check, on the same server, I did the following.

```
(venv_orson)[ec2-user@ip-172-31-47-182 ~]$ mkdir test
(venv_orson)[ec2-user@ip-172-31-47-182 ~]$ cd test
(venv_orson)[ec2-user@ip-172-31-47-182 test]$ ansible-container --debug init
2017-07-06T02:26:12.862245 Rendered Jinja Template:       [container.utils] body=galaxy_info:
  author: Your name
  description: Describe your awesome application here.
  company: Your company

  # If the issue tracker for your role is not on GitHub, uncomment the
  # next line and provide a value
  # issue_tracker_url:

  # Some suggested licenses:
  # - BSD (default)
  # - MIT
  # - GPLv2
  # - GPLv3
  # - Apache
  # - CC-BY
  license: license (GPLv2, CC-BY, etc)

  min_ansible_container_version: 0.9.2rc0

  # Optionally specify the branch Galaxy will use when accessing the GitHub
  # repo for this role. During role install, if no tags are available,
  # Galaxy will use this branch. During import Galaxy will access files on
  # this branch. If travis integration is cofigured, only notification for this
  # branch will be accepted. Otherwise, in all cases, the repo's default branch
  # (usually master) will be used.
  #github_branch:

  tags: []
    # List tags for your app here, one per line. A tag is a keyword that describes and categorizes the app.
    # Users will find your app by searching for tags. Be sure to remove the '[]' above.
    #
    # NOTE: A tag is limited to a single word comprised of alphanumeric characters. Maximum 20 tags.
 caller_file=/home/ec2-user/venv_orson/ansible-container/container/utils/__init__.py caller_func=jinja_render_to_temp caller_line=82
2017-07-06T02:26:12.863626 Rendered Jinja Template:       [container.utils] body=# These are the python requirements for your Ansible Container builder.
# You do not need to include Ansible itself in this file.
 caller_file=/home/ec2-user/venv_orson/ansible-container/container/utils/__init__.py caller_func=jinja_render_to_temp caller_line=82
2017-07-06T02:26:12.864882 Rendered Jinja Template:       [container.utils] body=# Set any ansible.cfg overrides in this file.
# See: https://docs.ansible.com/ansible/intro_configuration.html#explanation-of-values-by-section
 caller_file=/home/ec2-user/venv_orson/ansible-container/container/utils/__init__.py caller_func=jinja_render_to_temp caller_line=82
2017-07-06T02:26:12.867269 Rendered Jinja Template:       [container.utils] body=version: "2"
settings:

  conductor:
    # The Conductor container does the heavy lifting, and provides a portable
    # Python runtime for building your target containers. It should be derived
    # from the same distribution as you're building your target containers with.
    base: centos:7
    # roles_path:   # Specify a local path containing Ansible roles
    # volumes:      # Provide a list of volumes to mount
    # environment:  # List or mapping of environment variables

  # Set the name of the project. Defaults to basename of the project directory.
  # For built services, concatenated with service name to form the built image name.
  project_name: test

  # The deployment_output_path is mounted to the Conductor container, and the
  # `run` and `deployment` commands then write generated Ansible playbooks to it.
  # deployment_output_path: ./ansible-deployment

  # When using the k8s or openshift engines, use the following to authorize with the API.
  # Values set here will be passed to the Ansible modules. Any file paths will be mounted
  # to the conductor container, allowing the `run` command to access the API.
  #k8s_auth:
    # path to a K8s config file
    #config_file:
    # name of a context found within the config file
    #context:
    # URL for accessing the K8s API
    #host:
    # An API authentication token
    #api_key:
    # Path to a ca cert file
    #ssl_ca_cert:
    # Path to a cert file
    #cert_file:
    # Path to a key file
    #key_file:
    # boolean, indicating if SSL certs should be validated
    #verify_ssl:

  # When using the k8s or openshift engines, use the following to set the namespace.
  # If not set, the project name will be used. For openshift, the namespace maps to a project,
  # and description and display_name are supported.
  #k8s_namespace:
  #  name:
  #  description:
  #  display_name:

services: {}
  # Add your containers here, specifying the base image you want to build from.
  # To use this example, uncomment it and delete the curly braces after services key.
  # You may need to run `docker pull ubuntu:trusty` for this to work.

  # web:
  #   from: "centos:7"
  #   ports:
  #     - "80:80"
  #   command: ["/usr/bin/dumb-init", "/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
  #   dev_overrides:
  #     environment:
  #       - "DEBUG=1"
registries: {}
  # Add optional registries used for deployment. For example:
  #  google:
  #    url: https://gcr.io
  #    namespace: my-cool-project-xxxxxx
 caller_file=/home/ec2-user/venv_orson/ansible-container/container/utils/__init__.py caller_func=jinja_render_to_temp caller_line=82
2017-07-06T02:26:12.868604 Rendered Jinja Template:       [container.utils] body=# Install Ansible Roles
# ---------------------
# When making the Conductor image `ansible-galaxy install -r requirements.yml` is executed
# using this file. Follow the instructions at http://docs.ansible.com/ansible/galaxy.html
# to include any roles you want installed prior to running main.yml.
 caller_file=/home/ec2-user/venv_orson/ansible-container/container/utils/__init__.py caller_func=jinja_render_to_temp caller_line=82
2017-07-06T02:26:12.869237 Ansible Container initialized. [container.core] caller_file=/home/ec2-user/venv_orson/ansible-container/container/core.py caller_func=hostcmd_init caller_line=123
```

Then

```
(venv_orson)[ec2-user@ip-172-31-47-182 test]$ ansible-container --debug version
Ansible Container, version 0.9.2rc0
Linux, ip-172-31-47-182, 4.9.32-15.41.amzn1.x86_64, #1 SMP Thu Jun 22 06:20:54 UTC 2017, x86_64
2.7.12 (default, Sep  1 2016, 22:14:00)
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] /home/ec2-user/venv_orson/bin/python2.7
ERROR	Unknown exception You must install Ansible Container with Docker(tm) support. Try:
pip install ansible-container==0.9.2rc0[docker]
Traceback (most recent call last):
  File "/home/ec2-user/venv_orson/ansible-container/container/cli.py", line 278, in __call__
    getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
  File "/home/ec2-user/venv_orson/ansible-container/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/home/ec2-user/venv_orson/ansible-container/container/core.py", line 429, in hostcmd_version
    {}, **kwargs)
  File "/home/ec2-user/venv_orson/ansible-container/container/utils/loader.py", line 16, in load_engine
    package='container')
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ec2-user/venv_orson/ansible-container/container/docker/engine.py", line 45, in <module>
    container.__version__
ImportError: You must install Ansible Container with Docker(tm) support. Try:
pip install ansible-container==0.9.2rc0[docker]
(venv_orson)[ec2-user@ip-172-31-47-182 test]$
```

Then
```
(venv_orson)[ec2-user@ip-172-31-47-182 test]$ ansible-container --debug build
2017-07-06T02:27:31.698133 The default type is            [container.config] caller_file=/home/ec2-user/venv_orson/ansible-container/container/config.py caller_func=_resolve_defaults caller_line=160 config=<class 'ruamel.yaml.comments.CommentedMap'> defaults=<type '_ordereddict.ordereddict'>
2017-07-06T02:27:31.698948 Getting environment variables... [container.config] caller_file=/home/ec2-user/venv_orson/ansible-container/container/config.py caller_func=_get_environment_variables caller_line=176
2017-07-06T02:27:31.699728 Read environment variables     [container.config] caller_file=/home/ec2-user/venv_orson/ansible-container/container/config.py caller_func=_get_environment_variables caller_line=181 env_vars={}
2017-07-06T02:27:31.700443 Resolved template variables    [container.config] caller_file=/home/ec2-user/venv_orson/ansible-container/container/config.py caller_func=_resolve_defaults caller_line=165 template_vars={}
2017-07-06T02:27:31.701176 Parsed config                  [container.config] caller_file=/home/ec2-user/venv_orson/ansible-container/container/config.py caller_func=set_env caller_line=141 config={"version": "2", "settings": {"conductor": {"base": "centos:7"}, "project_name": "test", "pwd": "/home/ec2-user/test"}, "services": {}, "registries": {}, "defaults": {}}
2017-07-06T02:27:31.701824 Loading engine capabilities    [container.utils.loader] caller_file=/home/ec2-user/venv_orson/ansible-container/container/utils/loader.py caller_func=load_engine caller_line=14 capabilities=['BUILD', 'RUN'] engine=docker
2017-07-06T02:27:31.712065 Unknown exception You must install Ansible Container with Docker(tm) support. Try:
pip install ansible-container==0.9.2rc0[docker] [container.cli] caller_file=/home/ec2-user/venv_orson/local/lib/python2.7/site-packages/structlog/stdlib.py caller_func=exception caller_line=95
Traceback (most recent call last):
  File "/home/ec2-user/venv_orson/ansible-container/container/cli.py", line 278, in __call__
    getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
  File "/home/ec2-user/venv_orson/ansible-container/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/home/ec2-user/venv_orson/ansible-container/container/core.py", line 133, in hostcmd_build
    config['services'], **kwargs)
  File "/home/ec2-user/venv_orson/ansible-container/container/utils/loader.py", line 16, in load_engine
    package='container')
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ec2-user/venv_orson/ansible-container/container/docker/engine.py", line 45, in <module>
    container.__version__
ImportError: You must install Ansible Container with Docker(tm) support. Try:
pip install ansible-container==0.9.2rc0[docker]
(venv_orson)[ec2-user@ip-172-31-47-182 test]$
```

**Comment by mchassy** [comment]
BTW ... I am sure that one your first comments may be, hey why didn't you use ansible to provision the server to begin with. That's a good question, and I am not sure I have a real answer, though I am not sure that it would have made a difference in this case. The stupid answer is that I wanted to make this is ansible/ansible-container image a template inside my AWS account and I wanted to make sure that the install was in no way affected by the environment on my mac (that part may be the really stupid part).

**Comment by mchassy** [comment]
Closing this ... the main problem seems to have stemmed from leaving this out of the initial docker install
sudo usermod -aG docker ec2-user

But I have to admit, this raises a number of security questions.
