### ISSUE TITLE
ansible-container build error

### ISSUE THREAD

**Issue by yogeshVU** [ansible/ansible-container#640]
##### ISSUE TYPE

 - Bug Report

##### container.yml 

```version: "2"
settings:
  conductor_base: centos:7
defaults:
  POSTGRES_USER: django
  POSTGRES_PASSWORD: sesame
  POSTGRES_DB: django
  DJANGO_PORT: 8080
services:
  django:
    from: centos:7
    roles:
      - django-gunicorn
    environment:
      DATABASE_URL: "pgsql://{{ POSTGRES_USER }}:{{ POSTGRES_PASSWORD }}@postgres:5432/{{ POSTGRES_DB }}"
      DJANGO_ROOT: '{{ DJANGO_ROOT }}'
      DJANGO_VENV: '{{ DJANGO_VENV }}'
    links:
    - postgres
    - postgres:postgresql
    ports:
    - '{{ DJANGO_PORT }}'
    working_dir: '{{ DJANGO_ROOT }}'
    user: '{{ DJANGO_USER }}'
    command: ['{{ DJANGO_VENV }}/bin/gunicorn', '-w', '2', '-b', '0.0.0.0:{{ DJANGO_PORT }}', 'project.wsgi:application']
    entrypoint: ['/usr/bin/dumb-init', '/usr/bin/entrypoint.sh']
    volumes:
      - 'static:{{ DJANGO_ROOT }}'
    dev_overrides:
      command: ['{{ DJANGO_VENV }}/bin/python', 'manage.py', 'runserver', '0.0.0.0:{{ DJANGO_PORT }}']
      volumes:
      - '${PWD}:{{ DJANGO_ROOT }}'
      - "static:/static"
      expose:
      - "{{ DJANGO_PORT }}"
      environment:
        DEBUG: "1"
  nginx:
    from: centos:7
    roles:
    - nginx
    ports:
    - '{{ DJANGO_PORT }}:8000'
    user: nginx
    links:
    - django
    command: ['/usr/bin/dumb-init', 'nginx', '-c', '/etc/nginx/nginx.conf']
    volumes:
    - 'static:{{ STATIC_ROOT }}'
    dev_overrides:
      ports: []
      command: /bin/false
      volumes: []
  postgres:
    from: postgres:9.6
    environment:
      POSTGRES_USER: "{{ POSTGRES_USER }}"
      POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"
      POSTGRES_DB: "{{ POSTGRES_DB }}"
volumes:
  static:
    docker: {}
registries: {}


```

##### OS / ENVIRONMENT

```
Ansible Container, version 0.9.1
Linux, vagrant, 4.2.0-27-generic, #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016, x86_64
2.7.12 (default, Jul 18 2016, 15:02:52) 
[GCC 4.8.4] /usr/bin/python
ERROR	Unknown exception You must install Ansible Container with Docker(tm) support. Try:
pip install ansible-container==0.9.1[docker]	
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/container/cli.py", line 268, in __call__
    getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
  File "/usr/local/lib/python2.7/dist-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/container/core.py", line 414, in hostcmd_version
    {}, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/container/utils/loader.py", line 16, in load_engine
    package='container')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/container/docker/engine.py", line 44, in <module>
    container.__version__
ImportError: You must install Ansible Container with Docker(tm) support. Try:
pip install ansible-container==0.9.1[docker]

```
##### SUMMARY

I get error on container build as shown below. I have already installed using the
sudo pip install ansible-container==0.9.1[docker]

Error persists

##### STEPS TO REPRODUCE

```

ansible-container build
```

##### EXPECTED RESULTS

should run 
##### ACTUAL RESULTS

```
ansible-container build
ERROR	Unknown exception	
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/container/cli.py", line 268, in __call__
    getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
  File "/usr/local/lib/python2.7/dist-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/container/core.py", line 137, in hostcmd_build
    config['services'], **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/container/utils/loader.py", line 16, in load_engine
    package='container')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/container/docker/engine.py", line 44, in <module>
    container.__version__
ImportError: You must install Ansible Container with Docker(tm) support. Try:
pip install ansible-container==0.9.1[docker]
```

**Comment by chouseknecht** [comment]
@yogeshVU 

Thanks for using Ansible Container, and for sharing your feedback. 

Can you share the output from running `sudo pip install ansible-container==0.9.1[docker]`?

It looks like, based on the error messages you shared, you don't have the `docker` module installed, or perhaps not a recent enough version. I would suggest trying `sudo pip install --upgrade docker`. 

Ansible Container requires `docker>=2.1`.

**Comment by yogeshVU** [comment]
` sudo pip install --upgrade docker `
Did the trick, though I got the same error when running from the source. 

I am currently running it through the git source. I can test the pip way to see if the error gets resolved. But then I need to uninstall the current ansible-container installed through source. How can I uninstall it. what is the command?

**Comment by chouseknecht** [comment]
To uninstall: `pip uninstall ansible-container`

Sounds like the `docker` module was already installed. You might benefit from completely uninstalling it (e.g. `pip uninstall docker`) prior to reinstalling Ansible Container. 

This is why [virtualenv](http://python-guide-pt-br.readthedocs.io/en/latest/dev/virtualenvs/) exists. :-)

**Comment by yogeshVU** [comment]
Thanks but the ansible-container is installed using the git source. and if I try to issue the pip uninstall it complains that the package is not available.

**Comment by chouseknecht** [comment]
@yogeshVU 

Is this still an issue, or can it be closed?

**Comment by yogeshVU** [comment]
can be closed.

**Comment by jijeesh** [comment]
sudo pip install ansible-container

it will solve the issue
