### ISSUE TITLE
Container builds failing after ~July 26 with 'ansible.errors.AnsibleError: the role was not found'

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible-container#673]
##### ISSUE TYPE

 - Bug Report

##### container.yml 

https://github.com/geerlingguy/solr-container/blob/master/container.yml

##### OS / ENVIRONMENT

https://gist.github.com/geerlingguy/6363e5ac37672166053693b605506d98

##### SUMMARY

Ever since ~July 26, my automated daily builds of [solr-container](https://github.com/geerlingguy/solr-container) have been failing. Confirmed the same issue exists when building with ansible-container `develop/HEAD` locally. This problem did not exist in earlier builds.

Every night, the automated build pulls the latest AC head and runs a build against the project, and it seems that maybe one of the past few commits may have changed Ansible Container's interaction with roles, breaking the build?

##### STEPS TO REPRODUCE

1. Clone or download https://travis-ci.org/geerlingguy/solr-container
2. Ensure you're running ansible-container at the latest `develop` `HEAD` commit.
3. `ansible-container --debug --var-file vars-6.x.yml build` to build the container.

##### EXPECTED RESULTS

The build should succeed.

##### ACTUAL RESULTS

```
...
2017-07-30T16:40:20.304291 Docker run:                    [container.docker.engine] caller_file=/Users/jgeerling/Downloads/ansible-container/container/docker/engine.py caller_func=run_conductor caller_line=382 image=u'sha256:c99a95dd61a2a862d0892efe80b21db3e3fdb9e767837777e6f958c2afeab0a8' params={'name': u'solr-container_conductor', 'cap_add': ['SYS_ADMIN'], 'environment': {'DOCKER_HOST': 'unix:///var/run/docker.sock', 'ANSIBLE_ROLES_PATH': '/src/roles:/etc/ansible/roles'}, 'working_dir': '/src', 'command': ['conductor', 'build', '--project-name', 'solr-container', '--engine', 'docker', '--params', u'eyJ3aXRoX3ZvbHVtZXMiOiBbXSwgImNhY2hlIjogdHJ1ZSwgImxvY2FsX3B5dGhvbiI6IGZhbHNlLCAid2l0aF92YXJpYWJsZXMiOiBbXSwgInNlbGludXgiOiB0cnVlLCAicHVyZ2VfbGFzdCI6IHRydWUsICJzdWJjb21tYW5kIjogImJ1aWxkIiwgImRldmVsIjogZmFsc2UsICJjb25maWdfdmFycyI6IHsiamF2YV9wYWNrYWdlcyI6IFsib3Blbmpkay04LWpkayJdLCAic29scl9yZW1vdmVfY3J1ZnQiOiB0cnVlLCAic29scl92ZXJzaW9uIjogIjYuNi4wIiwgImNvbnRhaW5lcl93b3JraW5nX2RpciI6ICIvIiwgImNvbnRhaW5lcl9zdGFydF9jb21tYW5kIjogWyIvb3B0L3NvbHIvYmluL3NvbHIiLCAic3RhcnQiLCAiLWYiLCAiLWZvcmNlIl19LCAicm9sZXNfcGF0aCI6IFtdLCAiY29uZHVjdG9yX2NhY2hlIjogdHJ1ZSwgImFuc2libGVfb3B0aW9ucyI6ICIiLCAiZmxhdHRlbiI6IGZhbHNlLCAiY29udGFpbmVyX2NhY2hlIjogdHJ1ZSwgImRlYnVnIjogdHJ1ZSwgInNlcnZpY2VzX3RvX2J1aWxkIjogbnVsbCwgInNhdmVfY29uZHVjdG9yX2NvbnRhaW5lciI6IGZhbHNlfQ==', '--config', u'eyJzZXJ2aWNlcyI6IFtbInNvbHIiLCB7ImZyb20iOiAiZGViaWFuOjkiLCAicG9ydHMiOiBbIjg5ODM6ODk4MyJdLCAid29ya2luZ19kaXIiOiAie3sgY29udGFpbmVyX3dvcmtpbmdfZGlyIH19IiwgImNvbW1hbmQiOiAie3sgY29udGFpbmVyX3N0YXJ0X2NvbW1hbmQgfX0iLCAicm9sZXMiOiBbInNldHVwIiwgImdlZXJsaW5nZ3V5LmphdmEiLCAiZ2VlcmxpbmdndXkuc29sciJdfV1dLCAic2V0dGluZ3MiOiBbWyJjb25kdWN0b3JfYmFzZSIsICJkZWJpYW46OSJdLCBbInB3ZCIsICIvVXNlcnMvamdlZXJsaW5nL0Ryb3Bib3gvVk1zL2RvY2tlci9zb2xyLWNvbnRhaW5lciJdXSwgInZlcnNpb24iOiAiMiIsICJkZWZhdWx0cyI6IFtbImphdmFfcGFja2FnZXMiLCBbIm9wZW5qZGstOC1qZGsiXV0sIFsic29scl9yZW1vdmVfY3J1ZnQiLCB0cnVlXSwgWyJzb2xyX3ZlcnNpb24iLCAiNi42LjAiXSwgWyJjb250YWluZXJfd29ya2luZ19kaXIiLCAiLyJdLCBbImNvbnRhaW5lcl9zdGFydF9jb21tYW5kIiwgWyIvb3B0L3NvbHIvYmluL3NvbHIiLCAic3RhcnQiLCAiLWYiLCAiLWZvcmNlIl1dXSwgInJlZ2lzdHJpZXMiOiBbWyJkb2NrZXIiLCB7InVybCI6ICJodHRwczovL2RvY2tlci5pbyIsICJuYW1lc3BhY2UiOiAiZ2VlcmxpbmdndXkiLCAicmVwb3NpdG9yeV9wcmVmaXgiOiAiIn1dXX0=', '--encoding', 'b64json'], 'user': 'root', 'volumes': {'solr-container_secrets': {'bind': '/run/secrets', 'mode': 'rw'}, '/var/run/docker.sock': {'bind': '/var/run/docker.sock', 'mode': 'rw'}, '/Users/jgeerling/Dropbox/VMs/docker/solr-container': {'bind': '/src', 'mode': 'ro'}, '/Users/jgeerling/.docker/config.json': {'bind': '/Users/jgeerling/.docker/config.json', 'mode': 'rw'}}, 'detach': True, 'privileged': True}
Parsing conductor CLI args.
2017-07-30T21:40:30.600636 Processing defaults section... [container.config] caller_file=/_ansible/container/config.py caller_func=_process_defaults caller_line=320
2017-07-30T21:40:30.611488 Processing section...          [container.config] caller_file=/_ansible/container/config.py caller_func=_process_top_level_sections caller_line=329 section=volumes
2017-07-30T21:40:30.618407 Processing section...          [container.config] caller_file=/_ansible/container/config.py caller_func=_process_top_level_sections caller_line=329 section=registries
2017-07-30T21:40:30.626980 Processing section...          [container.config] caller_file=/_ansible/container/config.py caller_func=_process_top_level_sections caller_line=329 section=secrets
2017-07-30T21:40:30.631032 Processing service...          [container.config] caller_file=/_ansible/container/config.py caller_func=_process_services caller_line=335 service=u'solr' service_data={u'command': u'{{ container_start_command }}', u'working_dir': u'{{ container_working_dir }}', u'from': u'debian:9', u'ports': [u'8983:8983'], u'roles': [u'setup', u'geerlingguy.java', u'geerlingguy.solr']}
Traceback (most recent call last):
  File "/usr/local/bin/conductor", line 11, in <module>
    load_entry_point('ansible-container', 'console_scripts', 'conductor')()
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/cli.py", line 382, in conductor_commandline
    conductor_config = AnsibleContainerConductorConfig(list_to_ordereddict(containers_config))
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/config.py", line 292, in __init__
    self._process_services()
  File "/_ansible/container/config.py", line 352, in _process_services
    role_metadata = get_metadata_from_role(role_name)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/utils/__init__.py", line 271, in get_metadata_from_role
    return get_content_from_role(role_name, os.path.join('meta', 'container.yml'))
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/utils/__init__.py", line 260, in get_content_from_role
    role_path = resolve_role_to_path(role_name)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/utils/__init__.py", line 209, in resolve_role_to_path
    loader=loader)
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/role/include.py", line 59, in load
    return ri.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/base.py", line 242, in load_data
    ds = self.preprocess_data(ds)
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/role/definition.py", line 94, in preprocess_data
    (role_name, role_path) = self._load_role_path(role_name)
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/role/definition.py", line 187, in _load_role_path
    raise AnsibleError("the role '%s' was not found in %s" % (role_name, ":".join(role_search_paths)), obj=self._ds)
ansible.errors.AnsibleError: the role 'geerlingguy.java' was not found in ./roles:/src/roles:/etc/ansible/roles:.
2017-07-30T16:40:31.119128 Conductor terminated. Cleaning up. [container.docker.engine] caller_file=/Users/jgeerling/Downloads/ansible-container/container/docker/engine.py caller_func=await_conductor_command caller_line=409 command_rc=1 conductor_id=u'0d395a3873e16e3d392095f127ffb374171112fc94b7dd1906cb800256252a45' save_container=False
2017-07-30T16:40:31.859500 Conductor exited with status 1 [container.cli] caller_file=/Users/jgeerling/Downloads/ansible-container/container/cli.py caller_func=__call__ caller_line=303
```

More specifically, it seems this is the error at the end:

```
ansible.errors.AnsibleError: the role 'geerlingguy.java' was not found in ./roles:/src/roles:/etc/ansible/roles:.
```

For reference: https://github.com/geerlingguy/solr-container/issues/10

**Comment by geerlingguy** [comment]
Troubleshooting:

```
git bisect start
git bisect good 9e49bd3 # last known working state locally
git bisect bad 3cb3cdb # HEAD currently
```

(Reinstalled ansible-container with `pip install -e .[docker]` between each commit).

**Comment by geerlingguy** [comment]
Well, now even checking out `9e49bd3`, removing all existing containers and images, and rebuilding isn't working locally :/

**Comment by geerlingguy** [comment]
Ah, I just noticed that in the previous passing build, the roles downloaded inside the container to the path `/etc/ansible/roles/geerlingguy.java`.

The failing builds are downloading the role to `/root/.ansible/roles/geerlingguy.java`.

**Comment by geerlingguy** [comment]
I wonder if the problem is that, now that I'm rebuilding the conductor container, the _conductor_ container is grabbing the latest commit in `develop`, thus I'm unable to build a conductor with the older version of `roles_path`?

Because even going way back to 0.9.1 isn't working. Basically, I can't find a way to get my project to build anymore :/

**Comment by geerlingguy** [comment]
So then, I tried using `ansible-container --debug --var-file vars-6.x.yml build --roles-path 
'/root/.ansible/roles'` (I noticed a new `--roles-path` var was added...), and got:

```
APIError: 502 Server Error: Bad Gateway ("Mounts denied: 
The path /root/.ansible/roles
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
.")
```

Maybe I have a fundamental misunderstanding here... do I have to manually install galaxy requirements before building the container? I thought the conductor did all that for me.

**Comment by marcusianlevine** [comment]
@geerlingguy this is very similar to the issue that was reported and I commented on in #658 

Check out my PR #672 for a quick workaround

**Comment by geerlingguy** [comment]
@marcusianlevine - The weird thing is, I've been testing daily against ansible-container HEAD, and I've had no problems at all until the build on the 26th. It seems like #672 might fix it, but it's still somewhat odd that the actual path where ansible-container used to download the roles was the standard global path (`/etc/ansible/roles`), and now it's local to the root user in the container.

**Comment by j00bar** [comment]
Hey folks... So here's how the code (is supposed to?) work...

When you do an `install`, it spins up an instance of your conductor and runs `ansible-galaxy` install from inside of the conductor. That validates the role reference is good and identifies its dependencies as well. Then it adds, the role to `requirements.yml` and terminates.

Then when you `ansible-container build` after the `install`, the conductor image should get rebuilt because the `Dockerfile` changed. Part of that rebuild is processing `requirements.yml` into the image's `/etc/ansible/roles` directory. Your updated conductor image now has the missing roles.

Take a look in the `--debug build` output at the `Dockerfile` being processed. Is it actually running `ansible-galaxy install -r`?

**Comment by chouseknecht** [comment]
@joobar

During the post-install `build`, it is installing the role. However, in my environment I'm seeing the following:

```
- downloading role 'nginx-container', owned by ansible
- downloading role from https://github.com/ansible/nginx-container/archive/master.tar.gz
- extracting ansible.nginx-container to /root/.ansible/roles/ansible.nginx-container
- ansible.nginx-container (master) was installed successfully
```

It's installing the role to `/root/.ansible/roles`. It completely ignores the `-p`. I think something changed in the `ansible-galaxy` client code. Checking...

**Comment by j00bar** [comment]
That would certainly explain why @geerlingguy believes the old code used to work but now doesn't.

**Comment by geerlingguy** [comment]
Exactly—it is installing all the roles... but it installs them in a path that doesn't seem to work.

Everything was the same leading up to that point, except for the roles being installed in `/root/.ansible/roles` instead of `/etc/ansible/roles` inside the conductor.

**Comment by geerlingguy** [comment]
@chouseknecht++ - builds are passing again: https://travis-ci.org/geerlingguy/solr-container/builds/259507708

**Comment by chouseknecht** [comment]
[PR #27524](https://github.com/ansible/ansible/issues/27524) fixed the role install issue. Roles are now installed to `/etc/ansible/roles`.

#675 Adds mo' betta docs for the `install` command

**Comment by dchsueh** [comment]
would one of you with knowledge of this problem and the fix take a look at https://github.com/ansible/ansible-container/issues/942 please?  same error text output, same behavior that after a certain date a new role cannot be found, all around bizarre...

thank you
