### ISSUE TITLE
Errors setting up ansible-container and running ansible-container build

### ISSUE THREAD

**Issue by emaildano** [ansible/ansible-container#677]
##### ISSUE TYPE
 - Bug Report

##### container.yml 

```
version: "2"
settings:
  conductor_base: centos:7
defaults:
  POSTGRES_USER: django
  POSTGRES_PASSWORD: sesame
  POSTGRES_DB: django
  DJANGO_PORT: 8080
services:
  django:
    from: centos:7
    roles:
      - django-gunicorn
    environment:
      DATABASE_URL: "pgsql://{{ POSTGRES_USER }}:{{ POSTGRES_PASSWORD }}@postgres:5432/{{ POSTGRES_DB }}"
      DJANGO_ROOT: '{{ DJANGO_ROOT }}'
      DJANGO_VENV: '{{ DJANGO_VENV }}'
    links:
    - postgres
    - postgres:postgresql
    ports:
    - '{{ DJANGO_PORT }}'
    working_dir: '{{ DJANGO_ROOT }}'
    user: '{{ DJANGO_USER }}'
    command: ['{{ DJANGO_VENV }}/bin/gunicorn', '-w', '2', '-b', '0.0.0.0:{{ DJANGO_PORT }}', 'project.wsgi:application']
    entrypoint: ['/usr/bin/dumb-init', '/usr/bin/entrypoint.sh']
    volumes:
      - 'static:{{ DJANGO_ROOT }}'
    dev_overrides:
      command: ['{{ DJANGO_VENV }}/bin/python', 'manage.py', 'runserver', '0.0.0.0:{{ DJANGO_PORT }}']
      volumes:
      - '${PWD}:{{ DJANGO_ROOT }}'
      - "static:/static"
      expose:
      - "{{ DJANGO_PORT }}"
      environment:
        DEBUG: "1"
  nginx:
    from: centos:7
    roles:
    - nginx
    ports:
    - '{{ DJANGO_PORT }}:8000'
    user: nginx
    links:
    - django
    command: ['/usr/bin/dumb-init', 'nginx', '-c', '/etc/nginx/nginx.conf']
    volumes:
    - 'static:{{ STATIC_ROOT }}'
    dev_overrides:
      ports: []
      command: /bin/false
      volumes: []
  postgres:
    from: postgres:9.6
    environment:
      POSTGRES_USER: "{{ POSTGRES_USER }}"
      POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"
      POSTGRES_DB: "{{ POSTGRES_DB }}"
volumes:
  static:
    docker: {}
registries: {}

```

##### OS / ENVIRONMENT

```
$ ansible-container --debug version
Ansible Container, version 0.9.1
Darwin, Daniels-MacBook-Pro.local, 16.7.0, Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64, x86_64
2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] /usr/bin/python
ERROR	Unknown exception Error while fetching server API version: ('Connection aborted.', error(2, 'No such file or directory'))	
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/container/cli.py", line 268, in __call__
    getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
  File "/Library/Python/2.7/site-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/container/core.py", line 415, in hostcmd_version
    engine_obj.print_version_info()
  File "/Library/Python/2.7/site-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/container/docker/engine.py", line 181, in print_version_info
    print(json.dumps(self.client.info(), indent=2))
  File "/Library/Python/2.7/site-packages/container/docker/engine.py", line 122, in client
    self._client = docker.from_env(version='auto')
  File "/Library/Python/2.7/site-packages/docker/client.py", line 80, in from_env
    **kwargs_from_env(**kwargs))
  File "/Library/Python/2.7/site-packages/docker/client.py", line 37, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/docker/api/client.py", line 147, in __init__
    self._version = self._retrieve_server_version()
  File "/Library/Python/2.7/site-packages/docker/api/client.py", line 174, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
DockerException: Error while fetching server API version: ('Connection aborted.', error(2, 'No such file or directory'))
```
##### SUMMARY
I'm trying to give ansible-container a try and so far no luck. I can't tell if this is me or the required dependencies are unstable. I've followed the install get started guide a few times, uninstalled, reinstalled, etc.

##### ACTUAL RESULTS

```
$ ansible-container build
Building Docker Engine context...	
Starting Docker build of Ansible Container Conductor image (please be patient)...	
ERROR	Unknown exception	
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/container/cli.py", line 268, in __call__
    getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
  File "/Library/Python/2.7/site-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/container/core.py", line 150, in hostcmd_build
    cache=kwargs['cache']
  File "/Library/Python/2.7/site-packages/container/docker/engine.py", line 82, in __wrapped__
    return fn(self, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/container/docker/engine.py", line 744, in build_conductor_image
    nocache=not cache)
  File "/Library/Python/2.7/site-packages/docker/models/images.py", line 175, in build
    raise BuildError(chunk['error'])
BuildError: The command '/bin/sh -c python /get-pip.py &&     mkdir -p /etc/ansible/roles /_ansible/src &&     cd /usr/local/bin &&     tar -xz --strip-components=1 -f /tmp/docker.tgz' returned a non-zero code: 2
```

**Comment by j00bar** [comment]
Are you sure your Docker daemon is running and properly configured? That the Docker daemon socket can't be found is a bad sign.

**Comment by chouseknecht** [comment]
@emaildano 

Looks like you're on a Mac, and so presumably running Docker machine. Can you run `docker ps` or `docker images`?

**Comment by emaildano** [comment]
`docker ps` returns the following:

```
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

**Comment by chouseknecht** [comment]
Is it possible you have `DOCKER_HOST` set in your environment? That's not typically set on a mac. But, if you're accessing the daemon via TCP, then you would likely have it set.

The default method of accessing the daemon from within the conductor is via `/var/run/docker.sock`. That actually gets mounted to the conductor. 

In your Docker Machine preferences, under File Sharing, you should see the following volumes:

```
/Users
/Volumes
/tmp
/private
```
If `/private` is missing, that might explain what's going on. Without it, the conductor won't have access to `/var/run/docker.sock`, as `/var` is sym linked to `/private`.

**Comment by Demonsthere** [comment]
If you run it on Mac, try to install the 0.9.2 version from the develop branch by compiling it manually. 
https://docs.ansible.com/ansible-container/installation.html#running-from-source

**Comment by zamoose** [comment]
This is an issue with `COPY` vs. `ADD`. `ADD` does an implicit untar/ungzip operation, making `/tmp/docker.tgz` a directory, which also makes the `tar -xf` fail. I encountered the exact same thing on my Mac.

**Comment by emaildano** [comment]
@zamoose Thanks! Philly local to the rescue.

**Comment by bmcgair** [comment]
This is still broken on mac with ansible-container 0.9.2 even after factory reset of docker, and using an ansible supplied example. 

Building Docker Engine context...	
Starting Docker build of Ansible Container Conductor image (please be patient)...	
ERROR	Unknown exception	
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/container/cli.py", line 299, in __call__
    getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
  File "/usr/local/lib/python2.7/site-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/container/core.py", line 181, in hostcmd_build
    environment=env_vars
  File "/usr/local/lib/python2.7/site-packages/container/docker/engine.py", line 105, in __wrapped__
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/container/docker/engine.py", line 1070, in build_conductor_image
    return image.id
AttributeError: 'tuple' object has no attribute 'id'

**Comment by marcusianlevine** [comment]
@bmcgair that is a different issue, see #869
