### ISSUE TITLE
ERROR	Unknown exception

### ISSUE THREAD

**Issue by basictheprogram** [ansible/ansible-container#680]
##### ISSUE TYPE

 - Bug Report

##### container.yml 

```
version: "2"
defaults:
  keep_deb_src: false
  keep_build_essentials: false
settings:
  conductor:
    base: ubuntu
    volumes: [/Users/tanner/projects/ansible.git/playbooks.git/roles:/etc/ansible/roles:ro]
  project_name: dev
services:
  apache2-servers:
    from: ubuntu
    roles:
      - { role: postfix-satellite }
registries: {}
```

##### OS / ENVIRONMENT

```
$ ansible-container --debug version
Ansible Container, version 0.9.2rc0
Darwin, alliance.local, 16.6.0, Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64, x86_64
2.7.10 (default, Feb  7 2017, 00:08:15)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] /Users/tanner/projects/ansible.git/bin/python
{
  "ContainersPaused": 0,
  "Labels": null,
  "CgroupDriver": "cgroupfs",
  "ContainersRunning": 1,
  "ContainerdCommit": {
    "Expected": "3addd840653146c90a254301d6c3a663c7fd6429",
    "ID": "3addd840653146c90a254301d6c3a663c7fd6429"
  },
  "InitBinary": "docker-init",
  "NGoroutines": 38,
  "Swarm": {
    "ControlAvailable": false,
    "NodeID": "",
    "Error": "",
    "RemoteManagers": null,
    "LocalNodeState": "inactive",
    "NodeAddr": ""
  },
  "LoggingDriver": "json-file",
  "OSType": "linux",
  "HttpProxy": "",
  "Runtimes": {
    "runc": {
      "path": "docker-runc"
    }
  },
  "DriverStatus": [
    [
      "Backing Filesystem",
      "extfs"
    ],
    [
      "Supports d_type",
      "true"
    ],
    [
      "Native Overlay Diff",
      "true"
    ]
  ],
  "OperatingSystem": "Alpine Linux v3.5",
  "Containers": 31,
  "HttpsProxy": "",
  "BridgeNfIp6tables": true,
  "MemTotal": 2095882240,
  "SecurityOptions": [
    "name=seccomp,profile=default"
  ],
  "Driver": "overlay2",
  "IndexServerAddress": "https://index.docker.io/v1/",
  "ClusterStore": "",
  "InitCommit": {
    "Expected": "949e6fa",
    "ID": "949e6fa"
  },
  "Isolation": "",
  "SystemStatus": null,
  "OomKillDisable": true,
  "ClusterAdvertise": "",
  "SystemTime": "2017-08-05T23:57:12.76726973Z",
  "Name": "moby",
  "CPUSet": true,
  "RegistryConfig": {
    "AllowNondistributableArtifactsCIDRs": [],
    "Mirrors": [],
    "IndexConfigs": {
      "docker.io": {
        "Official": true,
        "Name": "docker.io",
        "Secure": true,
        "Mirrors": []
      }
    },
    "AllowNondistributableArtifactsHostnames": [],
    "InsecureRegistryCIDRs": [
      "127.0.0.0/8"
    ]
  },
  "DefaultRuntime": "runc",
  "ContainersStopped": 30,
  "NCPU": 4,
  "NFd": 26,
  "Architecture": "x86_64",
  "KernelMemory": true,
  "CpuCfsQuota": true,
  "Debug": true,
  "ID": "SJPY:DOQH:RM2R:4YZ4:RA53:KJYW:G7JV:5YLB:NETC:W5GZ:TYA7:4T3K",
  "IPv4Forwarding": true,
  "KernelVersion": "4.9.38-moby",
  "BridgeNfIptables": true,
  "NoProxy": "",
  "LiveRestoreEnabled": false,
  "ServerVersion": "17.07.0-ce-rc1",
  "CpuCfsPeriod": true,
  "ExperimentalBuild": true,
  "MemoryLimit": true,
  "SwapLimit": true,
  "Plugins": {
    "Volume": [
      "local"
    ],
    "Network": [
      "bridge",
      "host",
      "ipvlan",
      "macvlan",
      "null",
      "overlay"
    ],
    "Authorization": null,
    "Log": [
      "awslogs",
      "fluentd",
      "gcplogs",
      "gelf",
      "journald",
      "json-file",
      "logentries",
      "splunk",
      "syslog"
    ]
  },
  "Images": 3,
  "DockerRootDir": "/var/lib/docker",
  "NEventsListener": 1,
  "CPUShares": true,
  "RuncCommit": {
    "Expected": "2d41c047c83e09a6d61d464906feb2a2f3c52aa4",
    "ID": "2d41c047c83e09a6d61d464906feb2a2f3c52aa4"
  }
}
{
  "KernelVersion": "4.9.38-moby",
  "Arch": "amd64",
  "BuildTime": "2017-07-26T05:25:01.392492215+00:00",
  "ApiVersion": "1.31",
  "Version": "17.07.0-ce-rc1",
  "MinAPIVersion": "1.12",
  "GitCommit": "8c4be39",
  "Os": "linux",
  "Experimental": true,
  "GoVersion": "go1.8.3"
}
```
##### SUMMARY

Random failure of ansible-container

##### STEPS TO REPRODUCE

```
ansible-container --vars-files ~/projects/bootstrap.yml   --debug build
```

##### EXPECTED RESULTS

ansible-container would successfully complete

##### ACTUAL RESULTS

Not sure what's out of disk space?

My local computer
```
$ df -ha
Filesystem                          Size   Used  Avail Capacity iused      ifree %iused  Mounted on
/dev/disk1                         931Gi  594Gi  337Gi    64% 2937282 4292029997    0%   /
```

```
<snip>
Step 3/11 : RUN apt-get update -y &&     apt-get install -y make gcc python2.7 git python-dev curl rsync libffi-dev libssl-dev dpkg-dev python-apt libpopt0 &&     cd /usr/bin &&     rm -f lsb_release &&     ln -fs python2.7 python &&     apt-get clean
Err:4 http://security.ubuntu.com/ubuntu xenial-security/universe Sources
  Error writing to output file - write (28: No space left on device) Error writing to file - write (28: No space left on device) [IP: 91.189.91.26 80]
<snip>
Err:18 http://archive.ubuntu.com/ubuntu xenial/universe Sources
  Error writing to output file - write (28: No space left on device) Error writing to file - write (28: No space left on device) [IP: 91.189.88.162 80]
<snip>
Err:36 http://archive.ubuntu.com/ubuntu xenial-backports/main amd64 Packages
  Error writing to output file - write (28: No space left on device) Error writing to file - write (28: No space left on device) [IP: 91.189.88.162 80]
<snip>
W: The repository 'http://archive.ubuntu.com/ubuntu xenial-backports Release' does not have a Release file.
E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/universe/source/Sources  Error writing to output file - write (28: No space left on device) Error writing to file - write (28: No space left on device) [IP: 91.189.91.26 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/universe/source/Sources  Error writing to output file - write (28: No space left on device) Error writing to file - write (28: No space left on device) [IP: 91.189.88.162 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/universe/source/Sources  Error writing to output file - write (28: No space left on device) Error writing to file - write (28: No space left on device) [IP: 91.189.88.162 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-backports/main/binary-amd64/Packages  Error writing to output file - write (28: No space left on device) Error writing to file - write (28: No space left on device) [IP: 91.189.88.162 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
<snip>
Unknown exception Error building conductor image: The command '/bin/sh -c apt-get update -y &&     apt-get install -y make gcc python2.7 git python-dev curl rsync libffi-dev libssl-dev dpkg-dev python-apt libpopt0 &&     cd /usr/bin &&     rm -f lsb_release &&     ln -fs python2.7 python &&     apt-get clean' returned a non-zero code: 100ESC[0m [ESC[34mESC[1mcontainer.cliESC[0m] ESC[36mcaller_fileESC[0m=ESC[35m/Users/tanner/projects/ansible.git/lib/python2.7/site-packages/structlog/stdlib.pyESC[0m ESC[36mcaller_funcESC[0m=ESC[35mexceptionESC[0m ESC[36mcaller_lineESC[0m=ESC[35m95ESC[0m
Traceback (most recent call last):
  File "/Users/tanner/projects/ansible.git/ansible-container/container/cli.py", line 291, in __call__
    getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
  File "/Users/tanner/projects/ansible.git/ansible-container/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/Users/tanner/projects/ansible.git/ansible-container/container/core.py", line 146, in hostcmd_build
    cache=conductor_cache
  File "/Users/tanner/projects/ansible.git/ansible-container/container/docker/engine.py", line 87, in __wrapped__
    return fn(self, *args, **kwargs)
  File "/Users/tanner/projects/ansible.git/ansible-container/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/Users/tanner/projects/ansible.git/ansible-container/container/docker/engine.py", line 910, in build_conductor_image
    "Error building conductor image: {0}".format(line_json['errorDetail']['message']))
AnsibleContainerException: Error building conductor image: The command '/bin/sh -c apt-get update -y &&     apt-get install -y make gcc python2.7 git python-dev curl rsync libffi-dev libssl-dev dpkg-dev python-apt libpopt0 &&     cd /usr/bin &&     rm -f lsb_release &&     ln -fs python2.7 python &&     apt-get clean' returned a non-zero code: 100
```

**Comment by chouseknecht** [comment]
@basictheprogram 

I think I ran into this before when I had a large number of docker volumes. What do you see when you run `docker volume ls`?

**Comment by basictheprogram** [comment]
> On Aug 7, 2017, at 11:08 AM, Chris Houseknecht <notifications@github.com> wrote:
> 
> I think I ran into this before when I had a large number of docker volumes. What do you see when you run docker volume ls?
> 
> 


$ docker volume ls | wc -l
     234

I assume listing all 234 here isn’t necessary?

How do I prune or purge this?


--
Bob Tanner <tanner@real-time.com>                                 | Phone : 952-943-8700
http://www.real-time.com, Linux, OSX, VMware, Windows | Fax      : 952-943-8500
Key fingerprint = 9906 320A 8BB6 64AD 96A7  7785 CBFB 10BF 568B F98C

**Comment by chouseknecht** [comment]
Try: 

```
docker volume rm --force $(docker volume ls -q)
```

**Comment by chouseknecht** [comment]
@basictheprogram 

Have you had a chance to clear out the excess volumes? Wondering if we can close this.

**Comment by basictheprogram** [comment]
docker volume rm --force $(docker volume ls -q) fixes the problem.

Thanks.
