### ISSUE TITLE
Empty service environment key results in an exception

### ISSUE THREAD

**Issue by shalomb** [ansible/ansible-container#691]
##### ISSUE TYPE

 - Bug Report

##### container.yml 

```
...services:
  web:
    from: "debian:latest"
    environment:
      #-  http_proxy={{ proxy_url }}
      #- https_proxy={{ proxy_url }}
      #-   ftp_proxy={{ proxy_url }}
      #-    no_proxy='localhost'
...

```

##### OS / ENVIRONMENT

```
0.9.1
```
##### SUMMARY

An empty `environment` key results in an exception being thrown - it would nice for `ansible-container` to warn (or fail-early) should the user accidentally have a `container.yml` like this (in my case, I was debugging an issue and only commented out the keys under the service's `environment`)
```
Applied role to service role=ansible-java service=web
Traceback (most recent call last):
  File "/usr/local/bin/conductor", line 11, in <module>
    load_entry_point('ansible-container', 'console_scripts', 'conductor')()
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/cli.py", line 360, in conductor_commandline
    **params)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/core.py", line 738, in conductorcmd_build
    with_name=is_last_role)
  File "/_ansible/container/docker/engine.py", line 82, in __wrapped__
    return fn(self, *args, **kwargs)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/docker/engine.py", line 501, in commit_role_as_layer
    image_config = utils.metadata_to_image_config(metadata)
  File "/_ansible/container/utils/__init__.py", line 150, in metadata_to_image_config
    config[key] = (translator(metadata[metadata_key]) if translator
  File "/_ansible/container/utils/__init__.py", line 110, in format_environment
    to_return.update(environment)
TypeError: 'NoneType' object is not iterable
```
##### STEPS TO REPRODUCE

```

```

##### EXPECTED RESULTS

A warning would have been better to catch the issue early. Something along the lines of ..

```
 ERROR   Invalid container.yml: empty key 'environment' for service 'web' ..
```

##### ACTUAL RESULTS

```

```

**Comment by chouseknecht** [comment]
@shalomb 

Thanks for using Ansible Container! And, nice catch! Appreciate you taking the time to report this.

**Comment by morganchristiansson** [comment]
I can report this error too. ```ansible-container init``` did not include this key in the example (except under dev_overrides)
