### ISSUE TITLE
GET_URL inconsistent timeout

### ISSUE THREAD

**Issue by bearrito** [ansible/ansible-container#697]
The issue occurs 70% of the time.

I can download the url with no problem from the host.

##### ISSUE TYPE

 - Bug Report

##### OS / ENVIRONMENT
Ansible Container, version 0.9.1
Linux, gucamole, 3.19.0-80-generic, #88~14.04.1-Ubuntu SMP Fri Jan 13 14:54:07 UTC 2017, x86_64
2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] /home/barrett/.virtualenvs/ansible/bin/python

##### SUMMARY
get_url timesout when running in ac

##### STEPS TO REPRODUCE

```

```

##### EXPECTED RESULTS
The file to be downloaded

##### ACTUAL RESULTS
Timeout

```
TASK [flume : Download Required Files] *****************************************
failed: [web] (item={u'url': u'http://www.apache.org/dist/flume/1.7.0/apache-flume-1.7.0-bin.tar.gz', u'dest': u'/opt/apache-flume-1.7.0-bin.tar.gz', u'checksum': u'sha1:845f69165d09538330c7a67b15dc4325958b1efc'}) => {"failed": true, "item": {"checksum": "sha1:845f69165d09538330c7a67b15dc4325958b1efc", "dest": "/opt/apache-flume-1.7.0-bin.tar.gz", "url": "http://www.apache.org/dist/flume/1.7.0/apache-flume-1.7.0-bin.tar.gz"}, "msg": "failed to create temporary content file: timed out"}
	to retry, use: --limit @/tmp/tmpXuEUOS/playbook.retry

PLAY RECAP *********************************************************************
web                        : ok=8    changed=6    unreachable=0    failed=1

ERROR	Error applying role!	engine=<container.docker.engine.Engine object at 0x7f9ecb7d3990> exit_code=2 playbook=[{'hosts': u'web', 'roles': ['flume'], 'vars': {}}]
Traceback (most recent call last):
  File "/usr/local/bin/conductor", line 11, in <module>
    load_entry_point('ansible-container', 'console_scripts', 'conductor')()
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/cli.py", line 360, in conductor_commandline
    **params)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/core.py", line 724, in conductorcmd_build
    raise RuntimeError('Build failed.')
RuntimeError: Build failed.
Conductor terminated. Cleaning up.	command_rc=1 conductor_id=78ce52569af5316a21ac45e24126ee4c171120c09118955844817571260fbd07 save_container=False
ERROR	Conductor exited with status 1
```

**Comment by chouseknecht** [comment]
@bearrito 

Thank you for using Ansible Container. We appreciate your feedback!

Would it be possible to provide a copy of the `container.yml` file and any role task details that might help us recreate the issue you're seeing.
Also, noticing that the error message is `msg: failed to create temporary content file: timed out`. It leads me to think that there is some sort of I/O issue happening when the `get_url` module attempts to write to temporary space. Maybe there isn't any temporary space, or maybe it takes too long to allocate. Not sure. Would be worth running the build with `--debug` to see if you can get any additional stacktrace info from the playbook.

**Comment by bearrito** [comment]
I'll re-run with more --debug flag later. 

Note, this is a known issue in regular ansible, so I'm not sure where fault lies, but I found it in ac.

```
version: "2"
settings:
  conductor_base: ubuntu:xenial
services:
  web:
    from: ubuntu:xenial
    roles:
      - container_base
      - flume
    ports:
      - "8443:443"
    command: ['/srv/bin/start.sh']
    dev_overrides:
      environment:
        - "DEBUG=1"
    k8s:
      state: present
      service:
        type: LoadBalancer
      deployment:
        replicas: 2
```

```

- name: Download Required Files
  get_url:
    force: no
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    owner: "{{ flume_user }}"
    group: "{{ flume_group }}"
    checksum: "{{ item.checksum }}"
    timeout: 60
  with_items: "{{ required_files }}"

```
