### ISSUE TITLE
Give nicer error message if docker daemon isn't running

### ISSUE THREAD

**Issue by imphil** [ansible/ansible-container#710]
##### ISSUE TYPE
 - Feature Idea (low priority)

When the docker engine isn't running I get the following output when running `ansible-container build`:
~~~
$ ansible-container --var-file vars.yml build 
ERROR   Unknown exception
Traceback (most recent call last):
  File "xxx/venv/lib/python2.7/site-packages/container/cli.py", line 268, in __call__
    getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
  File "xxx/venv/lib/python2.7/site-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "xxx/venv/lib/python2.7/site-packages/container/core.py", line 139, in hostcmd_build
    conductor_container_id = engine_obj.get_container_id_for_service('conductor')
  File "xxx/venv/lib/python2.7/site-packages/container/docker/engine.py", line 380, in get_container_id_for_service
    container_info = self.client.containers.get(self.container_name_for_service(service_name))
  File "xxx/venv/lib/python2.7/site-packages/container/docker/engine.py", line 122, in client
    self._client = docker.from_env(version='auto')
  File "xxx/venv/lib/python2.7/site-packages/docker/client.py", line 80, in from_env
    **kwargs_from_env(**kwargs))
  File "xxx/venv/lib/python2.7/site-packages/docker/client.py", line 37, in __init__
    self.api = APIClient(*args, **kwargs)
  File "xxx/venv/lib/python2.7/site-packages/docker/api/client.py", line 147, in __init__
    self._version = self._retrieve_server_version()
  File "xxx/venv/lib/python2.7/site-packages/docker/api/client.py", line 174, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
DockerException: Error while fetching server API version: ('Connection aborted.', error(2, 'No such file or directory'))
~~~

Actually, the error is easily resolved: `systemctl start docker` and everything works. If you have a spare cycle, maybe the error message could be made a more obvious hint what's going on?

**Comment by chouseknecht** [comment]
@imphil

Thanks for using Ansible Container, and for taking the time to share your feedback. 

We should definitely clean this up.

Thanks!

**Comment by gerl1ng** [comment]
Got a similar error message on a new user without correct permissions.
ErrorMessage was
`ErrorMessage: Error while fetching server API version: ('Connection aborted.', error(13, 'Permission denied'))`

Already worked on this and will submit a merge request soon.

**Comment by superscott** [comment]
+1 for running into this and not realizing docker was not running (and then feeling dumb when i found this issue).


`DockerException: Error while fetching server API version`
```
docker --version
Docker version 18.02.0-ce-rc2, build f968a2c

Ansible Container, version 0.9.2
```
