### ISSUE TITLE
Trying to download dependencies for mediadrop.video using "python setup.py develop" on ubuntu 14.04 and this is what I get. Can anyone help?

### ISSUE THREAD

**Issue by njmulhsn** [ansible/ansible-container#714]
Download error on http://static.mediadrop.video/dependencies/dev/: hostname 'static.mediadrop.video' doesn't match 'dev.mediadrop.video' -- Some packages may not be found!

Note: Bypassing https://pypi.python.org/simple/PasteScript/ (disallowed host; see http://bit.ly/1dg9ijs for details).

Couldn't find index page for 'PasteScript' (maybe misspelled?)

Note: Bypassing https://pypi.python.org/simple/ (disallowed host; see http://bit.ly/1dg9ijs for details).

No local packages or download links found for PasteScript>=1.7.4.2
Traceback (most recent call last):
  File "setup.py", line 106, in <module>
    **extra_arguments_for_setup
  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/najam/venv/local/lib/python2.7/site-packages/setuptools/dist.py", line 239, in __init__
    self.fetch_build_eggs(attrs.pop('setup_requires'))
  File "/home/najam/venv/local/lib/python2.7/site-packages/setuptools/dist.py", line 264, in fetch_build_eggs
    replace_conflicting=True
  File "/home/najam/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 580, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/home/najam/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 818, in best_match
    return self.obtain(req, installer) # try and download/install
  File "/home/najam/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 830, in obtain
    return installer(requirement)
  File "/home/najam/venv/local/lib/python2.7/site-packages/setuptools/dist.py", line 314, in fetch_build_egg
    return cmd.easy_install(req)
  File "/home/najam/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 587, in easy_install
    raise DistutilsError(msg)
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('PasteScript>=1.7.4.2')

**Comment by chouseknecht** [comment]
@njmulhsn 

Thanks for taking the time to open an issue. We always appreciate feedback. 

Is this issue related to Ansible Container? If so, can you please provide the following so that we can reproduce, and hopefully solve the problem you're experiencing:

- A copy of your `container.yml` with any sensitive data (i.e. usernames, passwords, etc.) removed
- A copy of the Ansible role your attempting to run, or at least enough task-level information to help with troubleshooting. 

Thanks!

**Comment by DavidFBakker** [comment]
Add
,*.python.org
to the end of allow_hosts in your setup.cfg file
