### ISSUE TITLE
docker-credential-osxkeychain not installed on build

### ISSUE THREAD

**Issue by mastermindg** [ansible/ansible-container#722]
##### ISSUE TYPE
 - Bug Report

##### container.yml 
```
version: "2"
services:
   web:
     from: "centos/7"
     roles: 
       - apache
     ports:
       - "80:80"

registries: {}
```

##### OS / ENVIRONMENT
```
Ansible Container, version 0.9.1
Darwin, Kenneths-MacBook-Pro.local, 15.6.0, Darwin Kernel Version 15.6.0: Sun Jun  4 21:43:07 PDT 2017; root:xnu-3248.70.3~1/RELEASE_X86_64, x86_64
2.7.13 (default, Jul 18 2017, 09:16:53)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] /usr/local/opt/python/bin/python2.7
{
  "ContainersPaused": 0,
  "Labels": null,
  "DefaultRuntime": "runc",
  "CgroupDriver": "cgroupfs",
  "ContainersRunning": 0,
  "NGoroutines": 29,
  "Swarm": {
    "Managers": 0,
    "ControlAvailable": false,
    "NodeID": "",
    "Cluster": {
      "Spec": {
        "Raft": {},
        "CAConfig": {},
        "Dispatcher": {},
        "Orchestration": {},
        "TaskDefaults": {}
      },
      "Version": {},
      "ID": "",
      "CreatedAt": "0001-01-01T00:00:00Z",
      "UpdatedAt": "0001-01-01T00:00:00Z"
    },
    "Nodes": 0,
    "Error": "",
    "RemoteManagers": null,
    "LocalNodeState": "inactive",
    "NodeAddr": ""
  },
  "LoggingDriver": "json-file",
  "OSType": "linux",
  "HttpProxy": "",
  "Runtimes": {
    "runc": {
      "path": "docker-runc"
    }
  },
  "DriverStatus": [
    [
      "Root Dir",
      "/var/lib/docker/aufs"
    ],
    [
      "Backing Filesystem",
      "extfs"
    ],
    [
      "Dirs",
      "602"
    ],
    [
      "Dirperm1 Supported",
      "true"
    ]
  ],
  "OperatingSystem": "Alpine Linux v3.4",
  "Containers": 21,
  "HttpsProxy": "",
  "BridgeNfIp6tables": true,
  "MemTotal": 2094661632,
  "Driver": "aufs",
  "IndexServerAddress": "https://index.docker.io/v1/",
  "ClusterStore": "",
  "ExecutionDriver": "",
  "SystemStatus": null,
  "OomKillDisable": true,
  "ClusterAdvertise": "",
  "SystemTime": "2017-09-09T19:28:49.640461861Z",
  "Name": "moby",
  "CPUSet": true,
  "RegistryConfig": {
    "InsecureRegistryCIDRs": [
      "127.0.0.0/8"
    ],
    "IndexConfigs": {
      "registry.service.kensnet.priv": {
        "Official": false,
        "Name": "registry.service.kensnet.priv",
        "Secure": false,
        "Mirrors": []
      },
      "docker.io": {
        "Official": true,
        "Name": "docker.io",
        "Secure": true,
        "Mirrors": null
      }
    },
    "Mirrors": null
  },
  "SecurityOptions": [
    "seccomp"
  ],
  "ContainersStopped": 21,
  "NCPU": 4,
  "NFd": 17,
  "Architecture": "x86_64",
  "KernelMemory": false,
  "CpuCfsQuota": true,
  "Debug": true,
  "ID": "Z43O:RM35:PACR:G4KW:422J:IDAU:R6UC:MWHM:DZWI:GLW3:LPR7:J4BK",
  "IPv4Forwarding": true,
  "KernelVersion": "4.4.41-moby",
  "BridgeNfIptables": true,
  "NoProxy": "*.local, 169.254/16",
  "LiveRestoreEnabled": false,
  "ServerVersion": "1.12.6",
  "CpuCfsPeriod": true,
  "ExperimentalBuild": false,
  "MemoryLimit": true,
  "SwapLimit": true,
  "Plugins": {
    "Volume": [
      "local"
    ],
    "Network": [
      "bridge",
      "host",
      "null",
      "overlay"
    ],
    "Authorization": null
  },
  "Images": 712,
  "DockerRootDir": "/var/lib/docker",
  "NEventsListener": 1,
  "CPUShares": true
}
{
  "KernelVersion": "4.4.41-moby",
  "Os": "linux",
  "BuildTime": "2017-01-11T00:23:16.798962489+00:00",
  "ApiVersion": "1.24",
  "Version": "1.12.6",
  "GitCommit": "78d1802",
  "Arch": "amd64",
  "GoVersion": "go1.6.4"
}
```
##### SUMMARY
I verified that the issue has not been reported to this repo. This is my first time using ansible-container. I just installed it today.

##### STEPS TO REPRODUCE
1) ansbile-container init
2) Replace container.yml with above code
3) ansible-container build

##### EXPECTED RESULTS
I expect this command to build an image from centos/7 and the apache role.
##### ACTUAL RESULTS
The build failed with an error:

```
Building Docker Engine context...
Starting Docker build of Ansible Container Conductor image (please be patient)...
ERROR	Unknown exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/container/cli.py", line 268, in __call__
    getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
  File "/usr/local/lib/python2.7/site-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/container/core.py", line 150, in hostcmd_build
    cache=kwargs['cache']
  File "/usr/local/lib/python2.7/site-packages/container/docker/engine.py", line 82, in __wrapped__
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/container/docker/engine.py", line 744, in build_conductor_image
    nocache=not cache)
  File "/usr/local/lib/python2.7/site-packages/docker/models/images.py", line 168, in build
    resp = self.client.api.build(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/docker/api/build.py", line 238, in build
    self._set_auth_headers(headers)
  File "/usr/local/lib/python2.7/site-packages/docker/api/build.py", line 285, in _set_auth_headers
    self._auth_configs, registry
  File "/usr/local/lib/python2.7/site-packages/docker/auth.py", line 97, in resolve_authconfig
    authconfig, registry, store_name
  File "/usr/local/lib/python2.7/site-packages/docker/auth.py", line 142, in _resolve_authconfig_credstore
    'Credentials store error: {0}'.format(repr(e))
DockerException: Credentials store error: StoreError('docker-credential-osxkeychain not installed or not available in PATH',)
```

**Comment by chouseknecht** [comment]
@mastermindg 

If you're using Docker Machine, you might try disabling the `securely store Docker logins in macOS keychain` option under Preferences. 

Also, check your `~/.docker/config.json` file to see if it's pointing at the macOS keychain. If it is, you'll need to temporarily disable this by either modifying the file, or removing it all together.

**Comment by mastermindg** [comment]
That was it. I had a remnant in my config.json. I removed it and that fixed it.
