### ISSUE TITLE
Tracking Pre-baked image RH Security Scan and push to Container Catalog

### ISSUE THREAD

**Issue by chouseknecht** [ansible/ansible-container#725]
Internal doc on how to build a RHEL V7 VM with scanner here: https://git.iam.redhat.com/iam/RHC4TP_scanning_plugin

**Comment by chouseknecht** [comment]
Steps to create an RHEL 7 VM on AWS

- Image ID for RHEL 7.2 in us-east-1: ami-a8d369c0 
- Log in as `ec2-user`

As `root`:
- Set `enabled=1` in `/etc/yum/pluginconf.d/subscription-manager.conf`
- `subscription-manager register`. Log in with RH dev credentials.
- `yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm`
- `subscription-manager attach --auto`
- `yum-config-manager --enable rhui-REGION-client-config-server-7`
- `yum-config-manager --enable rhui-REGION-rhel-server-extras`
- `yum-config-manager --enable rhui-REGION-rhel-server-optional`
- `yum-config-manager --enable rhui-REGION-rhel-server-releases`
- `yum-config-manager --enable rhui-REGION-rhel-server-rh-common`
- `yum-config-manager --enable rhui-REGION-rhel-server-supplementary`
- `yum -y install docker atomic git unzip`

Post install of Docker: 
As `root`: 
- groupadd docker 
- usermod -a -G docker ec2-user 
- systemctl restart docker
- log out of ec2-user

As `ec2-user`, build the plugin:

- Copy the plugin project 
- From the project directory, run the `docker build` command per instructions

**Comment by chouseknecht** [comment]
First scan attempt. Running into:

```
Traceback (most recent call last):
  File "/usr/bin/atomic", line 31, in <module>
    import docker
  File "/usr/lib/python2.7/site-packages/docker/__init__.py", line 6, in <module>
    from .client import Client, AutoVersionClient, from_env # flake8: noqa
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 11, in <module>
    from . import api
  File "/usr/lib/python2.7/site-packages/docker/api/__init__.py", line 2, in <module>
    from .build import BuildApiMixin
  File "/usr/lib/python2.7/site-packages/docker/api/build.py", line 9, in <module>
    from .. import utils
  File "/usr/lib/python2.7/site-packages/docker/utils/__init__.py", line 2, in <module>
    from .utils import (
  File "/usr/lib/python2.7/site-packages/docker/utils/utils.py", line 19, in <module>
    from .. import tls
  File "/usr/lib/python2.7/site-packages/docker/tls.py", line 5, in <module>
    from .ssladapter import ssladapter
  File "/usr/lib/python2.7/site-packages/docker/ssladapter/__init__.py", line 1, in <module>
    from .ssladapter import SSLAdapter # flake8: noqa
  File "/usr/lib/python2.7/site-packages/docker/ssladapter/ssladapter.py", line 22, in <module>
    urllib3.connection.match_hostname = match_hostname
AttributeError: 'module' object has no attribute 'connection'
```
Fix: 

- `yum install python-pip`
- `pip install --upgrade urllib3`

**Comment by chouseknecht** [comment]
Use `sudo` to install the plugin. 
Run the scan:
```
$ sudo atomic --debug scan --scanner plugin docker.io/ansible/container-conductor-centos-7:0.9.2rc0
```

Results in:

```
Created /run/atomic/2017-09-13-12-11-56-478754
create() takes exactly 3 arguments (2 given)
Traceback (most recent call last):
  File "/bin/atomic", line 185, in <module>
    sys.exit(_func())
  File "/usr/lib/python2.7/site-packages/Atomic/scan.py", line 133, in scan
    self.scan_list = self._get_scan_list()
  File "/usr/lib/python2.7/site-packages/Atomic/scan.py", line 215, in _get_scan_list
    _, scan_obj = beu.get_backend_and_image_obj(scan_target)
  File "/usr/lib/python2.7/site-packages/Atomic/backendutils.py", line 94, in get_backend_and_image_obj
    img_obj = be.has_image(img)
  File "/usr/lib/python2.7/site-packages/Atomic/backends/_ostree.py", line 79, in has_image
    if self.syscontainers.has_image(img):
  File "/usr/lib/python2.7/site-packages/Atomic/syscontainers.py", line 1746, in has_image
    repo = self._get_ostree_repo()
  File "/usr/lib/python2.7/site-packages/Atomic/syscontainers.py", line 922, in _get_ostree_repo
    repo.create(OSTree.RepoMode.BARE)
  File "/usr/lib64/python2.7/site-packages/gi/types.py", line 113, in function
    return info.invoke(*args, **kwargs)
TypeError: create() takes exactly 3 arguments (2 given)
```

Sent an email to Dustin Minnich looking for some help with this.

**Comment by chouseknecht** [comment]
Thanks to Dustin, got the scanner working. 

I can successfully scan a RHEL image using the delivered openscap plugin:

```
# atomic scan --plugin openscap registry.access.redhat.com/rhel7
atomic: unrecognized arguments: --plugin
Try 'atomic --help' for more information.
[root@ip-10-0-10-247 ~]# atomic --debug scan --scanner openscap registry.access.redhat.com/rhel7
Created /run/atomic/2017-09-14-13-53-44-546683
docker run -t --rm -v /etc/localtime:/etc/localtime -v /run/atomic/2017-09-14-13-53-44-546683:/scanin -v /var/lib/atomic/openscap/2017-09-14-13-53-44-546683:/scanout:rw,Z -v /etc/oscapd:/etc/oscapd:ro registry.access.redhat.com/rhel7/openscap oscapd-evaluate scan --no-standard-compliance --targets chroots-in-dir:///scanin --output /scanout -j1
Created /run/atomic/2017-09-14-13-53-44-546683/4a974767fba69453003f076889906df7531ecdff0a0190797aec49387108fffc
Mounted 4a974767fba69453003f076889906df7531ecdff0a0190797aec49387108fffc to /run/atomic/2017-09-14-13-53-44-546683/4a974767fba69453003f076889906df7531ecdff0a0190797aec49387108fffc
Creating the output dir at /var/lib/atomic/openscap/2017-09-14-13-53-44-546683
INFO:OpenSCAP Daemon one-off evaluator 0.1.6
INFO:Autodetected "oscap" in path "/usr/bin/oscap".
INFO:Autodetected "oscap-ssh" in path "/usr/bin/oscap-ssh".
INFO:Autodetected "oscap-vm" in path "/usr/bin/oscap-vm".
INFO:Autodetected "oscap-docker" in path "/usr/bin/oscap-docker".
INFO:Autodetected "oscap-chroot" in path "/usr/bin/oscap-chroot".
WARNING:Can't import the 'docker' package. Container scanning functionality will be disabled.
INFO:Autodetected SCAP content at "/usr/share/openscap/cpe/openscap-cpe-oval.xml".
INFO:Autodetected SCAP content in path "/usr/share/xml/scap/ssg/content".
INFO:Creating tasks directory at '/var/lib/oscapd/tasks' because it didn't exist.
INFO:Creating results directory at '/var/lib/oscapd/results' because it didn't exist.
INFO:Creating results work in progress directory at '/var/lib/oscapd/work_in_progress' because it didn't exist.
INFO:Evaluated EvaluationSpec, exit_code=0.
INFO:Had a local version of /var/lib/oscapd/cve_feeds/com.redhat.rhsa-RHEL7.xml but it wasn't new enough
INFO:Evaluated EvaluationSpec, exit_code=0.
INFO:[100.00%] Scanned target 'chroot:///scanin/4a974767fba69453003f076889906df7531ecdff0a0190797aec49387108fffc'

registry.access.redhat.com/rhel7 (4a974767fba6945)

registry.access.redhat.com/rhel7 passed the scan

Files associated with this scan are in /var/lib/atomic/openscap/2017-09-14-13-53-44-546683.

Unmounted /run/atomic/2017-09-14-13-53-44-546683/4a974767fba69453003f076889906df7531ecdff0a0190797aec49387108fffc
```

However, when I attempt to scan our CentOS image, I get the following:
```
# atomic --debug scan --scanner openscap ansible/container-conductor-centos-7:0.9.2
Created /run/atomic/2017-09-14-13-49-27-088776
docker run -t --rm -v /etc/localtime:/etc/localtime -v /run/atomic/2017-09-14-13-49-27-088776:/scanin -v /var/lib/atomic/openscap/2017-09-14-13-49-27-088776:/scanout:rw,Z -v /etc/oscapd:/etc/oscapd:ro registry.access.redhat.com/rhel7/openscap oscapd-evaluate scan --no-standard-compliance --targets chroots-in-dir:///scanin --output /scanout -j1
Created /run/atomic/2017-09-14-13-49-27-088776/4d1864b202cf3adfb71e6ee697a7c0dcaa580757a49be17cb54b08af5bc1e46c
Mounted 4d1864b202cf3adfb71e6ee697a7c0dcaa580757a49be17cb54b08af5bc1e46c to /run/atomic/2017-09-14-13-49-27-088776/4d1864b202cf3adfb71e6ee697a7c0dcaa580757a49be17cb54b08af5bc1e46c
Creating the output dir at /var/lib/atomic/openscap/2017-09-14-13-49-27-088776
INFO:OpenSCAP Daemon one-off evaluator 0.1.6
INFO:Autodetected "oscap" in path "/usr/bin/oscap".
INFO:Autodetected "oscap-ssh" in path "/usr/bin/oscap-ssh".
INFO:Autodetected "oscap-vm" in path "/usr/bin/oscap-vm".
INFO:Autodetected "oscap-docker" in path "/usr/bin/oscap-docker".
INFO:Autodetected "oscap-chroot" in path "/usr/bin/oscap-chroot".
WARNING:Can't import the 'docker' package. Container scanning functionality will be disabled.
INFO:Autodetected SCAP content at "/usr/share/openscap/cpe/openscap-cpe-oval.xml".
INFO:Autodetected SCAP content in path "/usr/share/xml/scap/ssg/content".
INFO:Creating tasks directory at '/var/lib/oscapd/tasks' because it didn't exist.
INFO:Creating results directory at '/var/lib/oscapd/results' because it didn't exist.
INFO:Creating results work in progress directory at '/var/lib/oscapd/work_in_progress' because it didn't exist.
INFO:Evaluated EvaluationSpec, exit_code=0.
ERROR:Failed to scan target 'chroot:///scanin/4d1864b202cf3adfb71e6ee697a7c0dcaa580757a49be17cb54b08af5bc1e46c' for vulnerabilities.
Traceback (most recent call last):
  File "/usr/bin/oscapd-evaluate", line 143, in scan_worker
    es.evaluate(config)
  File "/usr/lib/python2.7/site-packages/openscap_daemon/evaluation_spec.py", line 473, in evaluate
    wip_result = self.evaluate_into_dir(config)
  File "/usr/lib/python2.7/site-packages/openscap_daemon/evaluation_spec.py", line 470, in evaluate_into_dir
    return oscap_helpers.evaluate(self, config)
  File "/usr/lib/python2.7/site-packages/openscap_daemon/oscap_helpers.py", line 300, in evaluate
    args = get_evaluation_args(spec, config)
  File "/usr/lib/python2.7/site-packages/openscap_daemon/oscap_helpers.py", line 275, in get_evaluation_args
    ret.extend(spec.get_oscap_arguments(config))
  File "/usr/lib/python2.7/site-packages/openscap_daemon/evaluation_spec.py", line 444, in get_oscap_arguments
    ret.append(config.get_cve_feed(self.get_cpe_ids(config)))
  File "/usr/lib/python2.7/site-packages/openscap_daemon/config.py", line 402, in get_cve_feed
    return self.cve_feed_manager.get_cve_feed(cpe_ids)
  File "/usr/lib/python2.7/site-packages/openscap_daemon/cve_feed_manager.py", line 219, in get_cve_feed
    "Can't find a supported CPE ID in %s" % (", ".join(cpe_ids))
RuntimeError: Can't find a supported CPE ID in cpe:/o:centos:centos:7
INFO:[100.00%] Scanned target 'chroot:///scanin/4d1864b202cf3adfb71e6ee697a7c0dcaa580757a49be17cb54b08af5bc1e46c'

ansible/container-conductor-centos-7:0.9.2 (4d1864b202cf3ad)

     ansible/container-conductor-centos-7:0.9.2 is not supported for this scan.

Files associated with this scan are in /var/lib/atomic/openscap/2017-09-14-13-49-27-088776.

Unmounted /run/atomic/2017-09-14-13-49-27-088776/4d1864b202cf3adfb71e6ee697a7c0dcaa580757a49be17cb54b08af5bc1e46c
```

**Comment by chouseknecht** [comment]
Seems all we need is a RHEL7:latest based conductor. I've been able to build a VM on AWS, create the conductor image, and scan it. 

The following are being flagged by the scanner: 

```
container-conductor-rhel7-latest:0.9.2 (24cc990807e6845)

The following results were found:

       failing_checks:
         has_licenses
         atomic_help_exists
```

Checking with Brian Cook to see how we remediate these. 

Also, had to make some changes to get the image built and passing tests. Here's the PR #735 contains the changes.

**Comment by chouseknecht** [comment]
Just need to test, and hopefully push an image to RHCC.
