### ISSUE TITLE
AnsibleContainerException: Error building conductor image: pull access denied for container-conductor-ubuntu

### ISSUE THREAD

**Issue by basictheprogram** [ansible/ansible-container#736]
##### ISSUE TYPE

 - Bug Report

##### container.yml 

```yaml
version: "2"

defaults:
  keep_deb_src: false
  keep_build_essentials: false
  private_data: "/local-private-data"

settings:
  conductor:
    base: ubuntu
    # roles_path:
    volumes:
      - ~/projects/ansible.git/playbooks.git/roles:/etc/ansible/roles:ro
      - ~/projects/ansible.git/playbooks.git/private_data:/local-private-data:ro

  project_name: dev

services:
  web:
    from: ubuntu

    command: ["/bin/ls", "/etc"]

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "4443:4443"

    roles:
      - { role: apache2-servers }

      environment:
        - "DEBUG=1"
```

##### OS / ENVIRONMENT

```
$ ansible-container --debug version
Ansible Container, version 0.9.3rc0
Darwin, alliance.int.celadonsystems.com, 16.7.0, Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64, x86_64
2.7.10 (default, Feb  7 2017, 00:08:15)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] /Users/tanner/projects/ansible.git/bin/python
{
  "ContainersPaused": 0,
  "Labels": null,
  "CgroupDriver": "cgroupfs",
  "ContainersRunning": 0,
  "ContainerdCommit": {
    "Expected": "3addd840653146c90a254301d6c3a663c7fd6429",
    "ID": "3addd840653146c90a254301d6c3a663c7fd6429"
  },
  "InitBinary": "docker-init",
  "NGoroutines": 30,
  "Swarm": {
    "ControlAvailable": false,
    "NodeID": "",
    "Error": "",
    "RemoteManagers": null,
    "LocalNodeState": "inactive",
    "NodeAddr": ""
  },
  "LoggingDriver": "json-file",
  "OSType": "linux",
  "HttpProxy": "",
  "Runtimes": {
    "runc": {
      "path": "docker-runc"
    }
  },
  "DriverStatus": [
    [
      "Backing Filesystem",
      "extfs"
    ],
    [
      "Supports d_type",
      "true"
    ],
    [
      "Native Overlay Diff",
      "true"
    ]
  ],
  "OperatingSystem": "Alpine Linux v3.5",
  "Containers": 54,
  "HttpsProxy": "",
  "BridgeNfIp6tables": true,
  "MemTotal": 2095882240,
  "SecurityOptions": [
    "name=seccomp,profile=default"
  ],
  "Driver": "overlay2",
  "IndexServerAddress": "https://index.docker.io/v1/",
  "ClusterStore": "",
  "InitCommit": {
    "Expected": "949e6fa",
    "ID": "949e6fa"
  },
  "Isolation": "",
  "SystemStatus": null,
  "OomKillDisable": true,
  "ClusterAdvertise": "",
  "SystemTime": "2017-09-20T22:39:28.223517424Z",
  "Name": "moby",
  "CPUSet": true,
  "RegistryConfig": {
    "AllowNondistributableArtifactsCIDRs": [],
    "Mirrors": [],
    "IndexConfigs": {
      "docker.io": {
        "Official": true,
        "Name": "docker.io",
        "Secure": true,
        "Mirrors": []
      }
    },
    "AllowNondistributableArtifactsHostnames": [],
    "InsecureRegistryCIDRs": [
      "127.0.0.0/8"
    ]
  },
  "DefaultRuntime": "runc",
  "ContainersStopped": 54,
  "NCPU": 4,
  "NFd": 19,
  "Architecture": "x86_64",
  "KernelMemory": true,
  "CpuCfsQuota": true,
  "Debug": true,
  "ID": "J3KP:SGVL:626G:CWPL:QN26:7FTT:NEXN:VXJ6:DOP4:WISZ:DVS7:H63Q",
  "IPv4Forwarding": true,
  "KernelVersion": "4.9.38-moby",
  "BridgeNfIptables": true,
  "NoProxy": "",
  "LiveRestoreEnabled": false,
  "ServerVersion": "17.07.0-ce-rc1",
  "CpuCfsPeriod": true,
  "ExperimentalBuild": true,
  "MemoryLimit": true,
  "SwapLimit": true,
  "Plugins": {
    "Volume": [
      "local"
    ],
    "Network": [
      "bridge",
      "host",
      "ipvlan",
      "macvlan",
      "null",
      "overlay"
    ],
    "Authorization": null,
    "Log": [
      "awslogs",
      "fluentd",
      "gcplogs",
      "gelf",
      "journald",
      "json-file",
      "logentries",
      "splunk",
      "syslog"
    ]
  },
  "Images": 1,
  "DockerRootDir": "/var/lib/docker",
  "NEventsListener": 1,
  "CPUShares": true,
  "RuncCommit": {
    "Expected": "2d41c047c83e09a6d61d464906feb2a2f3c52aa4",
    "ID": "2d41c047c83e09a6d61d464906feb2a2f3c52aa4"
  }
}
{
  "KernelVersion": "4.9.38-moby",
  "Arch": "amd64",
  "BuildTime": "2017-07-26T05:25:01.392492215+00:00",
  "ApiVersion": "1.31",
  "Version": "17.07.0-ce-rc1",
  "MinAPIVersion": "1.12",
  "GitCommit": "8c4be39",
  "Os": "linux",
  "Experimental": true,
  "GoVersion": "go1.8.3"
}
```
##### SUMMARY

ansible-container build fails

##### STEPS TO REPRODUCE

```
$ ansible-container build
```

##### EXPECTED RESULTS

Ansible Container Conductor image to be built

##### ACTUAL RESULTS

```
$ docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username (): <removed>
Password: <removed>
Login Succeeded
```
```
$ ansible-container --debug build
2017-09-20T17:44:31.112238 The default type is            [container.config] caller_file=/Users/tanner/projects/ansible.git/ansible-container/container/config.py caller_func=_resolve_defaults caller_line=189 config=<class 'ruamel.yaml.comments.CommentedMap'> defaults=<type '_ordereddict.ordereddict'>
2017-09-20T17:44:31.113044 Getting environment variables... [container.config] caller_file=/Users/tanner/projects/ansible.git/ansible-container/container/config.py caller_func=_get_environment_variables caller_line=205
2017-09-20T17:44:31.113707 Read environment variables     [container.config] caller_file=/Users/tanner/projects/ansible.git/ansible-container/container/config.py caller_func=_get_environment_variables caller_line=210 env_vars={}
2017-09-20T17:44:31.114307 Resolved template variables    [container.config] caller_file=/Users/tanner/projects/ansible.git/ansible-container/container/config.py caller_func=_resolve_defaults caller_line=194 template_vars={"keep_deb_src": false, "keep_build_essentials": false, "private_data": "/local-private-data"}
2017-09-20T17:44:31.114995 Parsed config                  [container.config] caller_file=/Users/tanner/projects/ansible.git/ansible-container/container/config.py caller_func=set_env caller_line=148 config={"version": "2", "defaults": {"keep_deb_src": false, "keep_build_essentials": false, "private_data": "/local-private-data"}, "settings": {"conductor": {"base": "ubuntu", "volumes": ["~/projects/ansible.git/playbooks.git/roles:/etc/ansible/roles:ro", "~/projects/clients/comap.com/ansible-container/group_vars/comap.com:/local-group-vars:ro", "~/projects/ansible.git/playbooks.git/private_data:/local-private-data:ro"]}, "project_name": "dev.comap.com", "pwd": "/Users/tanner/projects/clients/comap.com/ansible-container"}, "services": {"web": {"from": "ubuntu", "command": ["/bin/ls", "/etc"], "ports": ["80:80", "443:443", "8080:8080", "4443:4443"], "roles": [{"role": "dump-variables", "become": "no"}, {"role": "updates"}, {"role": "bootstrap"}, {"role": "virtual-servers"}, {"role": "postfix-satellite"}, {"role": "logrotate"}, {"role": "apticron"}, {"role": "listchanges"}, {"role": "support-users"}, {"role": "apache2-servers"}], "build_overrides": {"volumes": ["~/projects/clients/comap.com/www.comap.com:/media/comap.com:ro", "~/projects/ansible.git/playbooks.git/private_data:/local-private-data:ro"]}}}, "registries": {}}
2017-09-20T17:44:31.115650 Loading engine capabilities    [container.utils.loader] caller_file=/Users/tanner/projects/ansible.git/ansible-container/container/utils/loader.py caller_func=load_engine caller_line=14 capabilities=['BUILD', 'RUN'] engine=docker
2017-09-20T17:44:31.136536 Setting Docker client timeout to 60 [container.docker.engine] caller_file=/Users/tanner/projects/ansible.git/ansible-container/container/docker/engine.py caller_func=get_timeout caller_line=122
2017-09-20T17:44:31.152999 Could not find container for conductor [container.docker.engine] all_containers=[] caller_file=/Users/tanner/projects/ansible.git/ansible-container/container/docker/engine.py caller_func=get_container_id_for_service caller_line=531 container=u'dev.comap.com_conductor'
2017-09-20T17:44:31.159550 Could not find the latest image for service, searching for other tags with same image name [container.docker.engine] caller_file=/Users/tanner/projects/ansible.git/ansible-container/container/docker/engine.py caller_func=get_latest_image_for_service caller_line=570 image_name=u'dev.comap.com-conductor' service=conductor
2017-09-20T17:44:31.162896 Call: Engine.build_conductor_image [container.docker.engine] args=('/Users/tanner/projects/clients/comap.com/ansible-container', 'ubuntu') caller_file=/Users/tanner/projects/ansible.git/ansible-container/container/docker/engine.py caller_func=Engine.build_conductor_image caller_line=23 kwargs={'environment': [], 'cache': True}
2017-09-20T17:44:31.167803 Using temporary directory      [container.utils.temp] caller_file=/Users/tanner/projects/ansible.git/ansible-container/container/utils/temp.py caller_func=__enter__ caller_line=17 path=/var/folders/y_/w_pbl7355vg3gv5xkmsld49m0000gn/T/tmp_0102R
2017-09-20T17:44:31.168544 Building Docker Engine context... [container.docker.engine] caller_file=/Users/tanner/projects/ansible.git/ansible-container/container/docker/engine.py caller_func=build_conductor_image caller_line=963
2017-09-20T17:44:31.193519 Rendered Jinja Template:       [container.utils] body=FROM ubuntu
ENV ANSIBLE_CONTAINER=1




RUN apt-get update -y && \
    apt-get install -y make dpkg-dev curl gcc git libffi-dev libpopt0 libssl-dev python2.7 python-apt python-dev rsync sudo && \
    cd /usr/bin && \
    rm -f lsb_release && \
    ln -fs python2.7 python && \

    apt-get clean


RUN (curl https://bootstrap.pypa.io/get-pip.py | python - --no-cache-dir ) && \
    mkdir -p /etc/ansible/roles /_ansible/src && \
    (curl https://get.docker.com/builds/Linux/x86_64/docker-17.04.0-ce.tgz \
       | tar -zxC /usr/local/bin/ --strip-components=1 docker/docker )

# The COPY here will break cache if the version of Ansible Container changed
COPY /container-src /_ansible/container
RUN cd /_ansible && \
    pip install --no-cache-dir -r container/conductor-build/conductor-requirements.txt && \
    PYTHONPATH=. LC_ALL="en_US.UTF-8" python container/conductor-build/setup.py develop -v -N && \
    ansible-galaxy install -p /etc/ansible/roles -r container/conductor-build/conductor-requirements.yml




 caller_file=/Users/tanner/projects/ansible.git/ansible-container/container/utils/__init__.py caller_func=jinja_render_to_temp caller_line=83
2017-09-20T17:44:31.197235 Rendered Jinja Template:       [container.utils] body=FROM container-conductor-ubuntu:0.9.3rc0


VOLUME /usr

VOLUME /lib


# The COPY here will break cache if the requirements or ansible.cfg has changed
COPY /build-src /_ansible/build
RUN ( test -f /_ansible/build/ansible-requirements.txt && pip install --no-cache-dir -r /_ansible/build/ansible-requirements.txt || true ) && \
    ( test -f /_ansible/build/requirements.yml && ansible-galaxy install -p /etc/ansible/roles -r /_ansible/build/requirements.yml || true ) && \
    ( test -f /_ansible/build/ansible.cfg && cp /_ansible/build/ansible.cfg /etc/ansible/ansible.cfg || true)
 caller_file=/Users/tanner/projects/ansible.git/ansible-container/container/utils/__init__.py caller_func=jinja_render_to_temp caller_line=83
2017-09-20T17:44:31.199359 Context manifest:              [container.docker.engine] caller_file=/Users/tanner/projects/ansible.git/ansible-container/container/docker/engine.py caller_func=build_conductor_image caller_line=1030
2017-09-20T17:44:31.199780 tarball item: build-src/ansible.cfg (144 bytes) [container.docker.engine] bytes=144 file=build-src/ansible.cfg
2017-09-20T17:44:31.200061 tarball item: build-src/ansible-requirements.txt (130 bytes) [container.docker.engine] bytes=130 file=build-src/ansible-requirements.txt
2017-09-20T17:44:31.200350 tarball item: build-src/requirements.yml (298 bytes) [container.docker.engine] bytes=298 file=build-src/requirements.yml
2017-09-20T17:44:31.200640 tarball item: build-src/.touch (0 bytes) [container.docker.engine] bytes=0 file=build-src/.touch
2017-09-20T17:44:31.200903 tarball item: contrib/get-pip.py (1595409 bytes) [container.docker.engine] bytes=1595409 file=contrib/get-pip.py
2017-09-20T17:44:31.201086 tarball item: container-src (0 bytes) [container.docker.engine] bytes=0L file=container-src
2017-09-20T17:44:31.201236 tarball item: container-src/__init__.py (950 bytes) [container.docker.engine] bytes=950 file=container-src/__init__.py
2017-09-20T17:44:31.201352 tarball item: container-src/__init__.pyc (1494 bytes) [container.docker.engine] bytes=1494 file=container-src/__init__.pyc
2017-09-20T17:44:31.201465 tarball item: container-src/cli.py (22794 bytes) [container.docker.engine] bytes=22794 file=container-src/cli.py
2017-09-20T17:44:31.201577 tarball item: container-src/cli.pyc (18129 bytes) [container.docker.engine] bytes=18129 file=container-src/cli.pyc
2017-09-20T17:44:31.201688 tarball item: container-src/config.py (15653 bytes) [container.docker.engine] bytes=15653 file=container-src/config.py
2017-09-20T17:44:31.201798 tarball item: container-src/config.pyc (15416 bytes) [container.docker.engine] bytes=15416 file=container-src/config.pyc
2017-09-20T17:44:31.201908 tarball item: container-src/core.py (42745 bytes) [container.docker.engine] bytes=42745 file=container-src/core.py
2017-09-20T17:44:31.202024 tarball item: container-src/core.pyc (30717 bytes) [container.docker.engine] bytes=30717 file=container-src/core.pyc
2017-09-20T17:44:31.202128 tarball item: container-src/docker (0 bytes) [container.docker.engine] bytes=0L file=container-src/docker
2017-09-20T17:44:31.202232 tarball item: container-src/docker/__init__.py (205 bytes) [container.docker.engine] bytes=205 file=container-src/docker/__init__.py
2017-09-20T17:44:31.202336 tarball item: container-src/docker/__init__.pyc (347 bytes) [container.docker.engine] bytes=347 file=container-src/docker/__init__.pyc
2017-09-20T17:44:31.202449 tarball item: container-src/docker/config.py (2393 bytes) [container.docker.engine] bytes=2393 file=container-src/docker/config.py
2017-09-20T17:44:31.202550 tarball item: container-src/docker/config.pyc (2434 bytes) [container.docker.engine] bytes=2434 file=container-src/docker/config.pyc
2017-09-20T17:44:31.202651 tarball item: container-src/docker/deploy.py (248 bytes) [container.docker.engine] bytes=248 file=container-src/docker/deploy.py
2017-09-20T17:44:31.202751 tarball item: container-src/docker/engine.py (49646 bytes) [container.docker.engine] bytes=49646 file=container-src/docker/engine.py
2017-09-20T17:44:31.202852 tarball item: container-src/docker/engine.pyc (40585 bytes) [container.docker.engine] bytes=40585 file=container-src/docker/engine.pyc
2017-09-20T17:44:31.202952 tarball item: container-src/docker/files (0 bytes) [container.docker.engine] bytes=0L file=container-src/docker/files
2017-09-20T17:44:31.203053 tarball item: container-src/docker/files/get-pip.py (1595409 bytes) [container.docker.engine] bytes=1595409 file=container-src/docker/files/get-pip.py
2017-09-20T17:44:31.203154 tarball item: container-src/docker/importer.py (24838 bytes) [container.docker.engine] bytes=24838 file=container-src/docker/importer.py
2017-09-20T17:44:31.203255 tarball item: container-src/docker/secrets.py (5255 bytes) [container.docker.engine] bytes=5255 file=container-src/docker/secrets.py
2017-09-20T17:44:31.203354 tarball item: container-src/docker/secrets.pyc (5233 bytes) [container.docker.engine] bytes=5233 file=container-src/docker/secrets.pyc
2017-09-20T17:44:31.203454 tarball item: container-src/docker/templates (0 bytes) [container.docker.engine] bytes=0L file=container-src/docker/templates
2017-09-20T17:44:31.203554 tarball item: container-src/docker/templates/conductor-local-dockerfile.j2 (674 bytes) [container.docker.engine] bytes=674 file=container-src/docker/templates/conductor-local-dockerfile.j2
2017-09-20T17:44:31.203655 tarball item: container-src/docker/templates/conductor-src-dockerfile.j2 (3020 bytes) [container.docker.engine] bytes=3020 file=container-src/docker/templates/conductor-src-dockerfile.j2
2017-09-20T17:44:31.203758 tarball item: container-src/docker/tests (0 bytes) [container.docker.engine] bytes=0L file=container-src/docker/tests
2017-09-20T17:44:31.203858 tarball item: container-src/docker/tests/import (0 bytes) [container.docker.engine] bytes=0L file=container-src/docker/tests/import
2017-09-20T17:44:31.203958 tarball item: container-src/docker/tests/import/blue-fish.txt (10 bytes) [container.docker.engine] bytes=10 file=container-src/docker/tests/import/blue-fish.txt
2017-09-20T17:44:31.204058 tarball item: container-src/docker/tests/import/Dockerfile (1151 bytes) [container.docker.engine] bytes=1151 file=container-src/docker/tests/import/Dockerfile
2017-09-20T17:44:31.204158 tarball item: container-src/docker/tests/import/lulz.tgz (59072 bytes) [container.docker.engine] bytes=59072 file=container-src/docker/tests/import/lulz.tgz
2017-09-20T17:44:31.204257 tarball item: container-src/docker/tests/import/one-fish.txt (6 bytes) [container.docker.engine] bytes=6 file=container-src/docker/tests/import/one-fish.txt
2017-09-20T17:44:31.204356 tarball item: container-src/docker/tests/import/red-fish (0 bytes) [container.docker.engine] bytes=0L file=container-src/docker/tests/import/red-fish
2017-09-20T17:44:31.204456 tarball item: container-src/docker/tests/import/red-fish/lulz.txt (10 bytes) [container.docker.engine] bytes=10 file=container-src/docker/tests/import/red-fish/lulz.txt
2017-09-20T17:44:31.204555 tarball item: container-src/docker/tests/import/two-fish (0 bytes) [container.docker.engine] bytes=0L file=container-src/docker/tests/import/two-fish
2017-09-20T17:44:31.204654 tarball item: container-src/docker/tests/import/two-fish/green-eggs (0 bytes) [container.docker.engine] bytes=0L file=container-src/docker/tests/import/two-fish/green-eggs
2017-09-20T17:44:31.204753 tarball item: container-src/docker/tests/import/two-fish/green-eggs/ham.txt (5 bytes) [container.docker.engine] bytes=5 file=container-src/docker/tests/import/two-fish/green-eggs/ham.txt
2017-09-20T17:44:31.204853 tarball item: container-src/docker/tests/import/two-fish/who.txt (7 bytes) [container.docker.engine] bytes=7 file=container-src/docker/tests/import/two-fish/who.txt
2017-09-20T17:44:31.204953 tarball item: container-src/engine.py (6740 bytes) [container.docker.engine] bytes=6740 file=container-src/engine.py
2017-09-20T17:44:31.205187 tarball item: container-src/engine.pyc (11325 bytes) [container.docker.engine] bytes=11325 file=container-src/engine.pyc
2017-09-20T17:44:31.205337 tarball item: container-src/exceptions.py (2158 bytes) [container.docker.engine] bytes=2158 file=container-src/exceptions.py
2017-09-20T17:44:31.205472 tarball item: container-src/exceptions.pyc (6174 bytes) [container.docker.engine] bytes=6174 file=container-src/exceptions.pyc
2017-09-20T17:44:31.205581 tarball item: container-src/k8s (0 bytes) [container.docker.engine] bytes=0L file=container-src/k8s
2017-09-20T17:44:31.205689 tarball item: container-src/k8s/__init__.py (196 bytes) [container.docker.engine] bytes=196 file=container-src/k8s/__init__.py
2017-09-20T17:44:31.205795 tarball item: container-src/k8s/base_config.py (932 bytes) [container.docker.engine] bytes=932 file=container-src/k8s/base_config.py
2017-09-20T17:44:31.205900 tarball item: container-src/k8s/base_deploy.py (34216 bytes) [container.docker.engine] bytes=34216 file=container-src/k8s/base_deploy.py
2017-09-20T17:44:31.206004 tarball item: container-src/k8s/base_engine.py (10144 bytes) [container.docker.engine] bytes=10144 file=container-src/k8s/base_engine.py
2017-09-20T17:44:31.206106 tarball item: container-src/k8s/config.py (660 bytes) [container.docker.engine] bytes=660 file=container-src/k8s/config.py
2017-09-20T17:44:31.206209 tarball item: container-src/k8s/deploy.py (1720 bytes) [container.docker.engine] bytes=1720 file=container-src/k8s/deploy.py
2017-09-20T17:44:31.206311 tarball item: container-src/k8s/engine.py (1276 bytes) [container.docker.engine] bytes=1276 file=container-src/k8s/engine.py
2017-09-20T17:44:31.206413 tarball item: container-src/openshift (0 bytes) [container.docker.engine] bytes=0L file=container-src/openshift
2017-09-20T17:44:31.206515 tarball item: container-src/openshift/__init__.py (196 bytes) [container.docker.engine] bytes=196 file=container-src/openshift/__init__.py
2017-09-20T17:44:31.206617 tarball item: container-src/openshift/config.py (427 bytes) [container.docker.engine] bytes=427 file=container-src/openshift/config.py
2017-09-20T17:44:31.206718 tarball item: container-src/openshift/deploy.py (6241 bytes) [container.docker.engine] bytes=6241 file=container-src/openshift/deploy.py
2017-09-20T17:44:31.206818 tarball item: container-src/openshift/engine.py (2207 bytes) [container.docker.engine] bytes=2207 file=container-src/openshift/engine.py
2017-09-20T17:44:31.206918 tarball item: container-src/templates (0 bytes) [container.docker.engine] bytes=0L file=container-src/templates
2017-09-20T17:44:31.207020 tarball item: container-src/templates/ansible-container-inventory.py (1230 bytes) [container.docker.engine] bytes=1230 file=container-src/templates/ansible-container-inventory.py
2017-09-20T17:44:31.207123 tarball item: container-src/templates/ansible-dockerfile.j2 (1194 bytes) [container.docker.engine] bytes=1194 file=container-src/templates/ansible-dockerfile.j2
2017-09-20T17:44:31.207224 tarball item: container-src/templates/ansible.cfg (41 bytes) [container.docker.engine] bytes=41 file=container-src/templates/ansible.cfg
2017-09-20T17:44:31.207325 tarball item: container-src/templates/builder.sh (620 bytes) [container.docker.engine] bytes=620 file=container-src/templates/builder.sh
2017-09-20T17:44:31.207425 tarball item: container-src/templates/compose_versioned.j2.yml (237 bytes) [container.docker.engine] bytes=237 file=container-src/templates/compose_versioned.j2.yml
2017-09-20T17:44:31.207525 tarball item: container-src/templates/hosts.j2 (90 bytes) [container.docker.engine] bytes=90 file=container-src/templates/hosts.j2
2017-09-20T17:44:31.207624 tarball item: container-src/templates/init (0 bytes) [container.docker.engine] bytes=0L file=container-src/templates/init
2017-09-20T17:44:31.207725 tarball item: container-src/templates/init/ansible-requirements.j2.txt (131 bytes) [container.docker.engine] bytes=131 file=container-src/templates/init/ansible-requirements.j2.txt
2017-09-20T17:44:31.207826 tarball item: container-src/templates/init/ansible.j2.cfg (145 bytes) [container.docker.engine] bytes=145 file=container-src/templates/init/ansible.j2.cfg
2017-09-20T17:44:31.207926 tarball item: container-src/templates/init/container.j2.yml (2514 bytes) [container.docker.engine] bytes=2514 file=container-src/templates/init/container.j2.yml
2017-09-20T17:44:31.208026 tarball item: container-src/templates/init/meta.j2.yml (1231 bytes) [container.docker.engine] bytes=1231 file=container-src/templates/init/meta.j2.yml
2017-09-20T17:44:31.208126 tarball item: container-src/templates/init/requirements.j2.yml (299 bytes) [container.docker.engine] bytes=299 file=container-src/templates/init/requirements.j2.yml
2017-09-20T17:44:31.208226 tarball item: container-src/templates/install-docker-compose.j2.yml (712 bytes) [container.docker.engine] bytes=712 file=container-src/templates/install-docker-compose.j2.yml
2017-09-20T17:44:31.208326 tarball item: container-src/templates/restart-docker-compose.j2.yml (75 bytes) [container.docker.engine] bytes=75 file=container-src/templates/restart-docker-compose.j2.yml
2017-09-20T17:44:31.208425 tarball item: container-src/templates/role (0 bytes) [container.docker.engine] bytes=0L file=container-src/templates/role
2017-09-20T17:44:31.208526 tarball item: container-src/templates/role/.travis.j2.yml (540 bytes) [container.docker.engine] bytes=540 file=container-src/templates/role/.travis.j2.yml
2017-09-20T17:44:31.208626 tarball item: container-src/templates/role/defaults (0 bytes) [container.docker.engine] bytes=0L file=container-src/templates/role/defaults
2017-09-20T17:44:31.208726 tarball item: container-src/templates/role/defaults/main.j2.yml (55 bytes) [container.docker.engine] bytes=55 file=container-src/templates/role/defaults/main.j2.yml
2017-09-20T17:44:31.208825 tarball item: container-src/templates/role/meta (0 bytes) [container.docker.engine] bytes=0L file=container-src/templates/role/meta
2017-09-20T17:44:31.209057 tarball item: container-src/templates/role/meta/main.j2.yml (3220 bytes) [container.docker.engine] bytes=3220 file=container-src/templates/role/meta/main.j2.yml
2017-09-20T17:44:31.209166 tarball item: container-src/templates/role/README.j2.md (1287 bytes) [container.docker.engine] bytes=1287 file=container-src/templates/role/README.j2.md
2017-09-20T17:44:31.209271 tarball item: container-src/templates/role/test (0 bytes) [container.docker.engine] bytes=0L file=container-src/templates/role/test
2017-09-20T17:44:31.209375 tarball item: container-src/templates/role/test/test.j2.yml (81 bytes) [container.docker.engine] bytes=81 file=container-src/templates/role/test/test.j2.yml
2017-09-20T17:44:31.209477 tarball item: container-src/templates/run-docker-compose.j2.yml (75 bytes) [container.docker.engine] bytes=75 file=container-src/templates/run-docker-compose.j2.yml
2017-09-20T17:44:31.209579 tarball item: container-src/templates/stop-docker-compose.j2.yml (75 bytes) [container.docker.engine] bytes=75 file=container-src/templates/stop-docker-compose.j2.yml
2017-09-20T17:44:31.209679 tarball item: container-src/templates/wait_on_host.py (2365 bytes) [container.docker.engine] bytes=2365 file=container-src/templates/wait_on_host.py
2017-09-20T17:44:31.209781 tarball item: container-src/utils (0 bytes) [container.docker.engine] bytes=0L file=container-src/utils
2017-09-20T17:44:31.209882 tarball item: container-src/utils/__init__.py (11391 bytes) [container.docker.engine] bytes=11391 file=container-src/utils/__init__.py
2017-09-20T17:44:31.209983 tarball item: container-src/utils/__init__.pyc (12043 bytes) [container.docker.engine] bytes=12043 file=container-src/utils/__init__.pyc
2017-09-20T17:44:31.210082 tarball item: container-src/utils/_text.py (12304 bytes) [container.docker.engine] bytes=12304 file=container-src/utils/_text.py
2017-09-20T17:44:31.210182 tarball item: container-src/utils/_text.pyc (8856 bytes) [container.docker.engine] bytes=8856 file=container-src/utils/_text.pyc
2017-09-20T17:44:31.210281 tarball item: container-src/utils/galaxy.py (8120 bytes) [container.docker.engine] bytes=8120 file=container-src/utils/galaxy.py
2017-09-20T17:44:31.210380 tarball item: container-src/utils/galaxy.pyc (7481 bytes) [container.docker.engine] bytes=7481 file=container-src/utils/galaxy.pyc
2017-09-20T17:44:31.210479 tarball item: container-src/utils/loader.py (906 bytes) [container.docker.engine] bytes=906 file=container-src/utils/loader.py
2017-09-20T17:44:31.210579 tarball item: container-src/utils/loader.pyc (1210 bytes) [container.docker.engine] bytes=1210 file=container-src/utils/loader.pyc
2017-09-20T17:44:31.210678 tarball item: container-src/utils/logmux.py (1313 bytes) [container.docker.engine] bytes=1313 file=container-src/utils/logmux.py
2017-09-20T17:44:31.210777 tarball item: container-src/utils/logmux.pyc (2739 bytes) [container.docker.engine] bytes=2739 file=container-src/utils/logmux.pyc
2017-09-20T17:44:31.210878 tarball item: container-src/utils/ordereddict.py (678 bytes) [container.docker.engine] bytes=678 file=container-src/utils/ordereddict.py
2017-09-20T17:44:31.210978 tarball item: container-src/utils/ordereddict.pyc (975 bytes) [container.docker.engine] bytes=975 file=container-src/utils/ordereddict.pyc
2017-09-20T17:44:31.211077 tarball item: container-src/utils/temp.py (698 bytes) [container.docker.engine] bytes=698 file=container-src/utils/temp.py
2017-09-20T17:44:31.211188 tarball item: container-src/utils/temp.pyc (1438 bytes) [container.docker.engine] bytes=1438 file=container-src/utils/temp.pyc
2017-09-20T17:44:31.211292 tarball item: container-src/utils/visibility.py (3329 bytes) [container.docker.engine] bytes=3329 file=container-src/utils/visibility.py
2017-09-20T17:44:31.211395 tarball item: container-src/utils/visibility.pyc (4328 bytes) [container.docker.engine] bytes=4328 file=container-src/utils/visibility.pyc
2017-09-20T17:44:31.211495 tarball item: container-src/conductor-build/setup.py (4628 bytes) [container.docker.engine] bytes=4628 file=container-src/conductor-build/setup.py
2017-09-20T17:44:31.211596 tarball item: container-src/conductor-build/conductor-requirements.txt (273 bytes) [container.docker.engine] bytes=273 file=container-src/conductor-build/conductor-requirements.txt
2017-09-20T17:44:31.211698 tarball item: container-src/conductor-build/conductor-requirements.yml (60 bytes) [container.docker.engine] bytes=60 file=container-src/conductor-build/conductor-requirements.yml
2017-09-20T17:44:31.216743 tarball item: Dockerfile (1021 bytes) [container.docker.engine] bytes=1021 file=Dockerfile
2017-09-20T17:44:31.216907 tarball item: build-src/ansible.cfg (144 bytes) [container.docker.engine] bytes=144 file=build-src/ansible.cfg
2017-09-20T17:44:31.217026 tarball item: build-src/ansible-requirements.txt (130 bytes) [container.docker.engine] bytes=130 file=build-src/ansible-requirements.txt
2017-09-20T17:44:31.217140 tarball item: build-src/requirements.yml (298 bytes) [container.docker.engine] bytes=298 file=build-src/requirements.yml
2017-09-20T17:44:31.217250 tarball item: build-src/.touch (0 bytes) [container.docker.engine] bytes=0 file=build-src/.touch
2017-09-20T17:44:31.217360 tarball item: Dockerfile (582 bytes) [container.docker.engine] bytes=582 file=Dockerfile
2017-09-20T17:44:31.225445 Starting Docker build of Ansible Container Conductor image (please be patient)... [container.docker.engine] caller_file=/Users/tanner/projects/ansible.git/ansible-container/container/docker/engine.py caller_func=build_conductor_image caller_line=1038
Step 1/5 : FROM container-conductor-ubuntu:0.9.3rc0
2017-09-20T17:44:32.087539 Cleaning up temporary directory [container.utils.temp] caller_file=/Users/tanner/projects/ansible.git/ansible-container/container/utils/temp.py caller_func=__exit__ caller_line=22 path=/var/folders/y_/w_pbl7355vg3gv5xkmsld49m0000gn/T/tmp_0102R
2017-09-20T17:44:32.088663 Unknown exception Error building conductor image: pull access denied for container-conductor-ubuntu, repository does not exist or may require 'docker login' [container.cli] caller_file=/Users/tanner/projects/ansible.git/lib/python2.7/site-packages/structlog/stdlib.py caller_func=exception caller_line=95
Traceback (most recent call last):
  File "/Users/tanner/projects/ansible.git/ansible-container/container/cli.py", line 299, in __call__
    getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
  File "/Users/tanner/projects/ansible.git/ansible-container/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/Users/tanner/projects/ansible.git/ansible-container/container/core.py", line 181, in hostcmd_build
    environment=env_vars
  File "/Users/tanner/projects/ansible.git/ansible-container/container/docker/engine.py", line 105, in __wrapped__
    return fn(self, *args, **kwargs)
  File "/Users/tanner/projects/ansible.git/ansible-container/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/Users/tanner/projects/ansible.git/ansible-container/container/docker/engine.py", line 1054, in build_conductor_image
    "Error building conductor image: {0}".format(line['errorDetail']['message']))
AnsibleContainerException: Error building conductor image: pull access denied for container-conductor-ubuntu, repository does not exist or may require 'docker login'
```

**Comment by chouseknecht** [comment]
@basictheprogram 

In your `container.yml` the `base` needs to include the tag. In the case of ubuntu, available tags are `trusty`,`xenial`, `precise`, and `zesty`.

**Comment by basictheprogram** [comment]
Is the tag requirement something "new" in the last 3 weeks?

I have built base images from 3 weeks ago where this container.yml worked. 

Just curious and thanks for the quick response.

**Comment by chouseknecht** [comment]
@basictheprogram 

New in 0.9.2. We're attempting to speed up the build by pulling pre-baked conductor base images. More details here: http://docs.ansible.com/ansible-container/conductor.html

**Comment by basictheprogram** [comment]
I'll try to stay current on with devel branch and patch notes. 

Closing issue.
