### ISSUE TITLE
Ansible container builds from source/devel HEAD running on Python 3.6 failing today

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible-container#746]
##### ISSUE TYPE

 - Bug Report

##### container.yml 

https://github.com/geerlingguy/solr-container/blob/master/container.yml

##### OS / ENVIRONMENT

```
Travis CI
Ubuntu 14.04 Trusty
Docker 17.03.1-ce
```

##### SUMMARY

I have a matrix of four builds running for [solr-container](https://github.com/geerlingguy/solr-container) on Travis CI, on a daily cron. The four builds are:

  1. Python 2.7, latest pip release
  2. Python 3.6, latest pip release
  3. Python 2.7, devel HEAD from source
  4. Python 3.6, devel HEAD from source

As of today, I can't get a build to pass when running HEAD/source on Python 3.6; see failing build: https://travis-ci.org/geerlingguy/solr-container/jobs/281456639#L514-L536 (run 2x now, both failed with the same error).

Yesterday's build passed without issue: https://travis-ci.org/geerlingguy/solr-container/jobs/280721592

##### STEPS TO REPRODUCE

```
# Install ansible-container devel HEAD.
git clone https://github.com/ansible/ansible-container.git
cd ansible-container
pip install -e .[docker]
cd ..

# Build solr-container.
ansible-container --var-file vars-6.x.yml build --no-container-cache
```

##### EXPECTED RESULTS

All builds should pass (all 4 combinations of pip/source and 2.7/3.6).

##### ACTUAL RESULTS

```
$ ansible-container --var-file vars-6.x.yml build --no-container-cache
Building Docker Engine context...	
ERROR	Unknown exception	
Traceback (most recent call last):
  File "/home/travis/build/geerlingguy/solr-container/ansible-container/container/cli.py", line 299, in __call__
    getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
  File "/home/travis/build/geerlingguy/solr-container/ansible-container/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/home/travis/build/geerlingguy/solr-container/ansible-container/container/core.py", line 181, in hostcmd_build
    environment=env_vars
  File "/home/travis/build/geerlingguy/solr-container/ansible-container/container/docker/engine.py", line 106, in __wrapped__
    return fn(self, *args, **kwargs)
  File "/home/travis/build/geerlingguy/solr-container/ansible-container/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/home/travis/build/geerlingguy/solr-container/ansible-container/container/docker/engine.py", line 1042, in build_conductor_image
    tarball)
  File "/home/travis/build/geerlingguy/solr-container/ansible-container/container/docker/engine.py", line 952, in _prepare_conductor_manifest
    if modules_to_install(base_path):
  File "/home/travis/build/geerlingguy/solr-container/ansible-container/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/home/travis/build/geerlingguy/solr-container/ansible-container/container/utils/__init__.py", line 325, in modules_to_install
    with open(path, 'ro') as fs:
ValueError: invalid mode: 'ro'
```

**Comment by chouseknecht** [comment]
@geerlingguy 

My bad! Thanks for reporting this. Should be fixed now.

**Comment by geerlingguy** [comment]
Indeed, everything works great now!
