### ISSUE TITLE
build with --project-path and --roles-path fails due to mount of ""

### ISSUE THREAD

**Issue by hans-d** [ansible/ansible-container#756]
##### ISSUE TYPE

 - Bug Report / Request for help

##### container.yml 

```
# not specific
```

##### OS / ENVIRONMENT

```
Ansible Container, version 0.9.2
Linux, d52e69e7fbd8, 4.4.0-96-generic, #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017, x86_64
2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] /usr/bin/python
```
Special: Trying to run ansible-container in a docker container, with /var/run/docker.sock passed through

##### SUMMARY

Trying to ansible-container to run in it's own docker container.

```
docker run -it --rm \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v $(pwd):/$(pwd) \
        -v $(which docker):/usr/bin/docker \
        -w $(pwd) \
        ansible-container
```
Passing in the docker sock, and because mounting is relative to the original .sock mirroring the working dir in the container as well.

```
# in the container, in working dir:
# ls
test     roles
```
`test` containing the container.yml, roles containing the roles

##### STEPS TO REPRODUCE

see above

```
ansible-container --project-path test build
```

##### EXPECTED RESULTS

being able to run ansible-container without issues

##### ACTUAL RESULTS

```
Building Docker Engine context...
Starting Docker build of Ansible Container Conductor image (please be patient)...
Parsing conductor CLI args.
Traceback (most recent call last):
  File "/usr/local/bin/conductor", line 11, in <module>
    load_entry_point('ansible-container', 'console_scripts', 'conductor')()
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/cli.py", line 389, in conductor_commandline
    conductor_config = AnsibleContainerConductorConfig(list_to_ordereddict(containers_config))
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/config.py", line 297, in __init__
    self._process_services()
  File "/_ansible/container/config.py", line 357, in _process_services
    role_metadata = get_metadata_from_role(role_name)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/utils/__init__.py", line 275, in get_metadata_from_role
    return get_content_from_role(role_name, os.path.join('meta', 'container.yml'))
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/utils/__init__.py", line 264, in get_content_from_role
    role_path = resolve_role_to_path(role_name)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/utils/__init__.py", line 210, in resolve_role_to_path
    loader=loader)
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/role/include.py", line 59, in load
    return ri.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/base.py", line 244, in load_data
    ds = self.preprocess_data(ds)
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/role/definition.py", line 94, in preprocess_data
    (role_name, role_path) = self._load_role_path(role_name)
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/role/definition.py", line 187, in _load_role_path
    raise AnsibleError("the role '%s' was not found in %s" % (role_name, ":".join(role_search_paths)), obj=self._ds)
ansible.errors.AnsibleError: the role 'squid' was not found in ./roles:/src/roles:/etc/ansible/roles:.
Conductor terminated. Cleaning up.      command_rc=1 conductor_id=3247d0f9fb461b7362efe71cd016245b291bec7eb27b24468714f6c0d0337513 save_container=False
ERROR   Conductor exited with status 1
```

explicit binding with `--src-mount-path` results in 
```
Building Docker Engine context...
Starting Docker build of Ansible Container Conductor image (please be patient)...
Parsing conductor CLI args.
Docker™ daemon integration engine loaded. Build starting.       project=test
Building service...     project=test service=test
Traceback (most recent call last):
  File "/usr/local/bin/conductor", line 11, in <module>
    load_entry_point('ansible-container', 'console_scripts', 'conductor')()
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/cli.py", line 399, in conductor_commandline
    **params)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/core.py", line 800, in conductorcmd_build
    container_id = engine.run_container(cur_image_id, service_name, **run_kwargs)
  File "/_ansible/container/docker/engine.py", line 105, in __wrapped__
    return fn(self, *args, **kwargs)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/docker/engine.py", line 270, in run_container
    **run_kwargs
  File "/usr/local/lib/python2.7/dist-packages/docker/models/containers.py", line 708, in run
    detach=detach, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/models/containers.py", line 759, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/container.py", line 449, in create_container
    return self.create_container_from_config(config, name)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/container.py", line 460, in create_container_from_config
    return self._result(res, True)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 226, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 222, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("Invalid volume spec "": Invalid volume specification: ''")
Conductor terminated. Cleaning up.      command_rc=1 conductor_id=ba8ca5e70794d71c45c783c20794ac68273f8657dab55001408b77da02dcea2a save_container=False
ERROR   Conductor exited with status 1
```

Hower, running (inside the container):
```
docker -it -v /existing/path/on/out/host:/whatever ubuntu bash
```
works fine and I can access the content

##### Dockerfile
```
FROM            ubuntu:16.04

ENV             ANSIBLE_CONTAINER_VERSION=0.9.2 \
                ANSIBLE_CONTAINER_TYPES="[docker]"

RUN             apt-get update ;\
                apt-get install -y \
                        python \
                        python-pip ;\
                rm -rf /var/lib/apt/lists/* ;\
                pip install \
                        ansible-container$ANSIBLE_CONTAINER_TYPES==$ANSIBLE_CONTAINER_VERSION

VOLUME          [ "/ansible" ]
WORKDIR         /ansible

ENTRYPOINT      ["ansible-container"]
CMD             ["help"]
```

**Comment by hans-d** [comment]
some more output with --debug
```
2017-10-05T11:57:13.353719 Docker run:                    [container.docker.engine] caller_file=/usr/local/lib/python2.7/dist-packages/container/docker/engine.py caller_func=run_conductor caller_line=435 image=u'sha256:4d72a25e1b2736173c0df88a84ef4ed93e0bc18772babd3e9df081b20d8ba896' params={'name': u'test_conductor', 'cap_add': ['SYS_ADMIN'], 'environment': {'DOCKER_HOST': 'unix:///var/run/docker.sock', 'ANSIBLE_ROLES_PATH': '/src/roles:/etc/ansible/roles'}, 'working_dir': '/src', 'command': ['conductor', 'build', '--project-name', 'test', '--engine', 'docker', '--params', u'eyJ3aXRoX3ZvbHVtZXMiOiBbXSwgImNvbmZpZ192YXJzIjoge30sICJjb25kdWN0b3JfY2FjaGUiOiB0cnVlLCAibG9jYWxfcHl0aG9uIjogZmFsc2UsICJ3aXRoX3ZhcmlhYmxlcyI6IFtdLCAic2VsaW51eCI6IHRydWUsICJwdXJnZV9sYXN0IjogdHJ1ZSwgImNhY2hlIjogdHJ1ZSwgInZvbHVtZV9kcml2ZXIiOiBudWxsLCAiZGV2ZWwiOiBmYWxzZSwgInNyY19tb3VudF9wYXRoIjogIi9ob21lL2hhbnNkL2RvY2tlciIsICJyb2xlc19wYXRoIjogW10sICJzdWJjb21tYW5kIjogImJ1aWxkIiwgImFuc2libGVfb3B0aW9ucyI6ICIiLCAiZmxhdHRlbiI6IGZhbHNlLCAiY29udGFpbmVyX2NhY2hlIjogdHJ1ZSwgImRlYnVnIjogdHJ1ZSwgInNlcnZpY2VzX3RvX2J1aWxkIjogbnVsbCwgInNhdmVfY29uZHVjdG9yX2NvbnRhaW5lciI6IGZhbHNlfQ==', '--config', u'eyJzZXJ2aWNlcyI6IFtbInNxdWlkIiwgeyJmcm9tIjogInVidW50dToxNi4wNCIsICJlbnZpcm9ubWVudCI6IHsiU1FVSURfQ0FDSEVfRElSIjogIi92YXIvc3Bvb2wvc3F1aWQifSwgInBvcnRzIjogWzMxMjhdLCAidm9sdW1lcyI6IFsie3sgbG9va3VwKCdlbnYnLCAnU1FVSURfQ0FDSEVfRElSJykgfX0iXSwgImVudHJ5cG9pbnQiOiBbIi91c3Ivc2Jpbi9zcXVpZCJdLCAicm9sZXMiOiBbInNxdWlkIl19XV0sICJkZWZhdWx0cyI6IFtdLCAic2V0dGluZ3MiOiBbWyJjb25kdWN0b3JfYmFzZSIsICJ1YnVudHU6MTYuMDQiXSwgWyJwd2QiLCAic3F1aWQtYWMiXV19', '--encoding', 'b64json'], 'user': 'root', 'volumes': {'/var/run/docker.sock': {'bind': '/var/run/docker.sock', 'mode': 'rw'}, '/home/hansd/docker': {'bind': '/src', 'mode': 'ro'}, 'test_secrets': {'bind': '/run/secrets', 'mode': 'rw'}, '/root/.docker/config.json': {'bind': '/root/.docker/config.json', 'mode': 'rw'}}, 'detach': True, 'privileged': True}
Parsing conductor CLI args.
2017-10-05T11:57:19.031867 Processing defaults section... [container.config] caller_file=/_ansible/container/config.py caller_func=_process_defaults caller_line=325
2017-10-05T11:57:19.037959 Processing section...          [container.config] caller_file=/_ansible/container/config.py caller_func=_process_top_level_sections caller_line=334 section=volumes
2017-10-05T11:57:19.044117 Processing section...          [container.config] caller_file=/_ansible/container/config.py caller_func=_process_top_level_sections caller_line=334 section=registries
2017-10-05T11:57:19.047649 Processing section...          [container.config] caller_file=/_ansible/container/config.py caller_func=_process_top_level_sections caller_line=334 section=secrets
2017-10-05T11:57:19.053521 Processing service...          [container.config] caller_file=/_ansible/container/config.py caller_func=_process_services caller_line=340 service=u'test' service_data={u'from': u'ubuntu:16.04', u'roles': [u'test'], u'environment': {u'TEST_CACHE_DIR': u'/var/spool/test'}, u'entrypoint': [u'/usr/sbin/mytest'], u'volumes': [u"{{ lookup('env', 'TEST_CACHE_DIR') }}"], u'ports': [3111]}
2017-10-05T11:57:19.059916 Rendering service keys from defaults [container.config] caller_file=/_ansible/container/config.py caller_func=_process_services caller_line=363 defaults={} service=u'test'
2017-10-05T11:57:19.086226 Starting Ansible Container Conductor: build [container.cli] caller_file=/_ansible/container/cli.py caller_func=conductor_commandline caller_line=391 services={"test": {"from": "ubuntu:16.04", "roles": ["test"], "environment": {"TEST_CACHE_DIR": "/var/spool/test"}, "entrypoint": ["/usr/sbin/test"], "volumes": [""], "ports": [3111], "defaults": {}}}
2017-10-05T11:57:19.092266 Loading engine capabilities    [container.utils.loader] caller_file=/_ansible/container/utils/loader.py caller_func=load_engine caller_line=14 capabilities=['BUILD'] engine=docker
2017-10-05T11:57:19.115295 2017-10-05T11:57:19.115295 Docker™ daemon integration engine loaded. Build starting. [container.core] caller_file=/_ansible/container/core.py caller_func=conductorcmd_build caller_line=688 project=test
2017-10-05T11:57:19.125613 Building service...            [container.core] caller_file=/_ansible/container/core.py caller_func=conductorcmd_build caller_line=694 project=test service=u'test'
2017-10-05T11:57:19.140735 Setting Docker client timeout to 60 [container.docker.engine] caller_file=/_ansible/container/docker/engine.py caller_func=get_timeout caller_line=122
2017-10-05T11:57:19.152328 Base fingerprint hash = 97dc9eec5cac994275ed4b78e4f494c6f8188230b2f6f32bae5943aaa74bc723 [container.core] caller_file=/_ansible/container/core.py caller_func=conductorcmd_build caller_line=710 hash=97dc9eec5cac994275ed4b78e4f494c6f8188230b2f6f32bae5943aaa74bc723 service=u'test'
2017-10-05T11:57:19.165380 Could not find container for test [container.docker.engine] all_containers=[<Container: e1cf33e9bd>, <Container: c8081fd37d>] caller_file=/_ansible/container/docker/engine.py caller_func=get_container_id_for_service caller_line=531 container=u'test_test'
2017-10-05T11:57:19.173377 Still trying to keep cache.    [container.core] caller_file=/_ansible/container/core.py caller_func=conductorcmd_build caller_line=725 service=u'test'
2017-10-05T11:57:19.207360 Cache busted! No layer found   [container.core] caller_file=/_ansible/container/core.py caller_func=conductorcmd_build caller_line=740 fingerprint=0ae2977f74db4869c513eb1eb214d2fc24fb7966e8ca51e88ed0c7773a521e34 service=u'test'
2017-10-05T11:57:19.242039 Detected architecture x86_64-linux-gnu [container.core] architecture=x86_64-linux-gnu caller_file=/_ansible/container/core.py caller_func=conductorcmd_build caller_line=775 service=u'test'
2017-10-05T11:57:19.253615 Call: Engine.run_container     [container.docker.engine] args=(u'sha256:2d696327ab2e15a3354ca258249358e244f3219eef76c653d0e6d3bd87f7830f', u'test') caller_file=/_ansible/container/docker/engine.py caller_func=Engine.run_container caller_line=14 kwargs={'name': u'test_test', 'environment': {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/_usr/sbin:/_usr/bin:/_usr/local/sbin:/_usr/local/bin', 'CPATH': '/usr/include:/usr/local/include:/_usr/include:/_usr/local/include', 'ANSIBLE_CONTAINER': 1, 'LD_LIBRARY_PATH': '/usr/lib:/usr/lib64:/_usr/lib:/_usr/lib64:/_usr/local/lib:/_usr/lib/x86_64-linux-gnu:/_usr/local/lib/x86_64-linux-gnu:/_lib/x86_64-linux-gnu:/_lib'}, 'working_dir': '/', 'command': 'sh -c "while true; do sleep 1; done"', 'user': 'root', 'volumes': {'': {u'bind': '', u'mode': 'rw'}, u'19a8336128cd7b27878ba9c72750572e8ae329a10dc7fb6b58edf33d3451ed24': {'bind': '/_usr', 'mode': 'ro'}, u'db11944853871e71bd81dfd91a1e0052c0a6298665b00d187fb11db7ba05ae66': {'bind': '/_lib', 'mode': 'ro'}}, 'entrypoint': [], 'privileged': True}
2017-10-05T11:57:19.259836 Removing keys                  [container.docker.engine] caller_file=/_ansible/container/docker/engine.py caller_func=run_kwargs_for_service caller_line=241 keys=[u'from', u'roles', 'defaults', 'links']
2017-10-05T11:57:19.266105 Running container in docker    [container.docker.engine] caller_file=/_ansible/container/docker/engine.py caller_func=run_container caller_line=265 image=u'sha256:2d696327ab2e15a3354ca258249358e244f3219eef76c653d0e6d3bd87f7830f' params={"environment": {"PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/_usr/sbin:/_usr/bin:/_usr/local/sbin:/_usr/local/bin", "CPATH": "/usr/include:/usr/local/include:/_usr/include:/_usr/local/include", "ANSIBLE_CONTAINER": 1, "LD_LIBRARY_PATH": "/usr/lib:/usr/lib64:/_usr/lib:/_usr/lib64:/_usr/local/lib:/_usr/lib/x86_64-linux-gnu:/_usr/local/lib/x86_64-linux-gnu:/_lib/x86_64-linux-gnu:/_lib"}, "entrypoint": [], "volumes": {"": {"bind": "", "mode": "rw"}, "19a8336128cd7b27878ba9c72750572e8ae329a10dc7fb6b58edf33d3451ed24": {"bind": "/_usr", "mode": "ro"}, "db11944853871e71bd81dfd91a1e0052c0a6298665b00d187fb11db7ba05ae66": {"bind": "/_lib", "mode": "ro"}}, "ports": {"3128": [null]}, "name": "test_test", "working_dir": "/", "command": "sh -c \"while true; do sleep 1; done\"", "user": "root", "privileged": true}
Traceback (most recent call last):
  File "/usr/local/bin/conductor", line 11, in <module>
    load_entry_point('ansible-container', 'console_scripts', 'conductor')()
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/cli.py", line 399, in conductor_commandline
    **params)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/core.py", line 800, in conductorcmd_build
    container_id = engine.run_container(cur_image_id, service_name, **run_kwargs)
  File "/_ansible/container/docker/engine.py", line 105, in __wrapped__
    return fn(self, *args, **kwargs)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/docker/engine.py", line 270, in run_container
    **run_kwargs
  File "/usr/local/lib/python2.7/dist-packages/docker/models/containers.py", line 708, in run
    detach=detach, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/models/containers.py", line 759, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/container.py", line 449, in create_container
    return self.create_container_from_config(config, name)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/container.py", line 460, in create_container_from_config
    return self._result(res, True)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 226, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 222, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("Invalid volume spec "": Invalid volume specification: ''")
2017-10-05T11:57:19.440283 Conductor terminated. Cleaning up. [container.docker.engine] caller_file=/usr/local/lib/python2.7/dist-packages/container/docker/engine.py caller_func=await_conductor_command caller_line=462 command_rc=1 conductor_id=u'e1cf33e9bd1f336c827a106a14e33a6037a73e5f89467546b46dfc4d948a003a' save_container=False
2017-10-05T11:57:19.881600 Conductor exited with status 1 [container.cli] caller_file=/usr/local/lib/python2.7/dist-packages/container/cli.py caller_func=__call__ caller_line=311
```

**Comment by hans-d** [comment]
last line before the error (reformatted to please the reader)
```
2017-10-05T11:57:19.266105 Running container in docker    [container.docker.engine] 
caller_file=/_ansible/container/docker/engine.py caller_func=run_container caller_line=265 image=u'sha256:2d696327ab2e15a3354ca258249358e244f3219eef76c653d0e6d3bd87f7830f' params={"environment": {"PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/_usr/sbin:/_usr/bin:/_usr/local/sbin:/_usr/local/bin", "CPATH": "/usr/include:/usr/local/include:/_usr/include:/_usr/local/include", "ANSIBLE_CONTAINER": 1, "LD_LIBRARY_PATH": "/usr/lib:/usr/lib64:/_usr/lib:/_usr/lib64:/_usr/local/lib:/_usr/lib/x86_64-linux-gnu:/_usr/local/lib/x86_64-linux-gnu:/_lib/x86_64-linux-gnu:/_lib"}, "entrypoint": [], 
"volumes": {
"": {"bind": "", "mode": "rw"},
"19a8336128cd7b27878ba9c72750572e8ae329a10dc7fb6b58edf33d3451ed24": {"bind": "/_usr", "mode": "ro"}, 
"db11944853871e71bd81dfd91a1e0052c0a6298665b00d187fb11db7ba05ae66": {"bind": "/_lib", "mode": "ro"}
}, "ports": {"3128": [null]}, "name": "test_test", "working_dir": "/", "command": "sh -c \"while true; do sleep 1; done\"", "user": "root", "privileged": true}
```
an empty volume is mounted here ....

**Comment by hans-d** [comment]
Reran without docker
```
ansible-container --project-path test build --roles-path roles
```
also on ubuntu 16.04, fails with same error

**Comment by hans-d** [comment]
seems introduced by 0.9.2

**Comment by chouseknecht** [comment]
@hans-d 

Thanks for using Ansible Container, and for sharing your feedback. 

Running Ansible Container inside a container is not currently on the road map. There are probably a bunch of things that won't work without some thought, and perhaps code change.

**Comment by hans-d** [comment]
@chouseknecht I'm tracking it down a bit more. I can reproduce it without running it in a docker-container

**Comment by hans-d** [comment]
ok, running inside docker works. It was how th container.yml produced some empty mount. Once sorted out, I'll create a new ticket for that
