### ISSUE TITLE
Another issue related to Error while fetching server API version: ('Connection aborted.', error(13, 'Permission denied'))

### ISSUE THREAD

**Issue by hadrien-toma** [ansible/ansible-container#761]
##### ISSUE TYPE
 - Bug Report

##### container.yml 
```
version: "2"
settings:

  conductor:
    # The Conductor container does the heavy lifting, and provides a portable
    # Python runtime for building your target containers. It should be derived
    # from the same distribution as you're building your target containers with.
    base: centos:7
    # roles_path:   # Specify a local path containing Ansible roles
    # volumes:      # Provide a list of volumes to mount
    # environment:  # List or mapping of environment variables

  # Set the name of the project. Defaults to basename of the project directory.
  # For built services, concatenated with service name to form the built image name.
  project_name: hello-ansible-container

  # The deployment_output_path is mounted to the Conductor container, and the 
  # `run` and `deployment` commands then write generated Ansible playbooks to it.
  # deployment_output_path: ./ansible-deployment

  # When using the k8s or openshift engines, use the following to authorize with the API.
  # Values set here will be passed to the Ansible modules. Any file paths will be mounted
  # to the conductor container, allowing the `run` command to access the API.
  #k8s_auth:
    # path to a K8s config file
    #config_file:
    # name of a context found within the config file
    #context:
    # URL for accessing the K8s API
    #host:
    # An API authentication token
    #api_key:
    # Path to a ca cert file
    #ssl_ca_cert:
    # Path to a cert file
    #cert_file:
    # Path to a key file
    #key_file:
    # boolean, indicating if SSL certs should be validated
    #verify_ssl:

  # When using the k8s or openshift engines, use the following to set the namespace.
  # If not set, the project name will be used. For openshift, the namespace maps to a project,
  # and description and display_name are supported.
  #k8s_namespace:
  #  name:
  #  description:
  #  display_name:

services: {}
  # Add your containers here, specifying the base image you want to build from.
  # To use this example, uncomment it and delete the curly braces after services key.
  # You may need to run `docker pull ubuntu:trusty` for this to work.

  # web:
  #   from: "centos:7"
  #   ports:
  #     - "80:80"
  #   command: ["/usr/bin/dumb-init", "/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
  #   dev_overrides:
  #     environment:
  #       - "DEBUG=1"
registries: {}
  # Add optional registries used for deployment. For example:
  #  google:
  #    url: https://gcr.io
  #    namespace: my-cool-project-xxxxxx
```

##### OS / ENVIRONMENT

```
Ansible Container, version 0.9.2
Linux, metamorph, 4.10.0-35-generic, #39~16.04.1-Ubuntu SMP Wed Sep 13 09:02:42 UTC 2017, x86_64
2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] /home/ash/github/hello-ansible-container/virtualenv/bin/python
ERROR	Unknown exception Error while fetching server API version: ('Connection aborted.', error(13, 'Permission denied'))	
Traceback (most recent call last):
  File "/home/ash/github/hello-ansible-container/virtualenv/local/lib/python2.7/site-packages/container/cli.py", line 299, in __call__
    getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
  File "/home/ash/github/hello-ansible-container/virtualenv/local/lib/python2.7/site-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/home/ash/github/hello-ansible-container/virtualenv/local/lib/python2.7/site-packages/container/core.py", line 465, in hostcmd_version
    engine_obj.print_version_info()
  File "/home/ash/github/hello-ansible-container/virtualenv/local/lib/python2.7/site-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/home/ash/github/hello-ansible-container/virtualenv/local/lib/python2.7/site-packages/container/docker/engine.py", line 255, in print_version_info
    print(json.dumps(self.client.info(), indent=2))
  File "/home/ash/github/hello-ansible-container/virtualenv/local/lib/python2.7/site-packages/container/docker/engine.py", line 164, in client
    self._client = docker.from_env(version='auto', timeout=timeout)
  File "/home/ash/github/hello-ansible-container/virtualenv/local/lib/python2.7/site-packages/docker/client.py", line 80, in from_env
    **kwargs_from_env(**kwargs))
  File "/home/ash/github/hello-ansible-container/virtualenv/local/lib/python2.7/site-packages/docker/client.py", line 37, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/home/ash/github/hello-ansible-container/virtualenv/local/lib/python2.7/site-packages/docker/api/client.py", line 147, in __init__
    self._version = self._retrieve_server_version()
  File "/home/ash/github/hello-ansible-container/virtualenv/local/lib/python2.7/site-packages/docker/api/client.py", line 174, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
DockerException: Error while fetching server API version: ('Connection aborted.', error(13, 'Permission denied'))
```
##### SUMMARY
I was following the official documentation but couldn't install `ansible-container` correctly. I have read many issues that talked about this error but none of the solutions proposed did the trick for me. Moreover this issue gives minimal commands to throws the error (others I saw treated about ahead errors).

##### STEPS TO REPRODUCE
```
mkdir hello-ansible-container
cd hello-ansible-container/
virtualenv virtualenv
source ./virtualenv/bin/activate
pip install ansible-container[docker]
ansible-container --debug version
```

##### EXPECTED RESULTS
Having a working `ansible-container` version.

##### ACTUAL RESULTS
The error given by the `ansible-container --debug version` section.

**Comment by hadrien-toma** [comment]
Alright, I simply forgot to add my user to the docker group.... if it is also your case, simply run these commands to solve the issue:
```
> sudo gpasswd -a $USER docker
> newgrp docker
```
