### ISSUE TITLE
Confusing error message when missing project_name

### ISSUE THREAD

**Issue by gaqzi** [ansible/ansible-container#770]
##### ISSUE TYPE
 - Bug Report

##### container.yml 
```
version: "2"
settings:
  conductor:
    base: centos:7
#  project_name: ci
services:
  agent:
    from: centos:7
    roles:
      - role: build-essentials
```

##### OS / ENVIRONMENT

```
Ansible Container, version 0.9.2
Darwin, djuproera.local, 17.0.0, Darwin Kernel Version 17.0.0: Thu Aug 24 21:48:19 PDT 2017; root:xnu-4570.1.46~2/RELEASE_X86_64, x86_64
2.7.11 (default, Dec 26 2015, 17:47:53) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] /Users/ba/.virtualenvs/ansible/bin/python2.7
{
  "ContainersPaused": 0, 
  "Labels": null, 
  "CgroupDriver": "cgroupfs", 
  "ContainersRunning": 1, 
  "ContainerdCommit": {
    "Expected": "06b9cb35161009dcb7123345749fef02f7cea8e0", 
    "ID": "06b9cb35161009dcb7123345749fef02f7cea8e0"
  }, 
  "InitBinary": "docker-init", 
  "NGoroutines": 35, 
  "Swarm": {
    "ControlAvailable": false, 
    "NodeID": "", 
    "Error": "", 
    "RemoteManagers": null, 
    "LocalNodeState": "inactive", 
    "NodeAddr": ""
  }, 
  "LoggingDriver": "json-file", 
  "OSType": "linux", 
  "HttpProxy": "", 
  "Runtimes": {
    "runc": {
      "path": "docker-runc"
    }
  }, 
  "DriverStatus": [
    [
      "Root Dir", 
      "/var/lib/docker/aufs"
    ], 
    [
      "Backing Filesystem", 
      "extfs"
    ], 
    [
      "Dirs", 
      "221"
    ], 
    [
      "Dirperm1 Supported", 
      "true"
    ]
  ], 
  "OperatingSystem": "Alpine Linux v3.5", 
  "Containers": 76, 
  "HttpsProxy": "", 
  "BridgeNfIp6tables": true, 
  "MemTotal": 2095874048, 
  "SecurityOptions": [
    "name=seccomp,profile=default"
  ], 
  "Driver": "aufs", 
  "IndexServerAddress": "https://index.docker.io/v1/", 
  "ClusterStore": "", 
  "InitCommit": {
    "Expected": "949e6fa", 
    "ID": "949e6fa"
  }, 
  "GenericResources": null, 
  "Isolation": "", 
  "SystemStatus": null, 
  "OomKillDisable": true, 
  "ClusterAdvertise": "", 
  "SystemTime": "2017-10-15T04:31:24.883889175Z", 
  "Name": "moby", 
  "CPUSet": true, 
  "RegistryConfig": {
    "AllowNondistributableArtifactsCIDRs": [], 
    "Mirrors": [], 
    "IndexConfigs": {
      "docker.io": {
        "Official": true, 
        "Name": "docker.io", 
        "Secure": true, 
        "Mirrors": []
      }
    }, 
    "AllowNondistributableArtifactsHostnames": [], 
    "InsecureRegistryCIDRs": [
      "127.0.0.0/8"
    ]
  }, 
  "DefaultRuntime": "runc", 
  "ContainersStopped": 75, 
  "NCPU": 4, 
  "NFd": 26, 
  "Architecture": "x86_64", 
  "KernelMemory": true, 
  "CpuCfsQuota": true, 
  "Debug": true, 
  "ID": "42WW:W6HC:TLHR:QMVX:5X34:XFNR:P3KV:3IAD:ZKQH:SYBC:EWPL:YDTD", 
  "IPv4Forwarding": true, 
  "KernelVersion": "4.9.49-moby", 
  "BridgeNfIptables": true, 
  "NoProxy": "*.local, 169.254/16", 
  "LiveRestoreEnabled": false, 
  "ServerVersion": "17.09.0-ce", 
  "CpuCfsPeriod": true, 
  "ExperimentalBuild": true, 
  "MemoryLimit": true, 
  "SwapLimit": true, 
  "Plugins": {
    "Volume": [
      "local"
    ], 
    "Network": [
      "bridge", 
      "host", 
      "ipvlan", 
      "macvlan", 
      "null", 
      "overlay"
    ], 
    "Authorization": null, 
    "Log": [
      "awslogs", 
      "fluentd", 
      "gcplogs", 
      "gelf", 
      "journald", 
      "json-file", 
      "logentries", 
      "splunk", 
      "syslog"
    ]
  }, 
  "Images": 93, 
  "DockerRootDir": "/var/lib/docker", 
  "NEventsListener": 1, 
  "CPUShares": true, 
  "RuncCommit": {
    "Expected": "3f2f8b84a77f73d38244dd690525642a72156c64", 
    "ID": "3f2f8b84a77f73d38244dd690525642a72156c64"
  }
}
{
  "KernelVersion": "4.9.49-moby", 
  "Arch": "amd64", 
  "BuildTime": "2017-09-26T22:45:38.000000000+00:00", 
  "ApiVersion": "1.32", 
  "Version": "17.09.0-ce", 
  "MinAPIVersion": "1.12", 
  "GitCommit": "afdb6d4", 
  "Os": "linux", 
  "Experimental": true, 
  "GoVersion": "go1.8.3"
}

```
##### SUMMARY

When running `ansible-container build` I get a stacktrace like this:

```
ERROR	Unknown exception
Traceback (most recent call last):
  File "/Users/ba/.virtualenvs/ansible/lib/python2.7/site-packages/container/cli.py", line 299, in __call__
    getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
  File "/Users/ba/.virtualenvs/ansible/lib/python2.7/site-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/Users/ba/.virtualenvs/ansible/lib/python2.7/site-packages/container/core.py", line 159, in hostcmd_build
    conductor_image_id = engine_obj.get_latest_image_id_for_service('conductor')
  File "/Users/ba/.virtualenvs/ansible/lib/python2.7/site-packages/container/docker/engine.py", line 555, in get_latest_image_id_for_service
    image = self.get_latest_image_for_service(service_name)
  File "/Users/ba/.virtualenvs/ansible/lib/python2.7/site-packages/container/docker/engine.py", line 563, in get_latest_image_for_service
    '%s:latest' % self.image_name_for_service(service_name))
  File "/Users/ba/.virtualenvs/ansible/lib/python2.7/site-packages/docker/models/images.py", line 204, in get
    return self.prepare_model(self.client.api.inspect_image(name))
  File "/Users/ba/.virtualenvs/ansible/lib/python2.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/Users/ba/.virtualenvs/ansible/lib/python2.7/site-packages/docker/api/image.py", line 262, in inspect_image
    self._get(self._url("/images/{0}/json", image)), True
  File "/Users/ba/.virtualenvs/ansible/lib/python2.7/site-packages/docker/api/client.py", line 226, in _result
    self._raise_for_status(response)
  File "/Users/ba/.virtualenvs/ansible/lib/python2.7/site-packages/docker/api/client.py", line 222, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/Users/ba/.virtualenvs/ansible/lib/python2.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
APIError: 400 Client Error: Bad Request ("no such image: .playbooks-conductor:latest: invalid reference format")
```

Where `.playbooks` is the folder I have all my Ansible stuff. 
##### STEPS TO REPRODUCE
1. Use the `container.yml` above
2. Run `ansible-container build`
3. See the stack trace above
4. Uncomment the `project_name`
5. Run `ansible-container build`
6. See it go past this problem

I noticed what was wrong by doing a diff between ansible-container init and my own container.yml but it would've been nice if there was an error message leading me there. :)

**Comment by gerl1ng** [comment]
Hello gaqzi,

I just reproduced your error. This is an edge-case you ran into. Usually the default project name is the folder your file is placed at. It seems that your folder is .playbooks and the container are not allowed to start with a . (dot) or a leading -.

How should this issue be fixed?

1. Remove leading chars from the cwd and project_name until a-zA-Z0-9 is at the leading char? (Next edge-case if container.yml is placed at /. So also add a better error message.)

2. Just add a more verbose and better error message?

**Comment by TomasTomecek** [comment]
We should probably run the `project-name` through a regex and report a sensible error if the validation fails.
