### ISSUE TITLE
Ansible Container Exception : Error while building image using ansible container build

### ISSUE THREAD

**Issue by Manigunner** [ansible/ansible-container#783]
#

 - Bug Report

container.yml 
version: '2'
settings:
  conductor_base: p0xvoaxa0001.xxxxxx.com:5000/nflott/node:alpine
services:
  ansible.node-container:
    roles:
    - node_container
    ports:
    - '3001:3001'
    user: node

```

OS / ENVIRONMENT
Ansible Container, version 0.9.3rc0
Linux, d1xvoaxa0027.xxxxx.com, 3.10.0-327.13.1.el7.x86_64, #1 SMP Mon Feb 29 13:22:02 EST 2016, x86_64
2.7.5 (default, May  3 2017, 07:55:04)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-14)] /usr/bin/python
ERROR   The connection to Docker was aborted. Check your Docker environment configuration.
ErrorMessage: Error while fetching server API version: ('Connection aborted.', error(13, 'Permission denied'))


```
##### SUMMARY

I am building a nodejs image using ansible container and while am building it , its failing with error couldnt find conductor from container and also failed to get images from server
##### STEPS TO REPRODUCE
sudo ansible-container --debug build

##### EXPECTED RESULTS
Image should be build successfully

##### ACTUAL RESULTS
$ sudo ansible-container --debug build
2017-11-03T06:57:27.205719 The default type is            [container.config] caller_file=/app/ansible-container/container/config.py caller_func=_resolve_defaults caller_line=248 config=<class 'ruamel.yaml.comments.CommentedMap'> defaults=<type '_ordereddict.ordereddict'>
2017-11-03T06:57:27.207514 Getting environment variables... [container.config] caller_file=/app/ansible-container/container/config.py caller_func=_get_environment_variables caller_line=264
2017-11-03T06:57:27.209045 Read environment variables     [container.config] caller_file=/app/ansible-container/container/config.py caller_func=_get_environment_variables caller_line=269 env_vars={}
2017-11-03T06:57:27.210417 Resolved template variables    [container.config] caller_file=/app/ansible-container/container/config.py caller_func=_resolve_defaults caller_line=253 template_vars={}
2017-11-03T06:57:27.211776 Parsed config                  [container.config] caller_file=/app/ansible-container/container/config.py caller_func=set_env caller_line=189 config={"version": "2", "settings": {"conductor_base": "p0xvoaxa0001.xxxx.com:5000/nflott/node:alpine", "pwd": "/home/mt801t/ansicon/ansible-containers/ansible_container_dotcom"}, "services": {"ansible.node-container": {"roles": ["node_container"], "ports": ["3001:3001"], "user": "node", "command": ["/usr/bin/dumb-init", "/app/nflott/node/conf", "app/nflott/node/temp", "app/nflott/node/archive"]}}, "registries": {}, "defaults": {}}
2017-11-03T06:57:27.213093 Loading engine capabilities    [container.utils.loader] caller_file=/app/ansible-container/container/utils/loader.py caller_func=load_engine caller_line=14 capabilities=['BUILD', 'RUN'] engine=docker
2017-11-03T06:57:27.247819 Setting Docker client timeout to 60 [container.docker.engine] caller_file=/app/ansible-container/container/docker/engine.py caller_func=get_timeout caller_line=123
2017-11-03T06:57:27.271920 Could not find container for conductor [container.docker.engine] all_containers=[<Container: 39c3c78e73>, <Container: c5f7625f26>] caller_file=/app/ansible-container/container/docker/engine.py caller_func=get_container_id_for_service caller_line=535 container=u'ansible_container_dotcom_conductor'
2017-11-03T06:57:27.300022 Could not find the latest image for service, searching for other tags with same image name [container.docker.engine] caller_file=/app/ansible-container/container/docker/engine.py caller_func=get_latest_image_for_service caller_line=574 image_name=u'ansible_container_dotcom-conductor' service=conductor
2017-11-03T06:57:27.303813 Call: Engine.build_conductor_image [container.docker.engine] args=('/home/mt801t/ansicon/ansible-containers/ansible_container_dotcom', 'p0xvoaxa0001.xxxx.com:5000/nflott/node:alpine') caller_file=/app/ansible-container/container/docker/engine.py caller_func=Engine.build_conductor_image caller_line=23 kwargs={'environment': [], 'cache': True}
2017-11-03T06:57:27.305762 Using temporary directory      [container.utils.temp] caller_file=/app/ansible-container/container/utils/temp.py caller_func=__enter__ caller_line=17 path=/tmp/tmpSsqIKf
2017-11-03T06:57:27.306993 Building Docker Engine context... [container.docker.engine] caller_file=/app/ansible-container/container/docker/engine.py caller_func=build_conductor_image caller_line=979
2017-11-03T06:57:27.368002 Rendered Jinja Template:       [container.utils] body=FROM p0xvoaxa0001.xxxxx.com:5000/nflott/node:alpine
ENV ANSIBLE_CONTAINER=1

RUN (curl https://bootstrap.pypa.io/get-pip.py | python - --no-cache-dir ) && \
    mkdir -p /etc/ansible/roles /_ansible/src && \
    (curl https://get.docker.com/builds/Linux/x86_64/docker-17.04.0-ce.tgz \
       | tar -zxC /usr/local/bin/ --strip-components=1 docker/docker )

# The COPY here will break cache if the version of Ansible Container changed
COPY /container-src /_ansible/container
RUN cd /_ansible && \
    pip install --no-cache-dir -r container/conductor-build/conductor-requirements.txt && \
    PYTHONPATH=. LC_ALL="en_US.UTF-8" python container/conductor-build/setup.py develop -v -N && \
    ansible-galaxy install -p /etc/ansible/roles -r container/conductor-build/conductor-requirements.yml

 caller_file=/app/ansible-container/container/utils/__init__.py caller_func=jinja_render_to_temp caller_line=84
2017-11-03T06:57:27.380300 Rendered Jinja Template:       [container.utils] body=FROM container-conductor-p0xvoaxa0001.xxxxx.com-5000/nflott/node-alpine:0.9.3rc0

 caller_file=/app/ansible-container/container/utils/__init__.py caller_func=jinja_render_to_temp caller_line=84
2017-11-03T06:57:27.380300 Rendered Jinja Template:       [container.utils] body=FROM container-conductor-p0xvoaxa0001.xxxxx.com-5000/nflott/node-alpine:0.9.3rc0

VOLUME /usr

# The COPY here will break cache if the requirements or ansible.cfg has changed
COPY /build-src /_ansible/build

RUN ansible-galaxy install -p /etc/ansible/roles -r /_ansible/build/requirements.yml && \
cp /_ansible/build/ansible.cfg /etc/ansible/ansible.cfg

 caller_file=/app/ansible-container/container/utils/__init__.py caller_func=jinja_render_to_temp caller_line=84
2017-11-03T06:57:27.383084 Context manifest:              [container.docker.engine] caller_file=/app/ansible-container/container/docker/engine.py caller_func=build_conductor_image caller_line=1046
2017-11-03T06:57:27.383492 tarball item: build-src/ansible.cfg (144 bytes) [container.docker.engine] bytes=144 file=build-src/ansible.cfg
2017-11-03T06:57:27.383931 tarball item: build-src/ansible-requirements.txt (130 bytes) [container.docker.engine] bytes=130 file=build-src/ansible-requirements.txt
2017-11-03T06:57:27.384325 tarball item: build-src/requirements.yml (31 bytes) [container.docker.engine] bytes=31 file=build-src/requirements.yml
2017-11-03T06:57:27.384727 tarball item: build-src/.touch (0 bytes) [container.docker.engine] bytes=0 file=build-src/.touch
2017-11-03T06:57:27.385168 tarball item: contrib/get-pip.py (1595409 bytes) [container.docker.engine] bytes=1595409 file=contrib/get-pip.py
2017-11-03T06:57:27.385577 tarball item: container-src (0 bytes) [container.docker.engine] bytes=0L file=container-src
2017-11-03T06:57:27.386041 tarball item: container-src/utils (0 bytes) [container.docker.engine] bytes=0L file=container-src/utils
2017-11-03T06:57:27.386378 tarball item: container-src/utils/visibility.py (3270 bytes) [container.docker.engine] bytes=3270 file=container-src/utils/visibility.py
2017-11-03T06:57:27.386648 tarball item: container-src/utils/ordereddict.py (678 bytes) [container.docker.engine] bytes=678 file=container-src/utils/ordereddict.py
2017-11-03T06:57:27.386937 tarball item: container-src/utils/__init__.py (12915 bytes) [container.docker.engine] bytes=12915 file=container-src/utils/__init__.py
2017-11-03T06:57:27.387208 tarball item: container-src/utils/logmux.pyc (2469 bytes) [container.docker.engine] bytes=2469 file=container-src/utils/logmux.pyc
2017-11-03T06:57:27.387475 tarball item: container-src/utils/_text.py (12304 bytes) [container.docker.engine] bytes=12304 file=container-src/utils/_text.py
2017-11-03T06:57:27.387740 tarball item: container-src/utils/ordereddict.pyc (885 bytes) [container.docker.engine] bytes=885 file=container-src/utils/ordereddict.pyc
2017-11-03T06:57:27.388029 tarball item: container-src/utils/logmux.py (1313 bytes) [container.docker.engine] bytes=1313 file=container-src/utils/logmux.py
2017-11-03T06:57:27.388296 tarball item: container-src/utils/_text.pyc (8766 bytes) [container.docker.engine] bytes=8766 file=container-src/utils/_text.pyc
2017-11-03T06:57:27.388561 tarball item: container-src/utils/temp.py (698 bytes) [container.docker.engine] bytes=698 file=container-src/utils/temp.py
2017-11-03T06:57:27.388838 tarball item: container-src/utils/loader.py (906 bytes) [container.docker.engine] bytes=906 file=container-src/utils/loader.py
2017-11-03T06:57:27.389125 tarball item: container-src/utils/galaxy.py (8120 bytes) [container.docker.engine] bytes=8120 file=container-src/utils/galaxy.py
2017-11-03T06:57:27.389390 tarball item: container-src/utils/__init__.pyc (13066 bytes) [container.docker.engine] bytes=13066 file=container-src/utils/__init__.pyc
2017-11-03T06:57:27.389656 tarball item: container-src/utils/loader.pyc (1150 bytes) [container.docker.engine] bytes=1150 file=container-src/utils/loader.pyc
2017-11-03T06:57:27.389974 tarball item: container-src/utils/temp.pyc (1318 bytes) [container.docker.engine] bytes=1318 file=container-src/utils/temp.pyc
2017-11-03T06:57:27.390241 tarball item: container-src/utils/visibility.pyc (4027 bytes) [container.docker.engine] bytes=4027 file=container-src/utils/visibility.pyc
2017-11-03T06:57:27.390506 tarball item: container-src/__init__.py (950 bytes) [container.docker.engine] bytes=950 file=container-src/__init__.py
2017-11-03T06:57:27.390769 tarball item: container-src/config.py (18435 bytes) [container.docker.engine] bytes=18435 file=container-src/config.py
2017-11-03T06:57:27.391053 tarball item: container-src/engine.py (6740 bytes) [container.docker.engine] bytes=6740 file=container-src/engine.py
2017-11-03T06:57:27.391318 tarball item: container-src/cli.py (23236 bytes) [container.docker.engine] bytes=23236 file=container-src/cli.py
2017-11-03T06:57:27.391581 tarball item: container-src/docker (0 bytes) [container.docker.engine] bytes=0L file=container-src/docker
2017-11-03T06:57:27.391844 tarball item: container-src/docker/tests (0 bytes) [container.docker.engine] bytes=0L file=container-src/docker/tests
2017-11-03T06:57:27.392129 tarball item: container-src/docker/tests/import (0 bytes) [container.docker.engine] bytes=0L file=container-src/docker/tests/import
2017-11-03T06:57:27.392395 tarball item: container-src/docker/tests/import/two-fish (0 bytes) [container.docker.engine] bytes=0L file=container-src/docker/tests/import/two-fish
2017-11-03T06:57:27.392659 tarball item: container-src/docker/tests/import/two-fish/green-eggs (0 bytes) [container.docker.engine] bytes=0L file=container-src/docker/tests/import/two-fish/green-eggs
2017-11-03T06:57:27.392981 tarball item: container-src/docker/tests/import/two-fish/green-eggs/ham.txt (5 bytes) [container.docker.engine] bytes=5 file=container-src/docker/tests/import/two-fish/green-eggs/ham.txt
2017-11-03T06:57:27.393249 tarball item: container-src/docker/tests/import/two-fish/who.txt (7 bytes) [container.docker.engine] bytes=7 file=container-src/docker/tests/import/two-fish/who.txt
2017-11-03T06:57:27.393512 tarball item: container-src/docker/tests/import/red-fish (0 bytes) [container.docker.engine] bytes=0L file=container-src/docker/tests/import/red-fish
2017-11-03T06:57:27.393775 tarball item: container-src/docker/tests/import/red-fish/lulz.txt (10 bytes) [container.docker.engine] bytes=10 file=container-src/docker/tests/import/red-fish/lulz.txt
2017-11-03T06:57:27.394076 tarball item: container-src/docker/tests/import/lulz.tgz (59072 bytes) [container.docker.engine] bytes=59072 file=container-src/docker/tests/import/lulz.tgz
2017-11-03T06:57:27.394341 tarball item: container-src/docker/tests/import/one-fish.txt (6 bytes) [container.docker.engine] bytes=6 file=container-src/docker/tests/import/one-fish.txt
2017-11-03T06:57:27.394909 tarball item: container-src/docker/tests/import/Dockerfile (1151 bytes) [container.docker.engine] bytes=1151 file=container-src/docker/tests/import/Dockerfile
2017-11-03T06:57:27.395182 tarball item: container-src/docker/tests/import/blue-fish.txt (10 bytes) [container.docker.engine] bytes=10 file=container-src/docker/tests/import/blue-fish.txt
2017-11-03T06:57:27.395447 tarball item: container-src/docker/__init__.py (205 bytes) [container.docker.engine] bytes=205 file=container-src/docker/__init__.py
2017-11-03T06:57:27.395711 tarball item: container-src/docker/config.py (2384 bytes) [container.docker.engine] bytes=2384 file=container-src/docker/config.py
2017-11-03T06:57:27.395997 tarball item: container-src/docker/engine.py (50597 bytes) [container.docker.engine] bytes=50597 file=container-src/docker/engine.py
2017-11-03T06:57:27.396264 tarball item: container-src/docker/templates (0 bytes) [container.docker.engine] bytes=0L file=container-src/docker/templates
2017-11-03T06:57:27.396529 tarball item: container-src/docker/templates/conductor-src-dockerfile.j2 (3021 bytes) [container.docker.engine] bytes=3021 file=container-src/docker/templates/conductor-src-dockerfile.j2
2017-11-03T06:57:27.396805 tarball item: container-src/docker/templates/conductor-local-dockerfile.j2 (348 bytes) [container.docker.engine] bytes=348 file=container-src/docker/templates/conductor-local-dockerfile.j2
2017-11-03T06:57:27.397096 tarball item: container-src/docker/importer.py (24838 bytes) [container.docker.engine] bytes=24838 file=container-src/docker/importer.py
2017-11-03T06:57:27.397362 tarball item: container-src/docker/deploy.py (248 bytes) [container.docker.engine] bytes=248 file=container-src/docker/deploy.py
2017-11-03T06:57:27.397627 tarball item: container-src/docker/secrets.py (5255 bytes) [container.docker.engine] bytes=5255 file=container-src/docker/secrets.py
2017-11-03T06:57:27.398114 tarball item: container-src/docker/engine.pyc (39757 bytes) [container.docker.engine] bytes=39757 file=container-src/docker/engine.pyc
2017-11-03T06:57:27.398404 tarball item: container-src/docker/__init__.pyc (317 bytes) [container.docker.engine] bytes=317 file=container-src/docker/__init__.pyc
2017-11-03T06:57:27.398674 tarball item: container-src/docker/files (0 bytes) [container.docker.engine] bytes=0L file=container-src/docker/files
2017-11-03T06:57:27.399060 tarball item: container-src/docker/files/get-pip.py (1595409 bytes) [container.docker.engine] bytes=1595409 file=container-src/docker/files/get-pip.py
2017-11-03T06:57:27.399417 tarball item: container-src/docker/config.pyc (2296 bytes) [container.docker.engine] bytes=2296 file=container-src/docker/config.pyc
2017-11-03T06:57:27.399749 tarball item: container-src/docker/secrets.pyc (5023 bytes) [container.docker.engine] bytes=5023 file=container-src/docker/secrets.pyc
2017-11-03T06:57:27.400107 tarball item: container-src/templates (0 bytes) [container.docker.engine] bytes=0L file=container-src/templates
2017-11-03T06:57:27.400453 tarball item: container-src/templates/role (0 bytes) [container.docker.engine] bytes=0L file=container-src/templates/role
2017-11-03T06:57:27.400724 tarball item: container-src/templates/role/test (0 bytes) [container.docker.engine] bytes=0L file=container-src/templates/role/test
2017-11-03T06:57:27.401064 tarball item: container-src/templates/role/test/test.j2.yml (81 bytes) [container.docker.engine] bytes=81 file=container-src/templates/role/test/test.j2.yml
2017-11-03T06:57:27.401333 tarball item: container-src/templates/role/README.j2.md (1287 bytes) [container.docker.engine] bytes=1287 file=container-src/templates/role/README.j2.md
2017-11-03T06:57:27.401598 tarball item: container-src/templates/role/meta (0 bytes) [container.docker.engine] bytes=0L file=container-src/templates/role/meta
2017-11-03T06:57:27.401893 tarball item: container-src/templates/role/meta/main.j2.yml (3220 bytes) [container.docker.engine] bytes=3220 file=container-src/templates/role/meta/main.j2.yml
2017-11-03T06:57:27.402178 tarball item: container-src/templates/role/defaults (0 bytes) [container.docker.engine] bytes=0L file=container-src/templates/role/defaults
2017-11-03T06:57:27.402576 tarball item: container-src/templates/role/defaults/main.j2.yml (55 bytes) [container.docker.engine] bytes=55 file=container-src/templates/role/defaults/main.j2.yml
2017-11-03T06:57:27.402847 tarball item: container-src/templates/role/.travis.j2.yml (540 bytes) [container.docker.engine] bytes=540 file=container-src/templates/role/.travis.j2.yml
2017-11-03T06:57:27.403136 tarball item: container-src/templates/hosts.j2 (90 bytes) [container.docker.engine] bytes=90 file=container-src/templates/hosts.j2
2017-11-03T06:57:27.403400 tarball item: container-src/templates/init (0 bytes) [container.docker.engine] bytes=0L file=container-src/templates/init
2017-11-03T06:57:27.403666 tarball item: container-src/templates/init/ansible.j2.cfg (145 bytes) [container.docker.engine] bytes=145 file=container-src/templates/init/ansible.j2.cfg
2017-11-03T06:57:27.403951 tarball item: container-src/templates/init/ansible-requirements.j2.txt (131 bytes) [container.docker.engine] bytes=131 file=container-src/templates/init/ansible-requirements.j2.txt
2017-11-03T06:57:27.404220 tarball item: container-src/templates/init/meta.j2.yml (1231 bytes) [container.docker.engine] bytes=1231 file=container-src/templates/init/meta.j2.yml
2017-11-03T06:57:27.404485 tarball item: container-src/templates/init/requirements.j2.yml (299 bytes) [container.docker.engine] bytes=299 file=container-src/templates/init/requirements.j2.yml
2017-11-03T06:57:27.404763 tarball item: container-src/templates/init/container.j2.yml (2514 bytes) [container.docker.engine] bytes=2514 file=container-src/templates/init/container.j2.yml
2017-11-03T06:57:27.405050 tarball item: container-src/templates/restart-docker-compose.j2.yml (75 bytes) [container.docker.engine] bytes=75 file=container-src/templates/restart-docker-compose.j2.yml
2017-11-03T06:57:27.405317 tarball item: container-src/templates/stop-docker-compose.j2.yml (75 bytes) [container.docker.engine] bytes=75 file=container-src/templates/stop-docker-compose.j2.yml
2017-11-03T06:57:27.405582 tarball item: container-src/templates/ansible-dockerfile.j2 (1194 bytes) [container.docker.engine] bytes=1194 file=container-src/templates/ansible-dockerfile.j2
2017-11-03T06:57:27.405872 tarball item: container-src/templates/ansible-container-inventory.py (1230 bytes) [container.docker.engine] bytes=1230 file=container-src/templates/ansible-container-inventory.py
2017-11-03T06:57:27.406177 tarball item: container-src/templates/wait_on_host.py (2365 bytes) [container.docker.engine] bytes=2365 file=container-src/templates/wait_on_host.py
2017-11-03T06:57:27.406443 tarball item: container-src/templates/ansible.cfg (41 bytes) [container.docker.engine] bytes=41 file=container-src/templates/ansible.cfg
2017-11-03T06:57:27.406706 tarball item: container-src/templates/builder.sh (620 bytes) [container.docker.engine] bytes=620 file=container-src/templates/builder.sh
2017-11-03T06:57:27.406991 tarball item: container-src/templates/install-docker-compose.j2.yml (712 bytes) [container.docker.engine] bytes=712 file=container-src/templates/install-docker-compose.j2.yml
2017-11-03T06:57:27.407260 tarball item: container-src/templates/compose_versioned.j2.yml (237 bytes) [container.docker.engine] bytes=237 file=container-src/templates/compose_versioned.j2.yml
2017-11-03T06:57:27.407525 tarball item: container-src/templates/run-docker-compose.j2.yml (75 bytes) [container.docker.engine] bytes=75 file=container-src/templates/run-docker-compose.j2.yml
2017-11-03T06:57:27.407788 tarball item: container-src/openshift (0 bytes) [container.docker.engine] bytes=0L file=container-src/openshift
2017-11-03T06:57:27.408074 tarball item: container-src/openshift/__init__.py (196 bytes) [container.docker.engine] bytes=196 file=container-src/openshift/__init__.py
2017-11-03T06:57:27.408337 tarball item: container-src/openshift/config.py (427 bytes) [container.docker.engine] bytes=427 file=container-src/openshift/config.py
2017-11-03T06:57:27.408600 tarball item: container-src/openshift/engine.py (2207 bytes) [container.docker.engine] bytes=2207 file=container-src/openshift/engine.py
2017-11-03T06:57:27.408893 tarball item: container-src/openshift/deploy.py (6302 bytes) [container.docker.engine] bytes=6302 file=container-src/openshift/deploy.py
2017-11-03T06:57:27.409163 tarball item: container-src/core.py (43494 bytes) [container.docker.engine] bytes=43494 file=container-src/core.py
2017-11-03T06:57:27.409426 tarball item: container-src/exceptions.pyc (5797 bytes) [container.docker.engine] bytes=5797 file=container-src/exceptions.pyc
2017-11-03T06:57:27.409689 tarball item: container-src/engine.pyc (10155 bytes) [container.docker.engine] bytes=10155 file=container-src/engine.pyc
2017-11-03T06:57:27.410062 tarball item: container-src/k8s (0 bytes) [container.docker.engine] bytes=0L file=container-src/k8s
2017-11-03T06:57:27.410376 tarball item: container-src/k8s/__init__.py (196 bytes) [container.docker.engine] bytes=196 file=container-src/k8s/__init__.py
2017-11-03T06:57:27.410644 tarball item: container-src/k8s/config.py (660 bytes) [container.docker.engine] bytes=660 file=container-src/k8s/config.py
2017-11-03T06:57:27.410934 tarball item: container-src/k8s/engine.py (1276 bytes) [container.docker.engine] bytes=1276 file=container-src/k8s/engine.py
2017-11-03T06:57:27.411200 tarball item: container-src/k8s/base_config.py (932 bytes) [container.docker.engine] bytes=932 file=container-src/k8s/base_config.py
2017-11-03T06:57:27.411463 tarball item: container-src/k8s/deploy.py (1903 bytes) [container.docker.engine] bytes=1903 file=container-src/k8s/deploy.py
2017-11-03T06:57:27.411725 tarball item: container-src/k8s/base_deploy.py (34402 bytes) [container.docker.engine] bytes=34402 file=container-src/k8s/base_deploy.py
2017-11-03T06:57:27.412009 tarball item: container-src/k8s/base_engine.py (10144 bytes) [container.docker.engine] bytes=10144 file=container-src/k8s/base_engine.py
2017-11-03T06:57:27.412275 tarball item: container-src/cli.pyc (17924 bytes) [container.docker.engine] bytes=17924 file=container-src/cli.pyc
2017-11-03T06:57:27.412538 tarball item: container-src/__init__.pyc (1229 bytes) [container.docker.engine] bytes=1229 file=container-src/__init__.pyc
2017-11-03T06:57:27.412811 tarball item: container-src/core.pyc (30389 bytes) [container.docker.engine] bytes=30389 file=container-src/core.pyc
2017-11-03T06:57:27.413099 tarball item: container-src/config.pyc (16835 bytes) [container.docker.engine] bytes=16835 file=container-src/config.pyc
2017-11-03T06:57:27.413386 tarball item: container-src/exceptions.py (2319 bytes) [container.docker.engine] bytes=2319 file=container-src/exceptions.py
2017-11-03T06:57:27.413652 tarball item: container-src/conductor-build/setup.py (4628 bytes) [container.docker.engine] bytes=4628 file=container-src/conductor-build/setup.py
2017-11-03T06:57:27.413954 tarball item: container-src/conductor-build/conductor-requirements.txt (274 bytes) [container.docker.engine] bytes=274 file=container-src/conductor-build/conductor-requirements.txt
2017-11-03T06:57:27.414223 tarball item: container-src/conductor-build/conductor-requirements.yml (60 bytes) [container.docker.engine] bytes=60 file=container-src/conductor-build/conductor-requirements.yml
2017-11-03T06:57:27.414489 tarball item: Dockerfile (802 bytes) [container.docker.engine] bytes=802 file=Dockerfile
2017-11-03T06:57:27.414752 tarball item: build-src/ansible.cfg (144 bytes) [container.docker.engine] bytes=144 file=build-src/ansible.cfg
2017-11-03T06:57:27.415038 tarball item: build-src/ansible-requirements.txt (130 bytes) [container.docker.engine] bytes=130 file=build-src/ansible-requirements.txt
2017-11-03T06:57:27.415303 tarball item: build-src/requirements.yml (31 bytes) [container.docker.engine] bytes=31 file=build-src/requirements.yml
2017-11-03T06:57:27.415566 tarball item: build-src/.touch (0 bytes) [container.docker.engine] bytes=0 file=build-src/.touch
2017-11-03T06:57:27.415828 tarball item: Dockerfile (361 bytes) [container.docker.engine] bytes=361 file=Dockerfile
2017-11-03T06:57:27.417338 Starting Docker build of Ansible Container Conductor image (please be patient)... [container.docker.engine] caller_file=/app/ansible-container/container/docker/engine.py caller_func=build_conductor_image caller_line=1054
Step 1/4 : FROM container-conductor-p0xvoaxa0001.xxxx.com-5000/nflott/node-alpine:0.9.3rc0
2017-11-03T06:57:27.520748 Cleaning up temporary directory [container.utils.temp] caller_file=/app/ansible-container/container/utils/temp.py caller_func=__exit__ caller_line=22 path=/tmp/tmpSsqIKf
2017-11-03T06:57:27.522160 Unknown exception Error building conductor image: Get https://container-conductor-p0xvoaxa0001.xxxx.com-5000/v1/_ping: dial tcp: lookup container-conductor-p0xvoaxa0001.xxxx.com-5000 on 147.22.57.1:53: no such host [container.cli] caller_file=/usr/lib/python2.7/site-packages/structlog/stdlib.py caller_func=exception caller_line=95
Traceback (most recent call last):
  File "/app/ansible-container/container/cli.py", line 299, in __call__
    getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
  File "/app/ansible-container/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/app/ansible-container/container/core.py", line 184, in hostcmd_build
    environment=env_vars
  File "/app/ansible-container/container/docker/engine.py", line 106, in __wrapped__
    return fn(self, *args, **kwargs)
  File "/app/ansible-container/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/app/ansible-container/container/docker/engine.py", line 1070, in build_conductor_image
    "Error building conductor image: {0}".format(line['errorDetail']['message']))
AnsibleContainerException: Error building conductor image: Get https://container-conductor-p0xvoaxa0001.xxxxx.com-5000/v1/_ping: dial tcp: lookup container-conductor-p0xvoaxa0001.xxxx.com-5000 on 147.22.57.1:53: no such host

Please check the logs and help in resolving the issue

**Comment by TomasTomecek** [comment]
seems like a typo in the registry name, shouldn't it be:
```diff
-container-conductor-p0xvoaxa0001.directv.com-5000
+container-conductor-p0xvoaxa0001.directv.com:5000
```

You should also be able to pull the base using docker:
```
$ docker pull container-conductor-p0xvoaxa0001.directv.com-5000/nflott/node-alpine:0.9.3rc0
```

**Comment by chouseknecht** [comment]
@Manigunner 

Take a look at [Conductor Container](http://docs.ansible.com/ansible-container/conductor.html) in our docs. It's expected that the base image for the conductor is one of the pre-baked images available on Docker Hub. 

You can also build your own conductor base image. And if you do, we expect the image name to match the format `container-conductor-$DISTRO-$TAG:$ANSIBLE_CONTAINER_VERSION`.
