### ISSUE TITLE
ansible-container build can't resolved registry.access.redhat.com repo

### ISSUE THREAD

**Issue by wannaknowmo** [ansible/ansible-container#799]
##### ISSUE TYPE
 - Bug Report
##### container.yml 
```
settings:
  conductor_base: registry.access.redhat.com/rhel7
services:
  jenkins:
    roles:
    - jenkins
```

##### OS / ENVIRONMENT

```
Ansible Container, version 0.9.2
Linux, XXXX, 3.10.0-693.5.2.el7.x86_64, #1 SMP Fri Oct 13 10:46:25 EDT 2017, x86_64
2.7.5 (default, May  3 2017, 07:55:04)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-14)] /root/ansible-container/bin/python2
{
  "ContainersPaused": 0,
  "Labels": null,
  "CgroupDriver": "cgroupfs",
  "ContainersRunning": 10,
  "ContainerdCommit": {
    "Expected": "06b9cb35161009dcb7123345749fef02f7cea8e0",
    "ID": "06b9cb35161009dcb7123345749fef02f7cea8e0"
  },
  "InitBinary": "docker-init",
  "NGoroutines": 368,
  "Swarm": {
    "Managers": 1,
    "ControlAvailable": true,
    "NodeID": "ayfm6u6hrh73i3lit2uyuxeo3",
    "Cluster": {
      "RootRotationInProgress": false,
      "TLSInfo": {
        "CertIssuerSubject": "MBMxETAPBgNVBAMTCHN3YXJtLWNh",
        "CertIssuerPublicKey": "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEOUOIPLc2YvkU3Xg02l8xqhqwybIAmW2n4dGPupuQwpeov7IHdnvSBCMuAxk326qF68FRLHRA4GZ1LPw96WLGJA==",
        "TrustRoot": "-----BEGIN CERTIFICATE-----\nXXXXX\n-----END CERTIFICATE-----\n"
      },
      "ID": "a8p8z8u5xv91cxe8oqs8gxvih",
      "Version": {
        "Index": 768865
      },
      "UpdatedAt": "2017-11-22T13:34:21.697652409Z",
      "Spec": {
        "Name": "default",
        "Labels": {},
        "TaskDefaults": {},
        "Orchestration": {
          "TaskHistoryRetentionLimit": 5
        },
        "EncryptionConfig": {
          "AutoLockManagers": false
        },
        "Raft": {
          "HeartbeatTick": 1,
          "LogEntriesForSlowFollowers": 500,
          "KeepOldSnapshots": 0,
          "ElectionTick": 3,
          "SnapshotInterval": 10000
        },
        "CAConfig": {
          "NodeCertExpiry": 7776000000000000
        },
        "Dispatcher": {
          "HeartbeatPeriod": 5000000000
        }
      },
      "CreatedAt": "2017-11-15T21:09:55.231969743Z"
    },
    "Nodes": 9,
    "Error": "",
    "RemoteManagers": [
      {
        "NodeID": "ayfm6u6hrh73i3lit2uyuxeo3",
        "Addr": "10.210.147.58:2377"
      }
    ],
    "LocalNodeState": "active",
    "NodeAddr": "10.210.147.58"
  },
  "LoggingDriver": "json-file",
  "OSType": "linux",
  "HttpProxy": "",
  "Runtimes": {
    "runc": {
      "path": "docker-runc"
    }
  },
  "DriverStatus": [
    [
      "Backing Filesystem",
      "xfs"
    ],
    [
      "Supports d_type",
      "false"
    ]
  ],
  "OperatingSystem": "Red Hat Enterprise Linux Server 7.4 (Maipo)",
  "Containers": 16,
  "HttpsProxy": "",
  "BridgeNfIp6tables": true,
  "MemTotal": 16658817024,
  "SecurityOptions": [
    "name=seccomp,profile=default"
  ],
  "Driver": "overlay",
  "IndexServerAddress": "https://index.docker.io/v1/",
  "ClusterStore": "",
  "InitCommit": {
    "Expected": "949e6fa",
    "ID": "949e6fa"
  },
  "GenericResources": null,
  "Isolation": "",
  "SystemStatus": null,
  "OomKillDisable": true,
  "ClusterAdvertise": "",
  "SystemTime": "2017-11-22T14:50:20.657795125-06:00",
  "Name": "xxxxx",
  "CPUSet": true,
  "RegistryConfig": {
    "AllowNondistributableArtifactsCIDRs": [],
    "Mirrors": [],
    "IndexConfigs": {
      "docker.io": {
        "Official": true,
        "Name": "docker.io",
        "Secure": true,
        "Mirrors": []
      }
    },
    "AllowNondistributableArtifactsHostnames": [],
    "InsecureRegistryCIDRs": [
      "127.0.0.0/8"
    ]
  },
  "DefaultRuntime": "runc",
  "ContainersStopped": 6,
  "NCPU": 2,
  "NFd": 142,
  "Architecture": "x86_64",
  "KernelMemory": true,
  "CpuCfsQuota": true,
  "Debug": true,
  "ID": "AYWC:MASV:5HJ4:J6MJ:OLGT:RJGD:XES3:VG76:MXN4:N4FL:OK7E:ULPQ",
  "IPv4Forwarding": true,
  "KernelVersion": "3.10.0-693.5.2.el7.x86_64",
  "BridgeNfIptables": true,
  "NoProxy": "",
  "LiveRestoreEnabled": false,
  "ServerVersion": "17.09.0-ce",
  "CpuCfsPeriod": true,
  "ExperimentalBuild": false,
  "MemoryLimit": true,
  "SwapLimit": true,
  "Plugins": {
    "Volume": [
      "local"
    ],
    "Network": [
      "bridge",
      "host",
      "macvlan",
      "null",
      "overlay"
    ],
    "Authorization": null,
    "Log": [
      "awslogs",
      "fluentd",
      "gcplogs",
      "gelf",
      "journald",
      "json-file",
      "logentries",
      "splunk",
      "syslog"
    ]
  },
  "Images": 39,
  "DockerRootDir": "/var/lib/docker",
  "NEventsListener": 7,
  "CPUShares": true,
  "RuncCommit": {
    "Expected": "3f2f8b84a77f73d38244dd690525642a72156c64",
    "ID": "3f2f8b84a77f73d38244dd690525642a72156c64"
  }
}
{
  "KernelVersion": "3.10.0-693.5.2.el7.x86_64",
  "Arch": "amd64",
  "BuildTime": "2017-09-26T22:42:49.000000000+00:00",
  "ApiVersion": "1.32",
  "Version": "17.09.0-ce",
  "MinAPIVersion": "1.12",
  "GitCommit": "afdb6d4",
  "Os": "linux",
  "GoVersion": "go1.8.3"
}

```
##### SUMMARY

i did an import of jenkins dockerfiles which work fine, jenkins roles has been created.
ansible-container build cmd is failing on the FROM statemenr of the dockerfile, can't resolve registry.access.redhat.com repo address.

##### STEPS TO REPRODUCE
create a small container from the redhat repo ( registry.access.redhat.com)

```
FROM registry.access.redhat.com/rhel7
```

##### EXPECTED RESULTS
move to step 2 

##### ACTUAL RESULTS

redhat repo can't be resolved with container-ansible build cmd, it works fine with a docker build cmd
```
(ansible-container) [root@XXXX~/ansible-container]# head -2 /var/docker/jenkins/Dockerfile 
#RHEL 7
FROM registry.access.redhat.com/rhel7
```

```
2017-11-22T15:00:17.648027 Unknown exception Error building conductor image: Get https://container-conductor-registry.access.redhat.com/v2/: dial tcp: lookup container-conductor-registry.access.redhat.com on 127.0.0.1:53: no such host [container.cli] caller_file=/root/ansible-container/lib/python2.7/site-packages/structlog/stdlib.py caller_func=exception caller_line=95
Traceback (most recent call last):
  File "/root/ansible-container/lib/python2.7/site-packages/container/cli.py", line 299, in __call__
    getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
  File "/root/ansible-container/lib/python2.7/site-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/root/ansible-container/lib/python2.7/site-packages/container/core.py", line 181, in hostcmd_build
    environment=env_vars
  File "/root/ansible-container/lib/python2.7/site-packages/container/docker/engine.py", line 105, in __wrapped__
    return fn(self, *args, **kwargs)
  File "/root/ansible-container/lib/python2.7/site-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/root/ansible-container/lib/python2.7/site-packages/container/docker/engine.py", line 1054, in build_conductor_image
    "Error building conductor image: {0}".format(line['errorDetail']['message']))
AnsibleContainerException: Error building conductor image: Get https://container-conductor-registry.access.redhat.com/v2/: dial tcp: lookup container-conductor-registry.access.redhat.com on 127.0.0.1:53: no such host
```

**Comment by wannaknowmo** [comment]
if i switch to a centos connector i'm getting the following error
```
2017-11-22T22:17:27.019292 Error applying role!           [container.core] caller_file=/_ansible/container/core.py caller_func=apply_role_to_container caller_line=680 engine=<container.docker.engine.Engine object at 0x7f250987de90> exit_code=2 playbook=[{'hosts': u'jenkins', 'roles': ['jenkins'], 'vars': {}}]
2017-11-22T22:17:27.030831 Playbook run finished.         [container.core] caller_file=/_ansible/container/core.py caller_func=conductorcmd_build caller_line=811 exit_code=2
Traceback (most recent call last):
  File "/usr/bin/conductor", line 11, in <module>
    load_entry_point('ansible-container', 'console_scripts', 'conductor')()
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/cli.py", line 399, in conductor_commandline
    **params)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/core.py", line 813, in conductorcmd_build
    raise RuntimeError('Build failed.')
RuntimeError: Build failed.
2017-11-22T16:17:27.317806 Conductor terminated. Cleaning up. [container.docker.engine] caller_file=/root/ansible-container/lib/python2.7/site-packages/container/docker/engine.py caller_func=await_conductor_command caller_line=462 command_rc=1 conductor_id=u'748b95aa2cb6527bf54d149c45e88ff0e9015984eb183b0f66f10c41ca9c945a' save_container=False
2017-11-22T16:17:27.385243 Conductor exited with status 1 [container.cli] caller_file=/root/ansible-container/lib/python2.7/site-packages/container/cli.py caller_func=__call__ caller_line=31
```

**Comment by TomasTomecek** [comment]
We would need to know more information why the build failed -- are there any more logs or error messages, ideally what is the reason of the failure to apply the role?

Regarding `rhel7` as the conductor, seems like we don't ship RHEL7-based conductor, yet (given the fact there is this PR https://github.com/ansible/ansible-container/pull/769). You won't be able to easily build one on your own (unless you have correct subscription on your machine).

**Comment by wannaknowmo** [comment]
hi Tomas,
looks like the issue is in the import of the dockerfile, the following dockerfile works
```
FROM centos:7
#ENV pkgs="curl"
RUN yum -y install curl  && yum clean all
CMD bash
```
this one does not, the pkgs variable doesn't get expanded, same dockerfile works with a docker build cmd
```
FROM centos:7
ENV pkgs="curl"
RUN yum -y install $pkgs  && yum clean all
CMD bash
```

**Comment by TomasTomecek** [comment]
I'm sorry but I don't follow. Which dockerfile are you talking about?

**Comment by wannaknowmo** [comment]
for example i'm importing a test project
```
ansible-container import /var/docker/test --force
```
project was imported successfully.
in my test project the dockerfile looks like this
```
cat  /var/docker/test/Dockerfile 
FROM centos:7
ENV pkgs="curl"
RUN yum -y install $pkgs  && yum clean all
CMD bash
```
when i build the project with ansible-container --debug build i'm getting the following error msg
```
fatal: [test]: FAILED! => {
    "changed": true,
    "cmd": "yum -y install $pkgs && yum clean all",
    "delta": "0:00:02.794274",
    "end": "2017-11-24 16:46:15.392162",
    "failed": true,
    "invocation": {
        "module_args": {
            "_raw_params": "yum -y install $pkgs && yum clean all",
            "_uses_shell": true,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "warn": true
        }
    },
    "msg": "non-zero return code",
    "rc": 1,
    "start": "2017-11-24 16:46:12.597888",
    "stderr": "Error: Need to pass a list of pkgs to install\n Mini usage:\n\ninstall PACKAGE...\n\nInstall a package or packages on your system\n\naliases: install-n, install-na, install-nevra",
    "stderr_lines": [
        "Error: Need to pass a list of pkgs to install",
        " Mini usage:",
        "",
        "install PACKAGE...",
        "",
        "Install a package or packages on your system",
        "",
        "aliases: install-n, install-na, install-nevra"
    ],
    "stdout": "Loaded plugins: fastestmirror, ovl",
    "stdout_lines": [
        "Loaded plugins: fastestmirror, ovl"
    ]
}
        to retry, use: --limit @/tmp/tmpYJAlWn/playbook.retry

PLAY RECAP *********************************************************************
test                       : ok=1    changed=0    unreachable=0    failed=1

2017-11-24T16:46:18.699130 Error applying role!           [container.core] caller_file=/_ansible/container/core.py caller_func=apply_role_to_container caller_line=680 engine=<container.docker.engine.Engine object at 0x7ff0de7cee90> exit_code=2 playbook=[{'hosts': u'test', 'roles': ['test'], 'vars': {}}]
2017-11-24T16:46:18.709556 Playbook run finished.         [container.core] caller_file=/_ansible/container/core.py caller_func=conductorcmd_build caller_line=811 exit_code=2
Traceback (most recent call last):
  File "/usr/bin/conductor", line 11, in <module>
    load_entry_point('ansible-container', 'console_scripts', 'conductor')()
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/cli.py", line 399, in conductor_commandline
    **params)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/core.py", line 813, in conductorcmd_build
    raise RuntimeError('Build failed.')
RuntimeError: Build failed.
2017-11-24T10:46:19.451406 Conductor terminated. Cleaning up. [container.docker.engine] caller_file=/root/ansible-container/lib/python2.7/site-packages/container/docker/engine.py caller_func=await_conductor_command caller_line=462 command_rc=1 conductor_id=u'd254bfc2510a5cc740264083b23b5cf529ea27bb6a3944086380b841a52ed881' save_container=False
2017-11-24T10:46:19.689303 Conductor exited with status 1 [container.cli] caller_file=/root/ansible-container/lib/python2.7/site-packages/container/cli.py caller_func=__call__ caller_line=311
```
the $pkgs variable doesn't get evaluated, this dockerfile syntax works when i build a container with the docker build cmd.
if i change the dockerfile in my test project to 
```
FROM centos:7
#ENV pkgs="curl"
RUN yum -y install curl  && yum clean all
CMD bash
```
and reimport & rebuild, it works fine.

**Comment by TomasTomecek** [comment]
Now I understand, thanks for clarification! So, this is indeed a bug.

The thing is that `import` command does not cover all the use cases -- it's just a helper so you can start with ansible-container easily. This means that once you "import" your dockerfile, you should polish the generated role.

Glad you found an easy workaround.

**Comment by wannaknowmo** [comment]
thanks for your help
