### ISSUE TITLE
Unknown exception argument of type 'NoneType' is not iterable - Volumes

### ISSUE THREAD

**Issue by hans-d** [ansible/ansible-container#800]
##### ISSUE TYPE

 - Bug Report

##### container.yml 

```
---

settings:
  conductor_base: ubuntu:16.04

services:

  squid:
    from: ubuntu:16.04
    roles:
      - squid

    volumes:
      - squid-cache:/var/spool/squid

    ports:
      - 3128:3128

    entrypoint: ["/usr/sbin/squid"]

volumes:
  squid-cache:
```

##### OS / ENVIRONMENT

```
Ansible Container, version 0.9.2
Linux, 6a9347179437, 4.9.49-moby, #1 SMP Wed Sep 27 23:17:17 UTC 2017, x86_64
2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] /usr/bin/python
```
##### SUMMARY

Having the "short form" for volumes in container.result in Unknown exception argument of type 'NoneType' is not iterable

##### STEPS TO REPRODUCE

```
ansible-container build
```

##### EXPECTED RESULTS

regular container build

##### ACTUAL RESULTS

```
2017-11-23T19:15:04.905727 The default type is            [container.config] caller_file=/usr/local/lib/python2.7/dist-packages/container/config.py caller_func=_resolve_defaults caller_line=189 config=<class 'ruamel.yaml.comments.CommentedMap'> defaults=<type '_ordereddict.ordereddict'>
2017-11-23T19:15:04.907133 Getting environment variables... [container.config] caller_file=/usr/local/lib/python2.7/dist-packages/container/config.py caller_func=_get_environment_variables caller_line=205
2017-11-23T19:15:04.908683 Read environment variables     [container.config] caller_file=/usr/local/lib/python2.7/dist-packages/container/config.py caller_func=_get_environment_variables caller_line=210 env_vars={}
2017-11-23T19:15:04.910004 Resolved template variables    [container.config] caller_file=/usr/local/lib/python2.7/dist-packages/container/config.py caller_func=_resolve_defaults caller_line=194 template_vars={}
2017-11-23T19:15:04.911419 Parsed config                  [container.config] caller_file=/usr/local/lib/python2.7/dist-packages/container/config.py caller_func=set_env caller_line=148 config={"settings": {"conductor_base": "ubuntu:16.04", "pwd": "/Users/hans/vw/nextgen/ansible/containers/infra"}, "services": {"squid": {"from": "ubuntu:16.04", "roles": ["squid"], "volumes": ["squid-cache:/var/spool/squid"], "ports": ["3128:3128"], "entrypoint": ["/usr/sbin/squid"]}}, "volumes": {"squid-cache": null}, "defaults": {}}
2017-11-23T19:15:04.912849 Unknown exception argument of type 'NoneType' is not iterable [container.cli] caller_file=/usr/local/lib/python2.7/dist-packages/structlog/stdlib.py caller_func=exception caller_line=95
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/container/cli.py", line 299, in __call__
    getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
  File "/usr/local/lib/python2.7/dist-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/container/core.py", line 153, in hostcmd_build
    config = get_config(base_path, vars_files=vars_files, engine_name=engine_name, project_name=project_name)
  File "/usr/local/lib/python2.7/dist-packages/container/utils/__init__.py", line 49, in get_config
    project_name=project_name, vault_files=vault_files)
  File "/usr/local/lib/python2.7/dist-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/container/config.py", line 62, in __init__
    self.set_env('prod')
  File "/usr/local/lib/python2.7/dist-packages/container/docker/config.py", line 49, in set_env
    if 'docker' in self._config['volumes'][vol_key]:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by chouseknecht** [comment]
@hans-d 

I think the issue is actually the top-level `volumes` directive. We expect it to look something more like the following:

```
volumes:
  static-content:
    docker: {}
    k8s:
      force: false
      state: present
      access_modes:
      - ReadWriteOnce
      requested_storage: 1Gi
      metadata:
        annotations: 'volume.beta.kubernetes.io/mount-options: "discard"'
```

View [top-level volumes](http://docs.ansible.com/ansible-container/container_yml/reference.html#top-volumes) for more info.

**Comment by chouseknecht** [comment]
I think what we need here is better validation and error handling for the top-level volumes directive. Clearly this is not a great user experience.

**Comment by j00bar** [comment]
Yeah. I think ideally we need to write a JSONSchema document and validate `container.yml`

**Comment by hans-d** [comment]
That schema should also allow for how docker-compose allows settings, like the provided volumes top level key
