### ISSUE TITLE
Integer values in environment of composer.yml cause Exception

### ISSUE THREAD

**Issue by imphil** [ansible/ansible-container#808]
##### ISSUE TYPE
 - Bug Report

##### container.yml 
```
  aaa:
    from: "ubuntu:xenial"
    roles:
      - role: yyy
      - role: xxx
    command: ["/usr/bin/dumb-init", "/run.sh"]
    environment:
      PORT: 11113
```

##### OS / ENVIRONMENT
Ansible Container, version 0.9.2

##### SUMMARY
The container.yml snippet shown above specifies a environment variable (`PORT`) as integer. This causes an exception after the build has finished:

```
Applied role to service role=ordereddict([('role', 'yyy')]) service=aaa
Traceback (most recent call last):
  File "/usr/local/bin/conductor", line 11, in <module>
    load_entry_point('ansible-container', 'console_scripts', 'conductor')()
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/cli.py", line 399, in conductor_commandline
    **params)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/core.py", line 827, in conductorcmd_build
    with_name=is_last_role)
  File "/_ansible/container/docker/engine.py", line 105, in __wrapped__
    return fn(self, *args, **kwargs)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/docker/engine.py", line 672, in commit_role_as_layer
    image_config = utils.metadata_to_image_config(metadata)
  File "/_ansible/container/utils/__init__.py", line 152, in metadata_to_image_config
    config[key] = (translator(metadata[metadata_key]) if translator
  File "/_ansible/container/utils/__init__.py", line 113, in format_environment
    return ['='.join(tpl) for tpl in iteritems(to_return)]
TypeError: sequence item 1: expected string, int found
Conductor terminated. Cleaning up.      command_rc=1 conductor_id=bd9ee3b9b68bec55327c932f5efaca7d5741837aca99275e6042e0ba5dc
```

The exception goes away if I change the `PORT` to be a string, i.e. 
```
    environment:
      PORT: "11113"
```

Most likely just a `str()` around the `tpl` variable will solve the issue?

**Comment by hans-d** [comment]
same as #801
