### ISSUE TITLE
Fedora 27 conductor image not available

### ISSUE THREAD

**Issue by cverna** [ansible/ansible-container#868]
##### ISSUE TYPE
 - Bug Report

##### container.yml 
```
version: "2"
settings:

  conductor:
    # The Conductor container does the heavy lifting, and provides a portable
    # Python runtime for building your target containers. It should be derived
    # from the same distribution as you're building your target containers with.
    base: fedora:27
```

##### OS / ENVIRONMENT
```
Ansible Container, version 0.9.2
Linux, laptop, 4.14.14-300.fc27.x86_64, #1 SMP Fri Jan 19 13:19:54 UTC 2018, x86_64
3.6.4 (default, Jan 23 2018, 22:28:37) 
[GCC 7.2.1 20170915 (Red Hat 7.2.1-2)] /home/cverna/.virtualenvs/ansible-container/bin/python3
{
  "ID": "53CT:72FE:2DLR:KNLL:BQCX:SV3M:CHPP:JC2F:KMIK:HA2G:SVL5:I6TD",
  "Containers": 0,
  "ContainersRunning": 0,
  "ContainersPaused": 0,
  "ContainersStopped": 0,
  "Images": 87,
  "Driver": "overlay2",
  "DriverStatus": [
    [
      "Backing Filesystem",
      "extfs"
    ],
    [
      "Supports d_type",
      "true"
    ],
    [
      "Native Overlay Diff",
      "true"
    ]
  ],
  "SystemStatus": null,
  "Plugins": {
    "Volume": [
      "local"
    ],
    "Network": [
      "bridge",
      "host",
      "macvlan",
      "null",
      "overlay"
    ],
    "Authorization": [
      "rhel-push-plugin"
    ]
  },
  "MemoryLimit": true,
  "SwapLimit": true,
  "KernelMemory": true,
  "CpuCfsPeriod": true,
  "CpuCfsQuota": true,
  "CPUShares": true,
  "CPUSet": true,
  "IPv4Forwarding": true,
  "BridgeNfIptables": true,
  "BridgeNfIp6tables": true,
  "Debug": false,
  "NFd": 17,
  "OomKillDisable": true,
  "NGoroutines": 26,
  "SystemTime": "2018-01-29T17:46:59.645658397+01:00",
  "LoggingDriver": "journald",
  "CgroupDriver": "systemd",
  "NEventsListener": 0,
  "KernelVersion": "4.14.14-300.fc27.x86_64",
  "PkgVersion": "docker-1.13.1-44.git584d391.fc27.x86_64",
  "OperatingSystem": "Fedora 27 (Workstation Edition)",
  "OSType": "linux",
  "Architecture": "x86_64",
  "IndexServerAddress": "https://index.docker.io/v1/",
  "IndexServerName": "docker.io",
  "RegistryConfig": {
    "InsecureRegistryCIDRs": [
      "172.30.0.0/16",
      "127.0.0.0/8"
    ],
    "IndexConfigs": {
      "docker.io": {
        "Name": "docker.io",
        "Mirrors": null,
        "Secure": true,
        "Official": true
      },
      "registry.access.redhat.com": {
        "Name": "registry.access.redhat.com",
        "Mirrors": [],
        "Secure": true,
        "Official": false
      },
      "registry.fedoraproject.org": {
        "Name": "registry.fedoraproject.org",
        "Mirrors": [],
        "Secure": true,
        "Official": false
      }
    },
    "Mirrors": []
  },
  "NCPU": 4,
  "MemTotal": 16454201344,
  "DockerRootDir": "/var/lib/docker",
  "HttpProxy": "",
  "HttpsProxy": "",
  "NoProxy": "",
  "Name": "laptop",
  "Labels": null,
  "ExperimentalBuild": false,
  "ServerVersion": "1.13.1",
  "ClusterStore": "",
  "ClusterAdvertise": "",
  "Runtimes": {
    "oci": {
      "path": "/usr/libexec/docker/docker-runc-current"
    },
    "runc": {
      "path": "docker-runc"
    }
  },
  "DefaultRuntime": "oci",
  "Swarm": {
    "NodeID": "",
    "NodeAddr": "",
    "LocalNodeState": "inactive",
    "ControlAvailable": false,
    "Error": "",
    "RemoteManagers": null,
    "Nodes": 0,
    "Managers": 0,
    "Cluster": {
      "ID": "",
      "Version": {},
      "CreatedAt": "0001-01-01T00:00:00Z",
      "UpdatedAt": "0001-01-01T00:00:00Z",
      "Spec": {
        "Orchestration": {},
        "Raft": {
          "ElectionTick": 0,
          "HeartbeatTick": 0
        },
        "Dispatcher": {},
        "CAConfig": {},
        "TaskDefaults": {},
        "EncryptionConfig": {
          "AutoLockManagers": false
        }
      }
    }
  },
  "LiveRestoreEnabled": false,
  "Isolation": "",
  "InitBinary": "/usr/libexec/docker/docker-init-current",
  "ContainerdCommit": {
    "ID": "caba7670d38dc7cddb0c19bcd97cc27fdd65a789",
    "Expected": "aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1"
  },
  "RuncCommit": {
    "ID": "caba7670d38dc7cddb0c19bcd97cc27fdd65a789-dirty",
    "Expected": "9df8b306d01f59d3a8029be411de015b7304dd8f"
  },
  "InitCommit": {
    "ID": "N/A",
    "Expected": "949e6facb77383876aeff8a6944dde66b3089574"
  },
  "SecurityOptions": [
    "name=seccomp,profile=/etc/docker/seccomp.json",
    "name=selinux"
  ],
  "Registries": [
    {
      "Name": "docker.io",
      "Secure": true
    },
    {
      "Name": "registry.fedoraproject.org",
      "Secure": true
    },
    {
      "Name": "registry.access.redhat.com",
      "Secure": true
    },
    {
      "Name": "docker.io",
      "Secure": true
    }
  ]
}
{
  "Version": "1.13.1",
  "ApiVersion": "1.26",
  "MinAPIVersion": "1.12",
  "GitCommit": "caba767-unsupported",
  "GoVersion": "go1.9.1",
  "Os": "linux",
  "Arch": "amd64",
  "KernelVersion": "4.14.14-300.fc27.x86_64",
  "BuildTime": "2017-11-23T21:17:26.153384402+00:00",
  "PkgVersion": "docker-1.13.1-44.git584d391.fc27.x86_64"
}
```
##### SUMMARY
I cannot create a container based on Fedora 27 since the conductor does not exists.

##### STEPS TO REPRODUCE
`ansible-container build` any container.yml with fedora:27 as conductor base image

##### EXPECTED RESULTS
Fedora 27 container-conductor is available

##### ACTUAL RESULTS
```
Building Docker Engine context...
Starting Docker build of Ansible Container Conductor image (please be patient)...
ERROR   Unknown exception
Traceback (most recent call last):
  File "/home/cverna/.virtualenvs/ansible-container/lib64/python3.6/site-packages/container/cli.py", line 299, in __call__
    getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
  File "/home/cverna/.virtualenvs/ansible-container/lib64/python3.6/site-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/home/cverna/.virtualenvs/ansible-container/lib64/python3.6/site-packages/container/core.py", line 181, in hostcmd_build
    environment=env_vars
  File "/home/cverna/.virtualenvs/ansible-container/lib64/python3.6/site-packages/container/docker/engine.py", line 105, in __wrapped__
    return fn(self, *args, **kwargs)
  File "/home/cverna/.virtualenvs/ansible-container/lib64/python3.6/site-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/home/cverna/.virtualenvs/ansible-container/lib64/python3.6/site-packages/container/docker/engine.py", line 1069, in build_conductor_image
    nocache=not cache)
  File "/home/cverna/.virtualenvs/ansible-container/lib64/python3.6/site-packages/docker/models/images.py", line 179, in build
    raise BuildError(chunk['error'])
docker.errors.BuildError: repository docker.io/container-conductor-fedora-27 not found: does not exist or no pull access

```

**Comment by TomasTomecek** [comment]
Not sure if you were at the workshop on devconf. The issue is that we have F27 conductor image only for 0.9.3rc0 -- there will be a stable F27 conductor once we release Ansible Container `0.9.3`.

**Comment by j00bar** [comment]
+1 - 0.9.3 will be cut soon.
