### ISSUE TITLE
Python Docker client 3.0 breaking change

### ISSUE THREAD

**Issue by marcusianlevine** [ansible/ansible-container#869]
##### ISSUE TYPE

 - Bug Report

##### SUMMARY

Version [3.0.0 of the Python `docker` client was released last night](https://pypi.python.org/pypi/docker/3.0.0) which seems to have broken the conductor build process.

All of our `ansible-container` projects are failing to build this morning.

Pinning `docker` below 3.0 resolved the issue.

##### STEPS TO REPRODUCE

Force installation of new `docker` client:
`pip install -U ansible-container`

Build any container project with `--no-cache`

##### EXPECTED RESULTS

Containers build as usual

##### ACTUAL RESULTS

Conductor fails to build

```
Building Docker Engine context...	
Starting Docker build of Ansible Container Conductor image (please be patient)...	
Post stage
ERROR	Unknown exception	
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/container/cli.py", line 299, in __call__
    getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
  File "/usr/local/lib/python2.7/site-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/container/core.py", line 181, in hostcmd_build
    environment=env_vars
  File "/usr/local/lib/python2.7/site-packages/container/docker/engine.py", line 105, in __wrapped__
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/container/docker/engine.py", line 1070, in build_conductor_image
    return image.id
AttributeError: 'tuple' object has no attribute 'id'
```

**Comment by bmcgair** [comment]
Doesn't work:

:~/fuckansible>ansible-container build --no-cache
Setting project_name not defined. Fallback to current directory name.	
Building Docker Engine context...	
Starting Docker build of Ansible Container Conductor image (please be patient)...	
ERROR	Unknown exception	
Traceback (most recent call last):
  File "/Users/billm/ansible-container/container/cli.py", line 302, in __call__
    getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
  File "/Users/billm/ansible-container/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/Users/billm/ansible-container/container/core.py", line 184, in hostcmd_build
    environment=env_vars
  File "/Users/billm/ansible-container/container/docker/engine.py", line 107, in __wrapped__
    return fn(self, *args, **kwargs)
  File "/Users/billm/ansible-container/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/Users/billm/ansible-container/container/docker/engine.py", line 1156, in build_conductor_image
    return image.id
AttributeError: 'tuple' object has no attribute 'id'
