### ISSUE TITLE
500 Internal Server Error when *.retry file exists

### ISSUE THREAD

**Issue by chouseknecht** [ansible/ansible-container#9]
Seeing the following error:
```
$ ansible-container --debug build
(Re)building the Ansible Container image is necessary.
Using temporary directory /var/folders/g_/mr68c1yn1rl4b7qh6pntbmmm0000gn/T/tmpo1uinU...
Building Docker Engine context...
Starting Docker build of Ansible Container image...
Cleaning up temporary directory /var/folders/g_/mr68c1yn1rl4b7qh6pntbmmm0000gn/T/tmpo1uinU...
500 Server Error: Internal Server Error ("Untar re-exec error: exit status 1: output: unexpected EOF")
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/ansible_container-0.1-py2.7.egg/container/cli.py", line 144, in commandline
    **vars(args))
  File "/Library/Python/2.7/site-packages/ansible_container-0.1-py2.7.egg/container/engine.py", line 92, in cmdrun_build
    build_output = build_buildcontainer_image(base_path)
  File "/Library/Python/2.7/site-packages/ansible_container-0.1-py2.7.egg/container/engine.py", line 81, in build_buildcontainer_image
    tag='ansible-container-builder')]
  File "/Library/Python/2.7/site-packages/docker/client.py", line 238, in _stream_helper
    yield self._result(response)
  File "/Library/Python/2.7/site-packages/docker/client.py", line 158, in _result
    self._raise_for_status(response)
  File "/Library/Python/2.7/site-packages/docker/client.py", line 154, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
APIError: 500 Server Error: Internal Server Error ("Untar re-exec error: exit status 1: output: unexpected EOF")
```
Steps to reproduce:

1. `ansible-container --debug build`
2. main.yml playbook errors and leaves main.retry in the ansible directory
3. `ansible-container --debug build`

Removing main.retry from the ansible directory fixes the issue. Perhaps the build command should remove any *.retry files before attempting to start the build?

**Comment by chouseknecht** [comment]
This somehow went away. No idea what changed.
