### ISSUE TITLE
build fails with pip 10

### ISSUE THREAD

**Issue by jblom** [ansible/ansible-container#951]
##### ISSUE TYPE
 - Bug Report

##### OS / ENVIRONMENT

```
cannot build, but I have OSX High Sierra and use Python 3.6.3 and pip 10.0.1
```
##### SUMMARY
After running the pip install I got an error that is probably related to pip 10. See https://mail.python.org/pipermail/distutils-sig/2017-October/031642.html 

##### STEPS TO REPRODUCE

```
virtualenv venv
. venv/bin/activate
pip install "ansible-container[docker,openshift]"
```

##### EXPECTED RESULTS
a successful install

##### ACTUAL RESULTS
```
Collecting ansible-container[docker,openshift]
  Using cached https://files.pythonhosted.org/packages/bc/2a/b1252de3931173d26a30fc965be33c9cc0044cf7b23ce4c707f55d86830c/ansible-container-0.9.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/kk/v8l241ds0yb_vtgj9hmgc9600000gp/T/pip-install-11yi5z3_/ansible-container/setup.py", line 10, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'
```

**Comment by Voronenko** [comment]
Thank you for your report. Fixed in scope of  https://github.com/ansible/ansible-container/pull/939

Fix should be available in next pypi release.

At a moment workaround would be using virtualenv and downgrading pip  to 9.0.3

**Comment by jblom** [comment]
Ah great, good to see it was already detected. Thanks.

For now I'll wait for the release. Several basic ansible & docker things to dive into anyway.

**Comment by sysarcher** [comment]
I'd like to report that I see the same error with the new versioning scheme i.e. `pip 18.0`

**Comment by nuty** [comment]
same issue for me.

**Comment by Voronenko** [comment]
We are providing now preview build of the develop branch, available from pypi as temporary workaround
https://pypi.org/search/?q=ansible-container

**Comment by andreibogdan** [comment]
Same issue here:

- os x 10.14.1
- pip 18.1
- python 3.7

```
pip install ansible-container

Collecting ansible-container
  Using cached https://files.pythonhosted.org/packages/bc/2a/b1252de3931173d26a30fc965be33c9cc0044cf7b23ce4c707f55d86830c/ansible-container-0.9.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/y2/td_v2vgd3mq398zn30wx7vb80000gn/T/pip-install-clh1fmuo/ansible-container/setup.py", line 10, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/y2/td_v2vgd3mq398zn30wx7vb80000gn/T/pip-install-clh1fmuo/ansible-container/
```

**Comment by Voronenko** [comment]
None of pypi maintainers can be contacted at a moment. May be related to recent acquisition by IBM , may be not 

We are providing now preview build of the develop branch, available from pypi as temporary workaround
https://pypi.org/search/?q=ansible-container

i.e.
```
pip install sa-ansible-container
```

more contributors are welcome to join the project

**Comment by remkohdev** [comment]
For what it is worth, I was able to workaround it, by downgrading pip,
```
$ python -m pip install pip==9.0.3
```

**Comment by morganchristiansson** [comment]
Another workaround is to run version from git:

https://docs.ansible.com/ansible-container/installation.html#running-from-source

**Comment by morganchristiansson** [comment]
#945 is also duplicate
